Adept
-----

ADEPT
Hit Die: d6.
Class Skills
The adept’s class skills (and the key ability for each skill) are Concentration (Con), Craft (Int), Handle Animal (Cha), Heal (Wis), Knowledge (all skills taken individually) (Int), Profession (Wis), Spellcraft (Int), and Survival (Wis). 
Skill Points at 1st Level: (2 + Int modifier) x4.
Skill Points at Each Additional Level: 2 + Int modifier.

Table: The Adept
 




 
——— Spells per Day ——––
NPC Level
Base Attack
Bonus
Fort
Save
Ref
Save
Will
Save
Special
0
1st
2nd
3rd
4th
5th
1st
+0
+0
+0
+2

3
1
—
—
—
—
2nd
+1
+0
+0
+3
Summon familiar
3
1
—
—
—
—
3rd
+1
+1
+1
+3

3
2
—
—
—
—
4th
+2
+1
+1
+4

3
2
0
—
—
—
5th
+2
+1
+1
+4

3
2
1
—
—
—
6th
+3
+2
+2
+5

3
2
1
—
—
—
7th
+3
+2
+2
+5

3
3
2
—
—
—
8th
+4
+2
+2
+6

3
3
2
0
—
—
9th
+4
+3
+3
+6

3
3
2
1
—
—
10th
+5
+3
+3
+7

3
3
2
1
—
—
11th
+5
+3
+3
+7

3
3
3
2
—
—
12th
+6/+1
+4
+4
+8

3
3
3
2
0
—
13th
+6/+1
+4
+4
+8

3
3
3
2
1
—
14th
+7/+2
+4
+4
+9

3
3
3
2
1
—
15th
+7/+2
+5
+5
+9

3
3
3
3
2
—
16th
+8/+3
+5
+5
+10

3
3
3
3
2
0
17th
+8/+3
+5
+5
+10

3
3
3
3
2
1
18th
+9/+4
+6
+6
+11

3
3
3
3
2
1
19th
+9/+4
+6
+6
+11

3
3
3
3
3
2
20th
+10/+5
+6
+6
+12

3
3
3
3
3
2

Class Features
All of the following are class features of the adept NPC class.
Weapon and Armor Proficiency: Adepts are skilled with all simple weapons. Adepts are not proficient with any type of armor nor with shields.
Spells: An adept casts divine spells which are drawn from the adept spell list (see below). Like a cleric, an adept must choose and prepare her spells in advance. Unlike a cleric, an adept cannot spontaneously cast cure or inflict spells.
To prepare or cast a spell, an adept must have a Wisdom score equal to at least 10 + the spell level. The Difficulty Class for a saving throw against an adept’s spell is 10 + the spell level + the adept’s Wisdom modifier.
Adepts, unlike wizards, do not acquire their spells from books or scrolls, nor do they prepare them through study. Instead, they meditate or pray for their spells, receiving them as divine inspiration or through their own strength of faith. Each adept must choose a time each day at which she must spend an hour in quiet contemplation or supplication to regain her daily allotment of spells. Time spent resting has no effect on whether an adept can prepare spells.
Like other spellcasters, an adept can cast only a certain number of spells of each spell level per day. Her base daily spell allotment is given on Table: The Adept. In addition, she receives bonus spells per day if she has a high Wisdom score.
When Table: The Adept indicates that the adept gets 0 spells per day of a given spell level, she gains only the bonus spells she would be entitled to based on her Wisdom score for that spell level.
Each adept has a particular holy symbol (as a divine focus) depending on the adept’s magical tradition.
Summon Familiar: At 2nd level, an adept can call a familiar, just as a sorcerer or wizard can.

Adept Spell List
Adepts choose their spells from the following list.
0 Level: create water, cure minor wounds, detect magic, ghost sound, guidance, light, mending, purify food and drink, read magic, touch of fatigue.
1st Level: bless, burning hands, cause fear, command, comprehend languages, cure light wounds, detect chaos, detect evil, detect good, detect law, endure elements, obscuring mist, protection from chaos, protection from evil, protection from good, protection from law, sleep.
2nd Level: aid, animal trance, bear’s endurance, bull’s strength, cat’s grace, cure moderate wounds, darkness, delay poison, invisibility, mirror image, resist energy, scorching ray, see invisibility, web.
3rd Level: animate dead, bestow curse, contagion, continual flame, cure serious wounds, daylight, deeper darkness, lightning bolt, neutralize poison, remove curse, remove disease, tongues.
4th Level: cure critical wounds, minor creation, polymorph, restoration, stoneskin, wall of fire.
5th Level: baleful polymorph, break enchantment, commune, heal, major creation, raise dead, true seeing, wall of stone.
