Arcane Archer
-------------

The Arcane Archer
~~~~~~~~~~~~~~~~~

indexterm:[Class,Arcane Archer]

*Hit Die:* d8.

Requirements
^^^^^^^^^^^^

To qualify to become an arcane archer, a character must fulfill all the following criteria.

*Race:* Elf or half-elf.

*Base Attack Bonus:* +6.

*Feats:* Point Blank Shot, Precise Shot, Weapon Focus (longbow or shortbow).

*Spells:* Ability to cast 1st-level arcane spells.

Class Skills
^^^^^^^^^^^^

The arcane archer’s class skills (and the key ability for each skill) are Craft (Int), Hide (Dex). Listen (Wis), Move Silently (Dex), Ride (Dex), Spot (Wis), Survival (Wis), and Use Rope (Dex).

*Skill Points at Each Level:* 4 + Int modifier.

.The Arcane Archer
[options="header",cols="1,1,1,1,1,6"]
|=====
| Level | Base Attack Bonus | Fort Save | Ref Save | Will Save | Special
| 1st | +1 | +2 | +2 | +0 | Enhance arrow +1
| 2nd | +2 | +3 | +3 | +0 | Imbue arrow
| 3rd | +3 | +3 | +3 | +1 | Enhance arrow +2
| 4th | +4 | +4 | +4 | +1 | Seeker arrow
| 5th | +5 | +4 | +4 | +1 | Enhance arrow +3
| 6th | +6 | +5 | +5 | +2 | Phase arrow
| 7th | +7 | +5 | +5 | +2 | Enhance arrow +4
| 8th | +8 | +6 | +6 | +2 | Hail of arrows
| 9th | +9 | +6 | +6 | +3 | Enhance arrow +5
| 10th | +10 | +7 | +7 | +3 | Arrow of death
|=====

Class Features
^^^^^^^^^^^^^^

All of the following are Class Features of the arcane archer prestige class.

*Weapon and Armor Proficiency:* An arcane archer is proficient with all simple and martial weapons, light armor, medium armor, and shields.

indexterm:[Class Features,Enhance Arrow]

*Enhance Arrow (Su):* At 1st level, every nonmagical arrow an arcane archer nocks and lets fly becomes magical, gaining a +1 enhancement bonus. Unlike magic weapons created by normal means, the archer need not spend experience points or gold pieces to accomplish this task. However, an archer’s magic arrows only function for her. For every two levels the character advances past 1st level in the prestige class, the magic arrows she creates gain +1 greater potency (+1 at 1st level, +2 at 3rd level, +3 at 5th level, +4 at 7th level, and +5 at 9th level).

indexterm:[Class Features,Imbue Arrow]

*Imbue Arrow (Sp):* At 2nd level, an arcane archer gains the ability to place an area spell upon an arrow. When the arrow is fired, the spell’s area is centered on where the arrow lands, even if the spell could normally be centered only on the caster. This ability allows the archer to use the bow’s range rather than the spell’s range. It takes a standard action to cast the spell and fire the arrow. The arrow must be fired in the round the spell is cast, or the spell is wasted.

indexterm:[Class Features,Seeker Arrow]

*Seeker Arrow (Sp):* At 4th level, an arcane archer can launch an arrow once per day at a target known to her within range, and the arrow travels to the target, even around corners. Only an unavoidable obstacle or the limit of the arrow’s range prevents the arrow’s flight. This ability negates cover and concealment modifiers, but otherwise the attack is rolled normally. Using this ability is a standard action (and shooting the arrow is part of the action).

indexterm:[Class Features,Phase Arrow]

*Phase Arrow (Sp):* At 6th level, an arcane archer can launch an arrow once per day at a target known to her within range, and the arrow travels to the target in a straight path, passing through any nonmagical barrier or wall in its way. (Any magical barrier stops the arrow.) This ability negates cover, concealment, and even armor modifiers, but otherwise the attack is rolled normally.

Using this ability is a standard action (and shooting the arrow is part of the action).

indexterm:[Class Features,Hail of Arrows]

*Hail of Arrows (Sp):* In lieu of her regular attacks, once per day an arcane archer of 8th level or higher can fire an arrow at each and every target within range, to a maximum of one target for every arcane archer level she has earned. Each attack uses the archer’s primary attack bonus, and each enemy may only be targeted by a single arrow.

indexterm:[Class Features,Arrow of Death]

*Arrow of Death (Sp):* At 10th level, an arcane archer can create an arrow of death that forces the target, if damaged by the arrow’s attack, to make a DC 20 Fortitude save or be slain immediately. It takes one day to make an arrow of death, and the arrow only functions for the arcane archer who created it. The arrow of death lasts no longer than one year, and the archer can only have one such arrow in existence at a time.

Epic Arcane Archer
------------------

EPIC ARCANE ARCHER 
Hit Die: d8. 
Skill Points at Each Additional Level: 4 + Int modifier. 
Enchant Arrow: For every two levels beyond 9th, the potency of the arrows fired by the arcane archer increases by +1. 
Hail of Arrows: In lieu of his or her regular attacks, once per day the arcane archer can fire an arrow at each and every target within range, with a maximum number of targets equal to his or her arcane archer class level, as normal. 
Bonus Feats: The arcane archer gains a bonus feat (selected from the list of epic arcane archer feats) every four levels after 10th. 
Epic Arcane Archer Bonus Feat List: Blinding Speed, Combat Archery, Distant Shot, Epic Prowess, Epic Speed, Epic Toughness, Epic Weapon Focus (any bow other than a crossbow), Improved Arrow of Death, Improved Combat Casting, Improved Low-Light Vision, Improved Manyshot, Swarm of Arrows, Uncanny Accuracy. 
Table: The Epic Arcane Archer 
Level
Special 
11th
Enchant arrow +6 
12th
— 
13th
Enchant arrow +7 
14th
Bonus feat 
15th
Enchant arrow +8 
16th
— 
17th
Enchant arrow +9 
18th
Bonus feat 
19th
Enchant arrow +10 
20th
— 
