Aristocrat
----------

ARISTOCRAT
Hit Die: d8.
Class Skills
The aristocrat’s class skills (and the key ability for each skill) are Appraise (Int), Bluff (Cha), Diplomacy (Cha), Disguise (Cha), Forgery (Int), Gather Information (Cha), Handle Animal (Cha), Intimidate (Cha), Knowledge (all skills taken individually) (Int), Listen (Wis), Perform (Cha), Ride (Dex), Sense Motive (Wis), Speak Language, Spot (Wis), Swim (Str), and Survival (Wis). 
Skill Points at 1st Level: (4 + Int modifier) x4.
Skill Points at Each Additional Level: 4 + Int modifier.

Table: The Aristocrat
NPC Level
Base Attack
 Bonus
Fort
Save
Ref
Save
Will
Save
1st
+0
+0
+0
+2
2nd
+1
+0
+0
+3
3rd
+2
+1
+1
+3
4th
+3
+1
+1
+4
5th
+3
+1
+1
+4
6th
+4
+2
+2
+5
7th
+5
+2
+2
+5
8th
+6/+1
+2
+2
+6
9th
+6/+1
+3
+3
+6
10th
+7/+2
+3
+3
+7
11th
+8/+3
+3
+3
+7
12th
+9/+4
+4
+4
+8
13th
+9/+4
+4
+4
+8
14th
+10/+5
+4
+4
+9
15th
+11/+6/+1
+5
+5
+9
16th
+12/+7/+2
+5
+5
+10
17th
+12/+7/+2
+5
+5
+10
18th
+13/+8/+3
+6
+6
+11
19th
+14/+9/+4
+6
+6
+11
20th
+15/+10/+5
+6
+6
+12

Class Features
The following is a class feature of the aristocrat NPC class.
Weapon and Armor Proficiency: The aristocrat is proficient in the use of all simple and martial weapons and with all types of armor and shields.
