Blackguard
----------

The Blackguard Prestige Class
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

*Hit Die:* d10.

Requirements
^^^^^^^^^^^^

To qualify to become a blackguard, a character must fulfill all the following criteria.

*Alignment:* Any evil.

*Base Attack Bonus:* +6.

*Skills:* Hide 5 ranks, Knowledge (religion) 2 ranks. 

*Feats:* Cleave, Improved Sunder, Power Attack.

*Special:* The character must have made peaceful contact with an evil outsider who was summoned by him or someone else.

Class Skills
^^^^^^^^^^^^

*The blackguard’s class skills (and the key ability for each skill) are:* Concentration (Con), Craft (Int), Diplomacy (Cha), Handle Animal (Cha), Heal (Wis), Hide (Dex), Intimidate (Cha), Knowledge (religion) (Int), Profession (Wis), and Ride (Dex). 

*Skill Points at Each Level:* 2 + Int modifier.

.The Blackguard
[options="header",cols="1,2,1,1,1,8,1,1,1,1"]
|====
| Level | Base Attack Bonus | Fort Save | Ref Save | Will Save | Special | 1st | 2nd | 3rd | 4th
| 1st | +1 | +2 | 0 | 0 | Aura of evil, detect good, poison use | 0 | — | — | —
| 2nd | +2 | +3 | 0 | 0 | Dark blessing, smite good 1/day | 1 | — | — | —
| 3rd | +3 | +3 | +1 | +1 | Command undead, aura of despair | 1 | 0 | — | —
| 4th | +4 | +4 | +1 | +1 | Sneak attack +1d6 | 1 | 1 | — | —
| 5th | +5 | +4 | +1 | +1 | Fiendish servant, smite good 2/day | 1 | 1 | 0 | —
| 6th | +6 | +5 | +2 | +2 |  | 1 | 1 | 1 | —
| 7th | +7 | +5 | +2 | +2 | Sneak attack +2d6 | 2 | 1 | 1 | 0
| 8th | +8 | +6 | +2 | +2 |  | 2 | 1 | 1 | 1
| 9th | +9 | +6 | +3 | +3 |  | 2 | 2 | 1 | 1
| 10th | +10 | +7 | +3 | +3 | Sneak attack +3d6, smite good 3/day | 2 | 2 | 2 | 1
|====

Class Features
^^^^^^^^^^^^^^

All of the following are Class Features of the blackguard prestige class.

*Weapon and Armor Proficiency:* Blackguards are proficient with all simple and martial weapons, with all types of armor, and with shields.

indexterm:[Class Features,Aura of Evil]

*Aura of Evil (Ex):* The power of a blackguard’s aura of evil (see the detect evil spell) is equal to his class level plus his cleric level, if any.

indexterm:[Class Features,Detect Good]

*Detect Good (Sp):* At will, a blackguard can use detect good as a spell-like ability, duplicating the effect of the detect good spell.

indexterm:[Class Features,Poison Use]

*Poison Use:* Blackguards are skilled in the use of poison and never risk accidentally poisoning themselves when applying poison to a blade.

indexterm:[Class Features,Dark Blessing]

*Dark Blessing (Su):* A blackguard applies his Charisma modifier (if positive) as a bonus on all saving throws.

*Spells:* A blackguard has the ability to cast a small number of divine spells. To cast a blackguard spell, a blackguard must have a Wisdom score of at least 10 + the spell’s level, so a blackguard with a Wisdom of 10 or lower cannot cast these spells.

Blackguard bonus spells are based on Wisdom, and saving throws against these spells have a DC of 10 + spell level + the blackguard’s Wisdom modifier. When the blackguard gets 0 spells per day of a given spell level he gains only the bonus spells he would be entitled to based on his Wisdom score for that spell level. The blackguard’s spell list appears below. A blackguard has access to any spell on the list and can freely choose which to prepare, just as a cleric. A blackguard prepares and casts spells just as a cleric does (though a blackguard cannot spontaneously cast cure or inflict spells).

indexterm:[Class Features,Smite Good]

*Smite Good (Su):* Once a day, a blackguard of 2nd level or higher may attempt to smite good with one normal melee attack.

He adds his Charisma modifier (if positive) to his attack roll and deals 1 extra point of damage per class level. If a blackguard accidentally smites a creature that is not good, the smite has no effect but it is still used up for that day.

At 5th level, and again at 10th level, a blackguard may smite good one additional time per day.

indexterm:[Class Features,Aura of Despair]

*Aura of Despair (Su):* Beginning at 3rd level, the blackguard radiates a malign aura that causes enemies within 10 feet of him to take a –2 penalty on all saving throws.

indexterm:[Class Features,Command Undead]

*Command Undead (Su):* When a blackguard reaches 3rd level, he gains the supernatural ability to command and rebuke undead. He commands undead as would a cleric of two levels lower.

indexterm:[Class Features,Sneak Attack]

*Sneak Attack:* This ability, gained at 4th level, is like the rogue ability of the same name. The extra damage increases by +1d6 every third level beyond 4th (7th and 10th). If a blackguard gets a sneak attack bonus from another source the bonuses on damage stack.

Blackguard Spell List
^^^^^^^^^^^^^^^^^^^^^

Blackguards choose their spells from the following list:

*1st Level:* cause fear, corrupt weapon, cure light wounds, doom, inflict light wounds, magic weapon, summon monster I*.

*2nd Level:* bull’s strength, cure moderate wounds, darkness, death knell, eagle’s splendor, inflict moderate wounds, shatter, summon monster II*.

*3rd Level:* contagion, cure serious wounds, deeper darkness, inflict serious wounds, protection from elements, summon monster III*.

*4th Level:* cure critical wounds, freedom of movement, inflict critical wounds, poison, summon monster IV*.

* Evil creatures only.

Corrupt Weapon
^^^^^^^^^^^^^^

Blackguards have access to a special spell, corrupt weapon, which is the opposing counterpart of the paladin spell bless weapon. Instead of improving a weapon’s effectiveness against evil foes corrupt weapon makes a weapon more effective against good foes.

Fallen Paladins
^^^^^^^^^^^^^^^

Blackguards who have levels in the paladin class (that is to say, are now ex-paladins) gain extra abilities the more levels of paladin they have.

A fallen paladin who becomes a blackguard gains all of the following abilities that apply, according to the number of paladin levels the character has.

* 1–2: Smite good 1/day. (This is in addition to the ability granted to all blackguards at 2nd level.

* 3–4: Lay on hands. Once per day, the blackguard can use this supernatural ability to cure himself or his fiendish servant of damage equal to his Charisma bonus x his level.

* 5–6: Sneak attack damage increased by +1d6. Smite good 2/day.

* 7–8: Fiendish summoning. Once per day, the blackguard can use a summon monster I spell to call forth an evil creature. For this spell, the caster level is double the blackguard’s class level.

* 9–10: Undead companion. In addition to the fiendish servant, the blackguard gains (at 5th level) a Medium-size skeleton or zombie as a companion. This companion cannot be turned or rebuked and gains all special bonuses as a fiendish servant when the blackguard gains levels. Smite good 3/day.

* 11 or more: A fallen paladin of this stature immediately gains a blackguard level for each level of paladin he trades in. 

The character level of the character does not change. With the loss of paladin levels, the character no longer gains as many extra abilities for being a fallen paladin. 

include::blackguard_fiendish_servant.asciidoc[]

