Dragon Disciple
---------------

The Dragon Disciple Prestige Class
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Hit Die: d12.
Requirements
To qualify to become a dragon disciple, a character must fulfill all the following criteria.
Race: Any nondragon (cannot already be a half-dragon).
Skills: Knowledge (arcana) 8 ranks.
Languages: Draconic.
Spellcasting: Ability to cast arcane spells without preparation.
Special: The player chooses a dragon variety when taking the first level in this prestige class.
Class Skills
The dragon disciple’s class skills (and the key ability for each skill) are Concentration (Con), Craft (Int), Diplomacy (Cha), Escape Artist (Dex), Gather Information (Cha), Knowledge (all skills, taken individually) (Int) Listen (Wis), Profession (Wis), Search (Int), Speak Language (Int), Spellcraft (Int), and Spot (Wis). 
 Skill Points at Each Level: 2 + Int modifier.

Table: The Dragon Disciple
Level
Base
Attack
Bonus
Fort
Save
Ref
Save
Will
Save
Special
Bonus Spells
1st
+0
+2
+0
+2
Natural armor increase (+1)
1
2nd
+1
+3
+0
+3
Ability boost (Str +2), claws and bite
1
3rd
+2
+3
+1
+3
Breath weapon (2d8)
0
4th
+3
+4
+1
+4
Ability boost (Str +2), natural armor increase (+2)
1
5th
+3
+4
+1
+4
Blindsense 30 ft.
1
6th
+4
+5
+2
+5
Ability boost (Con +2)
1
7th
+5
+5
+2
+5
Breath weapon (4d8), natural armor increase (+3)
0
8th
+6
+6
+2
+6
Ability boost (Int +2)
1
9th
+6
+6
+3
+6
Wings
1
10th
+7
+7
+3
+7
Blindsense 60 ft., dragon apotheosis
0

Class Features
All of the following are Class Features of the dragon disciple prestige class.
Weapon and Armor Proficiency: Dragon disciples gain no proficiency with any weapon or armor.
Bonus Spells: Dragon disciples gain bonus spells as they gain levels in this prestige class, as if from having a high ability score, as given on Table: The Dragon Disciple. A bonus spell can be added to any level of spells the disciple already has the ability to cast.
If a character has more than one spellcasting class, he must decide to which class he adds each bonus spell as it is gained. Once a bonus spell has been applied, it cannot be shifted.
Natural Armor Increase (Ex): At 1st, 4th, and 7th level, a gains an increase to the character’s existing natural armor (if any), as indicated on Table: The Dragon Disciple (the numbers represent the total increase gained to that point). As his skin thickens, a dragon disciple takes on more and more of his progenitor’s physical aspect.
Claws and Bite (Ex): At 2nd level, a dragon disciple gains claw and bite attacks if he does not already have them. Use the values below or the disciple’s base claw and bite damage values, whichever are greater.

Size 
Bite Damage
Claw Damage
Small 
1d4
1d3
Medium 
1d6
1d4
Large 
1d8
1d6

A dragon disciple is considered proficient with these attacks. When making a full attack, a dragon disciple uses his full base attack bonus with his bite attack but takes a –5 penalty on claw attacks. The Multiattack feat reduces this penalty to only –2.
Ability Boost (Ex): As a dragon disciple gains levels in this prestige class, his ability scores increase as noted on Table: The Dragon Disciple.
These increases stack and are gained as if through level advancement.
Breath Weapon (Su): At 3rd level, a dragon disciple gains a minor breath weapon. The type and shape depend on the dragon variety whose heritage he enjoys (see below). Regardless of the ancestor, the breath weapon deals 2d8 points of damage of the appropriate energy type.
At 7th level, the damage increases to 4d8, and when a disciple attains dragon apotheosis at 10th level it reaches its full power at 6d8. Regardless of its strength, the breath weapon can be used only once per day. Use all the rules for dragon breath weapons except as specified here.
The DC of the breath weapon is 10 + class level + Con modifier.
A line-shaped breath weapon is 5 feet high, 5 feet wide, and 60 feet long. A cone-shaped breath weapon is 30 feet long.

Dragon Variety* 
Breath Weapon
Black 
Line of acid
Blue 
Line of lightning
Green 
Cone of corrosive gas (acid)
Red 
Cone of fire
White 
Cone of cold
Brass 
Line of fire
Bronze 
Line of lightning
Copper 
Line of acid
Gold 
Cone of fire
Silver 
Cone of cold
* Other varieties of dragon disciple are possible, using other dragon varieties as ancestors.

Blindsense (Ex): At 5th level, the dragon disciple gains blindsense with a range of 30 feet. Using nonvisual senses the dragon disciple notices things it cannot see. He usually does not need to make Spot or Listen checks to notice and pinpoint the location of creatures within range of his blindsense ability, provided that he has line of effect to that creature.
Any opponent the dragon disciple cannot see still has total concealment against him, and the dragon disciple still has the normal miss chance when attacking foes that have concealment. Visibility still affects the movement of a creature with blindsense. A creature with blindsense is still denied its Dexterity bonus to Armor Class against attacks from creatures it cannot see. At 10th level, the range of this ability increases to 60 feet.
Wings (Ex): At 9th level, a dragon disciple grows a set of draconic wings. He may now fly at a speed equal to his normal land speed, with average maneuverability.
Dragon Apotheosis: At 10th level, a dragon disciple takes on the half-dragon template. His breath weapon reaches full strength (as noted above), and he gains +4 to Strength and +2 to Charisma. His natural armor bonus increases to +4, and he acquires low-light vision, 60-foot darkvision, immunity to sleep and paralysis effects, and immunity to the energy type used by his breath weapon (see above).
