Duelist
-------

DUELIST
Hit Die: d10.
Requirements
To qualify to become a duelist, a character must fulfill all the following criteria.
Base Attack Bonus: +6.
 Skills: Perform 3 ranks, Tumble 5 ranks.
Feats: Dodge, Mobility, Weapon Finesse.
Class Skills
The duelist’s class skills (and the key ability for each skill) are Balance (Dex), Bluff (Cha), Escape Artist (Dex), Jump (Str), Listen (Wis), Perform (Cha), Sense Motive (Wis), Spot (Wis), and Tumble (Dex).
 Skill Points at Each Level: 4 + Int modifier.

Table: The Duelist
Level
Base
Attack
Bonus
Fort
Save
Ref
Save
Will
Save
Special
1st
+1
+0
+2
+0
Canny defense
2nd
+2
+0
+3
+0
Improved reaction +2
3rd
+3
+1
+3
+1
Enhanced mobility
4th
+4
+1
+4
+1
Grace
5th
+5
+1
+4
+1
Precise strike +1d6
6th
+6
+2
+5
+2
Acrobatic charge
7th
+7
+2
+5
+2
Elaborate parry
8th
+8
+2
+6
+2
Improved reaction +4
9th
+9
+3
+6
+3
Deflect Arrows
10th
+10
+3
+7
+3
Precise strike +2d6

Class Features
Weapon and Armor Proficiency: The duelist is proficient with all simple and martial weapons, but no type of armor or shield.
Canny Defense (Ex): When not wearing armor or using a shield, a duelist adds 1 point of Intelligence bonus (if any) per duelist class level to her Dexterity bonus to modify Armor Class while wielding a melee weapon. If a duelist is caught flat-footed or otherwise denied her Dexterity bonus, she also loses this bonus.
Improved Reaction (Ex): At 2nd level, a duelist gains a +2 bonus on initiative checks.
At 8th level, the bonus increases to +4. This bonus stacks with the benefit provided by the Improved Initiative feat.
Enhanced Mobility (Ex): When wearing no armor and not using a shield, a duelist gains an additional +4 bonus to AC against attacks of opportunity caused when she moves out of a threatened square.
Grace (Ex): At 4th level, a duelist gains an additional +2 competence bonus on all Reflex saving throws. This ability functions for a duelist only when she is wearing no armor and not using a shield.
Precise Strike (Ex): At 5th level, a duelist gains the ability to strike precisely with a light or one-handed piercing weapon, gaining an extra 1d6 damage added to her normal damage roll.
When making a precise strike, a duelist cannot attack with a weapon in her other hand or use a shield. A duelist’s precise strike only works against living creatures with discernible anatomies. Any creature that is immune to critical hits is not vulnerable to a precise strike, and any item or ability that protects a creature from critical hits also protects a creature from a precise strike. At 10th level, the extra damage on a precise strike increases to +2d6.
Acrobatic Charge (Ex): At 6th level, a duelist gains the ability to charge in situations where others cannot. She may charge over difficult terrain that normally slows movement. Depending on the circumstance, she may still need to make appropriate checks to successfully move over the terrain.
Elaborate Parry (Ex): At 7th level and higher, if a duelist chooses to fight defensively or use total defense in melee combat, she gains an additional +1 dodge bonus to AC for each level of duelist she has.
Deflect Arrows: At 9th level, a duelist gains the benefit of the Deflect Arrows feat when using a light or one-handed piercing weapon.

Epic Duelist
~~~~~~~~~~~~

EPIC DUELIST
Hit Die: d10
Skill Points at Each Additional Level: 4 + Int modifier
Precise Strike: Every five levels above 10th, the extra damage inflicted by the epic duelist’s precise strike increases by +1d6.
Bonus Feats: The epic duelist gains a bonus feat (selected from the list of epic duelist feats) every 3 levels after 10th.
Epic Duelist Bonus Feat List: Blinding Speed, Epic Prowess, Epic Reputation, Epic Skill Focus, Epic Speed, Epic Weapon Focus (rapier), Exceptional Deflection*, Improved Combat Reflexes, Improved Whirlwind Attack, Infinite Deflection*, Perfect Two-Weapon Fighting, Superior Initiative, Two-Weapon Rend.
*The epic duelist need not have Improved Unarmed Strike to qualify for these feats, but in that case must be using a light or one-handed piercing weapon.
Table: Epic Duelist
Level
Special
11th
—
12th
—
13th 
Bonus feat
14th
—
15th 
Precise strike +3d6
16th 
Bonus feat
17th
—
18th
—
19th 
Bonus feat
20th 
Precise strike +4d6

