Eldritch Knight
---------------

ELDRITCH KNIGHT
Hit Die: d6.
Requirements
To qualify to become an eldritch knight, a character must fulfill all the following criteria.
Weapon Proficiency: Must be proficient with all martial weapons.
Spells: Able to cast 3rd-level arcane spells.
Class Skills
The eldritch knight’s class skills (and the key ability for each skill) are Concentration (Con), Craft (Int), Decipher Script (Int), Jump (Str), Knowledge (arcana) (Int), Knowledge (nobility and royalty) (Int), Ride (Dex), Sense Motive (Wis), Spellcraft (Int), and Swim (Str). 
 Skill Points at Each Level: 2 + Int modifier.

Table: The Eldritch Knight
Level
Base
Attack
Bonus
Fort
Save
Ref
Save
Will
Save
Special
1st
+1
+2
+0
+0
Bonus feat
2nd
+2
+3
+0
+0
+1 level of existing arcane spellcasting class
3rd
+3
+3
+1
+1
+1 level of existing arcane spellcasting class
4th
+4
+4
+1
+1
+1 level of existing arcane spellcasting class
5th
+5
+4
+1
+1
+1 level of existing arcane spellcasting class
6th
+6
+5
+2
+2
+1 level of existing arcane spellcasting class
7th
+7
+5
+2
+2
+1 level of existing arcane spellcasting class
8th
+8
+6
+2
+2
+1 level of existing arcane spellcasting class
9th
+9
+6
+3
+3
+1 level of existing arcane spellcasting class
10th
+10
+7
+3
+3
+1 level of existing arcane spellcasting class

Class Features
All of the following are features of the eldritch knight prestige class.
Weapon and Armor Proficiency: Eldritch knights gain no proficiency with any weapon or armor.
Bonus Feat: At 1st level, an eldritch knight may choose a bonus feat from the list of feats available to fighters. This is in addition to the feats that a character of any class normally gets from advancing levels. The character must still meet any prerequisites for these bonus feats, including levels of fighter for the Weapon Specialization, Greater Weapon Focus, and Greater Weapon Specialization feats.
Spells per Day: From 2nd level on, when a new eldritch knight level is gained, the character gains new spells per day as if she had also gained a level in whatever arcane spellcasting class she belonged to before she added the prestige class. She does not, however, gain any other benefit a character of that class would have gained. This essentially means that she adds the level of eldritch knight to the level of whatever other arcane spellcasting class the character has, then determines spells per day and caster level accordingly.
If a character had more than one arcane spellcasting class before she became an eldritch knight, she must decide to which class she adds each level of eldritch knight for the purpose of determining spells per day.

Epic Eldritch Knight
~~~~~~~~~~~~~~~~~~~~

EPIC ELDRITCH KNIGHT
Hit Die: d6
Skill Points at Each Additional Level: 2 + Int modifier
Spells: The epic eldritch knight’s caster level increases by 1 per level gained above 10th. The epic eldritch knight continues to gain new spells per day (and spells known, if applicable) at each new level, up to the maximum spells per day and spells known of the arcane spellcasting class to which the eldritch knight belonged before adding the prestige class.
Bonus Feats: The epic eldritch knight gains a bonus feat (selected from the list of epic eldritch knight feats) every 4 levels after 10th.
Epic Eldritch Knight Bonus Feat List: Armor Skin, Automatic Still Spell, Combat Archery, Damage Reduction, Devastating Critical, Dire Charge, Distant Shot, Enhance Spell, Epic Prowess, Epic Spell Focus, Epic Spell Penetration, Epic Spellcasting, Epic Toughness, Epic Weapon Focus, Ignore Material Components, Improved Combat Casting, Improved Combat Reflexes, Improved Manyshot, Improved Spell Capacity, Improved Whirlwind Attack, Instant Reload, Legendary Rider, Overwhelming Critical, Penetrate Damage Reduction, Perfect Two-Weapon Fighting, Permanent Emanation, Spell Knowledge, Spell Opportunity, Spell Stowaway, Spellcasting Harrier, Spontaneous Spell, Storm of Throws, Superior Initiative, Swarm of Arrows, Tenacious Magic, Two-Weapon Rend, Uncanny Accuracy.
Table: Epic Eldritch Knight
Level 
Special
11th
—
12th 
—
13th
—
14th 
Bonus feat
15th
—
16th
—
17th
—
18th 
Bonus feat
19th
—
20th
—
