Fighter
-------

The Fighter Base Class
~~~~~~~~~~~~~~~~~~~~~~
*Alignment:* Any.

*Hit Die:* d10.

Class Skills
^^^^^^^^^^^^
*The fighter’s class skills (and the key ability for each skill) are:* Climb (Str), Craft (Int), Handle Animal (Cha), Intimidate (Cha), Jump (Str), Ride (Dex), and Swim (Str).

*Skill Points at 1st Level:* (2 + Int modifier) x4.

*Skill Points at Each Additional Level:* 2 + Int modifier.

.The Fighter
[options="header"]
|=====
| Level | Base Attack Bonus | Fort Save | Ref Save | Will Save | Special
| 1st | +1 | +2 | +0 | +0 | Bonus feat
| 2nd | +2 | +3 | +0 | +0 | Bonus feat
| 3rd | +3 | +3 | +1 | +1 | 
| 4th | +4 | +4 | +1 | +1 | Bonus feat
| 5th | +5 | +4 | +1 | +1 | 
| 6th | +6/+1 | +5 | +2 | +2 | Bonus feat
| 7th | +7/+2 | +5 | +2 | +2 | 
| 8th | +8/+3 | +6 | +2 | +2 | Bonus feat
| 9th | +9/+4 | +6 | +3 | +3 | 
| 10th | +10/+5 | +7 | +3 | +3 | Bonus feat
| 11th | +11/+6/+1 | +7 | +3 | +3 | 
| 12th | +12/+7/+2 | +8 | +4 | +4 | Bonus feat
| 13th | +13/+8/+3 | +8 | +4 | +4 | 
| 14th | +14/+9/+4 | +9 | +4 | +4 | Bonus feat
| 15th | +15/+10/+5 | +9 | +5 | +5 | 
| 16th | +16/+11/+6/+1 | +10 | +5 | +5 | Bonus feat
| 17th | +17/+12/+7/+2 | +10 | +5 | +5 | 
| 18th | +18/+13/+8/+3 | +11 | +6 | +6 | Bonus feat
| 19th | +19/+14/+9/+4 | +11 | +6 | +6 | 
| 20th | +20/+15/+10/+5 | +12 | +6 | +6 | Bonus feat
|=====

Class Features
^^^^^^^^^^^^^^

All of the following are class features of the fighter.

*Weapon and Armor Proficiency:* A fighter is proficient with all simple and martial weapons and with all armor (heavy, medium, and light) and shields (including tower shields).

*Bonus Feats:* At 1st level, a fighter gets a bonus combat-oriented feat in addition to the feat that any 1st-level character gets and the bonus feat granted to a human character. The fighter gains an additional bonus feat at 2nd level and every two fighter levels thereafter (4th, 6th, 8th, 10th, 12th, 14th, 16th, 18th, and 20th). These bonus feats must be drawn from the feats noted as fighter bonus feats. A fighter must still meet all prerequisites for a bonus feat, including ability score and base attack bonus minimums.

These bonus feats are in addition to the feat that a character of any class gets from advancing levels. A fighter is not limited to the list of fighter bonus feats when choosing these feats.

Epic Fighters
-------------

EPIC FIGHTER 
Hit Die: d10
Skill Points at Each Additional Level: 2 + Int modifier
Bonus Feats: The epic fighter gains a bonus feat (selected from the list of epic fighter bonus feats) every two levels after 20th. 
Epic Fighter Bonus Feat List: Armor Skin, Combat Archery, Damage Reduction, Devastating Critical, Dire Charge, Distant Shot, Energy Resistance, Epic Endurance, Epic Leadership, Epic Prowess, Epic Toughness, Epic Weapon Focus, Epic Weapon Specialization, Exceptional Deflection, Improved Combat Reflexes, Improved Manyshot, Improved Stunning Fist, Improved Whirlwind Attack, Infinite Deflection, Instant Reload, Legendary Commander, Legendary Rider, Legendary Wrestler, Overwhelming Critical, Penetrate Damage Reduction, Perfect Two-Weapon Fighting, Reflect Arrows, Spellcasting Harrier, Storm of Throws, Superior Initiative, Swarm of Arrows, Two-Weapon Rend, Uncanny Accuracy. In addition to the feats on this list, the fighter may treat any feat designated as a fighter bonus feat, but not listed here, as being on his or her bonus feat list. 
Table: The Epic Fighter 
Fighter Level
Special 
21st
— 
22nd
Bonus feat 
23rd
— 
24th
Bonus feat 
25th
— 
26th
Bonus feat 
27th
— 
28th
Bonus feat 
29th
— 
30th
Bonus feat 
