Loremaster
----------

LOREMASTER
Hit Die: d4.
Requirements
To qualify to become a loremaster, a character must fulfill all the following criteria.
Skills: Knowledge (any two) 10 ranks in each.
Feats: Any three metamagic or item creation feats, plus Skill Focus (Knowledge [any individual Knowledge skill]).
Spells: Able to cast seven different divination spells, one of which must be 3rd level or higher.
Class Skills
The loremaster’s class skills (and the key ability for each skill) are Appraise (Int), Concentration (Con), Craft (alchemy) (Int), Decipher Script (Int), Gather Information (Cha), Handle Animals (Cha), Heal (Wis), Knowledge (all skills taken individually) (Int), Perform (Cha), Profession (Wis), Speak Language, Spellcraft (Int), and Use Magic Device (Cha). 
Skill Points at Each Level: 4 + Int modifier.

Table : The Loremaster
Level
Base
Attack
Bonus
Fort
Save
Ref
Save
Will
Save
Special
Spells per Day
1st
+0
+0
+0
+2
Secret
+1 level of existing class
2nd
+1
+0
+0
+3
Lore
+1 level of existing class
3rd
+1
+1
+1
+3
Secret
+1 level of existing class
4th
+2
+1
+1
+4
Bonus language
+1 level of existing class
5th
+2
+1
+1
+4
Secret
+1 level of existing class
6th
+3
+2
+2
+5
Greater lore
+1 level of existing class
7th
+3
+2
+2
+5
Secret
+1 level of existing class
8th
+4
+2
+2
+6
Bonus language
+1 level of existing class
9th
+4
+3
+3
+6
Secret
+1 level of existing class
10th
+5
+3
+3
+7
True lore
+1 level of existing class

Class Features
All of the following are Class Features of the loremaster prestige class.
Weapon and Armor Proficiency: Loremasters gain no proficiency with any weapon or armor.
Spells per Day/Spells Known: When a new loremaster level is gained, the character gains new spells per day (and spells known, if applicable) as if she had also gained a level in a spellcasting class she belonged to before she added the prestige class. She does not, however, gain any other benefit a character of that class would have gained. This essentially means that she adds the level of loremaster to the level of some other spellcasting class the character has, then determines spells per day, spells known, and caster level accordingly.
Secret: At 1st level and every two levels higher than 1st (3rd, 5th, 7th, and 9th), the loremaster chooses one
secret from the table below. Her level plus Intelligence modifier determines the total number of secrets she can choose. She can’t choose the same secret twice.
Lore: At 2nd level, a loremaster gains the ability to know legends or information regarding various topics, just as a bard can with bardic knowledge. The loremaster adds her level and her Intelligence modifier to the lore check, which functions otherwise exactly like a bardic knowledge check.
Bonus Languages: A loremaster can choose any new language at 4th and 8th level.
Greater Lore (Ex): At 6th level, a loremaster gains the ability to understand magic items, as with the identify spell.
True Lore (Ex): At 10th level, once per day a loremaster can use her knowledge to gain the effect of a legend lore spell or an analyze dweomer spell.

Loremaster Secrets
Level +
Int Modifier 
Secret 
Effect
1 
Instant mastery 
4 ranks of a skill in which the character has no ranks
2 
Secret health 
+3 hit points
3 
Secrets of inner strength 
+2 bonus on Will saves
4 
The lore of true stamina 
+2 bonus on Fortitude saves
5 
Secret knowledge of avoidance
+2 bonus on Reflex saves
6 
Weapon trick 
+1 bonus on attack rolls
7 
Dodge trick 
+1 dodge bonus to AC
8 
Applicable knowledge 
Any one feat
9 
Newfound arcana 
1 bonus 1st-level spell*
10 
More newfound arcana 
1 bonus 2nd-level spell*
* As if gained through having a high ability score.
