Mystic Theurge
--------------

MYSTIC THEURGE
Hit Die: d4.
Requirements
To qualify to become a mystic theurge, a character must fulfill all the following criteria.
Skills: Knowledge (arcana) 6 ranks, Knowledge (religion) 6 ranks.
Spells: Able to cast 2nd-level divine spells and 2nd-level arcane spells.
Class Skills
The mystic theurge’s class skills (and the key ability for each skill) are Concentration (Con), Craft (Int), Decipher Script (Int), Knowledge (arcana) (Int), Knowledge (religion) (Int), Profession (Wis), Sense Motive (Wis), and Spellcraft (Int). 
 Skill Points at Each Level: 2 + Int modifier.

Table: The Mystic Theurge
Level
Base
Attack
Bonus
Fort
Save
Ref
Save
Will
Save
Spells per Day
1st
+0
+0
+0
+2
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
2nd
+1
+0
+0
+3
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
3rd
+1
+1
+1
+3
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
4th
+2
+1
+1
+4
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
5th
+2
+1
+1
+4
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
6th
+3
+2
+2
+5
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
7th
+3
+2
+2
+5
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
8th
+4
+2
+2
+6
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
9th
+4
+3
+3
+6
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class
10th
+5
+3
+3
+7
+1 level of existing arcane spellcasting class/
+1 level of existing divine spellcasting class

Class Features
All of the following are features of the mystic theurge prestige class.
Weapon and Armor Proficiency: Mystic theurges gain no proficiency with any weapon or armor.
Spells per Day: When a new mystic theurge level is gained, the character gains new spells per day as if he had also gained a level in any one arcane spellcasting class he belonged to before he added the prestige class and any one divine spellcasting class he belonged to previously. He does not, however, gain any other benefit a character of that class would have gained. This essentially means that he adds the level of mystic theurge to the level of whatever other arcane spellcasting class and divine spellcasting class the character has, then determines spells per day and caster level accordingly. If a character had more than one arcane spellcasting class or more than one divine spellcasting class before he became a mystic theurge, he must decide to which class he adds each level of mystic theurge for the purpose of determining spells per day.
