Sorcerer
--------

The Sorcerer Base Class
~~~~~~~~~~~~~~~~~~~~~~~

*Alignment:* Any.

*Hit Die:* d4.

Class Skills
^^^^^^^^^^^^

*The sorcerer’s class skills (and the key ability for each skill) are:* Bluff (Cha), Concentration (Con), Craft (Int), Knowledge (arcana) (Int), Profession (Wis), and Spellcraft (Int).

*Skill Points at 1st Level:* (2 + Int modifier) x4.

*Skill Points at Each Additional Level:* 2 + Int modifier.

.The Sorcerer
[options="header",cols="2,2,2,2,2,4,1,1,1,1,1,1,1,1,1,1"]
|=====
| Level | Base Attack Bonus | Fort Save | Ref Save | Will Save | Special | 0 | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th
| 1st | +0 | +0 | +0 | +2 | Summon familiar | 5 | 3 | — | — | — | — | — | — | — | —
| 2nd | +1 | +0 | +0 | +3 |  | 6 | 4 | — | — | — | — | — | — | — | —
| 3rd | +1 | +1 | +1 | +3 |  | 6 | 5 | — | — | — | — | — | — | — | —
| 4th | +2 | +1 | +1 | +4 |  | 6 | 6 | 3 | — | — | — | — | — | — | —
| 5th | +2 | +1 | +1 | +4 |  | 6 | 6 | 4 | — | — | — | — | — | — | —
| 6th | +3 | +2 | +2 | +5 |  | 6 | 6 | 5 | 3 | — | — | — | — | — | —
| 7th | +3 | +2 | +2 | +5 |  | 6 | 6 | 6 | 4 | — | — | — | — | — | —
| 8th | +4 | +2 | +2 | +6 |  | 6 | 6 | 6 | 5 | 3 | — | — | — | — | —
| 9th | +4 | +3 | +3 | +6 |  | 6 | 6 | 6 | 6 | 4 | — | — | — | — | —
| 10th | +5 | +3 | +3 | +7 |  | 6 | 6 | 6 | 6 | 5 | 3 | — | — | — | —
| 11th | +5 | +3 | +3 | +7 |  | 6 | 6 | 6 | 6 | 6 | 4 | — | — | — | —
| 12th | +6/+1 | +4 | +4 | +8 |  | 6 | 6 | 6 | 6 | 6 | 5 | 3 | — | — | —
| 13th | +6/+1 | +4 | +4 | +8 |  | 6 | 6 | 6 | 6 | 6 | 6 | 4 | — | — | —
| 14th | +7/+2 | +4 | +4 | +9 |  | 6 | 6 | 6 | 6 | 6 | 6 | 5 | 3 | — | —
| 15th | +7/+2 | +5 | +5 | +9 |  | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 4 | — | —
| 16th | +8/+3 | +5 | +5 | +10 |  | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 5 | 3 | —
| 17th | +8/+3 | +5 | +5 | +10 |  | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 4 | —
| 18th | +9/+4 | +6 | +6 | +11 |  | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 5 | 3
| 19th | +9/+4 | +6 | +6 | +11 |  | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 4
| 20th | +10/+5 | +6 | +6 | +12 |  | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 6 | 6
|=====

.Sorcerer Spells Known
[options="header"]
|=====
| Level | 0 | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th
| 1st | 4 | 2 | — | — | — | — | — | — | — | —
| 2nd | 5 | 2 | — | — | — | — | — | — | — | —
| 3rd | 5 | 3 | — | — | — | — | — | — | — | —
| 4th | 6 | 3 | 1 | — | — | — | — | — | — | —
| 5th | 6 | 4 | 2 | — | — | — | — | — | — | —
| 6th | 7 | 4 | 2 | 1 | — | — | — | — | — | —
| 7th | 7 | 5 | 3 | 2 | — | — | — | — | — | —
| 8th | 8 | 5 | 3 | 2 | 1 | — | — | — | — | —
| 9th | 8 | 5 | 4 | 3 | 2 | — | — | — | — | —
| 10th | 9 | 5 | 4 | 3 | 2 | 1 | — | — | — | —
| 11th | 9 | 5 | 5 | 4 | 3 | 2 | — | — | — | —
| 12th | 9 | 5 | 5 | 4 | 3 | 2 | 1 | — | — | —
| 13th | 9 | 5 | 5 | 4 | 4 | 3 | 2 | — | — | —
| 14th | 9 | 5 | 5 | 4 | 4 | 3 | 2 | 1 | — | —
| 15th | 9 | 5 | 5 | 4 | 4 | 4 | 3 | 2 | — | —
| 16th | 9 | 5 | 5 | 4 | 4 | 4 | 3 | 2 | 1 | —
| 17th | 9 | 5 | 5 | 4 | 4 | 4 | 3 | 3 | 2 | —
| 18th | 9 | 5 | 5 | 4 | 4 | 4 | 3 | 3 | 2 | 1
| 19th | 9 | 5 | 5 | 4 | 4 | 4 | 3 | 3 | 3 | 2
| 20th | 9 | 5 | 5 | 4 | 4 | 4 | 3 | 3 | 3 | 3
|=====

Class Features
^^^^^^^^^^^^^^

All of the following are class features of the sorcerer.

*Weapon and Armor Proficiency:* Sorcerers are proficient with all simple weapons. They are not proficient with any type of armor or shield. Armor of any type interferes with a sorcerer’s gestures, which can cause his spells with somatic components to fail.

*Spells:* A sorcerer casts arcane spells which are drawn primarily from the sorcerer/wizard spell list. He can cast any spell he knows without preparing it ahead of time, the way a wizard or a cleric must (see below).

To learn or cast a spell, a sorcerer must have a Charisma score equal to at least 10 + the spell level. The Difficulty Class for a saving throw against a sorcerer’s spell is 10 + the spell level + the sorcerer’s Charisma modifier.

Like other spellcasters, a sorcerer can cast only a certain number of spells of each spell level per day. His base daily spell allotment is given on Table: The Sorcerer. In addition, he receives bonus spells per day if he has a high Charisma score.

A sorcerer’s selection of spells is extremely limited. A sorcerer begins play knowing four 0-level spells and two 1st-level spells of your choice. At each new sorcerer level, he gains one or more new spells, as indicated on Table: Sorcerer Spells Known. (Unlike spells per day, the number of spells a sorcerer knows is not affected by his Charisma score; the numbers on Table: Sorcerer Spells Known are fixed.) These new spells can be common spells chosen from the sorcerer/wizard spell list, or they can be unusual spells that the sorcerer has gained some understanding of by study. The sorcerer can’t use this method of spell acquisition to learn spells at a faster rate, however.

Upon reaching 4th level, and at every even-numbered sorcerer level after that (6th, 8th, and so on), a sorcerer can choose to learn a new spell in place of one he already knows. In effect, the sorcerer “loses” the old spell in exchange for the new one. The new spell’s level must be the same as that of the spell being exchanged, and it must be at least two levels lower than the highest-level sorcerer spell the sorcerer can cast. A sorcerer may swap only a single spell at any given level, and must choose whether or not to swap the spell at the same time that he gains new spells known for the level.

Unlike a wizard or a cleric, a sorcerer need not prepare his spells in advance. He can cast any spell he knows at any time, assuming he has not yet used up his spells per day for that spell level. He does not have to decide ahead of time which spells he’ll cast.

*Familiar:* A sorcerer can obtain a familiar (see below). Doing so takes 24 hours and uses up magical materials that cost 100 gp. A familiar is a magical beast that resembles a small animal and is unusually tough and intelligent. The creature serves as a companion and servant.

The sorcerer chooses the kind of familiar he gets. As the sorcerer advances in level, his familiar also increases in power.

If the familiar dies or is dismissed by the sorcerer, the sorcerer must attempt a DC 15 Fortitude saving throw. Failure means he loses 200 experience points per sorcerer level; success reduces the loss to one-half that amount. However, a sorcerer’s experience point total can never go below 0 as the result of a familiar’s demise or dismissal. A slain or dismissed familiar cannot be replaced for a year and day. A slain familiar can be raised from the dead just as a character can be, and it does not lose a level or a Constitution point when this happy event occurs.

A character with more than one class that grants a familiar may have only one familiar at a time.

include::arcane_spells_and_armor.asciidoc[]

include::familiars.asciidoc[]

Epic Sorcerers
--------------


EPIC SORCERER
Hit Die: d4. 
Skill Points at Each Additional Level: 2 + Int modifier. 
Spells: The sorcerer’s caster level is equal to his or her class level. The sorcerer’s number of spells per day does not increase after 20th level. The sorcerer does not learn additional spells unless he or she selects the Spell Knowledge feat. 
Familiar: The sorcerer’s familiar continues to increase in power. Every two levels beyond 20th the familiar’s natural armor and Intelligence each increase by +1. The familiar’s spell resistance is equal to the master’s class level + 5. At 21st level and again every ten levels higher than 21st, the familiar gains the benefit of the Familiar Spell epic feat for a spell of its master’s choice.
Bonus Feats: The epic sorcerer gains a bonus feat (selected from the list of epic sorcerer bonus feats) every three levels after 20th. 
Epic Sorcerer Bonus Feat List: Augmented Alchemy, Automatic Quicken Spell, Automatic Silent Spell, Automatic Still Spell, Energy Resistance, Enhance Spell, Epic Spell Focus, Epic Spell Penetration, Epic Spellcasting, Familiar Spell, Ignore Material Components, Improved Combat Casting, Improved Heighten Spell, Improved Metamagic, Improved Spell Capacity, Intensify Spell, Master Staff, Master Wand, Multispell, Permanent Emanation, Spell Knowledge, Spell Stowaway, Spell Opportunity. 
Table: The Epic Sorcerer 
Sorcerer Level
Special 
21st
— 
22nd
— 
23rd
Bonus feat 
24th
— 
25th
— 
26th
Bonus feat 
27th
— 
28th
— 
29th
Bonus feat 
30th
—
