Wizard
------

The Wizard Base Class
~~~~~~~~~~~~~~~~~~~~~

*Alignment:* Any.

*Hit Die:* d4.

Class Skills
^^^^^^^^^^^^

*The wizard’s class skills (and the key ability for each skill) are:* Concentration (Con), Craft (Int), Decipher Script (Int), Knowledge (all skills, taken individually) (Int), Profession (Wis), and Spellcraft (Int). See Chapter 4: Skills for skill descriptions.

*Skill Points at 1st Level:* (2 + Int modifier) x4.

*Skill Points at Each Additional Level:* 2 + Int modifier.

.The Wizard
[options="header",cols="2,3,2,2,2,10,1,1,1,1,1,1,1,1,1,1"]
|=====
| Level | Base Attack Bonus | Fort Save | Ref Save | Will Save | Special | 0 | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th
| 1st | +0 | +0 | +0 | +2 | Summon familiar, Scribe Scroll | 3 | 1 | — | — | — | — | — | — | — | —
| 2nd | +1 | +0 | +0 | +3 |  | 4 | 2 | — | — | — | — | — | — | — | —
| 3rd | +1 | +1 | +1 | +3 |  | 4 | 2 | 1 | — | — | — | — | — | — | —
| 4th | +2 | +1 | +1 | +4 |  | 4 | 3 | 2 | — | — | — | — | — | — | —
| 5th | +2 | +1 | +1 | +4 | Bonus feat | 4 | 3 | 2 | 1 | — | — | — | — | — | —
| 6th | +3 | +2 | +2 | +5 |  | 4 | 3 | 3 | 2 | — | — | — | — | — | —
| 7th | +3 | +2 | +2 | +5 |  | 4 | 4 | 3 | 2 | 1 | — | — | — | — | —
| 8th | +4 | +2 | +2 | +6 |  | 4 | 4 | 3 | 3 | 2 | — | — | — | — | —
| 9th | +4 | +3 | +3 | +6 |  | 4 | 4 | 4 | 3 | 2 | 1 | — | — | — | —
| 10th | +5 | +3 | +3 | +7 | Bonus feat | 4 | 4 | 4 | 3 | 3 | 2 | — | — | — | —
| 11th | +5 | +3 | +3 | +7 |  | 4 | 4 | 4 | 4 | 3 | 2 | 1 | — | — | —
| 12th | +6/+1 | +4 | +4 | +8 |  | 4 | 4 | 4 | 4 | 3 | 3 | 2 | — | — | —
| 13th | +6/+1 | +4 | +4 | +8 |  | 4 | 4 | 4 | 4 | 4 | 3 | 2 | 1 | — | —
| 14th | +7/+2 | +4 | +4 | +9 |  | 4 | 4 | 4 | 4 | 4 | 3 | 3 | 2 | — | —
| 15th | +7/+2 | +5 | +5 | +9 | Bonus feat | 4 | 4 | 4 | 4 | 4 | 4 | 3 | 2 | 1 | —
| 16th | +8/+3 | +5 | +5 | +10 |  | 4 | 4 | 4 | 4 | 4 | 4 | 3 | 3 | 2 | —
| 17th | +8/+3 | +5 | +5 | +10 |  | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 3 | 2 | 1
| 18th | +9/+4 | +6 | +6 | +11 |  | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 3 | 3 | 2
| 19th | +9/+4 | +6 | +6 | +11 |  | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 3 | 3
| 20th | +10/+5 | +6 | +6 | +12 | Bonus feat | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 4
|=====

Class Features
^^^^^^^^^^^^^^

All of the following are class features of the wizard.

*Weapon and Armor Proficiency:* Wizards are proficient with the club, dagger, heavy crossbow, light crossbow, and quarterstaff, but not with any type of armor or shield. Armor of any type interferes with a wizard’s movements, which can cause her spells with somatic components to fail.

*Spells:* A wizard casts arcane spells which are drawn from the sorcerer/ wizard spell list. A wizard must choose and prepare her spells ahead of time (see below).

To learn, prepare, or cast a spell, the wizard must have an Intelligence score equal to at least 10 + the spell level. The Difficulty Class for a saving throw against a wizard’s spell is 10 + the spell level + the wizard’s Intelligence modifier.

Like other spellcasters, a wizard can cast only a certain number of spells of each spell level per day. Her base daily spell allotment is given on Table: The Wizard. In addition, she receives bonus spells per day if she has a high Intelligence score.

Unlike a bard or sorcerer, a wizard may know any number of spells. She must choose and prepare her spells ahead of time by getting a good night’s sleep and spending 1 hour studying her spellbook. While studying, the wizard decides which spells to prepare.

*Bonus Languages:* A wizard may substitute Draconic for one of the bonus languages available to the character because of her race.

*Familiar:* A wizard can obtain a familiar in exactly the same manner as a sorcerer can. See the sorcerer description and the information on Familiars below for details.

*Scribe Scroll:* At 1st level, a wizard gains Scribe Scroll as a bonus feat. 

*Bonus Feats:* At 5th, 10th, 15th, and 20th level, a wizard gains a bonus feat. At each such opportunity, she can choose a metamagic feat, an item creation feat, or Spell Mastery. The wizard must still meet all prerequisites for a bonus feat, including caster level minimums.

These bonus feats are in addition to the feat that a character of any class gets from advancing levels. The wizard is not limited to the categories of item creation feats, metamagic feats, or Spell Mastery when choosing these feats.

*Spellbooks:* A wizard must study her spellbook each day to prepare her spells. She cannot prepare any spell not recorded in her spellbook, except for read magic, which all wizards can prepare from memory.

A wizard begins play with a spellbook containing all 0-level wizard spells (except those from her prohibited school or schools, if any; see School Specialization, below) plus three 1st-level spells of your choice. For each point of Intelligence bonus the wizard has, the spellbook holds one additional 1st-level spell of your choice. At each new wizard level, she gains two new spells of any spell level or levels that she can cast (based on her new wizard level) for her spellbook. At any time, a wizard can also add spells found in other wizards’ spellbooks to her own.

School Specialization
^^^^^^^^^^^^^^^^^^^^^

A school is one of eight groupings of spells, each defined by a common theme. If desired, a wizard may specialize in one school of magic (see below). Specialization allows a wizard to cast extra spells from her chosen school, but she then never learns to cast spells from some other schools.

A specialist wizard can prepare one additional spell of her specialty school per spell level each day. She also gains a +2 bonus on Spellcraft checks to learn the spells of her chosen school.

The wizard must choose whether to specialize and, if she does so, choose her specialty at 1st level. At this time, she must also give up two other schools of magic (unless she chooses to specialize in divination; see below), which become her prohibited schools.

A wizard can never give up divination to fulfill this requirement.

Spells of the prohibited school or schools are not available to the wizard, and she can’t even cast such spells from scrolls or fire them from wands. She may not change either her specialization or her prohibited schools later.

The eight schools of arcane magic are abjuration, conjuration, divination, enchantment, evocation, illusion, necromancy, and transmutation.

Spells that do not fall into any of these schools are called universal spells.

*Abjuration:* Spells that protect, block, or banish. An abjuration specialist is called an abjurer.

*Conjuration:* Spells that bring creatures or materials to the caster. A conjuration specialist is called a conjurer.

*Divination:* Spells that reveal information. A divination specialist is called a diviner. Unlike the other specialists, a diviner must give up only one other school.

*Enchantment:* Spells that imbue the recipient with some property or grant the caster power over another being. An enchantment specialist is called an enchanter.

*Evocation:* Spells that manipulate energy or create something from nothing. An evocation specialist is called an evoker.

*Illusion:* Spells that alter perception or create false images. An illusion specialist is called an illusionist.

*Necromancy:* Spells that manipulate, create, or destroy life or life force. A necromancy specialist is called a necromancer.

*Transmutation:* Spells that transform the recipient physically or change its properties in a more subtle way. A transmutation specialist is called a transmuter.

*Universal:* Not a school, but a category for spells that all wizards can learn. A wizard cannot select universal as a specialty school or as a prohibited school. Only a limited number of spells fall into this category.

include::arcane_spells_and_armor.asciidoc[]

include::familiars.asciidoc[]

Epic Wizards
------------

EPIC WIZARD 
Hit Die: d4. 
Skill Points at Each Additional Level: 2 + Int modifier. 
Spells: The wizard’s caster level is equal to her class level. The wizard’s number of spells per day does not increase after 20th level. Each time the wizard achieves a new level, he or she learns two new spells of any spell levels that he or she can cast (according to his or her new level). 
Familiar: The wizards’s familiar continues to increase in power. Every two levels beyond 20th the familiar’s natural armor and Intelligence each increase by +1. The familiar’s spell resistance is equal to the master’s class level + 5. At 21st level and again every ten levels higher than 21st, the familiar gains the benefit of the Familiar Spell epic feat for a spell of its master’s choice.
Bonus Feats: The epic wizard gains a bonus feat (selected from the list of epic wizard feats) every three levels after 20th. 
Epic Wizard Bonus Feat List: Augmented Alchemy, Automatic Quicken Spell, Automatic Silent Spell, Automatic Still Spell, Combat Casting, Craft Epic Magic Arms and Armor, Craft Epic Rod, Craft Epic Staff, Craft Epic Wondrous Item, Efficient Item Creation, Enhance Spell, Epic Spell Focus, Epic Spell Penetration, Epic Spellcasting, Familiar Spell, Forge Epic Ring, Ignore Material Components, Improved Combat Casting, Improved Heighten Spell, Improved Metamagic, Improved Spell Capacity, Intensify Spell, Multispell, Permanent Emanation, Scribe Epic Scroll, Spell Focus, Spell Knowledge, Spell Mastery, Spell Penetration Spell Stowaway, Spell Opportunity, Spontaneous Spell, Tenacious Magic. In addition to the feats on this list, the wizard may select any item creation feat or metamagic feat not listed here. 
Table: The Epic Wizard 
Wizard Level
Special 
21st
— 
22nd
— 
23rd
Bonus feat 
24th
— 
25th
— 
26th
Bonus feat 
27th
— 
28th
— 
29th
Bonus feat 
30th
— 
