The Basics
==========

The Basics
----------
*The Core Mechanic:* Whenever you attempt an action that has some chance of failure, you roll a twenty-sided die (d20). To determine if your character succeeds at a task you do this:

* Roll a d20.

* Add any relevant modifiers.

* Compare the result to a target number.

If the result equals or exceeds the target number, your character succeeds. If the result is lower than the target number, you fail.

indexterm:[Dice]

Dice
~~~~
Dice rolls are described with expressions such as “3d4+3,” which means “roll three four-sided dice and add 3” (resulting in a number between 6 and 15). The first number tells you how many dice to roll (adding the results together). The number immediately after the “d” tells you the type of die to use. Any number after that indicates a quantity that is added or subtracted from the result.

*d%:* Percentile dice work a little differently. You generate a number between 1 and 100 by rolling two different ten-sided dice. One (designated before you roll) is the tens digit. The other is the ones digit. Two 0s represent 100.

Rounding Fractions
~~~~~~~~~~~~~~~~~~
In general, if you wind up with a fraction, round down, even if the fraction is one-half or larger.
Exception: Certain rolls, such as damage and hit points, have a minimum of 1.

Multiplying
~~~~~~~~~~~
Sometimes a rule makes you multiply a number or a die roll. As long as you’re applying a single multiplier, multiply the number normally. When two or more multipliers apply to any abstract value (such as a modifier or a die roll), however, combine them into a single multiple, with each extra multiple adding 1 less than its value to the first multiple. Thus, a double (×2) and a double (×2) applied to the same number results in a triple (×3, because 2 + 1 = 3).

When applying multipliers to real-world values (such as weight or distance), normal rules of math apply instead. A creature whose size doubles (thus multiplying its weight by 8) and then is turned to stone (which would multiply its weight by a factor of roughly 3) now weighs about 24 times normal, not 10 times normal. Similarly, a blinded creature attempting to negotiate difficult terrain would count each square as 4 squares (doubling the cost twice, for a total multiplier of ×4), rather than as 3 squares (adding 100% twice). 

Ability Scores
~~~~~~~~~~~~~~
Ability Modifiers
^^^^^^^^^^^^^^^^^
Each ability, after changes made because of race, has a modifier ranging from –5 to +5. Table: Ability Modifiers and Bonus Spells shows the modifier for each score. It also shows bonus spells, which you’ll need to know about if your character is a spellcaster.
The modifier is the number you apply to the die roll when your character tries to do something related to
that ability. You also use the modifier with some numbers that aren’t die rolls. A positive modifier is called a bonus, and a negative modifier is called a penalty.

.Ability Modifiers and Bonus Spells
[options="header,footer",cols="^,^,^,^,^,^,^,^,^,^,^,^"]
|=========================================================================================
|        |         10+^| Bonus Spells (by Spell Level)
|Score  | Modifier |  0  | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th
| 1  | -5 10+^| Can’t cast spells tied to this ability
| 2-3 | -4 10+^| Can’t cast spells tied to this ability
| 4-5 | -3 10+^| Can’t cast spells tied to this ability
| 6-7 | -2 10+^| Can’t cast spells tied to this ability
| 8-9 | -1 10+^| Can’t cast spells tied to this ability
| 10-11 | 0 | — | — | — | — | — | — | — | — | — | —
| 12-13 | +1 | — | 1 | — | — | — | — | — | — | — | —
| 14-15 | +2 | — | 1 | 1 | — | — | — | — | — | — | —
| 16-17 | +3 | — | 1 | 1 | 1 | — | — | — | — | — | —
| 18-19 | +4 | — | 1 | 1 | 1 | 1 | — | — | — | — | —
| 20-21 | +5 | — | 2 | 1 | 1 | 1 | 1 | — | — | — | —
| 22-23 | +6 | — | 2 | 2 | 1 | 1 | 1 | 1 | — | — | —
| 24-25 | +7 | — | 2 | 2 | 2 | 1 | 1 | 1 | 1 | — | —
| 26-27 | +8 | — | 2 | 2 | 2 | 2 | 1 | 1 | 1 | 1 | —
| 28-29 | +9 | — | 3 | 2 | 2 | 2 | 2 | 1 | 1 | 1 | 1
| 30-31 | +10 | — | 3 | 3 | 2 | 2 | 2 | 2 | 1 | 1 | 1
| 32-33 | +11 | — | 3 | 3 | 3 | 2 | 2 | 2 | 2 | 1 | 1
| 34-35 | +12 | — | 3 | 3 | 3 | 3 | 2 | 2 | 2 | 2 | 1
| 36-37 | +13 | — | 4 | 3 | 3 | 3 | 3 | 2 | 2 | 2 | 2
| 38-39 | +14 | — | 4 | 4 | 3 | 3 | 3 | 3 | 2 | 2 | 2
| 40-41 | +15 | — | 4 | 4 | 4 | 3 | 3 | 3 | 3 | 2 | 2
| 42-43 | +16 | — | 4 | 4 | 4 | 4 | 3 | 3 | 3 | 3 | 2
| 44-45 | +17 | — | 5 | 4 | 4 | 4 | 4 | 3 | 3 | 3 | 3
12+^| etc... 
|=========================================================================================

Abilities and Spellcasters
^^^^^^^^^^^^^^^^^^^^^^^^^^
The ability that governs bonus spells depends on what type of spellcaster your character is: Intelligence for wizards; Wisdom for clerics, druids, paladins, and rangers; or Charisma for sorcerers and bards. In addition to having a high ability score, a spellcaster must be of high enough class level to be able to cast spells of a given spell level. (See the class descriptions for details.)

THE POWER POINT RESERVE
Psionic characters fuel their abilities through a pool, or reserve, of power points. Your power point reserve is equal to your base power points gained from your class, bonus power points from a high key ability score (see Abilities and Manifesters, below), and any additional bonus power points from sources such as your character race and feat selections.

Multiclass Psionic Characters
If you have levels in more than one psionic class, you combine your power points from each class to make up your reserve. You can use these power points to manifest powers from any psionic class you have. 
While you maintain a single reserve of power points from your class, race, and feat selections, you are still limited by the manifester level you have achieved with each power you know. 

Abilities and Manifesters
^^^^^^^^^^^^^^^^^^^^^^^^^

The ability that your powers depend on—your key ability score as a manifester—is related to what psionic class (or classes) you have levels in: Intelligence (psion), Wisdom (psychic warrior), and Charisma (wilder). The modifier for this ability is referred to as your key ability modifier. If your character’s key ability score is 9 or lower, you can’t manifest powers from that psionic class.

Just as a high Intelligence score grants bonus spells to a wizard and a high Wisdom score grants bonus spells to a cleric, a character who manifests powers (psions, psychic warriors, and wilders) gains bonus power points according to his key ability score. Refer to Table: Ability Modifiers and Bonus Power Points.

How To Determine Bonus Power Points: Your key ability score grants you additional power points equal to your key ability modifier x your manifester level x1/2. Table: Ability Modifiers and Bonus Power Points shows these calculations for class levels 1st through 20th and key ability scores from 10 to 41.


Table: Ability Modifiers and Bonus Power Points
Ability Score
———————–—————–——— Bonus Power Points (by Class Level) ——–––——————–—————

1st
2nd
3rd
4th
5th
6th
7th
8th
9th
10th
11th
12th
13th
14th
15th
16th
17th
18th
19th
20th
10–11
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
12–13
0
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
14–15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
16–17
1
3
4
6
7
9
10
12
13
15
16
18
19
21
22
24
25
27
28
30
18–19
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
20–21
2
5
7
10
12
15
17
20
22
25
27
30
32
35
37
40
42
45
47
50
22–23
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
24–25
3
7
10
14
17
21
24
28
31
35
38
42
45
49
52
56
59
63
66
70
26–27
4
8
12
16
20
24
28
32
36
40
44
48
52
56
60
64
68
72
76
80
28–29
4
9
13
18
22
27
31
36
40
45
49
54
58
63
67
72
76
81
85
90
30–31
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
32–33
5
11
16
22
27
33
38
44
49
55
60
66
71
77
82
88
93
99
104
110
34–35
6
12
18
24
30
36
42
48
54
60
66
72
78
84
90
96
102
108
114
120
36–37
6
13
19
26
32
39
45
52
58
65
71
78
84
91
97
104
110
117
123
130
38–39
7
14
21
28
35
42
49
56
63
70
77
84
91
98
105
112
119
126
133
140
40–41
7
15
22
30
37
45
52
60
67
75
82
90
97
105
112
120
127
135
142
150






The Abilities
^^^^^^^^^^^^^
Each ability partially describes your character and affects some of his or her actions.

Strength (STR)
++++++++++++++
indexterm:[Strength]
Strength measures your character’s muscle and physical power. This ability is especially important for fighters, barbarians, paladins, rangers, and monks because it helps them prevail in combat. Strength also limits the amount of equipment your character can carry.
You apply your character’s Strength modifier to:

* Melee attack rolls.
* Damage rolls when using a melee weapon or a thrown weapon (including a sling). (Exceptions: Off-hand attacks receive only one-half the character’s Strength bonus, while two-handed attacks receive one and a half times the Strength bonus. A Strength penalty, but not a bonus, applies to attacks made with a bow that is not a composite bow.)
* Climb, Jump, and Swim checks. These are the skills that have Strength as their key ability.
* Strength checks (for breaking down doors and the like).

Dexterity (DEX)
+++++++++++++++
indexterm:[Dexterity]
Dexterity measures hand-eye coordination, agility, reflexes, and balance. This ability is the most important one for rogues, but it’s also high on the list for characters who typically wear light or medium armor (rangers and barbarians) or no armor at all (monks, wizards, and sorcerers), and for anyone who wants to be a skilled archer.
You apply your character’s Dexterity modifier to:

* Ranged attack rolls, including those for attacks made with bows, crossbows, throwing axes, and other ranged weapons.
* Armor Class (AC), provided that the character can react to the attack.
* Reflex saving throws, for avoiding fireballs and other attacks that you can escape by moving quickly.
* Balance, Escape Artist, Hide, Move Silently, Open Lock, Ride, Sleight of Hand, Tumble, and Use Rope checks. These are the skills that have Dexterity as their key ability.

Constitution (CON)
++++++++++++++++++
indexterm:[Constitution]
Constitution represents your character’s health and stamina. A Constitution bonus increases a character’s hit points, so the ability is important for all classes.
You apply your character’s Constitution modifier to:

* Each roll of a Hit Die (though a penalty can never drop a result below 1—that is, a character always gains at least 1 hit point each time he or she advances in level).
* Fortitude saving throws, for resisting poison and similar threats.
* Concentration checks. Concentration is a skill, important to spellcasters, that has Constitution as its key ability.

If a character’s Constitution score changes enough to alter his or her Constitution modifier, the character’s hit points also increase or decrease accordingly.

Intelligence (INT)
++++++++++++++++++
indexterm:[Intelligence]
Intelligence determines how well your character learns and reasons. This ability is important for wizards because it affects how many spells they can cast, how hard their spells are to resist, and how powerful their spells can be. It’s also important for any character who wants to have a wide assortment of skills.
You apply your character’s Intelligence modifier to:

* The number of languages your character knows at the start of the game.
* The number of skill points gained each level. (But your character always gets at least 1 skill point per level.)
* Appraise, Craft, Decipher Script, Disable Device, Forgery, Knowledge, Search, and Spellcraft checks. These are the skills that have Intelligence as their key ability.

A wizard gains bonus spells based on her Intelligence score. The minimum Intelligence score needed to cast a wizard spell is 10 + the spell’s level. 

An animal has an Intelligence score of 1 or 2. A creature of humanlike intelligence has a score of at least 3.

Wisdom (WIS)
++++++++++++
indexterm:[Wisdom]
Wisdom describes a character’s willpower, common sense, perception, and intuition. While Intelligence represents one’s ability to analyze information, Wisdom represents being in tune with and aware of one’s surroundings. Wisdom is the most important ability for clerics and druids, and it is also important for paladins and rangers. If you want your character to have acute senses, put a high score in Wisdom. Every creature has a Wisdom score.
You apply your character’s Wisdom modifier to:

* Will saving throws (for negating the effect of charm person and other spells).
* Heal, Listen, Profession, Sense Motive, Spot, and Survival checks. These are the skills that have Wisdom as their key ability.

Clerics, druids, paladins, and rangers get bonus spells based on their Wisdom scores. The minimum Wisdom score needed to cast a cleric, druid, paladin, or ranger spell is 10 + the spell’s level.

Charisma (CHA)
++++++++++++++
indexterm:[Charisma]
Charisma measures a character’s force of personality, persuasiveness, personal magnetism, ability to lead, and physical attractiveness. This ability represents actual strength of personality, not merely how one is perceived by others in a social setting. Charisma is most important for paladins, sorcerers, and bards. It is also important for clerics, since it affects their ability to turn undead. Every creature has a Charisma score.
You apply your character’s Charisma modifier to:

* Bluff, Diplomacy, Disguise, Gather Information, Handle Animal, Intimidate, Perform, and Use Magic Device checks. These are the skills that have Charisma as their key ability.
* Checks that represent attempts to influence others. 
* Turning checks for clerics and paladins attempting to turn zombies, vampires, and other undead.

Sorcerers and bards get bonus spells based on their Charisma scores. The minimum Charisma score needed to cast a sorcerer or bard spell is 10 + the spell’s level.

When an ability score changes, all attributes associated with that score change accordingly. A character does not retroactively get additional skill points for previous levels if she increases her intelligence.
