Prestige Classes
================

Prestige Class Overview
-----------------------

indexterm:[Prestige Classes]

Prestige classes offer a new form of multiclassing. Unlike the basic
classes, characters must meet Requirements before they can take their first
level of a prestige class. The rules for level advancement apply to this
system, meaning the first step of advancement is always choosing a class. If
a character does not meet the Requirements for a prestige class before that
first step, that character cannot take the first level of that prestige
class.  Taking a prestige class does not incur the experience point
penalties normally associated with multiclassing.

Definitions of Terms
~~~~~~~~~~~~~~~~~~~~

Here are definitions of some terms used in this section.

*Base Class:* One of the standard eleven classes.

*Caster Level:* Generally equal to the number of class levels (see below) in a
spellcasting class. Some prestige classes add caster levels to an existing
class.

*Character Level:* The total level of the character, which is the sum of all
class levels held by that character.

*Class Level:* The level of a character in a particular class. For a character
with levels in only one class, class level and character level are the same.

include::classes/arcane_archer.asciidoc[]

include::classes/arcane_trickster.asciidoc[]

include::classes/archmage.asciidoc[]

include::classes/assassin.asciidoc[]

include::classes/blackguard.asciidoc[]

include::classes/dragon_disciple.asciidoc[]

include::classes/duelist.asciidoc[]

include::classes/dwarven_defender.asciidoc[]

include::classes/eldritch_knight.asciidoc[]

include::classes/hierophant.asciidoc[]

include::classes/horizon_walker.asciidoc[]

include::classes/loremaster.asciidoc[]

include::classes/mystic_theurge.asciidoc[]

include::classes/shadowdancer.asciidoc[]

include::classes/thaumaturgist.asciidoc[]
