Feats
=====

Feats
-----

PREREQUISITES
Some feats have prerequisites. Your character must have the indicated ability score, class feature, feat, skill, base attack bonus, or other quality designated in order to select or use that feat. A character can gain a feat at the same level at which he or she gains the prerequisite.
A character can’t use a feat if he or she has lost a prerequisite.

TYPES OF FEATS
Some feats are general, meaning that no special rules govern them as a group. Others are item creation feats, which allow spellcasters to create magic items of all sorts. A metamagic feat lets a spellcaster prepare and cast a spell with greater effect, albeit as if the spell were a higher spell level than it actually is.

FIGHTER BONUS FEATS
Any feat designated as a fighter feat can be selected as a fighter’s bonus feat. This designation does not restrict characters of other classes from selecting these feats, assuming that they meet any prerequisites.

ITEM CREATION FEATS
An item creation feat lets a spellcaster create a magic item of a certain type. Regardless of the type of items they involve, the various item creation feats all have certain features in common.
XP Cost: Experience that the spellcaster would normally keep is expended when making a magic item. The XP cost equals 1/25 of the cost of the item in gold pieces. A character cannot spend so much XP on an item that he or she loses a level. However, upon gaining enough XP to attain a new level, he or she can immediately expend XP on creating an item rather than keeping the XP to advance a level.
Raw Materials Cost: The cost of creating a magic item equals one-half the sale cost of the item.
Using an item creation feat also requires access to a laboratory or magical workshop, special tools, and so on. A character generally has access to what he or she needs unless unusual circumstances apply.
Time: The time to create a magic item depends on the feat and the cost of the item. The minimum time is one day.
Item Cost: Brew Potion, Craft Wand, and Scribe Scroll create items that directly reproduce spell effects, and the power of these items depends on their caster level—that is, a spell from such an item has the power it would have if cast by a spellcaster of that level. The price of these items (and thus the XP cost and the cost of the raw materials) also depends on the caster level. The caster level must be high enough that the spellcaster creating the item can cast the spell at that level. To find the final price in each case, multiply the caster level by the spell level, then multiply the result by a constant, as shown below:
Scrolls: Base price = spell level x caster level x 25 gp.
Potions: Base price = spell level x caster level x 50 gp.
Wands: Base price = spell level x caster level x 750 gp.
A 0-level spell is considered to have a spell level of 1/2 for the purpose of this calculation.
Extra Costs: Any potion, scroll, or wand that stores a spell with a costly material component or an XP cost also carries a commensurate cost. For potions and scrolls, the creator must expend the material component or pay the XP cost when creating the item.
For a wand, the creator must expend fifty copies of the material component or pay fifty times the XP cost.
Some magic items similarly incur extra costs in material components or XP, as noted in their descriptions.

METAMAGIC FEATS
As a spellcaster’s knowledge of magic grows, she can learn to cast spells in ways slightly different from the ways in which the spells were originally designed or learned. Preparing and casting a spell in such a way is harder than normal but, thanks to metamagic feats, at least it is possible.  Spells modified by a metamagic feat use a spell slot higher than normal. This does not change the level of the spell, so the DC for saving throws against it does not go up.
Wizards and Divine Spellcasters: Wizards and divine spellcasters must prepare their spells in advance. During preparation, the character chooses which spells to prepare with metamagic feats (and thus which ones take up higher-level spell slots than normal).
Sorcerers and Bards: Sorcerers and bards choose spells as they cast them. They can choose when they cast their spells whether to apply their metamagic feats to improve them. As with other spellcasters, the improved spell uses up a higher-level spell slot. But because the sorcerer or bard has not prepared the spell in a metamagic form in advance, he must apply the metamagic feat on the spot. Therefore, such a character must also take more time to cast a metamagic spell (one enhanced by a metamagic feat) than he does to cast a regular spell. If the spell’s normal casting time is 1 action, casting a metamagic version is a full-round action for a sorcerer or bard. (This isn’t the same as a 1-round casting time.)
For a spell with a longer casting time, it takes an extra full-round action to cast the spell.
Spontaneous Casting and Metamagic Feats: A cleric spontaneously casting a cure or inflict spell can cast a metamagic version of it instead. Extra time is also required in this case. Casting a 1-action metamagic spell spontaneously is a full-round action, and a spell with a longer casting time takes an extra full-round action to cast.
Effects of Metamagic Feats on a Spell: In all ways, a metamagic spell operates at its original spell level, even though it is prepared and cast as a higher-level spell. Saving throw modifications are not changed unless stated otherwise in the feat description.
The modifications made by these feats only apply to spells cast directly by the feat user. A spellcaster can’t use a metamagic feat to alter a spell being cast from a wand, scroll, or other device.
Metamagic feats that eliminate components of a spell don’t eliminate the attack of opportunity provoked by casting a spell while threatened. However, casting a spell modified by Quicken Spell does not provoke an attack of opportunity.
Metamagic feats cannot be used with all spells. See the specific feat descriptions for the spells that a particular feat can’t modify.

Multiple Metamagic Feats on a Spell: A spellcaster can apply multiple metamagic feats to a single spell. Changes to its level are cumulative. You can’t apply the same metamagic feat more than once to a single spell.

Magic Items and Metamagic Spells: With the right item creation feat, you can store a metamagic version of a spell in a scroll, potion, or wand. Level limits for potions and wands apply to the spell’s higher spell level (after the application of the metamagic feat). A character doesn’t need the metamagic feat to activate an item storing a metamagic version of a spell.
Counterspelling Metamagic Spells: Whether or not a spell has been enhanced by a metamagic feat does not affect its vulnerability to counterspelling or its ability to counterspell another spell.

FEAT DESCRIPTIONS
Here is the format for feat descriptions.

FEAT NAME [TYPE OF FEAT]
Prerequisite: A minimum ability score, another feat or feats, a minimum base attack bonus, a minimum number of ranks in one or more skills, or a class level that a character must have in order to acquire this feat. This entry is absent if a feat has no prerequisite. A feat may have more than one prerequisite.
Benefit: What the feat enables the character (“you” in the feat description) to do. If a character has the same feat more than once, its benefits do not stack unless indicated otherwise in the description.
In general, having a feat twice is the same as having it once.
Normal: What a character who does not have this feat is limited to or restricted from doing. If not having the feat causes no particular drawback, this entry is absent.
Special: Additional facts about the feat that may be helpful when you decide whether to acquire the feat.


ACROBATIC [GENERAL]
Benefit: You get a +2 bonus on all Jump checks and Tumble checks.

AGILE [GENERAL]
Benefit: You get a +2 bonus on all Balance checks and Escape Artist checks.

ALERTNESS [GENERAL]
Benefit: You get a +2 bonus on all Listen checks and Spot checks.
Special: The master of a familiar gains the benefit of the Alertness feat whenever the familiar is within arm’s reach.

ANIMAL AFFINITY [GENERAL]
Benefit: You get a +2 bonus on all Handle Animal checks and Ride checks.

ARMOR PROFICIENCY (HEAVY) [GENERAL]
Prerequisites: Armor Proficiency (light), Armor Proficiency (medium).
Benefit: See Armor Proficiency (light).
Normal: See Armor Proficiency (light).
Special: Fighters, paladins, and clerics automatically have Armor Proficiency (heavy) as a bonus feat. They need not select it.

ARMOR PROFICIENCY (LIGHT) [GENERAL]
Benefit: When you wear a type of armor with which you are proficient, the armor check penalty for that armor applies only to Balance, Climb, Escape Artist, Hide, Jump, Move Silently, Sleight of Hand, and Tumble checks.
Normal: A character who is wearing armor with which she is not proficient applies its armor check penalty to attack rolls and to all skill checks that involve moving, including Ride.
Special: All characters except wizards, sorcerers, and monks automatically have Armor Proficiency (light) as a bonus feat. They need not select it.

ARMOR PROFICIENCY (MEDIUM) [GENERAL]
Prerequisite: Armor Proficiency (light).
Benefit: See Armor Proficiency (light).
Normal: See Armor Proficiency (light).
Special: Fighters, barbarians, paladins, clerics, druids, and bards automatically have Armor Proficiency (medium) as a bonus feat. They need not select it.

ATHLETIC [GENERAL]
Benefit: You get a +2 bonus on all Climb checks and Swim checks.

AUGMENT SUMMONING [GENERAL]
Prerequisite: Spell Focus (conjuration).
Benefit: Each creature you conjure with any summon spell gains a +4 enhancement bonus to Strength and Constitution for the duration of the spell that summoned it.

BLIND-FIGHT [GENERAL]
Benefit: In melee, every time you miss because of concealment, you can reroll your miss chance percentile roll one time to see if you actually hit.
An invisible attacker gets no advantages related to hitting you in melee. That is, you don’t lose your Dexterity bonus to Armor Class, and the attacker doesn’t get the usual +2 bonus for being invisible. The invisible attacker’s bonuses do still apply for ranged attacks, however.
You take only half the usual penalty to speed for being unable to see. Darkness and poor visibility in general reduces your speed to three-quarters normal, instead of one-half.
Normal: Regular attack roll modifiers for invisible attackers trying to hit you apply, and you lose your Dexterity bonus to AC. The speed reduction for darkness and poor visibility also applies.
Special: The Blind-Fight feat is of no use against a character who is the subject of a blink spell.
A fighter may select Blind-Fight as one of his fighter bonus feats.

BREW POTION [ITEM CREATION]
Prerequisite: Caster level 3rd.
Benefit: You can create a potion of any 3rd-level or lower spell that you know and that targets one or more creatures. Brewing a potion takes one day. When you create a potion, you set the caster level, which must be sufficient to cast the spell in question and no higher than your own level. The base price of a potion is its spell level x its caster level x 50 gp. To brew a potion, you must spend 1/25 of this base price in XP and use up raw materials costing one half this base price.
When you create a potion, you make any choices that you would normally make when casting the spell. Whoever drinks the potion is the target of the spell.
Any potion that stores a spell with a costly material component or an XP cost also carries a commensurate cost. In addition to the costs derived from the base price, you must expend the material component or pay the XP when creating the potion.

CLEAVE [GENERAL]
Prerequisites: Str 13, Power Attack.
Benefit: If you deal a creature enough damage to make it drop (typically by dropping it to below 0 hit points or killing it), you get an immediate, extra melee attack against another creature within reach. You cannot take a 5-foot step before making this extra attack. The extra attack is with the same weapon and at the same bonus as the attack that dropped the previous creature. You can use this ability once per round.
Special: A fighter may select Cleave as one of his fighter bonus feats.

COMBAT CASTING [GENERAL]
Benefit: You get a +4 bonus on Concentration checks made to cast a spell or use a spell-like ability while on the defensive or while you are grappling or pinned.

COMBAT EXPERTISE [GENERAL]
Prerequisite: Int 13.
Benefit: When you use the attack action or the full attack action in melee, you can take a penalty of as much as –5 on your attack roll and add the same number (+5 or less) as a dodge bonus to your Armor Class. This number may not exceed your base attack bonus. The changes to attack rolls and Armor Class last until your next action.
Normal: A character without the Combat Expertise feat can fight defensively while using the attack or full attack action to take a –4 penalty on attack rolls and gain a +2 dodge bonus to Armor Class.
Special: A fighter may select Combat Expertise as one of his fighter bonus feats.

COMBAT REFLEXES [GENERAL]
Benefit: You may make a number of additional attacks of opportunity equal to your Dexterity bonus.
With this feat, you may also make attacks of opportunity while flat-footed.
Normal: A character without this feat can make only one attack of opportunity per round and can’t make attacks of opportunity while flat-footed.
Special: The Combat Reflexes feat does not allow a rogue to use her opportunist ability more than once per round.
A fighter may select Combat Reflexes as one of his fighter bonus feats.
A monk may select Combat Reflexes as a bonus feat at 2nd level.

CRAFT MAGIC ARMS AND ARMOR [ITEM CREATION]
Prerequisite: Caster level 5th.
Benefit: You can create any magic weapon, armor, or shield whose prerequisites you meet. Enhancing a weapon, suit of armor, or shield takes one day for each 1,000 gp in the price of its magical features. To enhance a weapon, suit of armor, or shield, you must spend 1/25 of its features’ total price in XP and use up raw materials costing one-half of this total price.
The weapon, armor, or shield to be enhanced must be a masterwork item that you provide. Its cost is not included in the above cost.
You can also mend a broken magic weapon, suit of armor, or shield if it is one that you could make. Doing so costs half the XP, half the raw materials, and half the time it would take to craft that item in the first place.

CRAFT ROD [ITEM CREATION]
Prerequisite: Caster level 9th.
Benefit: You can create any rod whose prerequisites you meet. Crafting a rod takes one day for each 1,000 gp in its base price. To craft a rod, you must spend 1/25 of its base price in XP and use up raw materials costing one-half of its base price.
Some rods incur extra costs in material components or XP, as noted in their descriptions. These costs are in addition to those derived from the rod’s base price.

CRAFT STAFF [ITEM CREATION]
Prerequisite: Caster level 12th.
Benefit: You can create any staff whose prerequisites you meet.
Crafting a staff takes one day for each 1,000 gp in its base price. To craft a staff, you must spend 1/25 of its base price in XP and use up raw materials costing one-half of its base price. A newly created staff has 50 charges.
Some staffs incur extra costs in material components or XP, as noted in their descriptions. These costs are in addition to those derived from the staff ’s base price.

CRAFT WAND [ITEM CREATION]
Prerequisite: Caster level 5th.
Benefit: You can create a wand of any 4th-level or lower spell that you know. Crafting a wand takes one day for each 1,000 gp in its base price. The base price of a wand is its caster level x the spell level x 750 gp. To craft a wand, you must spend 1/25 of this base price in XP and use up raw materials costing one-half of this base price. A newly created wand has 50 charges.
Any wand that stores a spell with a costly material component or an XP cost also carries a commensurate cost. In addition to the cost derived from the base price, you must expend fifty copies of the material component or pay fifty times the XP cost.

CRAFT WONDROUS ITEM [ITEM CREATION]
Prerequisite: Caster level 3rd.
Benefit: You can create any wondrous item whose prerequisites you meet. Enchanting a wondrous item takes one day for each 1,000 gp in its price. To enchant a wondrous item, you must spend 1/25 of the item’s price in XP and use up raw materials costing half of this price.
You can also mend a broken wondrous item if it is one that you could make. Doing so costs half the XP, half the raw materials, and half the time it would take to craft that item in the first place.
Some wondrous items incur extra costs in material components or XP, as noted in their descriptions. These costs are in addition to those derived from the item’s base price. You must pay such a cost to create an item or to mend a broken one.

DECEITFUL [GENERAL]
Benefit: You get a +2 bonus on all Disguise checks and Forgery checks.

DEFLECT ARROWS [GENERAL]
Prerequisites: Dex 13, Improved Unarmed Strike.
Benefit: You must have at least one hand free (holding nothing) to use this feat. Once per round when you would normally be hit with a ranged weapon, you may deflect it so that you take no damage from it. You must be aware of the attack and not flatfooted.
Attempting to deflect a ranged weapon doesn’t count as an action. Unusually massive ranged weapons and ranged attacks generated by spell effects can’t be deflected.
Special: A monk may select Deflect Arrows as a bonus feat at 2nd level, even if she does not meet the prerequisites.
A fighter may select Deflect Arrows as one of his fighter bonus feats.

DEFT HANDS [GENERAL]
Benefit: You get a +2 bonus on all Sleight of Hand checks and Use Rope checks.

DIEHARD [GENERAL]
Prerequisite: Endurance.
Benefit: When reduced to between –1 and –9 hit points, you automatically become stable. You don’t have to roll d% to see if you lose 1 hit point each round.
When reduced to negative hit points, you may choose to act as if you were disabled, rather than dying. You must make this decision as soon as you are reduced to negative hit points (even if it isn’t your turn). If you do not choose to act as if you were disabled, you immediately fall unconscious.
When using this feat, you can take either a single move or standard action each turn, but not both, and you cannot take a full round action. You can take a move action without further injuring yourself, but if you perform any standard action (or any other action deemed as strenuous, including some free actions, such as casting a quickened spell) you take 1 point of damage after completing the act. If you reach –10 hit points, you immediately die.
Normal: A character without this feat who is reduced to between –1 and –9 hit points is unconscious and dying.

DILIGENT [GENERAL]
Benefit: You get a +2 bonus on all Appraise checks and Decipher Script checks.

DODGE [GENERAL]
Prerequisite: Dex 13.
Benefit: During your action, you designate an opponent and receive a +1 dodge bonus to Armor Class against attacks from that opponent. You can select a new opponent on any action.
A condition that makes you lose your Dexterity bonus to Armor Class (if any) also makes you lose dodge bonuses. Also, dodge bonuses stack with each other, unlike most other types of bonuses.
Special: A fighter may select Dodge as one of his fighter bonus feats.

EMPOWER SPELL [METAMAGIC]
Benefit: All variable, numeric effects of an empowered spell are increased by one-half.
Saving throws and opposed rolls are not affected, nor are spells without random variables. An empowered spell uses up a spell slot two levels higher than the spell’s actual level.

ENDURANCE [GENERAL]
Benefit: You gain a +4 bonus on the following checks and saves: Swim checks made to resist nonlethal damage, Constitution checks made to continue running, Constitution checks made to avoid nonlethal damage from a forced march, Constitution checks made to hold your breath, Constitution checks made to avoid nonlethal damage from starvation or thirst, Fortitude saves made to avoid nonlethal damage from hot or cold environments, and Fortitude saves made to resist damage from suffocation. Also, you may sleep in light or medium armor without becoming fatigued.
Normal: A character without this feat who sleeps in medium or heavier armor is automatically fatigued the next day.
Special: A ranger automatically gains Endurance as a bonus feat at 3rd level. He need not select it.

ENLARGE SPELL [METAMAGIC]
Benefit: You can alter a spell with a range of close, medium, or long to increase its range by 100%. An enlarged spell with a range of close now has a range of 50 ft. + 5 ft./level, while medium-range spells have a range of 200 ft. + 20 ft./level and long-range spells have a range of 800 ft. + 80 ft./level. An enlarged spell uses up a spell slot one level higher than the spell’s actual level.
Spells whose ranges are not defined by distance, as well as spells whose ranges are not close, medium, or long, do not have increased ranges.

ESCHEW MATERIALS [GENERAL]
Benefit: You can cast any spell that has a material component costing 1 gp or less without needing that component. (The casting of the spell still provokes attacks of opportunity as normal.) If the spell requires a material component that costs more than 1 gp, you must have the material component at hand to cast the spell, just as normal.

EXOTIC WEAPON PROFICIENCY [GENERAL]
Choose a type of exotic weapon. You understand how to use that type of exotic weapon in combat.
Prerequisite: Base attack bonus +1 (plus Str 13 for bastard sword or dwarven waraxe).
Benefit: You make attack rolls with the weapon normally.
Normal: A character who uses a weapon with which he or she is not proficient takes a –4 penalty on attack rolls.
Special: You can gain Exotic Weapon Proficiency multiple times. Each time you take the feat, it applies to a new type of exotic weapon. Proficiency with the bastard sword or the dwarven waraxe has an additional prerequisite of Str 13.
A fighter may select Exotic Weapon Proficiency as one of his fighter bonus feats.

EXTEND SPELL [METAMAGIC]
Benefit: An extended spell lasts twice as long as normal. A spell with a duration of concentration, instantaneous, or permanent is not affected by this feat. An extended spell uses up a spell slot one level higher than the spell’s actual level.

EXTRA TURNING [GENERAL]
Prerequisite: Ability to turn or rebuke creatures.
Benefit: Each time you take this feat, you can use your ability to turn or rebuke creatures four more times per day than normal.
If you have the ability to turn or rebuke more than one kind of creature each of your turning or rebuking abilities gains four additional uses per day.
Normal: Without this feat, a character can typically turn or rebuke undead (or other creatures) a number of times per day equal to 3 + his or her Charisma modifier.
Special: You can gain Extra Turning multiple times. Its effects stack. Each time you take the feat, you can use each of your turning or rebuking abilities four additional times per day.

FAR SHOT [GENERAL]
Prerequisite: Point Blank Shot.
Benefit: When you use a projectile weapon, such as a bow, its range increment increases by one-half (multiply by 1-1/2). When you use a thrown weapon, its range increment is doubled.
Special: A fighter may select Far Shot as one of his fighter bonus feats.

FORGE RING [ITEM CREATION]
Prerequisite: Caster level 12th.
Benefit: You can create any ring whose prerequisites you meet. Crafting a ring takes one day for each 1,000 gp in its base price. To craft a ring, you must spend 1/25 of its base price in XP and use up raw materials costing one-half of its base price.
You can also mend a broken ring if it is one that you could make. Doing so costs half the XP, half the raw materials, and half the time it would take to forge that ring in the first place.
Some magic rings incur extra costs in material components or XP, as noted in their descriptions. You must pay such a cost to forge such a ring or to mend a broken one.

GREAT CLEAVE [GENERAL]
Prerequisites: Str 13, Cleave, Power Attack, base attack bonus +4.
Benefit: This feat works like Cleave, except that there is no limit to the number of times you can use it per round.
Special: A fighter may select Great Cleave as one of his fighter bonus feats.

GREAT FORTITUDE [GENERAL]
Benefit: You get a +2 bonus on all Fortitude saving throws.

GREATER SPELL FOCUS [GENERAL]
Choose a school of magic to which you already have applied the Spell Focus feat.
Benefit: Add +1 to the Difficulty Class for all saving throws against spells from the school of magic you select. This bonus stacks with the bonus from Spell Focus.
Special: You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new school of magic to which you already have applied the Spell Focus feat.

GREATER SPELL PENETRATION [GENERAL]
Prerequisite: Spell Penetration.
Benefit: You get a +2 bonus on caster level checks (1d20 + caster level) made to overcome a creature’s spell resistance. This bonus stacks with the one from Spell Penetration.

GREATER TWO-WEAPON FIGHTING [GENERAL]
Prerequisites: Dex 19, Improved Two-Weapon Fighting, Two-Weapon Fighting, base attack bonus +11.
Benefit: You get a third attack with your off-hand weapon, albeit at a –10 penalty.
Special: A fighter may select Greater Two-Weapon Fighting as one of his fighter bonus feats.
An 11th-level ranger who has chosen the two-weapon combat style is treated as having Greater Two-Weapon Fighting, even if he does not have the prerequisites for it, but only when he is wearing light or no armor.

GREATER WEAPON FOCUS [GENERAL]
Choose one type of weapon for which you have already selected Weapon Focus. You can also choose unarmed strike or grapple as your weapon for purposes of this feat.
 Prerequisites: Proficiency with selected weapon, Weapon Focus with selected weapon, fighter level 8th.
Benefit: You gain a +1 bonus on all attack rolls you make using the selected weapon. This bonus stacks with other bonuses on attack rolls, including the one from Weapon Focus (see below).
Special: You can gain Greater Weapon Focus multiple times. Its effects do not stack. Each time you take the feat, it applies to a new type of weapon.
A fighter must have Greater Weapon Focus with a given weapon to gain the Greater Weapon Specialization feat for that weapon. 
A fighter may select Greater Weapon Focus as one of his fighter bonus feats.

GREATER WEAPON SPECIALIZATION [GENERAL]
Choose one type of weapon for which you have already selected Weapon Specialization. You can also choose unarmed strike or grapple as your weapon for purposes of this feat.
 Prerequisites: Proficiency with selected weapon, Greater Weapon Focus with selected weapon, Weapon Focus with selected weapon, Weapon Specialization with selected weapon, fighter level 12th.
Benefit: You gain a +2 bonus on all damage rolls you make using the selected weapon. This bonus stacks with other bonuses on damage rolls, including the one from Weapon Specialization (see below).
Special: You can gain Greater Weapon Specialization multiple times. Its effects do not stack. Each time you take the feat, it applies to a new type of weapon.
A fighter may select Greater Weapon Specialization as one of his fighter bonus feats.

HEIGHTEN SPELL [METAMAGIC]
Benefit: A heightened spell has a higher spell level than normal (up to a maximum of 9th level). Unlike other metamagic feats, Heighten Spell actually increases the effective level of the spell that it modifies. All effects dependent on spell level (such as saving throw DCs and ability to penetrate a lesser globe of invulnerability) are calculated according to the heightened level. The heightened spell is as difficult to prepare and cast as a spell of its effective level. 

IMPROVED BULL RUSH [GENERAL]
Prerequisites: Str 13, Power Attack.
Benefit: When you perform a bull rush you do not provoke an attack of opportunity from the defender. You also gain a +4 bonus on the opposed Strength check you make to push back the defender.
Special: A fighter may select Improved Bull Rush as one of his fighter bonus feats.

IMPROVED COUNTERSPELL [GENERAL]
Benefit: When counterspelling, you may use a spell of the same school that is one or more spell levels higher than the target spell.
Normal: Without this feat, you may counter a spell only with the same spell or with a spell specifically designated as countering the target spell.

IMPROVED CRITICAL [GENERAL]
Choose one type of weapon.
Prerequisite: Proficient with weapon, base attack bonus +8.
Benefit: When using the weapon you selected, your threat range is doubled.
Special: You can gain Improved Critical multiple times. The effects do not stack. Each time you take the feat, it applies to a new type of weapon.
This effect doesn’t stack with any other effect that expands the threat range of a weapon.
A fighter may select Improved Critical as one of his fighter bonus feats.

IMPROVED DISARM [GENERAL]
Prerequisites: Int 13, Combat Expertise.
Benefit: You do not provoke an attack of opportunity when you attempt to disarm an opponent, nor does the opponent have a chance to disarm you. You also gain a +4 bonus on the opposed attack roll you make to disarm your opponent.
Normal: See the normal disarm rules.
Special: A fighter may select Improved Disarm as one of his fighter bonus feats.
A monk may select Improved Disarm as a bonus feat at 6th level, even if she does not meet the prerequisites.

IMPROVED FAMILIAR [GENERAL]
This feat allows spellcasters to acquire a new familiar from a nonstandard list, but only when they could normally acquire a new familiar.
Prerequisites: Ability to acquire a new familiar, compatible alignment, sufficiently high level (see below).
Benefit: When choosing a familiar, the creatures listed below are also available to the spellcaster. The spellcaster may choose a familiar with an alignment up to one step away on each of the alignment axes (lawful through chaotic, good through evil).

Familiar 
Alignment 
Arcane Spellcaster Level
Shocker lizard 
Neutral 
5th
Stirge 
Neutral 
5th
Formian worker 
Lawful neutral 
7th
Imp 
Lawful evil 
7th
Pseudodragon 
Neutral good 
7th
Quasit 
Chaotic evil 
7th

Improved familiars otherwise use the rules for regular familiars, with two exceptions: If the creature’s type is something other than animal, its type does not change; and improved familiars do not gain the ability to speak with other creatures of their kind (although many of them already have the ability to communicate).

The list in the table above presents only a few possible improved familiars. Almost any creature of the same general size and power as those on the list makes a suitable familiar. Nor is the master’s alignment the only possible categorization. For instance, improved familiars could be assigned by the master’s creature type or subtype, as shown below.

Familiar
Type/Subtype
Arcane Spellcaster Level
Celestial hawk1
Good
3rd
Fiendish Tiny viper snake2
Evil
3rd
Air elemental, Small
Air
5th
Earth elemental, Small
Earth
5th
Fire elemental, Small
Fire
5th
Shocker lizard
Electricity
5th
Water elemental, Small
Water
5th
Homunculus3
Undead
7th
Ice mephit
Cold
7th
1 Or other celestial animal from the standard familiar list.
2 Or other fiendish animal from the standard familiar list.
3 The master must first create the homunculus, substituting ichor or another part of the master’s body for blood if necessary.

IMPROVED FEINT [GENERAL]
Prerequisites: Int 13, Combat Expertise.
Benefit: You can make a Bluff check to feint in combat as a move action.
Normal: Feinting in combat is a standard action.
A fighter may select Improved Feint as one of his fighter bonus feats.

IMPROVED GRAPPLE [GENERAL]
Prerequisites: Dex 13, Improved Unarmed Strike.
Benefit: You do not provoke an attack of opportunity when you make a touch attack to start a grapple. You also gain a +4 bonus on all grapple checks, regardless of whether you started the grapple.
Normal: Without this feat, you provoke an attack of opportunity when you make a touch attack to start a grapple.
Special: A fighter may select Improved Grapple as one of his fighter bonus feats.
A monk may select Improved Grapple as a bonus feat at 1st level, even if she does not meet the prerequisites.

IMPROVED INITIATIVE [GENERAL]
Benefit: You get a +4 bonus on initiative checks.
Special: A fighter may select Improved Initiative as one of his fighter bonus feats.

IMPROVED OVERRUN [GENERAL]
Prerequisites: Str 13, Power Attack.
Benefit: When you attempt to overrun an opponent, the target may not choose to avoid you. You also gain a +4 bonus on your Strength check to knock down your opponent.
Normal: Without this feat, the target of an overrun can choose to avoid you or to block you.
Special: A fighter may select Improved Overrun as one of his fighter bonus feats.

IMPROVED PRECISE SHOT [GENERAL]
Prerequisites: Dex 19, Point Blank Shot, Precise Shot, base attack bonus +11.
Benefit: Your ranged attacks ignore the AC bonus granted to targets by anything less than total cover, and the miss chance granted to targets by anything less than total concealment. Total cover and total concealment provide their normal benefits against your ranged attacks.
In addition, when you shoot or throw ranged weapons at a grappling opponent, you automatically strike at the opponent you have chosen.
Normal: See the normal rules on the effects of cover and concealment. Without this feat, a character who shoots or throws a ranged weapon at a target involved in a grapple must roll randomly to see which grappling combatant the attack strikes.
Special: A fighter may select Improved Precise Shot as one of his fighter bonus feats.
An 11th-level ranger who has chosen the archery combat style is treated as having Improved Precise Shot, even if he does not have the prerequisites for it, but only when he is wearing light or no armor.

IMPROVED SHIELD BASH [GENERAL]
Prerequisite: Shield Proficiency.
Benefit: When you perform a shield bash, you may still apply the shield’s shield bonus to your AC.
Normal: Without this feat, a character who performs a shield bash loses the shield’s shield bonus to AC until his or her next turn.
Special: A fighter may select Improved Shield Bash as one of his fighter bonus feats.

IMPROVED SUNDER [GENERAL]
Prerequisites: Str 13, Power Attack.
Benefit: When you strike at an object held or carried by an opponent (such as a weapon or shield), you do not provoke an attack of opportunity.
You also gain a +4 bonus on any attack roll made to attack an object held or carried by another character.
Normal: Without this feat, you provoke an attack of opportunity when you strike at an object held or carried by another character.
Special: A fighter may select Improved Sunder as one of his fighter bonus feats.

IMPROVED TRIP [GENERAL]
Prerequisites: Int 13, Combat Expertise.
Benefit: You do not provoke an attack of opportunity when you attempt to trip an opponent while you are unarmed. You also gain a +4 bonus on your Strength check to trip your opponent.
If you trip an opponent in melee combat, you immediately get a melee attack against that opponent as if you hadn’t used your attack for the trip attempt. 
Normal: Without this feat, you provoke an attack of opportunity when you attempt to trip an opponent while you are unarmed.
Special: At 6th level, a monk may select Improved Trip as a bonus feat, even if she does not have the prerequisites.
A fighter may select Improved Trip as one of his fighter bonus feats.

IMPROVED TURNING [GENERAL]
Prerequisite: Ability to turn or rebuke creatures.
Benefit: You turn or rebuke creatures as if you were one level higher than you are in the class that grants you the ability.

IMPROVED TWO-WEAPON FIGHTING [GENERAL]
Prerequisites: Dex 17, Two-Weapon Fighting, base attack bonus +6.
Benefit: In addition to the standard single extra attack you get with an off-hand weapon, you get a second attack with it, albeit at a –5 penalty.
Normal: Without this feat, you can only get a single extra attack with an off-hand weapon.
Special: A fighter may select Improved Two-Weapon Fighting as one of his fighter bonus feats.
A 6th-level ranger who has chosen the two-weapon combat style is treated as having Improved Two-Weapon Fighting, even if he does not have the prerequisites for it, but only when he is wearing light or no armor.

IMPROVED UNARMED STRIKE [GENERAL]
Benefit: You are considered to be armed even when unarmed —that is, you do not provoke attacks or opportunity from armed opponents when you attack them while unarmed. However, you still get an attack of opportunity against any opponent who makes an unarmed attack on you.
In addition, your unarmed strikes can deal lethal or nonlethal damage, at your option.
Normal: Without this feat, you are considered unarmed when attacking with an unarmed strike, and you can deal only nonlethal damage with such an attack.
Special: A monk automatically gains Improved Unarmed Strike as a bonus feat at 1st level. She need not select it. 
A fighter may select Improved Unarmed Strike as one of his fighter bonus feats.

INVESTIGATOR [GENERAL]
Benefit: You get a +2 bonus on all Gather Information checks and Search checks.

IRON WILL [GENERAL]
Benefit: You get a +2 bonus on all Will saving throws.

LEADERSHIP [GENERAL]
Prerequisite: Character level 6th.
Benefits: Having this feat enables the character to attract loyal companions and devoted followers, subordinates who assist her. See the table below for what sort of cohort and how many followers the character can recruit.
Leadership Modifiers: Several factors can affect a character’s Leadership score, causing it to vary from the base score (character level + Cha modifier). A character’s reputation (from the point of view of the cohort or follower he is trying to attract) raises or lowers his Leadership score:

Leader’s Reputation 
Modifier
Great renown 
+2
Fairness and generosity 
+1
Special power 
+1
Failure 
–1
Aloofness 
–1
Cruelty 
–2

Other modifiers may apply when the character tries to attract a cohort:
The Leader . . . 
Modifier
Has a familiar, special mount, or animal companion 
–2
Recruits a cohort of a different alignment
–1
Caused the death of a cohort 
–2*
* Cumulative per cohort killed.

Followers have different priorities from cohorts. When the character tries to attract a new follower, use any of the following modifiers that apply.
The Leader . . . 
Modifier
Has a stronghold, base of operations, guildhouse, or the like
+2
Moves around a lot 
–1
Caused the death of other followers 
–1.

Leadership Score
Cohort Level
—— Number of Followers by Level ——


1st
2nd
3rd
4th
5th
6th
1 or lower
—
—
—
—
—
—
—
2
1st
—
—
—
—
—
—
3
2nd
—
—
—
—
—
—
4
3rd
—
—
—
—
—
—
5
3rd
—
—
—
—
—
—
6
4th
—
—
—
—
—
—
7
5th
—
—
—
—
—
—
8
5th
—
—
—
—
—
—
9
6th
—
—
—
—
—
—
10
7th
5
—
—
—
—
—
11
7th
6
—
—
—
—
—
12
8th
8
—
—
—
—
—
13
9th
10
1
—
—
—
—
14
10th
15
1
—
—
—
—
15
10th
20
2
1
—
—
—
16
11th
25
2
1
—
—
—
17
12th
30
3
1
1
—
—
18
12th
35
3
1
1
—
—
19
13th
40
4
2
1
1
—
20
14th
50
5
3
2
1
—
21
15th
60
6
3
2
1
1
22
15th
75
7
4
2
2
1
23
16th
90
9
5
3
2
1
24
17th
110
11
6
3
2
1
25 or higher
17th
135
13
7
4
2
2

Leadership Score: A character’s base Leadership score equals his level plus any Charisma modifier. In order to take into account negative Charisma modifiers, this table allows for very low Leadership scores, but the character must still be 6th level or higher in order to gain the Leadership feat. Outside factors can affect a character’s Leadership score, as detailed above.
Cohort Level: The character can attract a cohort of up to this level. Regardless of a character’s Leadership score, he can only recruit a cohort who is two or more levels lower than himself. The cohort should be equipped with gear appropriate for its level. A character can try to attract a cohort of a particular race, class, and alignment. The cohort’s alignment may not be opposed to the leader’s alignment on either the law-vs-chaos or good-vs-evil axis, and the leader takes a Leadership penalty if he recruits a cohort of an alignment different from his own.
Cohorts earn XP as follows:
The cohort does not count as a party member when determining the party’s XP.
Divide the cohort’s level by the level of the PC with whom he or she is associated (the character with the Leadership feat who attracted the cohort).
Multiply this result by the total XP awarded to the PC and add that number of experience points to the cohort’s total.
If a cohort gains enough XP to bring it to a level one lower than the associated PC’s character level, the cohort does not gain the new level—its new XP total is 1 less than the amount needed attain the next level. 

Number of Followers by Level: The character can lead up to the indicated number of characters of each level. Followers are similar to cohorts, except they’re generally low-level NPCs. Because they’re generally five or more levels behind the character they follow, they’re rarely effective in combat.
Followers don’t earn experience and thus don’t gain levels. However, when a character with Leadership attains a new level, the player consults the table above to determine if she has acquired more followers, some of which may be higher level than the existing followers. (You don’t consult the table to see if your cohort gains levels, however, because cohorts earn experience on their own.)

LIGHTNING REFLEXES [GENERAL]
Benefit: You get a +2 bonus on all Reflex saving throws.

MAGICAL APTITUDE [GENERAL]
Benefit: You get a +2 bonus on all Spellcraft checks and Use Magic Device checks.

MANYSHOT [GENERAL]
Prerequisites: Dex 17, Point Blank Shot, Rapid Shot, base attack bonus +6
Benefit: As a standard action, you may fire two arrows at a single opponent within 30 feet. Both arrows use the same attack roll (with a –4 penalty) to determine success and deal damage normally (but see Special).
For every five points of base attack bonus you have above +6, you may add one additional arrow to this attack, to a maximum of four arrows at a base attack bonus of +16. However, each arrow after the second adds a cumulative –2 penalty on the attack roll (for a total penalty of –6 for three arrows and –8 for four).
Damage reduction and other resistances apply separately against each arrow fired.
Special: Regardless of the number of arrows you fire, you apply precision-based damage only once. If you score a critical hit, only the first arrow fired deals critical damage; all others deal regular damage.
A fighter may select Manyshot as one of his fighter bonus feats.
A 6th-level ranger who has chosen the archery combat style is treated as having Manyshot even if he does not have the prerequisites for it, but only when he is wearing light or no armor.

MARTIAL WEAPON PROFICIENCY [GENERAL]
Choose a type of martial weapon. You understand how to use that type of martial weapon in combat.
Benefit: You make attack rolls with the selected weapon normally.
Normal: When using a weapon with which you are not proficient, you take a –4 penalty on attack rolls.
Special: Barbarians, fighters, paladins, and rangers are proficient with all martial weapons. They need not select this feat.
You can gain Martial Weapon Proficiency multiple times. Each time you take the feat, it applies to a new type of weapon. 
A cleric who chooses the War domain automatically gains the Martial Weapon Proficiency feat related to his deity’s favored weapon as a bonus feat, if the weapon is a martial one. He need not select it.

MAXIMIZE SPELL [METAMAGIC]
Benefit: All variable, numeric effects of a spell modified by this feat are maximized. Saving throws and opposed rolls are not affected, nor are spells without random variables. A maximized spell uses up a spell slot three levels higher than the spell’s actual level.
An empowered, maximized spell gains the separate benefits of each feat: the maximum result plus one-half the normally rolled result.

MOBILITY [GENERAL]
Prerequisites: Dex 13, Dodge.
Benefit: You get a +4 dodge bonus to Armor Class against attacks of opportunity caused when you move out of or within a threatened area. A condition that makes you lose your Dexterity bonus to Armor Class (if any) also makes you lose dodge bonuses.
Dodge bonuses stack with each other, unlike most types of bonuses.
Special: A fighter may select Mobility as one of his fighter bonus feats.

MOUNTED ARCHERY [GENERAL]
Prerequisites: Ride 1 rank, Mounted Combat.
Benefit: The penalty you take when using a ranged weapon while mounted is halved: –2 instead of –4 if your mount is taking a double move, and –4 instead of –8 if your mount is running.
Special: A fighter may select Mounted Archery as one of his fighter bonus feats.

MOUNTED COMBAT [GENERAL]
Prerequisite: Ride 1 rank.
Benefit: Once per round when your mount is hit in combat, you may attempt a Ride check (as a reaction) to negate the hit. The hit is negated if your Ride check result is greater than the opponent’s attack roll. (Essentially, the Ride check result becomes the mount’s Armor Class if it’s higher than the mount’s regular AC.)
Special: A fighter may select Mounted Combat as one of his fighter bonus feats.

NATURAL SPELL [GENERAL]
Prerequisites: Wis 13, wild shape ability.
Benefit: You can complete the verbal and somatic components of spells while in a wild shape. You substitute various noises and gestures for the normal verbal and somatic components of a spell.
You can also use any material components or focuses you possess, even if such items are melded within your current form. This feat does not permit the use of magic items while you are in a form that could not ordinarily use them, and you do not gain the ability to speak while in a wild shape.

NEGOTIATOR [GENERAL]
Benefit: You get a +2 bonus on all Diplomacy checks and Sense Motive checks.

NIMBLE FINGERS [GENERAL]
Benefit: You get a +2 bonus on all Disable Device checks and Open Lock checks.

PERSUASIVE [GENERAL]
Benefit: You get a +2 bonus on all Bluff checks and Intimidate checks.

POINT BLANK SHOT [GENERAL]
Benefit: You get a +1 bonus on attack and damage rolls with ranged weapons at ranges of up to 30 feet.
Special: A fighter may select Point Blank Shot as one of his fighter bonus feats.

POWER ATTACK [GENERAL]
Prerequisite: Str 13.
Benefit: On your action, before making attack rolls for a round, you may choose to subtract a number from all melee attack rolls and add the same number to all melee damage rolls. This number may not exceed your base attack bonus. The penalty on attacks and bonus on damage apply until your next turn.
Special: If you attack with a two-handed weapon, or with a one-handed weapon wielded in two hands, instead add twice the number subtracted from your attack rolls. You can’t add the bonus from Power Attack to the damage dealt with a light weapon (except with unarmed strikes or natural weapon attacks), even though the penalty on attack rolls still applies. (Normally, you treat a double weapon as a one-handed weapon and a light weapon. If you choose to use a double weapon like a two-handed weapon, attacking with only one end of it in a round, you treat it as a two-handed weapon.)
A fighter may select Power Attack as one of his fighter bonus feats.

PRECISE SHOT [GENERAL]
Prerequisite: Point Blank Shot.
Benefit: You can shoot or throw ranged weapons at an opponent engaged in melee without taking the standard –4 penalty on your attack roll.
Special: A fighter may select Precise Shot as one of his fighter bonus feats.

QUICK DRAW [GENERAL]
Prerequisite: Base attack bonus +1.
Benefit: You can draw a weapon as a free action instead of as a move action. You can draw a hidden weapon (see the Sleight of Hand skill) as a move action.
A character who has selected this feat may throw weapons at his full normal rate of attacks (much like a character with a bow).
Normal: Without this feat, you may draw a weapon as a move action, or (if your base attack bonus is +1 or higher) as a free action as part of movement. Without this feat, you can draw a hidden weapon as a standard action.
Special: A fighter may select Quick Draw as one of his fighter bonus feats.

QUICKEN SPELL [METAMAGIC]
Benefit: Casting a quickened spell is a free action. You can perform another action, even casting another spell, in the same round as you cast a quickened spell. You may cast only one quickened spell per round. A spell whose casting time is more than 1 full round action cannot be quickened. A quickened spell uses up a spell slot four levels higher than the spell’s actual level. Casting a quickened spell doesn’t provoke an attack of opportunity.
Special: This feat can’t be applied to any spell cast spontaneously (including sorcerer spells, bard spells, and cleric or druid spells cast spontaneously), since applying a metamagic feat to a spontaneously cast spell automatically increases the casting time to a full-round action.

RAPID RELOAD [GENERAL]
Choose a type of crossbow (hand, light, or heavy).
Prerequisite: Weapon Proficiency (crossbow type chosen).
Benefit: The time required for you to reload your chosen type of crossbow is reduced to a free action (for a hand or light crossbow) or a move action (for a heavy crossbow). Reloading a crossbow still provokes an attack of opportunity.
If you have selected this feat for hand crossbow or light crossbow, you may fire that weapon as many times in a full attack action as you could attack if you were using a bow.
Normal: A character without this feat needs a move action to reload a hand or light crossbow, or a full-round action to reload a heavy crossbow. 
Special: You can gain Rapid Reload multiple times. Each time you take the feat, it applies to a new type of crossbow.
A fighter may select Rapid Reload as one of his fighter bonus feats.

RAPID SHOT [GENERAL]
Prerequisites: Dex 13, Point Blank Shot.
Benefit: You can get one extra attack per round with a ranged weapon. The attack is at your highest base attack bonus, but each attack you make in that round (the extra one and the normal ones) takes a –2 penalty. You must use the full attack action to use this feat.
Special: A fighter may select Rapid Shot as one of his fighter bonus feats.
A 2nd-level ranger who has chosen the archery combat style is treated as having Rapid Shot, even if he does not have the prerequisites for it, but only when he is wearing light or no armor.

RIDE-BY ATTACK [GENERAL]
Prerequisites: Ride 1 rank, Mounted Combat.
Benefit: When you are mounted and use the charge action, you may move and attack as if with a standard charge and then move again (continuing the straight line of the charge). Your total movement for the round can’t exceed double your mounted speed. You and your mount do not provoke an attack of opportunity from the opponent that you attack.
Special: A fighter may select Ride-By Attack as one of his fighter bonus feats.

RUN [GENERAL]
Benefit: When running, you move five times your normal speed (if wearing medium, light, or no armor and carrying no more than a medium load) or four times your speed (if wearing heavy armor or carrying a heavy load). If you make a jump after a running start (see the Jump skill description), you gain a +4 bonus on your Jump check. While running, you retain your Dexterity bonus to AC.
Normal: You move four times your speed while running (if wearing medium, light, or no armor and carrying no more than a medium load) or three times your speed (if wearing heavy armor or carrying a heavy load), and you lose your Dexterity bonus to AC.

SCRIBE SCROLL [ITEM CREATION]
Prerequisite: Caster level 1st.
Benefit: You can create a scroll of any spell that you know. Scribing a scroll takes one day for each 1,000 gp in its base price. The base price of a scroll is its spell level x its caster level x 25 gp. To scribe a scroll, you must spend 1/25 of this base price in XP and use up raw materials costing one-half of this base price.
Any scroll that stores a spell with a costly material component or an XP cost also carries a commensurate cost. In addition to the costs derived from the base price, you must expend the material component or pay the XP when scribing the scroll.

SELF-SUFFICIENT [GENERAL]
Benefit: You get a +2 bonus on all Heal checks and Survival checks.

SHIELD PROFICIENCY [GENERAL]
Benefit: You can use a shield and take only the standard penalties.
Normal: When you are using a shield with which you are not proficient, you take the shield’s armor check penalty on attack rolls and on all skill checks that involve moving, including Ride checks.
Special: Barbarians, bards, clerics, druids, fighters, paladins, and rangers automatically have Shield Proficiency as a bonus feat. They need not select it.

SHOT ON THE RUN [GENERAL]
Prerequisites: Dex 13, Dodge, Mobility, Point Blank Shot, base attack bonus +4.
Benefit: When using the attack action with a ranged weapon, you can move both before and after the attack, provided that your total distance moved is not greater than your speed.
Special: A fighter may select Shot on the Run as one of his fighter bonus feats.

SILENT SPELL [METAMAGIC]
Benefit: A silent spell can be cast with no verbal components. Spells without verbal components are not affected. A silent spell uses up a spell slot one level higher than the spell’s actual level.
Special: Bard spells cannot be enhanced by this metamagic feat.

SIMPLE WEAPON PROFICIENCY [GENERAL]
Benefit: You make attack rolls with simple weapons normally.
Normal: When using a weapon with which you are not proficient, you take a –4 penalty on attack rolls.
Special: All characters except for druids, monks, and wizards are automatically proficient with all simple weapons. They need not select this feat.

SKILL FOCUS [GENERAL]
Choose a skill.
Benefit: You get a +3 bonus on all checks involving that skill.
Special: You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new skill.

SNATCH ARROWS [GENERAL]
Prerequisites: Dex 15, Deflect Arrows, Improved Unarmed Strike.
Benefit: When using the Deflect Arrows feat you may catch the weapon instead of just deflecting it. Thrown weapons can immediately be thrown back at the original attacker (even though it isn’t your turn) or kept for later use.
You must have at least one hand free (holding nothing) to use this feat.
Special: A fighter may select Snatch Arrows as one of his fighter bonus feats.

SPELL FOCUS [GENERAL]
Choose a school of magic.
Benefit: Add +1 to the Difficulty Class for all saving throws against spells from the school of magic you select.
Special: You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new school of magic.

SPELL MASTERY [SPECIAL]
Prerequisite: Wizard level 1st.
Benefit: Each time you take this feat, choose a number of spells equal to your Intelligence modifier that you already know. From that point on, you can prepare these spells without referring to a spellbook.
Normal: Without this feat, you must use a spellbook to prepare all your spells, except read magic.

SPELL PENETRATION [GENERAL]
Benefit: You get a +2 bonus on caster level checks (1d20 + caster level) made to overcome a creature’s spell resistance.

SPIRITED CHARGE [GENERAL]
Prerequisites: Ride 1 rank, Mounted Combat, Ride-By Attack.
Benefit: When mounted and using the charge action, you deal double damage with a melee weapon (or triple damage with a lance).
Special: A fighter may select Spirited Charge as one of his fighter bonus feats.

SPRING ATTACK [GENERAL]
Prerequisites: Dex 13, Dodge, Mobility, base attack bonus +4.
Benefit: When using the attack action with a melee weapon, you can move both before and after the attack, provided that your total distance moved is not greater than your speed. Moving in this way does not provoke an attack of opportunity from the defender you attack, though it might provoke attacks of opportunity from other creatures, if appropriate. You can’t use this feat if you are wearing heavy armor.
You must move at least 5 feet both before and after you make your attack in order to utilize the benefits of Spring Attack.
Special: A fighter may select Spring Attack as one of his fighter bonus feats.

STEALTHY [GENERAL]
Benefit: You get a +2 bonus on all Hide checks and Move Silently checks.

STILL SPELL [METAMAGIC]
Benefit: A stilled spell can be cast with no somatic components.
Spells without somatic components are not affected. A stilled spell uses up a spell slot one level higher than the spell’s actual level.

STUNNING FIST [GENERAL]
Prerequisites: Dex 13, Wis 13, Improved Unarmed Strike, base attack bonus +8.
Benefit: You must declare that you are using this feat before you make your attack roll (thus, a failed attack roll ruins the attempt). Stunning Fist forces a foe damaged by your unarmed attack to make a Fortitude saving throw (DC 10 + 1/2 your character level + your Wis modifier), in addition to dealing damage normally. A defender who fails this saving throw is stunned for 1 round (until just before your next action). A stunned character can’t act, loses any Dexterity bonus to AC, and takes a –2 penalty to AC. You may attempt a stunning attack once per day for every four levels you have attained (but see Special), and no more than once per round. Constructs, oozes, plants, undead, incorporeal creatures, and creatures immune to critical hits cannot be stunned.
Special: A monk may select Stunning Fist as a bonus feat at 1st level, even if she does not meet the prerequisites. A monk who selects this feat may attempt a stunning attack a number of times per day equal to her monk level, plus one more time per day for every four levels she has in classes other than monk.
A fighter may select Stunning Fist as one of his fighter bonus feats.

TOUGHNESS [GENERAL]
Benefit: You gain +3 hit points.
Special: A character may gain this feat multiple times. Its effects stack.

TOWER SHIELD PROFICIENCY [GENERAL]
Prerequisite: Shield Proficiency.
Benefit: You can use a tower shield and suffer only the standard penalties.
Normal: A character who is using a shield with which he or she is not proficient takes the shield’s armor check penalty on attack rolls and on all skill checks that involve moving, including Ride.
Special: Fighters automatically have Tower Shield Proficiency as a bonus feat. They need not select it.

TRACK [GENERAL]
Benefit: To find tracks or to follow them for 1 mile requires a successful Survival check. You must make another Survival check every time the tracks become difficult to follow.
You move at half your normal speed (or at your normal speed with a –5 penalty on the check, or at up to twice your normal speed with a –20 penalty on the check). The DC depends on the surface and the prevailing conditions, as given on the table below:

Surface
Survival DC 
Surface Survival 
DC
Very soft ground 
5 
Firm ground 
15
Soft ground 
10 
Hard ground 
20

Very Soft Ground: Any surface (fresh snow, thick dust, wet mud) that holds deep, clear impressions of footprints.
Soft Ground: Any surface soft enough to yield to pressure, but firmer than wet mud or fresh snow, in which a creature leaves frequent but shallow footprints.
Firm Ground: Most normal outdoor surfaces (such as lawns, fields, woods, and the like) or exceptionally soft or dirty indoor surfaces (thick rugs and very dirty or dusty floors). The creature might leave some traces (broken branches or tufts of hair), but it leaves only occasional or partial footprints.
Hard Ground: Any surface that doesn’t hold footprints at all, such as bare rock or an indoor floor. Most streambeds fall into this category, since any footprints left behind are obscured or washed away. The creature leaves only traces (scuff marks or displaced pebbles). 
Several modifiers may apply to the Survival check, as given on the table below.

Condition 
Survival DC Modifier
Every three creatures in the group being tracked 
–1
Size of creature or creatures being tracked:1

Fine 
+8
Diminutive 
+4
Tiny 
+2
Small 
+1
Medium 
+0
Large 
–1
Huge 
–2
Gargantuan 
–4
Colossal 
–8
Every 24 hours since the trail was made 
+1
Every hour of rain since the trail was made 
+1
Fresh snow cover since the trail was made 
+10
Poor visibility:2

Overcast or moonless night 
+6
Moonlight 
+3
Fog or precipitation 
+3
Tracked party hides trail (and moves at half speed) 
+5
1 For a group of mixed sizes, apply only the modifier for the largest size category.
2 Apply only the largest modifier from this category.

If you fail a Survival check, you can retry after 1 hour (outdoors) or 10 minutes (indoors) of searching.
Normal: Without this feat, you can use the Survival skill to find tracks, but you can follow them only if the DC for the task is 10 or lower. Alternatively, you can use the Search skill to find a footprint or similar sign of a creature’s passage using the DCs given above, but you can’t use Search to follow tracks, even if someone else has already found them.
Special: A ranger automatically has Track as a bonus feat. He need not select it.
This feat does not allow you to find or follow the tracks made by a subject of a pass without trace spell.

TRAMPLE [GENERAL]
Prerequisites: Ride 1 rank, Mounted Combat.
Benefit: When you attempt to overrun an opponent while mounted, your target may not choose to avoid you. Your mount may make one hoof attack against any target you knock down, gaining the standard +4 bonus on attack rolls against prone targets.
Special: A fighter may select Trample as one of his fighter bonus feats.

TWO-WEAPON DEFENSE [GENERAL]
Prerequisites: Dex 15, Two-Weapon Fighting.
Benefit: When wielding a double weapon or two weapons (not including natural weapons or unarmed strikes), you gain a +1 shield bonus to your AC.
When you are fighting defensively or using the total defense action, this shield bonus increases to +2.
Special: A fighter may select Two-Weapon Defense as one of his fighter bonus feats.

TWO-WEAPON FIGHTING [GENERAL]
You can fight with a weapon in each hand. You can make one extra attack each round with the second weapon.
Prerequisite: Dex 15.
Benefit: Your penalties on attack rolls for fighting with two weapons are reduced. The penalty for your primary hand lessens by 2 and the one for your off hand lessens by 6.
Normal: If you wield a second weapon in your off hand, you can get one extra attack per round with that weapon. When fighting in this way you suffer a –6 penalty with your regular attack or attacks with your primary hand and a –10 penalty to the attack with your off hand. If your off-hand weapon is light the penalties are reduced by 2 each. (An unarmed strike is always considered light.)
Special: A 2nd-level ranger who has chosen the two-weapon combat style is treated as having Two-Weapon Fighting, even if he does not have the prerequisite for it, but only when he is wearing light or no armor.
A fighter may select Two-Weapon Fighting as one of his fighter bonus feats.

WEAPON FINESSE [GENERAL]
Prerequisite: Base attack bonus +1.
Benefit: With a light weapon, rapier, whip, or spiked chain made for a creature of your size category, you may use your Dexterity modifier instead of your Strength modifier on attack rolls. If you carry a shield, its armor check penalty applies to your attack rolls.
Special: A fighter may select Weapon Finesse as one of his fighter bonus feats.
Natural weapons are always considered light weapons.

WEAPON FOCUS [GENERAL]
Choose one type of weapon. You can also choose unarmed strike or grapple (or ray, if you are a spellcaster) as your weapon for purposes of this feat.
 Prerequisites: Proficiency with selected weapon, base attack bonus +1.
Benefit: You gain a +1 bonus on all attack rolls you make using the selected weapon.
Special: You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new type of weapon.
A fighter may select Weapon Focus as one of his fighter bonus feats. He must have Weapon Focus with a weapon to gain the Weapon Specialization feat for that weapon.

WEAPON SPECIALIZATION [GENERAL]
Choose one type of weapon for which you have already selected the Weapon Focus feat. You can also choose unarmed strike or grapple as your weapon for purposes of this feat. You deal extra damage when using this weapon.
 Prerequisites: Proficiency with selected weapon, Weapon Focus with selected weapon, fighter level 4th.
Benefit: You gain a +2 bonus on all damage rolls you make using the selected weapon.
Special: You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new type of weapon.
A fighter may select Weapon Specialization as one of his fighter bonus feats.

WHIRLWIND ATTACK [GENERAL]
Prerequisites: Dex 13, Int 13, Combat Expertise, Dodge, Mobility, Spring Attack, base attack bonus +4.
Benefit: When you use the full attack action, you can give up your regular attacks and instead make one melee attack at your full base attack bonus against each opponent within reach.
When you use the Whirlwind Attack feat, you also forfeit any bonus or extra attacks granted by other feats, spells, or abilities.
Special: A fighter may select Whirlwind Attack as one of his fighter bonus feats.

WIDEN SPELL [METAMAGIC]
Benefit: You can alter a burst, emanation, line, or spread shaped spell to increase its area. Any numeric measurements of the spell’s area increase by 100%.A widened spell uses up a spell slot three levels higher than the spell’s actual level.
Spells that do not have an area of one of these four sorts are not affected by this feat.

Psionic Feats
-------------


Psionic feats are available only to characters and creatures with the ability to manifest powers. (In other words, they either have a power point reserve or have psi-like abilities.)
Because psionic feats are supernatural abilities—a departure from the general rule that feats do not grant supernatural abilities—they cannot be disrupted in combat (as powers can be) and generally do not provoke attacks of opportunity (except as noted in their descriptions). Supernatural abilities are not subject to power resistance and cannot be dispelled; however, they do not function in areas where psionics is suppressed, such as a null psionics field. Leaving such an area immediately allows psionic feats to be used.
Many psionic feats can be used only when you are psionically focused; others require you to expend your psionic focus to gain their benefit. Expending your psionic focus does not require an action; it is part of another action (such as using a feat). When you expend your psionic focus, it applies only to the action for which you expended it.

PSIONIC ITEM CREATION FEATS
Manifesters can use their personal power to create lasting psionic items. Doing so, however, is draining. A manifester must put a little of himself or herself into every psionic item he or she creates.
A psionic item creation feat lets a manifester create a psionic item of a certain type. Regardless of the type of items they involve, the various item creation feats all have certain features in common.
XP Cost: Power and energy that the manifester would normally keep is expended when making a psionic item. The experience point cost of using a psionic item creation feat equals 1/25 the cost of the item in gold pieces. A character cannot spend so much XP on an item that he or she loses a level. However, upon gaining enough XP to attain a new level, he or she can immediately expend XP on creating an item rather than keeping the XP to advance a level.
Raw Materials Cost: Creating a psionic item requires costly components, most of which are consumed in the process. The cost of these materials equals 1/2 the cost of the item.
Using a psionic item creation feat also requires access to a laboratory or psionic workshop, special tools, and other equipment. A character generally has access to what he or she needs unless unusual circumstances apply (such as if he’s traveling far from home).
Time: The time to create a psionic item depends on the feat and the cost of the item. The minimum time is one day.
Item Cost: Craft Dorje, Imprint Stone, and Scribe Tattoo create items that directly reproduce the effects of powers, and the strength of these items depends on their manifester level—that is, a power from such an item has the strength it would have if manifested by a manifester of that level. Often, that is the minimum manifester level necessary to manifest the power. (Randomly discovered items usually follow this rule.) However, when making such an item, the item’s strength can be set higher than the minimum. Any time a character creates an item using a power augmented by spending additional power points, the character’s effective manifester level for the purpose of calculating the item’s cost increases by 1 for each 1 additional power point spent. (Augmentation is a feature of many powers that allows the power to be amplified in various ways if additional power points are spent.) All other level-dependent parameters of the power forged into the item are set according to the effective manifester level.
The price of psionic items (and thus the XP cost and the cost of the raw materials) depends on the level of the power and a character’s manifester level. The character’s manifester level must be high enough that the item creator can manifest the power at the chosen level. To find the final price in each case, multiply the character’s manifester level by the power level, then multiply the result by a constant, as shown below.
Power Stones: Base price = power level x manifester level x 25 gp
Psionic Tattoos: Base price = power level x manifester level x 50 gp
Dorjes: Base price = power level x manifester level x 750 gp
Extra Costs: Any dorje, power stone, or psionic tattoo that stores a power with an XP cost also carries a commensurate cost. 
For psionic tattoos and power stones, the creator must pay the XP cost when creating the item. For a dorje, the creator must pay fifty times the XP cost. 
Some psionic items similarly incur extra costs in XP, as noted in their descriptions.

METAPSIONIC FEATS
As a manifester’s knowledge of psionics grows, he can learn to manifest powers in ways slightly different from how the powers were originally designed or learned. Of course, manifesting a power while using a metapsionic feat is more expensive than manifesting the power normally.
Manifesting Time: Powers manifested using metapsionic feats take the same time as manifesting the powers normally unless the feat description specifically says otherwise.
Manifestation Cost: To use a metapsionic feat, a psionic character must both expend his psionic focus (see the Concentration skill description) and pay an increased power point cost as given in the feat description.
Limits on Use: As with all powers, you cannot spend more power points on a power than your manifester level. Metapsionic feats merely let you manifest powers in different ways; they do not let you violate this rule. 
Effects of Metapsionic Feats on a Power: In all ways, a metapsionic power operates at its original power level, even though it costs additional power points. The modifications to a power made by a metapsionic feat have only their noted effect on the power. A manifester can’t use a metapsionic feat to alter a power being cast from a power stone, dorje, or other device.
Manifesting a power modified by the Quicken Power feat does not provoke attacks of opportunity.
Some metapsionic feats apply only to certain powers, as described in each specific feat entry.
Psionic Items and Metapsionic Powers: With the right psionic item creation feat, you can store a metapsionic power in a power stone, psionic tattoo, or dorje. Level limits for psionic tattoos apply to the power’s higher metapsionic level. 
A character doesn’t need the appropriate metapsionic feat to activate an item in which a metapsionic power is stored, but does need the metapsionic feat to create such an item.

FEAT DESCRIPTIONS
These feat descriptions follow the standard format.

ALIGNED ATTACK [PSIONIC]
Your melee or ranged attack overcomes your opponent’s alignment-based damage reduction and deals additional damage.
Prerequisite: Base attack bonus +6.
Benefit: When you take this feat, choose either chaos, good, evil or law. (Your choice must match one of your alignment components. Once you’ve made this alignment choice, it cannot be changed.
To use this feat, you must expend your psionic focus. When you make a successful melee or ranged attack, you deal an extra 1d6 points of damage, and your attack is treated as either a good, evil, chaotic, or lawful attack (depending on your original choice) for the purpose of overcoming damage reduction.
You must decide whether or not to use this feat prior to making an attack. If your attack misses, you still expend your psionic focus.

ANTIPSIONIC MAGIC [GENERAL]
Your spells are more potent when used against psionic characters and creatures.
Prerequisite: Spellcraft 5 ranks.
Benefit: You get a get a +2 bonus on caster level checks made to overcome a psionic creature’s power resistance.
This bonus stacks with the bonus conferred by Spell Penetration and Greater Spell Penetration. Moreover, whenever a psionic creature attempts to dispel a spell you cast, it makes its manifester level check against a DC of 13 + its manifester level.
The benefits of this feat apply only to power resistance. 
The bonus does not apply to spell resistance. This is an exception to the psionics–magic transparency rule.
Special: You cannot take or use this feat if you have the ability to use powers (if you have a power point reserve or psi-like abilities).

AUTONOMOUS [GENERAL]
You have a knack for psionic self-sufficiency.
Benefit: You get a +2 bonus on all Autohypnosis checks and Knowledge (psionics) checks.

BODY FUEL [PSIONIC]
You can expand your power point total at the expense of your health.
Benefit: You can recover 2 power points by taking 1 point of ability burn damage to each of your three ability scores: Strength, Dexterity, and Constitution.
You can recover additional power points for a proportional cost to Strength, Dexterity, and Constitution. These recovered points are added to your power point reserve as if you had gained them by resting overnight.
Special: Only living creatures can use this feat. You can take advantage of this feat only while in your own body.

BOOST CONSTRUCT [PSIONIC]
Your astral constructs have more abilities.
Benefit: When you create an astral construct, you can give it one additional special ability from any menu that the construct currently has an ability from.

BURROWING POWER [METAPSIONIC]
Your powers sometimes bypass barriers.
Benefit: To use this feat, you must expend your psionic focus. You can attempt to manifest your powers against targets that are sheltered behind a wall or force effect. Your power briefly skips through the Astral Plane to bypass the barrier.
The strength and thickness of the barrier determine your chance of success. To successfully bypass the barrier with your power, you make a Psicraft check against a DC equal to 10 + the hardness of the barrier + 1 per foot of thickness (minimum 1). Assign a hardness of 20 to barriers without a hardness rating, such as force effects (or a wall of ectoplasm). Force walls or walls of ectoplasm are assumed to have less than 1 foot of thickness unless noted otherwise.
If a power requires line of sight (which includes most powers that affect a target or targets instead of an area), you cannot manifest it as a burrowing power unless you can somehow see the target, such as with clairvoyant sense. Using this feat increases the power point cost of the power by 2. The power’s total cost cannot exceed your manifester level.

CHAIN POWER [METAPSIONIC]
You can manifest powers that arc to hit other targets in addition to the primary target. 
Benefit: To use this feat, you must expend your psionic focus. You can chain any power that affects a single target and that deals either acid, cold, electricity, fire, or sonic damage. After the primary target is struck, the power can arc to a number of secondary targets equal to your manifester level (maximum twenty). The secondary arcs each strike one target and deal half as much damage as the primary one did (round down).
Each target gets to make a saving throw, if one is allowed by the power. You choose secondary targets as you like, but they must all be within 30 feet of the primary target, and no target can be struck more than once. You can choose to affect fewer secondary targets than the maximum (to avoid allies in the area, for example).
Using this feat increases the power point cost of the power by 6. The power’s total cost cannot exceed your manifester level.

CHAOTIC MIND [GENERAL]
The turbulence of your thoughts prevents others from gaining insight into your actions.
Prerequisite: Chaotic alignment, Cha 15.
Benefit: Creatures and characters who have an insight bonus on their attack rolls, an insight bonus to their Armor Class, or an insight bonus on skill checks or ability checks do not gain those bonuses against you.
The benefit of this feat applies only to insight bonuses gained from psionic powers and psi-like abilities. This is an exception to the psionics–magic transparency rule.
Special: You cannot take or use this feat if you have the ability to use powers (if you have a power point reserve or psi-like abilities).

CLOAK DANCE [GENERAL]
You are skilled at using optical tricks to make yourself seem to be where you are not.
Prerequisites: Hide 10 ranks, Perform (dance) 2 ranks.
Benefit: You can take a move action to obscure your exact position. Until your next turn, you have concealment. Alternatively, you can take a full-round action to entirely obscure your exact position. Until your next action, you have total concealment.

CLOSED MIND [GENERAL]
Your mind is better able to resist psionics than normal.
Benefit: You get a +2 bonus on all saving throws to resist powers.
The benefit of this feat applies only to psionic powers and psi-like abilities. This is an exception to the psionics–magic transparency rule.
Special: You cannot take or use this feat if you have the ability to use powers (if you have a power point reserve or psi-like abilities).

COMBAT MANIFESTATION [PSIONIC]
You are adept at manifesting powers in combat.
Benefit: You get a +4 bonus on Concentration checks made to manifest a power or use a psi-like ability while on the defensive or while you are grappling or pinned.

CRAFT COGNIZANCE CRYSTAL [ITEM CREATION]
You can create psionic cognizance crystals that store power points.
Prerequisite: Manifester level 3rd.
Benefit: You can create a cognizance crystal. Doing so takes one day for each 1,000 gp in its base price. The base price of a cognizance crystal is equal to the highest-level power it could manifest using all its stored power points, squared, multiplied by 1,000 gp. To create a cognizance crystal, you must spend 1/25 of its base price in XP and use up raw materials costing one-half its base price.

CRAFT DORJE [ITEM CREATION]
You can create slender crystal wands called dorjes than manifest powers when charges are expended.
Prerequisite: Manifester level 5th.
Benefit: You can create a dorje of any psionic power you know (barring exceptions, such as bestow power, as noted in a power’s description). Crafting a dorje takes one day for each 1,000 gp in its base price. The base price of a dorje is its manifester level x the power level x 750 gp. To craft a dorje, you must spend 1/25 of this base price in XP and use up raw materials costing one-half of this base price.
A newly created dorje has 50 charges.
Any dorje that stores a power with an XP cost also carries a commensurate cost. In addition to the XP cost derived from the base price, you must pay fifty times the XP cost.

CRAFT PSICROWN [ITEM CREATION]
You can create psicrowns, which have multiple psionic effects.
Prerequisite: Manifester level 12th.
Benefit: You can create any psicrown whose prerequisites you meet. Crafting a psicrown takes one day for each 1,000 gp in its base price. To craft a psicrown, you must spend 1/25 of its base price in XP and use up raw materials costing one-half of its base price. Some psicrowns incur extra costs in XP as noted in their descriptions. These costs are in addition to those derived from the psicrown’s base price.

CRAFT PSIONIC ARMS AND ARMOR [ITEM CREATION]
You can create psionic weapons, armor, and shields.
Prerequisite: Manifester level 5th.
Benefit: You can create any psionic weapon, armor, or shield whose prerequisites you meet. Enhancing a weapon, suit of armor, or shield takes one day for each 1,000 gp in the price of its psionic features. To enhance a weapon, you must spend 1/25 of its features’ total price in XP and use up raw materials costing one-half of this total price.
The weapon, armor, or shield to be enhanced must be a masterwork item that you provide. Its cost is not included in the above cost.
You can also mend a broken psionic weapon, suit of armor, or shield if it is one that you could make. Doing so costs half the XP, half the raw materials, and half the time it would take to enhance that item in the first place.

CRAFT PSIONIC CONSTRUCT [ITEM CREATION]
You can create golems and other psionic automatons that obey your orders.
Prerequisites: Craft Psionic Arms and Armor, Craft Universal Item.
Benefit: You can create any psionic construct whose prerequisites you meet. Creating a construct takes one day for each 1,000 gp in its base price. To create a construct, you must spend 1/25 of the construct’s base price in XP and use up raw materials costing one-half of this price. A newly created construct has average hit points for its Hit Dice.

CRAFT UNIVERSAL ITEM [ITEM CREATION]
You can create universal psionic items.
Prerequisite: Manifester level 3rd.
Benefit: You can create any universal psionic item whose prerequisites you meet. Crafting a universal psionic item takes one day for each 1,000 gp in its base price. To craft a universal psionic item, you must spend 1/25 of the item’s base price in XP and use up raw materials costing one-half of this price.
You can also mend a broken universal item if it is one that you could make. Doing so costs half the XP, half the raw materials, and half the time it would take to craft that item in the first place.
Some universal items incur extra costs in XP, as noted in their descriptions. These costs are in addition to those derived from the item’s base price. You must pay such a cost to create an item or to mend a broken one.

DEADLY PRECISION [GENERAL]
You empty your mind of all distracting emotion, becoming an instrument of deadly precision.
Prerequisite: Dex 15, base attack bonus +5.
Benefit: You have deadly accuracy with your sneak attacks. You can reroll any result of 1 on your sneak attack’s extra damage dice. You must keep the result of the reroll, even if it is another 1.

DEEP IMPACT [PSIONIC]
You can strike your foe with a melee weapon as if making a touch attack.
Prerequisite: Str 13, Psionic Weapon, base attack bonus +5.
Benefit: To use this feat, you must expend your psionic focus. You can resolve your attack with a melee weapon as a touch attack. You must decide whether or not to use this feat prior to making an attack. If your attack misses, you still expend your psionic focus.

DELAY POWER [METAPSIONIC]
You can manifest powers that go off up to 5 rounds later.
Benefit: To use this feat, you must expend your psionic focus. You can manifest a power as a delayed power. A delayed power doesn’t activate immediately. When you manifest the power, you choose one of three trigger mechanisms: (1) The power activates when you take a standard action to activate it; (2) It activates when a creature enters the area that the power will affect (only powers that affect areas can use this trigger condition); or (3) It activates on your turn after 5 rounds pass. If you choose one of the first two triggers and the conditions are not met within 5 rounds, the power activates automatically on the fifth round.
Only area and personal powers can be delayed.
Any decisions you would make about the delayed power, including attack rolls, designating targets, or determining or shaping an area, are decided when the power is manifested. Any effects resolved by those affected by the power, including saving throws, are decided when the delay period ends.
A delayed power can be dispelled normally during the delay, and can be detected normally in the area or on the target by the use of powers that can detect psionic effects. 
Using this feat increases the power point cost of the power by 2. The power’s total cost cannot exceed your manifester level.

EMPOWER POWER [METAPSIONIC]
You can manifest powers to greater effect.
Benefit: To use this feat, you must expend your psionic focus.
You can empower a power. All variable, numeric effects of an empowered power are increased by one-half. An empowered power deals half again as much damage as normal, cures half again as many hit points, affects half again as many targets, and so forth, as appropriate. Augmented powers can also be empowered (multiply 1-1/2 times the damage total of the augmented power). Saving throws and opposed checks (such as the one you make when you manifest dispel psionics) are not affected, nor are powers without random variables.
Using this feat increases the power point cost of the power by 2. The power’s total cost cannot exceed your manifester level.

ENLARGE POWER [METAPSIONIC]
You can manifest powers farther than normal.
Benefit: To use this feat, you must expend your psionic focus. You can alter a power with a range of close, medium, or long to increase its range by 100%. An enlarged power with a range of close has a range of 50 feet + 5 feet per level, a medium-range power has a range of 200 feet + 20 feet per level, and a long-range power has a range of 800 feet + 80 feet per level.
Powers whose ranges are not defined by distance, as well as powers whose ranges are not close, medium, or long, are
not affected.
Using this feat does not increase the power point cost of the power.

EXPANDED KNOWLEDGE [PSIONIC]
You learn another power.
Prerequisites: Manifester level 3rd.
Benefit: Add to your powers known one additional power of any level up to one level lower than the highest-level power you can manifest. You can choose any power, including powers from another discipline’s list or even from another class’s list.
Special: You can gain this feat multiple times. Each time, you learn one new power at any level up to one less than the highest-level power you can manifest.

EXTEND POWER [METAPSIONIC]
You can manifest powers that last longer than normal.
Benefit: To use this feat, you must expend your psionic focus.
You can manifest an extended power. An extended power lasts twice as long as normal. A power with a duration of concentration, instantaneous, or permanent is not affected by this feat.
Using this feat increases the power point cost of the power by 2. The power’s total cost cannot exceed your manifester level.

FELL SHOT [PSIONIC]
You can strike your foe with a ranged weapon as if making a touch attack.
Prerequisite: Dex 13, Point Blank Shot, Psionic Shot, base attack bonus +5.
Benefit: To use this feat, you must expend your psionic focus. You can resolve your ranged attack as a ranged touch attack.
You must decide whether or not to use this feat prior to making an attack. If your attack misses, you still expend your psionic focus.

FOCUSED SUNDER [PSIONIC]
You can sense the stress points on others’ weapons.
Prerequisite: Str 13, Power Attack, Improved Sunder.
Benefit: To use this feat, you must expend your psionic focus.
When you strike at an opponent’s weapon, you ignore half of the weapon’s total hardness (round down). Total hardness includes any magical or psionic enhancements possessed by the weapon that increase its hardness.
Special: You can also sense the stress points in any hard construction, such as wooden doors or stone walls, and can ignore half of the object’s total hardness (round down) when attacking that object.

FORCE OF WILL [GENERAL]
You are able to resist psionic attacks with extreme force of will.
Prerequisite: Iron Will.
Benefit: Once per round, when targeted by a psionic effect that allows a Reflex save or a Fortitude save, you can instead make a Will saving throw to avoid the effect.
The benefit of this feat applies only to psionic powers and psi-like abilities. This is an exception to the psionics–magic transparency rule.
Special: You cannot take or use this feat if you have the ability to use powers (if you have a power point reserve or psi-like abilities).

GHOST ATTACK [PSIONIC]
Your deadly strikes against incorporeal foes always find their mark.
Prerequisite: Base attack bonus +3.
Benefit: You must be psionically focused to use this feat. When you make a melee attack or a ranged attack against an incorporeal creature, you can make two rolls to check for the miss chance. If either is successful, the attack is treated as if it were made with a ghost touch weapon for the purpose of affecting the creature. Your weapon or natural weapon actually appears to become briefly incorporeal as the attack is made.

GREATER MANYSHOT [GENERAL]
You are skilled at firing many arrows at once, even at different opponents.
Prerequisites: Dex 17, Manyshot, Point Blank Shot, Rapid Shot, base attack bonus +6.
Benefit: When you use the Manyshot feat, you can fire each arrow at a different target instead of firing all of them at the same target. You make a separate attack roll for each arrow, regardless of whether you fire them at separate targets or the same target. Your precision-based damage applies to each arrow fired, and, if you score a critical hit with more than one of the arrows, each critical hit deals critical damage.
Special: A fighter may select this feat as one of his fighter bonus feats.

GREATER POWER PENETRATION [PSIONIC]
Your powers are especially potent at breaking through power resistance.
Prerequisite: Power Penetration.
Benefit: To use this feat, you must expend your psionic focus. You get a +4 bonus on manifester level checks to overcome a creature’s power resistance. This bonus stacks with the bonus from Power Penetration.

GREATER POWER SPECIALIZATION [PSIONIC]
You deal more damage with your powers.
Prerequisites: Power Specialization, Weapon Focus (ray), manifester level 12th.
Benefit: Your powers that deal damage deal an extra 2 points of damage. This damage stacks with other bonuses on damage rolls to powers, including the one from Power Specialization. The damage bonus applies only if the target or targets are within 30 feet.

GREATER PSIONIC ENDOWMENT [PSIONIC]
You can use meditation to focus your powers.
Prerequisite: Psionic Endowment.
Benefit: When you use the Psionic Endowment feat, you add +2 to the save DC of a power you manifest instead of +1.

GREATER PSIONIC FIST [PSIONIC]
You can charge your unarmed strike or natural weapon with additional damage potential.
Prerequisite: Str 13, Psionic Fist, base attack bonus +5.
Benefit: When you use the Psionic Fist feat, your unarmed attack or attack with a natural weapon deals an extra 4d6 points of damage instead of an extra 2d6 points.

GREATER PSIONIC SHOT [PSIONIC]
You can charge your ranged attacks with additional damage potential.
Prerequisite: Point Blank Shot, Psionic Shot, base attack bonus +5.
Benefit: When you use the Psionic Shot feat, your ranged attack deals an extra 4d6 points of damage instead of an extra 2d6 points.

GREATER PSIONIC WEAPON [PSIONIC]
You can charge your melee weapon with additional damage potential.
Prerequisite: Str 13, Psionic Weapon, base attack bonus +5.
Benefit: When you use the Psionic Weapon feat, your attack with a melee weapon deals an extra 4d6 points of damage instead of an extra 2d6 points.

HOSTILE MIND [GENERAL]
Your mind recoils violently against those who use psionics against you.
Prerequisite: Cha 15.
Benefit: Whenever you are subject to a power from the telepathy discipline (regardless of whether the power is harmful or beneficial to you), the manifester must make a Will saving throw against a DC of 10 + 1/2 your character level + your Charisma bonus or take 2d6 points of damage.
The benefit of this feat applies only to psionic powers and psi-like abilities. This is an exception to the psionics–magic transparency rule.
Special: You cannot take or use this feat if you have the ability to use powers (if you have a power point reserve or psi-like abilities).

IMPRINT STONE [ITEM CREATION]
You can create power stones to store psionic powers.
Prerequisite: Manifester level 1st.
Benefit: You can create a power stone of any power that you know. Encoding a power stone takes one day for each 1,000 gp in its base price. The base price of a power stone is the level of the stored power x its manifester level x 25 gp. To imprint a power stone, you must spend 1/25 of this base price in XP and use up raw materials costing one-half of this base price.
Any power stone that stores a power with an XP cost also carries a commensurate cost. In addition to the costs derived from the base price, you must pay the XP when encoding the stone.

IMPROVED PSICRYSTAL [PSIONIC]
You can upgrade your psicrystal.
Prerequisites: Psicrystal Affinity.
Benefit: You can implant another personality fragment in your psicrystal. You gain the benefits of both psicrystal personalities. Your psicrystal’s personality adjusts and becomes a blend between all implanted personality fragments. From now on, when determining the abilities of your psicrystal, treat your manifester level as one higher than your normal manifester level.
Special: You can gain this feat multiple times. Each time, you implant a new personality fragment in your psicrystal, from which you derive the noted benefits, and you treat your level as one higher for the purpose of determining your psicrystal’s abilities.

INQUISITOR [PSIONIC] 
You know when others lie.
Prerequisite: Wis 13.
Benefit: To use this feat, you must expend your psionic focus.
You gain a +10 bonus on a Sense Motive check to oppose a Bluff check.
You must decide whether or not to use this feat prior to making a Sense Motive check. If your check fails, or if the opponent isn’t lying, you still expend your psionic focus. 

MAXIMIZE POWER [METAPSIONIC]
You can manifest powers to maximum effect.
Benefit: To use this feat, you must expend your psionic focus.
You can maximize a power. All variable, numeric effects of a power modified by this feat are maximized. A maximized power deals maximum damage, cures the maximum number of hit points, affects the maximum number of targets, and so on, as appropriate. Saving throws and opposed checks are not affected, nor are powers without random variables.
Augmented powers can be maximized; a maximized augmented power deals the maximum damage (or cures the maximum hit points, and so on) of the augmented power.
An empowered and maximized power gains the separate benefits of each feat: the maximum result plus one-half the normally rolled result.
Using this feat increases the power point cost of the power by 4. The power’s total cost cannot exceed your manifester level.

MENTAL LEAP [PSIONIC]
You can make amazing jumps.
Prerequisite: Str 13, Jump 5 ranks.
Benefit: To use this feat, you must expend your psionic focus. You gain a +10 bonus on a Jump check. 

MENTAL RESISTANCE [GENERAL]
Your mind is armored against mental intrusion.
Prerequisite: Base Will save bonus +2.
Benefit: Against psionic attacks that do not employ an energy type to deal damage you gain damage reduction 3/–. In addition, when you are hit with ability damage (but not ability drain or ability burn damage) from a psionic attack, you take 3 points less than you would normally take.
The benefit of this feat applies only to psionic powers and psi-like abilities. This is an exception to the psionics–magic transparency rule.
Special: You cannot take or use this feat if you have the ability to use powers (if you have a power point reserve or psi-like abilities).

METAMORPHIC TRANSFER [PSIONIC]
You can gain a supernatural ability of a metamorphed form.
Prerequisite: Wis 13, manifester level 5th.
Benefit: Each time you change your form, such as through the metamorphosis power, you gain one of the new form’s supernatural abilities, if it has any.
You gain only three uses of the metamorphic ability per day, even if the creature into which you metamorph has a higher limit on uses (You are still subject to other restrictions on the use of the ability.) The save DC to resist a supernatural ability gained through Metamorphic Transfer (if it is an attack) is 10 + your Cha modifier + 1/2 your Hit Dice.
Normal: You cannot use the supernatural abilities of creatures whose form you assume.
Special: You can gain this feat multiple times. Each time, you can gain one additional supernatural ability.

MIND OVER BODY [GENERAL]
Your ability damage heals more rapidly.
Prerequisite: Con 13.
Benefit: You heal ability damage and ability burn damage more quickly than normal. You heal a number of ability points per day equal to 1 + your Constitution bonus. 
Normal: You heal ability damage and ability burn damage at a rate of 1 point per day.

NARROW MIND [PSIONIC]
Your ability to concentrate is as keen as an arrowhead, allowing you to gain your psionic focus even in the most turbulent situations.
Prerequisite: Wis 13.
Benefit: You gain a +4 bonus on Concentration checks you make to become psionically focused.

OPEN MINDED [GENERAL]
You are naturally able to reroute your memory, mind, and skill expertise.
Benefit: You immediately gain an extra 5 skill points. You spend these skill points as normal. If you spend them on a cross-class skills they count as 1/2 ranks. You cannot exceed the normal maximum ranks for your level in any skill. 
Special: You can gain this feat multiple times. Each time, you immediately gain another 5 skill points.

OPPORTUNITY POWER [METAPSIONIC]
You can make power-enhanced attacks of opportunity.
Benefit: To use this feat, you must expend your psionic focus. When you make an attack of opportunity, you can use any power you know with a range of touch, if you have at least one hand free.
Manifesting this power is an immediate action.
You cannot use this feat with a touch power whose manifesting time is longer than 1 full-round action.
Using this feat increases the power point cost of the power by 6. The power’s total cost cannot exceed your manifester level.
Normal: Attacks of opportunity can be made only with melee weapons.

OVERCHANNEL [PSIONIC]
You burn your life force to strengthen your powers.
Benefit: While manifesting a power, you can increase your effective manifester level by one, but in so doing you take 1d8 points of damage. At 8th level, you can choose to increase your effective manifester level by two, but you take 3d8 points of damage. At 15th level, you can increase your effective manifester level by three, but you take 5d8 points of damage.
The effective increase in manifester level increases the number of power points you can expend on a single power manifestation, as well as increasing all manifester level-dependent effects, such as range, duration, and overcoming power resistance.
Normal: Your manifester level is equal to your total levels in classes that manifest powers.

POWER PENETRATION [PSIONIC]
Your powers are especially potent, breaking through power resistance more readily than normal.
Benefit: To use this feat, you must expend your psionic focus. You get a +4 bonus on manifester level checks made to overcome a creature’s power resistance.

POWER SPECIALIZATION [PSIONIC]
You deal more damage with your powers.
Prerequisites: Weapon Focus (ray), manifester level 4th.
Benefit: With rays and ranged touch attack powers that deal damage, you deal an extra 2 points of damage. If you expend your psionic focus when you manifest a ray or a ranged touch attack power that deals damage, you add your key ability bonus to the damage (instead of adding 2).

PSICRYSTAL AFFINITY [PSIONIC]
You have created a psicrystal.
Prerequisites: Manifester level 1st.
Benefit: This feat allows you to gain a psicrystal.

PSICRYSTAL CONTAINMENT [PSIONIC]
Your psicrystal has advanced enough that it can hold a psionic focus that you store within it.
Prerequisites: Psicrystal Affinity, manifester level 3rd.
Benefit: You can spend a full-round action attempting to psionically focus your psicrystal. At any time when you need to expend your psionic focus, you can expend your psicrystal’s psionic focus instead, as long as the crystal is within 5 feet of you. Psionically focusing your psicrystal works just like focusing yourself. The psicrystal cannot focus itself—only the owner can spend the time to focus the crystal.

PSIONIC AFFINITY [GENERAL]
You have a knack for psionic endeavors.
Benefit: You get a +2 bonus on all Psicraft checks and Use Psionic Device checks.

PSIONIC BODY [PSIONIC]
Your mind reinforces your body.
Benefit: When you take this feat, you gain 2 hit points for each psionic feat you have (including this one). Whenever you take a new psionic feat, you gain 2 more hit points. 

PSIONIC CHARGE [PSIONIC]
You can charge in a crooked line.
Prerequisite: Dex 13, Speed of Thought.
Benefit: To use this feat, you must expend your psionic focus. When you charge, you can make one turn of up to 90 degrees during your movement. All other restrictions on charges still apply; for instance, you cannot pass through a square that blocks or slows movement, or that contains a creature. You must have line of sight to the opponent at the start of your turn.

PSIONIC DODGE [PSIONIC]
You are proficient at dodging blows.
Prerequisite: Dex 13, Dodge.
Benefit: You must be psionically focused to use this feat. You receive a +1 dodge bonus to your Armor Class. This bonus stacks with the bonus from the Dodge feat (but only applies on attacks made by the opponent you have designated).

PSIONIC ENDOWMENT [PSIONIC]
You can endow your manifestations with more concentrated focus.
Benefit: To use this feat, you must expend your psionic focus. You add 1 to the save DC of a power you manifest.

PSIONIC FIST [PSIONIC]
You can charge your unarmed strike or natural weapon with additional damage potential.
Prerequisite: Str 13.
Benefit: To use this feat, you must expend your psionic focus. Your unarmed strike or attack with a natural weapon deals an extra 2d6 points of damage.
You must decide whether or not to use this feat prior to making an attack. If your attack misses, you still expend your psionic focus.

PSIONIC HOLE [GENERAL]
You are anathema to psionic creatures and characters.
Prerequisite: Con 15.
Benefit: When a foe strikes you in melee combat, the foe immediately loses its psionic focus, if any. Also, if you are the target of a power, the manifester of the power must spend an additional number of power points equal to your Wisdom bonus, or the power fails (all the power points spent on the power are still lost). This extra cost does not count toward the maximum power points a manifester can spend on a single power.
Special: You cannot take or use this feat if you have the ability to use powers (if you have a power point reserve or psi-like abilities).

PSIONIC MEDITATION [PSIONIC]
You can focus your mind faster than normal, even under duress.
Prerequisite: Wis 13, Concentration 7 ranks.
Benefit: You can take a move action to become psionically focused.
Normal: A character without this feat must take a full-round action to become psionically focused.

PSIONIC SHOT [PSIONIC]
You can charge your ranged attacks with additional damage potential.
Prerequisite: Point Blank Shot.
Benefit: To use this feat, you must expend your psionic focus. Your ranged attack deals +2d6 points of damage. You must decide whether or not to use this feat prior to making an attack. If your attack misses, you still expend your psionic focus.

PSIONIC TALENT [PSIONIC]
You gain additional power points to supplement those you already had.
Prerequisite: Having a power point reserve.
Benefit: When you take this feat for the first time, you gain 2 power points.
Special: You can take this feat multiple times. Each time you take the feat after the first time, the number of power points you gain increases by 1.

PSIONIC WEAPON [PSIONIC]
You can charge your melee weapon with additional damage potential.
Prerequisite: Str 13.
Benefit: To use this feat, you must expend your psionic focus.
Your attack with a melee weapon deals an extra 2d6 points of damage. You must decide whether or not to use this feat prior to making an attack. If your attack misses, you still expend your psionic focus.

QUICKEN POWER [METAPSIONIC]
You can manifest a power with a moment’s thought.
Benefit: To use this feat, you must expend your psionic focus. You can quicken a power. You can perform another action, even manifest another power, in the same round that you manifest a quickened power. You can manifest only one quickened power per round. A power whose manifesting time is longer than 1 round cannot be quickened.
Using this feat increases the power point cost of the power by 6. The power’s total cost cannot exceed your manifester level.
Manifesting a quickened power does not provoke attacks of opportunity.

RAPID METABOLISM [GENERAL]
Your wounds heal rapidly.
Prerequisite: Con 13.
Benefit: You naturally heal a number of hit points per day equal to the standard healing rate + double your Constitution  bonus. You heal even if you do not rest. This healing replaces your normal natural healing. If you are tended successfully by someone with the Heal skill, you instead regain double the normal amount of hit points + double your Constitution bonus.

RECKLESS OFFENSE [GENERAL]
You can shift your focus from defense to offense.
Prerequisite: Base attack bonus +1.
Benefit: When you use the attack action or full attack action in melee, you can take a penalty of –4 to your Armor Class and add a +2 bonus on your melee attack roll. The bonus on attack rolls and penalty to Armor Class last until the beginning of your next turn.

RETURN SHOT [PSIONIC]
You can return incoming arrows, as well as crossbow bolts, spears, and other projectile or thrown weapons.
Prerequisite: Point Blank Shot, Psionic Shot, Fell Shot, base attack bonus +3.
Benefit: To use this feat, you must expend your psionic focus and have at least one hand free. Once per round when you would normally be hit by a projectile or a thrown weapon no more than one size category larger than your size, you can deflect the attack so that you take no damage from it. The attack is deflected back at your attacker, using the attack bonus of the original attack on you. You must be aware of the attack and not flat-footed. Attempting to return a shot is a free action.
Special: If you also have the Deflect Arrows feat, the deflected attack is made with the original attack bonus plus your Dexterity bonus.

SCRIBE TATTOO [ITEM CREATION]
You can create psionic tattoos, which store powers within their designs.
Prerequisite: Manifester level 3rd.
Benefit: You can create a psionic tattoo of any power of 3rd level or lower that you know and that targets one or more creatures. Scribing a psionic tattoo takes one day. When you create a psionic tattoo, you set the manifester level. The manifester level must be sufficient to manifest the power in question and no higher than your own level. The base price of a psionic tattoo is its power level x its manifester level x 50 gp. To scribe a tattoo, you must spend 1/25 of this base price in XP and use up raw materials (special inks, masterwork needles, and so on) costing one-half of this base price.
When you create a psionic tattoo, you make any choices that you would normally make when manifesting the power.
When its wearer physically activates the tattoo, the wearer is the target of the power.
Any psionic tattoo that stores a power with an XP cost also carries a commensurate cost. In addition to the costs derived from the base price, you must pay the XP when creating the tattoo.

SIDESTEP CHARGE [PSIONIC]
You are skilled at dodging past charging opponents and taking advantage when they miss.
Prerequisite: Dex 13, Dodge.
Benefit: You get a +4 dodge bonus to Armor Class against charge attacks. If a charging opponent fails to make a successful attack against you, you gain an immediate attack of opportunity. This feat does not grant you more attacks of opportunity than you are normally allowed in a round. If you are flat-footed or otherwise denied your Dexterity bonus to Armor Class, you do not gain the benefit of this feat.

SPEED OF THOUGHT [PSIONIC]
The energy of your mind energizes the alacrity of your body.
Prerequisite: Wis 13.
Benefit: As long as you are psionically focused and not wearing heavy armor, you gain an insight bonus to your speed of 10 feet.

SPLIT PSIONIC RAY [METAPSIONIC]
You can affect two targets with a single ray.
Prerequisite: Any other metapsionic feat.
Benefit: To use this feat, you must expend your psionic focus. You can split psionic rays you manifest. The split ray affects any two targets that are both within the power’s range and within 30 feet of each other. If the ray deals damage, each target takes as much damage as a single target would take.
Using this feat increases the power point cost of the power by 2.

STAND STILL [GENERAL]
You can prevent foes from fleeing or closing.
Prerequisite: Str 13.
Benefit: When a foe’s movement out of a square you threaten grants you an attack of opportunity, you can give up that attack and instead attempt to stop your foe in his tracks. Make your attack of opportunity normally. If you hit your foe, he must succeed on a Reflex save against a DC of 10 + your damage roll (the opponent does not actually take damage), or immediately halt as if he had used up his move actions for the round.
Since you use the Stand Still feat in place of your attack of opportunity, you can do so only a number of times per round equal to the number of times per round you could make an attack of opportunity (normally just one).
Normal: Attacks of opportunity cannot halt your foes in their tracks.

TALENTED [PSIONIC]
You can overchannel powers with less cost to yourself.
Prerequisite: Overchannel.
Benefit: To use this feat, you must expend your psionic focus. When manifesting a power of 3rd level or lower, you do not take damage from overchanneling.

TWIN POWER [METAPSIONIC]
You can manifest a power simultaneously with another power just like it.
Benefit: To use this feat, you must expend your psionic focus. You can twin a power. Manifesting a power altered by this feat causes the power to take effect twice on the area or target, as if you were simultaneously manifesting the same power two times on the same location or target. Any variables in the power (such as duration, number of targets, and so on) are the same for both of the resulting powers. The target experiences all the effects of both powers individually and receives a saving throw (if applicable) for each. In some cases, such as a twinned psionic charm, failing both saving throws results in redundant effects (although, in this example, any ally of the target would have to succeed on two dispel attempts to free the target from the charm effect).
Using this feat increases the power point cost of the power by 6. The power’s total cost cannot exceed your manifester level.

UNAVOIDABLE STRIKE [PSIONIC]
You can make an unarmed strike or use a natural weapon against your foe as if delivering a touch attack.
Prerequisite: Str 13, Psionic Fist, base attack bonus +5.
Benefit: To use this feat, you must expend your psionic focus. You can resolve your unarmed strike or attack with a natural weapon as a touch attack.
You must decide whether or not to use this feat prior to making an attack. If your attack misses, you still expend your psionic focus.

UNCONDITIONAL POWER [METAPSIONIC]
Disabling conditions do not hold you back.
Benefit: To use this feat, you must expend your psionic focus. Your mental strength is enough to overcome some otherwise disabling conditions. You can manifest an unconditional power when you are dazed, confused, nauseated, shaken, or stunned.
Only personal powers and powers that affect your person can be manifested as unconditional powers.
Using this feat increases the power point cost of the power by 8. The power’s total cost cannot exceed your manifester level.

UP THE WALLS [PSIONIC]
You can run on walls for brief distances.
Prerequisite: Wis 13.
Benefit: While you are psionically focused, you can take part of one of your move actions to traverse a wall or other relatively smooth vertical surface if you begin and end your move on a horizontal surface. The height you can achieve on the wall is limited only by this movement restriction. If you do not end your move on a horizontal surface, you fall prone, taking falling damage as appropriate for your distance above the ground. Treat the wall as a normal floor for the purpose of measuring your movement. Passing from floor to wall or wall to floor costs no movement; you can change surfaces freely. Opponents on the ground can make attacks of opportunity as you move up the wall.
Special: You can take other move actions in conjunction with moving along a wall. For instance, the Spring Attack feat allows you to make an attack from the wall against a foe standing on the ground who is within the area you threaten; however, if you are somehow prevented from completing your move, you fall. Likewise, you could tumble along the wall to avoid attacks of opportunity.

WIDEN POWER [METAPSIONIC]
You can increase the area of your powers.
Benefit: To use this feat, you must expend your psionic focus. You can alter a burst, emanation, line, or spread-shaped power to increase its area. (Powers that do not have an area of one of these four sorts are not affected by this feat.) Any numeric measurements of the power’s area increase by 100%.
Using this feat increases the power point cost of the power by 4. The power’s total cost cannot exceed your manifester level.

WILD TALENT [GENERAL]
Your mind wakes to a previously unrealized talent for psionics.
Benefit: Your latent power of psionics flares to life, conferring upon you the designation of a psionic character. As a psionic character, you gain a reserve of 2 power points and can take psionic feats, metapsionic feats, and psionic item creation feats. You do not, however, gain the ability to manifest powers simply by virtue of having this feat.

WOUNDING ATTACK [PSIONIC]
Your vicious attacks wound your foe.
Prerequisite: Base attack bonus +8.
Benefit: To use this feat, you must expend your psionic focus. You can make an attack with such vicious force that you wound your opponent. A wound deals 1 point of Constitution damage to your foe in addition to the usual damage dealt.
You must decide whether or not to use this feat prior to making an attack. If your attack misses, you still expend your psionic focus.

Epic Feats
----------

EPIC FEATS 

ACQUIRING EPIC FEATS
Characters gain epic feats in the following ways: 
At 21st level, and every three levels thereafter, the character may select an epic feat in place of a nonepic feat.
Each character class gains bonus epic feats according to the class description. These feats must be selected from the list of bonus epic feats for that class. 

PREREQUISITES
Most epic feats have prerequisites. A character must have the listed ability score, feat, skill, class feature, or base attack modifier in order to select or use that feat. A character can gain an epic feat at the same level at which he or she gains the prerequisite, just as with regular feats. A prerequisite expressed as a numerical value is a minimum; any value higher than the one given also meets the prerequisite. A character can’t use an epic feat if he or she has lost a prerequisite. 

TYPES OF EPIC FEATS 
Most epic feats are general, meaning that no special rules govern them as a group. Others may be item creation feats or metamagic feats, which follow all the normal rules for such feats, except as specified in the feat’s description. In addition, some feats are defined as divine feats or as wild feats. Such feats are described below. 

DIVINE FEATS 
The feats in this category share a few characteristics. First, they all have as a prerequisite the ability to turn (or, in most cases, rebuke) undead. Thus, they are open to clerics, paladins of 4th level or higher, and any prestige class that has that ability. (An ability to turn other creatures does not qualify a character to select one of these feats.) Second, the force that powers a divine feat is the ability to channel positive or negative energy to turn or rebuke undead. Each use of a divine feat costs the character one turn/rebuke attempt from his or her number of attempts each day. If a character doesn’t have any turn/rebuke attempts left, he or she can’t use the feat. Since turning or rebuking is a standard action, activating any of these feats is also a standard action. 

WILD FEATS 
The feats in this category share the characteristic of relating to the ability to use wild shape as a druid. These feats require the character to have the ability to use wild shape before acquiring the feat. 

EPIC PSIONIC FEATS 
Psionic characters can acquire epic “psionically flavored” feats.  Some feats require so much translation that converted feats are provided. Whenever a feat concerns conferring or altering a spell in some fashion, some translation must be done to use it with psionics. Sometimes this translation is as straightforward as changing a few names. Translating epic metamagic feats to epic metapsionic feats requires that Spellcraft prerequisites be replaced with Psicraft. It also requires a little math—instead of casting a spell at a higher level, a psionic character pays more power points. For every spell slot one level higher than the spell’s actual level the metamagic feat requires, the metapsionic feat requires a character to pay a power point cost equal to its standard cost +2. Likewise, when a feat allows a spellcaster to “pay” one less level to use a metamagic feat, the psionic version allows a character to pay 2 power points less for a given metapsionic feat. 

FEATS

ADDITIONAL MAGIC ITEM SPACE [EPIC] 
Benefit: Choose one type of magic item that has a limit on the number a character can simultaneously wear and gain its benefit. The character can now wear one more magic item of this type and also gain its benefit. 
Normal: Without this feat, a character is limited to one headband, hat, or helmet; one pair of eye lenses or goggles; one cloak, cape, or mantle; one amulet, brooch, medallion, necklace, periapt, or scarab; one suit of armor; one robe; one vest, vestment, or shirt; one pair of bracers or bracelets; one pair of gloves or gauntlets; two rings; one belt; and one pair of boots. 
Special: A character can gain this feat multiple times. Each time the character takes the feat, it applies to a new type of wearable magic item. 

ARMOR SKIN [EPIC] 
Benefit: The character gains a +1 natural armor bonus to Armor Class, or his or her existing natural armor bonus increases by 1. 
Special: A character can gain this feat multiple times. Its effects stack. 

AUGMENTED ALCHEMY [EPIC] 
Prerequisites: Int 21, Craft(alchemy) 24 ranks. 
Benefit: Whenever creating an alchemical item or substance, the character can choose to make it more powerful than normal by adding +20 to the DC required to create it and multiplying its price by 5. If the item or substance deals damage, double the damage dealt. If the item or substance doesn’t deal damage, double the duration of its effect. If the item or substance doesn’t deal damage and doesn’t have a specific listed duration (or has an instantaneous duration), double all dimensions of its area. If the item or substance doesn’t fit any of these categories, then it cannot be affected by this feat. See the Craft (alchemy) skill description. 

AUTOMATIC QUICKEN SPELL [EPIC] 
Prerequisites: Quicken Spell, Spellcraft 30 ranks, ability to cast 9th-level arcane or divine spells. 
Benefit: The character may cast all 0-, 1st-, 2nd-, and 3rd-level spells as quickened spells without using higher-level spell slots. The normal limit to the number of quickened spells a character may cast per round applies. Spells with a casting time of more than 1 full round can’t be quickened. 
Special: A character can gain this feat multiple times. Each time a character takes the feat, the spells of his or her next three lowest spell levels can now be quickened with no adjustment to their spell slots. This feat doesn’t increase the casting time for those spells that normally become full-round actions when cast in metamagic form. 

AUTOMATIC SILENT SPELL [EPIC] 
Prerequisites: Silent Spell, Spellcraft 24 ranks, ability to cast 9th-level arcane or divine spells. 
Benefit: The character may cast all 0-, 1st-, 2nd-, and 3rd-level spells as silent spells without using higher-level spell slots. 
Special: A character can gain this feat multiple times. Each time a character takes the feat, the spells of his or her next three lowest spell levels can now be silenced with no adjustment to their spell slots. This feat doesn’t increase the casting time for those spells that normally become full-round actions when cast in metamagic form. However, since bard spells can’t be enhanced with the Silent Spell feat, they can’t be affected by this feat either. 

AUTOMATIC STILL SPELL [EPIC] 
Prerequisites: Still Spell, Spellcraft 27 ranks, ability to cast 9th-level arcane or divine spells. 
Benefit: The character may cast all 0-, 1st-, 2nd-, and 3rd-level spells as stilled spells without using higher-level spell slots. 
Special: A character can gain this feat multiple times. Each time a character takes the feat, the spells of his or her next three lowest spell levels can now be stilled with no adjustment to their spell slots. This feat doesn’t increase the casting time for those spells that normally become full-round actions when cast in metamagic form. 

BANE OF ENEMIES [EPIC] 
Prerequisites: Survival 24 ranks, five or more favored enemies. 
Benefit: Any weapon the character wields against one of his or her favored enemies is treated as a bane weapon for that creature type (thus, its enhancement bonus is increased by +2 and it deals +2d6 points of damage). This ability doesn’t stack with similar abilities. 

BLINDING SPEED [EPIC] 
Prerequisite: Dex 25. 
Benefit: The character can act as if hasted for 5 rounds each day. The duration of the effect need not be consecutive rounds. Activating this power is a free action. 
Special: A character can gain this feat multiple times. Each time he or she takes the feat, it grants an additional 5 rounds of haste per day. 

BONUS DOMAIN [EPIC] 
Prerequisites: Wis 21, ability to cast 9th-level divine spells. 
Benefit: Choose an additional domain from the character’s deity’s domain list. The character now has access to that domain’s spells as normal for his or her domain spells and the domain’s granted powers. 
Special: A character can gain this feat multiple times. Each time he or she takes the feat, it applies to a different domain. 

BULWARK OF DEFENSE [EPIC] 
Prerequisites: Con 25, defensive stance 3/day. 
Benefit: The character’s defensive stance bonuses increase to +4 Strength, +6 Constitution, +4 resistance bonus on all saves, and +6 dodge bonus to AC. 

CHAOTIC RAGE [EPIC] 
Prerequisites: Rage 5/day, chaotic alignment. 
Benefit: Any weapon the character wields while in a rage is treated as an anarchic weapon (it is chaos-aligned and deals an extra 2d6 points of damage against creatures of lawful alignment). This ability does not stack with similar abilities. 

COLOSSAL WILD SHAPE [WILD][EPIC] 
Prerequisite: The ability to wild shape into a Gargantuan creature.
Benefit: The character can use his or her wild shape to take the shape of a Colossal animal. 
Normal: Without this feat, a character cannot wild shape into an animal of greater than Huge size. 

COMBAT ARCHERY [EPIC] 
Prerequisites: Dodge, Mobility, Point Blank Shot. 
Benefit: The character does not incur any attacks of opportunity for firing a bow when threatened. 
Normal: Without this feat, a character incurs an attack of opportunity from all opponents who threaten him or her whenever he or she uses a bow. 

CRAFT EPIC MAGIC ARMS AND ARMOR [ITEM CREATION] [EPIC] 
Prerequisites: Craft Magic Arms and Armor, Knowledge (arcana) 28 ranks, Spellcraft 28 ranks. 
Benefit: The character can craft magic arms and armor which exceed the normal limits for such items

CRAFT EPIC ROD [ITEM CREATION][EPIC] 
Prerequisites: Craft Rod, Knowledge (arcana) 32 ranks, Spellcraft 32 ranks. 
Benefit: The character can craft rods that exceed the normal limits for such items. 

CRAFT EPIC STAFF [ITEM CREATION][EPIC] 
Prerequisites: Craft Staff, Knowledge (arcana) 35 ranks, Spellcraft 35 ranks. 
Benefit: The character can craft staffs that exceed the normal limits for such items. 

CRAFT EPIC WONDROUS ITEM [ITEM CREATION][EPIC] 
Prerequisites: Craft Wondrous Item, Knowledge (arcana) 26 ranks, Spellcraft 26 ranks. 
Benefit: The character can craft wondrous items that exceed the normal limits for such items. 

DAMAGE REDUCTION [EPIC] 
Prerequisite: Con 21. 
Benefit: The character gains damage reduction 3/–. This does not stack with damage reduction granted by magic items or nonpermanent magical effects, but it does stack with any damage reduction granted by permanent magical effects, class features, or this feat itself. 
Special: A character can gain this feat multiple times. Each time he or she gains the feat, his or her damage reduction increases by 3. 

DEAFENING SONG [EPIC] 
Prerequisites: Perform 24 ranks, bardic music class feature. 
Benefit: The character can use song or poetics to temporarily deafen all enemies within a 30-foot spread from him or her. A successful Fortitude save (DC 10 + 1/2 the character’s class level + the character’s Charisma modifier) negates the effect. The deafening effect lasts for as long as the character continues the deafening song. The character can choose to exclude any characters from this effect. The character may sing, play, or recite a deafening song while taking other mundane actions, but not magical ones (see the bard’s inspire courage ability for more details). The character may keep up the deafening song for a maximum of 10 rounds. Using the deafening song counts as one of the character’s uses of song or poetics for the day. 

DEATH OF ENEMIES [EPIC] 
Prerequisites: Bane of Enemies, Survival 30 ranks, five or more favored enemies. 
Benefit: Any time the character scores a critical hit against one of his or her favored enemies, it must make a Fortitude save (DC 10 + 1/2 character’s ranger class level + character’s Wisdom modifier) or die instantly.
Special: Creatures immune to critical hits can’t be affected by this feat. 

DEVASTATING CRITICAL [EPIC] 
Prerequisites: Str 25, Cleave, Great Cleave, Improved Critical (chosen weapon), Overwhelming Critical (chosen weapon), Power Attack, Weapon Focus (chosen weapon). 
Benefit: Whenever the character scores a critical hit with the chosen weapon, the target must make a Fortitude save (DC 10 + 1/2 character level + character’s Strength modifier) or die instantly. (Creatures immune to critical hits can’t be affected by this feat.) 
Special: A character can gain this feat multiple times. Its effects do not stack. Each time a character takes the feat, it applies to a different type of weapon. 

DEXTEROUS FORTITUDE [EPIC] 
Prerequisites: Dex 25, slippery mind class feature. 
Benefit: Once per round, when targeted by an effect that requires a Fortitude saving throw, the character may make a Reflex save instead to avoid the effect (evasion is not applicable). 

DEXTEROUS WILL [EPIC] 
Prerequisites: Dex 25, slippery mind class feature. 
Benefit: Once per round, when targeted by an effect that requires a Will saving throw, the character may make a Reflex save instead to avoid the effect (evasion is not applicable). 

DIMINUTIVE WILD SHAPE [WILD][EPIC] 
Prerequisite: Ability to wild shape into a Huge animal. 
Benefit: The character can use wild shape to take the shape of a Diminutive animal. 
Normal: Without this feat, a character cannot wild shape into an animal of smaller than Tiny size. 

DIRE CHARGE [EPIC] 
Prerequisite: Improved Initiative. 
Benefit: If the character charges a foe during the first round of combat (or the surprise round, if the character is allowed to act in it), he or she can make a full attack against the opponent charged. 
Normal: Without this feat, a character may only make a single attack as part of a charge. 

DISTANT SHOT [EPIC]
Prerequisites: Dex 25, Far Shot, Point Blank Shot, Spot 20 ranks. 
Benefit: The character may throw or fire a ranged weapon at any target within line of sight, with no penalty for range. 

DRAGON WILD SHAPE [WILD][EPIC]
Prerequisites: Wis 30, Knowledge (nature) 30 ranks, wild shape 6/day. 
Benefit: The character may use wild shape to change into a dragon (black, blue, green, red, white, brass, bronze, copper, gold, or silver). The size limitation is the same as the character’s limitation on animal size. The character gains all extraordinary and supernatural abilities of the dragon whose form he or she takes. 

EFFICIENT ITEM CREATION [EPIC] 
Prerequisites: Item creation feat to be selected, Knowledge (arcana) 24 ranks, Spellcraft 24 ranks. 
Benefit: Select an item creation feat. Creating a magic item using that feat requires one day per 10,000 gp of the item’s market price, with a minimum of one day. 
Normal: Without this feat, creating a magic item requires one day for each 1,000 gp of the item’s market price.
Special: A character can gain this feat multiple times. Its effects do not stack. Each time a character takes the feat, it applies to a different item creation feat. 

ENERGY RESISTANCE [EPIC] 
Benefit: Choose a type of energy (acid, cold, electricity, fire, or sonic). The character gains resistance 10 to that type of energy, or the character’s existing resistance to that type of energy increases by 10. This feat does not stack with energy resistance granted by magic items or nonpermanent magical effects. 
Special: A character can gain this feat multiple times. If the same type of energy is chosen, the effects stack. 

ENHANCE SPELL [METAMAGIC][EPIC] 
Prerequisite: Maximize Spell. 
Benefit: The damage cap for the character’s spells increases by 10 dice (for spells that deal a number of dice of damage equal to caster level) or by 5 dice (for spells that deal a number of dice of damage equal to half caster level). An enhanced spell uses up a spell slot four levels higher than the spell’s actual level. This feat has no effect on spells that don’t specifically deal a number of dice of damage equal to the caster’s level or half level, even if the spell’s effect is largely dictated by the caster’s level. 
Normal: Without this feat, use the damage dice caps indicated in the spell’s description. 
Special: A character may gain this feat multiple times. Each time he or she selects this feat, the damage cap increases by 10 dice or 5 dice, as appropriate to the spell, and the enhanced spell takes up a spell slot an additional four levels higher. 

EPIC DODGE [EPIC] 
Prerequisites: Dex 25, Dodge, Tumble 30 ranks, improved evasion, defensive roll class feature. 
Benefit: Once per round, when struck by an attack from an opponent the character has designated as the object of his or her dodge, the character may automatically avoid all damage from the attack. 

EPIC ENDURANCE [EPIC] 
Prerequisites: Con 25, Endurance. 
Benefit: Whenever the character makes a check for performing a physical action that extends over a period of time, he or she gets a +10 bonus on the check. 

EPIC EXPANDED KNOWLEDGE [EPIC, PSIONIC]
You learn another power.
Prerequisites: Character level 21st, ability to manifest powers of the normal maximum power level in at least one psionic class.
Benefit: You learn one additional power at any level up to the highest level of power you can manifest. You can choose any power, even one that is part of another discipline’s list or another class’s list.
Special: You can gain this feat multiple times. Each time, you learn one new power at any level up to the highest level of power you can manifest.

EPIC FORTITUDE [EPIC] 
Benefit: The character gains a +4 bonus on all Fortitude saving throws. 

EPIC INSPIRATION [EPIC] 
Prerequisites: Cha 25, Perform 30 ranks, bardic music class feature. 
Benefit: All competence bonuses, dodge bonuses, and morale bonuses granted by the character’s bardic music ability increase by +1.  If you have the inspire greatness bardic music ability, it grants one additional bonus HD. 
Special: A character can gain this feat multiple times. Its effects stack. 

EPIC LEADERSHIP [EPIC] 
Prerequisites: Cha 25, Leadership, Leadership score 25. 
Benefit: The character attracts a cohort and followers as shown below on Table: Epic Leadership.  In all other ways Epic Leadership functions as the Leadership feat.
Normal: The Leadership feat provides no benefit for leadership scores beyond 25.

Table: Epic Leadership
Leadership Score
Cohort Level
——————————Number of Followers by Level —————————


1st
2nd
3rd
4th
5th
6th
7th
8th
9th
10th
25
17th
135
13
7
4
2
2
1
—
—
—
26
18th
160
16
8
4
2
2
1
—
—
—
27
18th
190
19
10
5
3
2
1
—
—
—
28
19th
220
22
11
6
3
2
1
—
—
—
29
19th
260
26
13
7
4
2
1
—
—
—
30
20th
300
30
15
8
4
2
1
—
—
—
31
20th
350
35
18
9
5
3
2
1
—
—
32
21st
400
40
20
10
5
3
2
1
—
—
33
21st
460
46
23
12
6
3
2
1
—
—
34
22nd
520
52
26
13
6
3
2
1
—
—
35
22nd
590
59
30
15
8
4
2
1
—
—
36
23rd
660
66
33
17
9
5
3
2
1
—
37
23rd
740
74
37
19
10
5
3
2
1
—
38
24th
820
82
41
21
11
6
3
2
1
—
39
24th
910
91
46
23
12
6
3
2
1
—
40
25th
1000
100
50
25
13
7
4
2
1
—
per +1
+1/2*
+100**
†
†
†
†
†
†
†
†
†

Leadership Score: A character’s Leadership score equals his or her level plus any Charisma modifier. Outside factors can affect a character’s Leadership score, as detailed in the Leadership feat. 
Cohort Level: The character can attract a cohort of up to this level. Regardless of the character’s Leadership score, he or she can’t recruit a cohort of his or her level or higher. 
Number of Followers by Level: The character can lead up to the indicated number of characters of each level. 
*The maximum cohort level increases by 1 for every 2 points of Leadership above 40. **The number of 1st-level followers increases by 100 for every point of Leadership above 40. 
†A character can command one-tenth as many 2nd-level followers as 1st-level followers. A character can command one-half as many 3rd-level followers as 2nd-level followers, one-half as many 4th-level followers as 3rd-level followers, and so on (round fractions up, except any fraction less than 1 rounds to 0). A character can’t have a follower of higher than 20th level.
Table: Example Special Epic Cohorts presents some creatures that make good cohorts for epic characters. 

Table: Example Special Epic Cohorts
Creature
Alignment
Level Equivalent
Angel, astral deva
Any good
20nd
Dragon, ancient silver
Lawful good
42nd
Couatl
Lawful good
16th
Giant, cloud
Neutral good
24th
Ghaele 
Chaotic good
20st
Giant, storm
Chaotic good
28th
Dragon, wyrm brass
Chaotic good
42th
Dragon turtle
Neutral
21st
Hydra, 12-headed
Neutral
19th
Roc
Neutral
23rd
Dragon, ancient green
Lawful evil
40th
Devil, ice (gelugon)
Lawful evil
21st
Giant, cloud
Neutral evil
24th
Demon, glabrezu
Chaotic evil
23rd
Demon, succubus
Chaotic evil
12th
Dragon, wyrm white
Chaotic evil
41th

EPIC PROWESS [EPIC] 
Benefit: Gain a +1 bonus on all attacks. 
Special: A character can gain this feat multiple times. Its effects stack. 

EPIC PSIONIC FOCUS [EPIC, PSIONIC]
You can expend your psionic focus to greater effect.
Prerequisites: Character level 21st, ability to manifest powers of the normal maximum power level in at least one psionic class.
Benefit: When you expend your psionic focus, you can simultaneously use two feats that require a psionic focus to be expended, instead of just one. The feats must be stackable. You must still spend the requisite power points required to use each metapsionic feat, and you cannot exceed the power point limit set by your manifester level.
Special: You can take this feat multiple times. Each time you do so, you can simultaneously use one additional feat that requires a psionic focus to be expended.

EPIC REFLEXES [EPIC] 
Benefit: The character gains a +4 bonus on all Reflex saving throws. 

EPIC REPUTATION [EPIC] 
Benefit: The character gains a +4 bonus on Bluff, Diplomacy, Gather Information, Intimidate, and Perform checks. 

EPIC SKILL FOCUS [EPIC] 
Prerequisite: 20 ranks in the skill selected. 
Benefit: The character gains a +10 bonus on all skill checks with that skill. 
Special: A character can gain this feat multiple times. Its effects do not stack. Each time a character takes the feat, it applies to a different skill. 

EPIC SPEED [EPIC] 
Prerequisites: Dex 21, Run. 
Benefit: The character’s speed increases by 30 feet. This benefit does not stack with increased speed granted by magic items or nonpermanent magical effects. 
Special: This feat only functions when the character is wearing medium armor, light armor, or no armor. 

EPIC SPELL FOCUS [EPIC] 
Prerequisites: Greater Spell Focus and Spell Focus in the school selected, ability to cast at least one 9th-level spell of the school to be chosen. 
Benefit: Add +1 to the Difficulty Class for all saving throws against spells from the school of magic the character selects to focus on. This stacks with the bonuses from Spell Focus and Greater Spell Focus. 
Special: A character can gain this feat multiple times. Its effects do not stack. Each time the character takes the feat, it applies to a different school of magic. 

EPIC SPELL PENETRATION [EPIC] 
Prerequisites: Greater Spell Penetration, Spell Penetration. 
Benefit: The character gets a +2 bonus on caster level checks to beat a creature’s spell resistance. This stacks with the bonuses from Spell Penetration and Greater Spell Penetration. 

EPIC SPELLCASTING [EPIC] 
Prerequisite: Spellcraft 24 ranks, Knowledge (arcana) 24 ranks, ability to cast 9th-level arcane spells. OR Spellcraft 24 ranks, Knowledge (religion) 24 ranks, ability to cast 9th-level divine spells. OR Spellcraft 24 ranks, Knowledge (nature) 24 ranks, ability to cast 9th-level divine spells. 
Benefit: The character may develop and cast epic spells.  If the character is an arcane spellcaster, he or she may cast a number of epic spells per day equal to his or her ranks in Knowledge (arcana) divided by 10. If the character is a divine spellcaster, he or she may cast a number of epic spells per day equal to his or her ranks in Knowledge (religion) or Knowledge (nature) divided by 10. 
Special: If the character meets more than one set of prerequisites, the limit on the number of spells he or she may cast per day is cumulative. 

EPIC TOUGHNESS [EPIC] 
Benefit: The character gains +30 hit points. 
Special: A character can gain this feat multiple times. Its effects stack. 

EPIC WEAPON FOCUS [EPIC] 
Prerequisite: Weapon Focus in the chosen weapon. 
Benefit: Add a +2 bonus to all attack rolls the character makes using the selected weapon. 
Special: A character can gain this feat multiple times. Its effects do not stack. Each time the character takes the feat it applies to a different type of weapon. 

EPIC WEAPON SPECIALIZATION [EPIC] 
Prerequisites: Epic Weapon Focus, Weapon Focus, Weapon Specialization (all in the chosen weapon). 
Benefit: Add +4 to all damage the character deals using the selected weapon. If the weapon is a ranged weapon, the damage bonus only applies if the target is within 30 feet. 
Special: A character can gain this feat multiple times. Its effects do not stack. Each time the character takes the feat, it applies to a different type of weapon. 

EPIC WILL [EPIC] 
Benefit: The character gains a +4 bonus on all Will saving throws. 

EXCEPTIONAL DEFLECTION [EPIC] 
Prerequisites: Dex 21, Wis 19, Deflect Arrows, Improved Unarmed Strike. 
Benefit: The character can deflect any ranged attacks (including spells that require ranged touch attacks) as if they were arrows. 

EXTENDED LIFE SPAN [EPIC] 
Benefit: Add one-half the maximum result of the character’s race’s maximum age modifier to the character’s normal middle age, old, and venerable age categories. Calculate the character’s maximum age using the new venerable number. This feat can’t lower the character’s current age category. 
Special: A character can gain this feat multiple times. Its effects stack. 

FAMILIAR SPELL [EPIC] 
Prerequisite: Int 25 (if the character’s spellcasting is controlled by Intelligence) or Cha 25 (if the character’s spellcasting is controlled by Charisma). 
Benefit: Choose one arcane spell the character knows of 8th level or lower. The character’s familiar can now use this spell once per day as a spell-like ability, at a caster level equal to the character’s caster level. A character cannot bestow a spell to his or her familiar if the spell normally has a material component cost of more than 1 gp or an XP cost. 
Special: A character can gain this feat multiple times. Each time the character takes the feat, he or she can give his or her familiar a different spell-like ability or another daily use of the same spell-like ability. 

FAST HEALING [EPIC] 
Prerequisite: Con 25. 
Benefit: The character gains fast healing 3, or the character’s existing fast healing increases by 3. This feat does not stack with fast healing granted by magic items or nonpermanent magical effects. 
Special: This feat may be taken multiple times. Its effects stack. 

FINE WILD SHAPE [WILD][EPIC]
Prerequisite: Ability to wild shape into a Diminutive creature. 
Benefit: The character can use his or her wild shape to take the shape of a Fine animal. 
Normal: Without this feat, a character cannot wild shape into an animal smaller than Tiny size. 

FORGE EPIC RING [ITEM CREATION][EPIC] 
Prerequisites: Forge Ring, Knowledge (arcana) 35 ranks, Spellcraft 35 ranks. 
Benefit: The character can forge magic rings that exceed the normal limits for such items.

GARGANTUAN WILD SHAPE [WILD][EPIC]
Prerequisite: Ability to wild shape into a Huge animal. 
Benefit: The character can use your wild shape to take the shape of a Gargantuan animal. 
Normal: Without this feat, a character cannot wild shape into an animal greater than Huge size. 

GREAT CHARISMA [EPIC] 
Benefit: The character’s Charisma increases by 1 point. 
Special: A character can gain this feat multiple times. Its effects stack. 

GREAT CONSTITUTION [EPIC] 
Benefit: The character’s Constitution increases by 1 point.
Special: A character can gain this feat multiple times. Its effects stack. 

GREAT DEXTERITY [EPIC] 
Benefit: The character’s Dexterity increases by 1 point. 
Special: A character can gain this feat multiple times. Its effects stack. 

GREAT INTELLIGENCE [EPIC] 
Benefit: The character’s Intelligence increases by 1 point. 
Special: A character can gain this feat multiple times. Its effects stack. 

GREAT SMITING [EPIC] 
Prerequisites: Cha 25, smite ability (from class feature or domain granted power). 
Benefit: Whenever the character makes a successful smite attack, add twice the appropriate level to damage (rather than just the character’s level). 
Special: A character may select this feat multiple times. Its effects stack. Remember that two doublings equals a tripling, and so forth.

GREAT STRENGTH [EPIC] 
Benefit: The character’s Strength increases by 1 point. 
Special: A character can gain this feat multiple times. Its effects stack. 

GREAT WISDOM [EPIC] 
Benefit: The character’s Wisdom increases by 1 point. 
Special: A character can gain this feat multiple times. Its effects stack. 

GROUP INSPIRATION [EPIC] 
Prerequisite: Perform 30 ranks, bardic music class feature. 
Benefit: The number of allies the character can affect with his or her inspire competence or inspire greatness bardic music ability doubles. When inspiring competence in multiple allies, the character can choose different skills to inspire for different allies. 
Special: A character can gain this feat multiple times. Its effects stack. Remember that two doublings equals a tripling, and so forth. 

HINDERING SONG [EPIC] 
Prerequisite: Deafening Song, Perform 27 ranks, bardic music class feature. 
Benefit: The character can use song or poetics to hinder enemy spellcasters within a 30-foot spread from the character. To successfully cast a spell within this area, a spellcaster must make a Concentration check as if he or she were casting defensively, and all such checks have a penalty equal to half the character’s level. The character can choose to exclude any characters from this effect. The character may sing, play, or recite a hindering song while taking other mundane actions, but not magical ones (see the bard’s inspire courage ability for more details). The character may keep up the hindering song for a maximum of 10 rounds. Using the hindering song counts as one of the character’s uses of song or poetics for the day. 

HOLY STRIKE [EPIC] 
Prerequisites: Smite evil class feature, any good alignment. 
Benefit: Any weapon the character wields is treated as a holy weapon (is good-aligned and deals an extra 2d6 points of damage against creatures of evil alignment).If the weapon already has an alignment, this feat has no effect on the weapon. 

IGNORE MATERIAL COMPONENTS [EPIC] 
Prerequisites: Eschew Materials, Spellcraft 25 ranks, ability to cast 9th-level arcane or divine spells. 
Benefit: The character may cast spells without any material components. This feat does not affect the need for a focus or divine focus. 

IMPROVED ALIGNMENT-BASED CASTING [EPIC] 
Prerequisites: Access to domain of Chaos, Evil, Good, or Law, alignment must match domain chosen, ability to cast 9th-level divine spells. 
Benefit: Select an alignment-based domain (Chaos, Evil, Good, or Law) to which the character has access. The character casts spells with that alignment descriptor at +3 caster level. 
Special: This benefit overrides (does not stack with) the granted powers of the Chaos, Evil, Good, and Law domains. A character may select this feat multiple times. Its effects do not stack. Each time a character takes the feat, it applies to a different alignment-based domain to which the character has access. 

IMPROVED ARROW OF DEATH [EPIC] 
Prerequisites: Dex 19, Wis 19, Point Blank Shot, Precise Shot, arrow of death class feature. 
Benefit: Add +2 to the DC of the character’s arrows of death. This feat may be taken multiple times. Its effects stack. 

IMPROVED AURA OF COURAGE [EPIC] 
Prerequisite: Cha 25, aura of courage class ability. 
Benefit: The character’s aura of courage grants a +8 morale bonus on saving throws against fear effects. 

IMPROVED AURA OF DESPAIR [EPIC] 
Prerequisite: Cha 25, aura of despair class ability. 
Benefit: The character’s aura of despair causes a –4 morale penalty on all saving throws. 

IMPROVED COMBAT CASTING [EPIC] 
Prerequisites: Combat Casting, Concentration 25 ranks. 
Benefit: The character doesn’t incur attacks of opportunity for casting spells when threatened. 

IMPROVED COMBAT REFLEXES [EPIC] 
Prerequisites: Dex 21, Combat Reflexes. 
Benefit: There is no limit to the number of attacks of opportunity the character can make in one round. (the character still can’t make more than one attack of opportunity for a given oppertunity.) 

IMPROVED DARKVISION [EPIC]
Prerequisite: Darkvision. 
Benefit: The range of the character’s darkvision doubles. This feat does not stack with darkvision granted by magic items or nonpermanent magical effects. 
Special: This feat may be taken multiple times. Its effects stack. Remember that two doublings equals a tripling, and so on. 

IMPROVED DEATH ATTACK [EPIC] 
Prerequisites: Death attack class feature, sneak attack +5d6. 
Benefit: Add +2 to the DC of the character’s death attack. 
Special: This feat may be taken multiple times. Its effects stack. 

IMPROVED ELEMENTAL WILD SHAPE [WILD][EPIC] 
Prerequisites: Wis 25, ability to wild shape into an elemental. 
Benefit: The character’s ability to wild shape into an elemental is expanded to include all elemental creatures (not just air, earth, fire, and water elementals) of any size that the character can take when using wild shape to become an animal. The character gains all extraordinary and supernatural abilities of the elemental whose form he or she takes. 
Normal: Without this feat, a character may only wild shape into a Small, Medium-size, or Large air, earth, fire, or water elemental. 

IMPROVED FAVORED ENEMY [EPIC] 
Prerequisite: Five or more favored enemies. 
Benefit: Add +1 to the bonus on Bluff, Listen, Sense Motive, Spot, and Survival checks and damage rolls against all the character’s favored enemies. 
Special: This feat may be taken multiple times. Its effects stack. 

IMPROVED HEIGHTEN SPELL [EPIC] 
Prerequisites: Heighten Spell, Spellcraft 20 ranks. 
Benefit: As Heighten Spell, but there is no limit to the level to which the character can heighten the spell. 
Normal: Without this feat, a spell can only be heightened to a maximum of 9th level. 

IMPROVED KI STRIKE [EPIC] 
Prerequisites: Wis 21, Ki strike (adamantine). 
Benefit: The character’s unarmed strikes are treated as epic magic weapons for the purposes of damage reduction. 

IMPROVED LOW-LIGHT VISION [EPIC] 
Prerequisite: Low-light vision. 
Benefit: The range of the character’s low-light vision doubles. This feat does not stack with low-light vision granted by magic items or nonpermanent magical effects. 
Special: This feat may be taken multiple times. Its effects stack. Remember that two doublings equals a tripling, and so on. 

IMPROVED MANIFESTATION [EPIC, PSIONIC]
You increase your power point reserve.
Prerequisites: Character level 21st, ability to manifest powers of the normal maximum power level in at least one psionic class.
Benefit: When you select this feat, you gain 19 power points.
Special: You can gain this feat multiple times. Each time you do so, you gain an additional number of power points
equal to your previous benefit +2.

IMPROVED MANYSHOT [EPIC] 
Prerequisites: Dex 19, base attack bonus +21, Many-shot, Point Blank Shot, Rapid Shot 
Benefits: As Manyshot, but the number of arrows the character can fire is limited only by his or her base attack bonus (two arrows, plus one arrow for every 5 points of base attack bonus above +6). 
Special: Regardless of the number of arrows the character fires, he or she only applies precision-based damage (such as sneak attack damage or the ranger’s favored enemy bonus) once. If the character scores a critical hit, only one of the arrows deals critical damage (character’s choice); all others deal normal damage. 
Normal: With the Manyshot feat, the character is limited to a maximum of four arrows fired (when the character’s base attack bonus is +16 or higher).

IMPROVED METAMAGIC [EPIC] 
Prerequisites: Four metamagic feats, Spellcraft 30 ranks. 
Benefit: The spell slot modifier of all the character’s metamagic feats is reduced by one level, to a minimum of +1. This feat has no effect on metamagic feats whose spell slot modifier is +1 or less. 
Special: A character can gain this feat multiple times. The effects stack, though a character can’t reduce any metamagic feat’s spell slot modifier to less than +1. 

IMPROVED METAPSIONICS [EPIC, PSIONIC]
You can manifest powers using metapsionic feats more easily than normal.
Prerequisites: Character level 21st, four metapsionic feats, Psicraft 30 ranks.
Benefit: Metapsionic powers you manifest cost 2 power points less than normal (to a minimum of 1 power point).
This feat has no effect on metapsionic powers that inflate the cost by only 2 power points.
Special: You can gain this feat multiple times. The effects stack, though you can’t lower the cost of any metapsionic
power to less than 1 power point.

IMPROVED SNEAK ATTACK [EPIC] 
Prerequisite: Sneak attack +8d6. 
Benefit: Add +1d6 to the character’s sneak attack damage. 
Special: This feat may be taken multiple times. Its effects stack. 

IMPROVED SPELL CAPACITY [EPIC] 
Prerequisite: Ability to cast spells of the normal maximum spell level in at least one spellcasting class. 
Benefit: When the character selects this feat, he or she gains one spell slot per day of any level up to one level higher than the highest-level spell the character can already cast in a particular class. The character must still have the requisite ability score (10 + spell level) in order to cast any spell stored in this slot. If the character has a high enough ability modifier to gain one or more bonus spells for this spell level, he or she also gains the bonus spells for this spell level. The character must use the spell slot as a member of the class in which he or she can already cast spells of the normal maximum spell level.
Special: A character can gain this feat multiple times.

Spell Slots Above 9th Level 
The Improved Spell Capacity feat allows characters to gain spell slots above 9th level (which can be used to hold lower-level spells or spells whose level has been increased beyond 9th by the use of metamagic feats).
A character with a very high score in the ability associated with his or her spellcasting (Intelligence for wizards; Wisdom for clerics, druids, paladins, and rangers; or Charisma for bards and sorcerers) may receive bonus spells of those levels, as shown on Table: Expanded Ability Modifiers and Bonus Spells, but only if they already have at least one spell slot of that level (such as from the Improved Spell Capacity feat). A character without any spell slots of a level can’t receive any bonus spells of that level, even if the appropriate ability score is high enough to award them.
Even though the table only includes ability scores up to 61 and spell slots up to 25th level, the progression continues infinitely in both directions. For ability scores beyond 61, or for spell slots above 25th level, expand the table to follow the same patterns as shown. 

Table: Expanded Ability Modifiers and Bonus Spells

——————————————— Spells per Day ——–———————–————————
Score
Modifier
10th
11th
12th
13th
14th
15th
16th
17th
18th
19th
20th
21st
22nd
23rd
24th
25th
10–11
+0
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
12–13
+1
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
14–15
+2
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
16–17
+3
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
18–19
+4
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
20–21
+5
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
22–23
+6
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
24–25
+7
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
26–27
+8
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
28–29
+9
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
30–31
+10
1
—
—
—
—
—
—
—
—
—
—
—
—
—
—
—
32–33
+11
1
1
—
—
—
—
—
—
—
—
—
—
—
—
—
—
34–35
+12
1
1
1
—
—
—
—
—
—
—
—
—
—
—
—
—
36–37
+13
1
1
1
1
—
—
—
—
—
—
—
—
—
—
—
—
38–39
+14
2
1
1
1
1
—
—
—
—
—
—
—
—
—
—
—
40–41
+15
2
2
1
1
1
1
—
—
—
—
—
—
—
—
—
—
42–43
+16
2
2
2
1
1
1
1
—
—
—
—
—
—
—
—
—
44–45
+17
2
2
2
2
1
1
1
1
—
—
—
—
—
—
—
—
46–47
+18
3
2
2
2
2
1
1
1
1
—
—
—
—
—
—
—
48–49
+19
3
3
2
2
2
2
1
1
1
1
—
—
—
—
—
—
50–51
+20
3
3
3
2
2
2
2
1
1
1
1
—
—
—
—
—
52–53
+21
3
3
3
3
2
2
2
2
1
1
1
1
—
—
—
—
54–55
+22
4
3
3
3
3
2
2
2
2
1
1
1
1
—
—
—
56–57
+23
4
4
3
3
3
3
2
2
2
2
1
1
1
1
—
—
58–59
+24
4
4
4
3
3
3
3
2
2
2
2
1
1
1
1
—
60–61
+25
4
4
4
4
3
3
3
3
2
2
2
2
1
1
1
1
etc. . . 


















IMPROVED SPELL RESISTANCE [EPIC] 
Prerequisite: Must have spell resistance from a feat, class feature, or other permanent effect. 
Benefit: The character’s spell resistance increases by +2. 
Special: A character can gain this feat multiple times. Its effects stack. 

IMPROVED STUNNING FIST [EPIC] 
Prerequisite: Dex 19, Wis 19, Improved Unarmed Strike, Stunning Fist. 
Benefit: Add +2 to the DC of the character’s stunning attack. 
Special: This feat may be taken multiple times. Its effects stack. 

IMPROVED WHIRLWIND ATTACK [EPIC] 
Prerequisites: Int 13, Dex 23, Combat Expertise, Dodge, Mobility, Spring Attack, Whirlwind Attack. 
Benefit: As a standard action, the character can make one melee attack for every five points of his or her base attack bonus (including epic attack bonus, round fractions down).
The character cannot attack any one opponent more than once as part of this action.  These attacks (as well as all other attacks made until the start of the character’s next turn) suffer a –4 penalty.
When using the Improved Whirlwind feat, the character also forfeits any bonus or extra attacks granted by other spells or abilities (such as Cleave or the haste spell).
Since these attacks are made as part of a standard action the character can’t make a 5-foot step between any two of the attacks.
Normal: Without this feat, using the Whirlwind Attack feat requires a full attack action, and the character can take a 5-foot step between any two of the attacks. 

INCITE RAGE [EPIC] 
Prerequisites: Cha 25, greater rage class feature. 
Benefit: When the character enters a rage, he or she can incite a barbarian rage in any or all allies within 60 feet. (Any ally who doesn’t wish to become enraged is unaffected.) The ally gains +4 to Strength, +4 to Constitution, and a +2 morale bonus on Will saves, but takes a –2 penalty to AC, for as long as the character remains raging. The rage of affected allies lasts a number of rounds equal to 3 + their Constitution modifier, regardless of whether they remain within 60 feet of the character. This is otherwise identical with normal barbarian rage (including the fatigue at its end). 
Special: This is a mind-affecting effect. 

INFINITE DEFLECTION [EPIC]
Prerequisites: Dex 25, Combat Reflexes, Deflect Arrows, Improved Unarmed Strike. 
Benefit: The character may perform any number of deflections each round, as the Deflect Arrows feat.

INSPIRE EXCELLENCE [EPIC] 
Prerequisite: Perform 30 ranks, bardic music class feature. 
Benefit: The character can use song or poetics to grant a bonus to one ability score to his or her allies. To be affected, an ally must hear the bard sing for 1 full round. The effect lasts as long as the bard sings and for 5 rounds after the bard stops singing (or 5 rounds after the ally can no longer hear the bard). While singing, the bard can fight but cannot cast spells, activate magic items by spell completion (such as scrolls), or activate magic items by command word (such as wands). Each ally to be inspired gains a +4 competence bonus to the same ability score, which the character must choose before he or she begins inspiring. Inspire excellence is a supernatural, mind-affecting ability. Use of this feat counts as one of the character’s bardic music uses for the day.
Special: This feat is treated as a bardic music inspiration ability for purposes of feats that affect such abilities. 

INSTANT RELOAD [EPIC]
Prerequisite: Quick Draw, Rapid Reload, Weapon Focus (crossbow type to be selected). 
Benefit: The character may fire the selected type of crossbow at his or her full normal attack rate. Reloading the crossbow does not provoke attacks of opportunity. 
Special: A character can gain this feat multiple times. Its effects do not stack. Each time a character takes the feat, it applies to a different type of crossbow. 

INTENSIFY SPELL [METAMAGIC][EPIC] 
Prerequisites: Empower Spell, Maximize Spell, Spellcraft 30 ranks, ability to cast 9th-level arcane or divine spells. 
Benefit: All variable, numeric effects of an intensified spell are maximized, then doubled. An intensified spell deals twice maximum damage, cures twice the maximum number of hit points, affects twice the maximum number of targets, and so forth, as appropriate. Saving throws and opposed rolls are not affected. An intensified spell uses up a spell slot seven levels higher than the spell’s actual level. A character can’t combine the effects of this feat with any other feat that affects the variable, numeric effects of a spell. 

KEEN STRIKE [EPIC] 
Prerequisites: Str 23, Wis 23, Improved Critical (unarmed strike), Improved Unarmed Strike, Stunning fist, ki strike (adamantine). 
Benefit: The character’s unarmed strike has a critical threat range of 18-20 and deals slashing damage (at the character’s option any attack can deal bludgeoning damage, but cannot then take advantage of the enhanced threat range). This ability doesn’t stack with other abilities that expand that character’s unarmed strike’s threat range. 

LASTING INSPIRATION [EPIC] 
Prerequisite: Perform 25 ranks, bardic music class feature. 
Benefit: The effects of the character’s bardic music inspiration abilities last for ten times as long as normal after he or she stops singing. This feat has no effect on inspiration abilities that have no duration after the character stops singing. 

LEGENDARY CLIMBER [EPIC]
Prerequisites: Dex 21, Balance 12 ranks, Climb 24 ranks. 
Benefit: The character can ignore any check penalties applied for accelerated climbing or rapid climbing. 
Normal: Without this feat, a character takes a –5 penalty on Climb checks when attempting to cover his or her full speed in climbing distance in a round, or a –20 penalty when attempting to cover twice his or her speed in climbing distance in a round.

LEGENDARY COMMANDER [EPIC]
Prerequisites: Cha 25, Epic Leadership, Leadership, Diplomacy 30 ranks, must rule own kingdom and have a stronghold. 
Benefit: Multiply the number of followers of each level that the character can lead by 10. This has no effect on cohorts. 

LEGENDARY LEAPER [EPIC] 
Prerequisite: Jump 24 ranks. 
Benefit: The character need only move 5 feet in a straight line to make a running jump.
Normal: Without this feat, a character must move at least 20 feet in a straight line before attempting a running jump. 

LEGENDARY RIDER [EPIC]
Prerequisite: Ride 24 ranks. 
Benefit: The character doesn’t take a penalty on Ride checks when riding a mount without a saddle (bareback).  The character never needs to make a Ride check to control a mount in combat (and even controlling a mount not trained for combat doesn’t require an action). 
Normal: Without this feat, a character takes a –5 penalty on Ride checks without a saddle, and must make a Ride check to control a mount in combat (and controlling a mount not trained for combat requires a move action). 

LEGENDARY TRACKER [EPIC] 
Prerequisites: Wis 25, Track, Knowledge (nature) 30 ranks, Survival 30 ranks. 
Benefit: The character can track creatures across water, under-water, or through the air. This adds the surfaces of water, underwater, and air to the list of surfaces found under the Track feat: 
Surface
DC 
Water
60 
Underwater
80 
Air
120 

LEGENDARY WRESTLER [EPIC] 
Prerequisite: Str 21, Dex 21, Improved Unarmed Strike, Escape Artist 15 ranks. 
Benefit: The character gains a +10 bonus on all grapple checks. 

LINGERING DAMAGE [EPIC] 
Prerequisite: Sneak attack +8d6, crippling strike class feature. 
Benefit: Any time the character deals damage with a sneak attack, that target takes damage equal to the character’s sneak attack bonus damage on the character’s next turn as well. 

MAGICAL BEAST COMPANION [WILD][EPIC] 
Prerequisites: Knowledge (nature) 24 ranks, wild shape 6/day. 
Benefit: The following magical beasts are added to the lists of animal companions from which you can select.
1st Level (no adjustment) 
Stirge
Darkmantle

4th Level (-3)
Hippogriff
Shocker lizard

7th Level (-6)
Cockatrice
Ankheg
Griffon
Owlbear
Sea cat*

10th Level (-9)
Basilisk
Digerster
Girallon
Spider eater

13th Level (-12)
Bulette
Chimera
Remorhaz

16th Level (-15)
Gorgon
Gray render

Special: Creatures marked with an asterisk are available only in an aquatic environment.

MAGICAL BEAST WILD SHAPE [WILD][EPIC]
Prerequisites: Wis 25, Knowledge (nature) 27 ranks, wild shape 6/day. 
Benefit: The character can use his or her normal wild shape ability to take the form of a magical beast. The size limitation is the same as the character’s limitation on animal size. The character gains all supernatural abilities of the magical beast whose form he or she takes. 

MASTER STAFF [EPIC] 
Prerequisite: Craft Staff, Spellcraft 15 ranks. 
Benefit: When the character activates a staff, he or she can substitute a spell slot instead of using a charge. The spell slot must be one the character ahs not used for the day, though the character may lose a prepared spell to emulate a wand charge (the character may not lose prepared spells from his or her school of specialty, if any). The spell slot lost must be equal to or higher in level than the specific spell stored in the staff, including any level-increasing metamagic enhancements. A character cannot emulate a charge for a staff function that does not match a specific spell.

MASTER WAND [EPIC] 
Prerequisite: Craft Wand, Spellcraft 15 ranks. 
Benefit: When the character activates a wand, he or she can substitute a spell slot instead of using a charge. The spell slot must be one the character has not used for the day, though he or she may lose a prepared spell to emulate a wand charge (the character may not lose prepared spells from his or her school of specialty, if any). The spell slot lost must be equal to or higher in level than the spell stored in the wand, including any level-increasing metamagic enhancements. 

MIGHTY RAGE [EPIC] 
Prerequisites: Str 21, Con 21, greater rage class feature, rage 5/day. 
Benefit: When the character rages, he or she gains a +8 bonus to Strength and Constitution and a +4 morale bonus on Will saves. (These bonuses replace the normal rage bonuses.) 

MOBILE DEFENSE [EPIC]
Prerequisites: Dex 15, Dodge, Mobility, Spring Attack, defensive stance 3/day class feature. 
Benefit: While in a defensive stance, the character may take one 5-foot adjustment each round without losing the benefits of the stance. 
Normal: Without this feat, a character can’t move while in a defensive stance. 

MULTISPELL [EPIC] 
Prerequisites: Quicken Spell, ability to cast 9th-level arcane or divine spells. 
Benefit: The character may cast one additional quickened spell in a round. 
Special: A character can gain this feat multiple times. Its effects stack. 

MULTIWEAPON REND [EPIC] 
Prerequisites: Dex 15, base attack bonus +9, three or more hands, Multiweapon Fighting. 
Benefit: If the character hits an opponent with two or more weapons (wielded in different hands) in the same round, he or she may automatically rend the opponent. This rending deals additional damage equal to the base damage of the smallest weapon that hit plus 1 1/2 times the character’s Strength modifier. The character can only rend once per round, regardless of how many successful attacks he or she makes. 
Special: This feat replaces the Two-Weapon Rend feat for creatures with more than two arms. 

MUSIC OF THE GODS [EPIC] 
Prerequisites: Cha 25, Perform 30 ranks, bardic music class feature. 
Benefit: The character’s bardic music can affect even those normally immune to mind-affecting effects. However, such creatures gain a +10 bonus on their Will saves to resist such effects. 

NEGATIVE ENERGY BURST [DIVINE][EPIC] 
Prerequisites: Cha 25, ability to rebuke or command undead, ability to cast inflict critical wounds, any evil alignment. 
Benefit: The character can use one rebuke or command undead attempt to unleash a wave of negative energy in a 60-foot-burst. Roll a normal rebuke (or command) check, except that the negative energy burst affects living creatures rather than undead. Any creature that would be rebuked by this result gains one negative level. Any creature that would be commanded by this check gains two negative levels. The Fortitude save DC to remove these levels one day later is equal to 10 + 1/2 the character’s effective turning level + the character’s Charisma modifier. 

OVERWHELMING CRITICAL [EPIC] 
Prerequisites: Str 23, Cleave, Great Cleave, Improved Critical (chosen weapon), Power Attack, Weapon Focus (chosen weapon). 
Benefit: When using the weapon the character has selected, he or she deals an extra 1d6 points of bonus damage on a successful critical hit. If the weapon’s critical multiplier is x3, add +2d6 points of bonus damage instead, and if the multiplier is x4, add +3d6 points of bonus damage instead. Creatures immune to critical hits can’t be affected by this feat.
Special: A character can gain this feat multiple times. Its effects do not stack. Each time a character takes the feat, it applies to a different type of weapon. 

PENETRATE DAMAGE REDUCTION [EPIC] 
Select a special material, such as adamantine. 
Benefit: The character melee weapons (including natural weapons) are treated as being crafted from the chosen special material for the purposes of bypassing the damage reduction of any creature the character strikes. None of the other special properties of special materials are gained by the character’s melee weapons.
Special: A character can gain this feat multiple times.  Each time the feat is selected the character selects a different special material.  The character’s melee attacks are treated as being crafted of all chosen materials for the purposes of bypassing damage reduction.

PERFECT HEALTH [EPIC] 
Prerequisite: Con 25, Great Fortitude. 
Benefit: The character is immune to all nonmagical diseases, as well as to all poisons whose Fortitude save DC is 25 or less. 

PERFECT MULTIWEAPON FIGHTING [EPIC] 
Prerequisite: Dex 25, three or more hands, Greater Multiweapon Fighting, Multiweapon Fighting. 
Benefit: The character can make as many attacks with each extra weapon as with his or her primary weapon, using the same base attack bonus. The character still takes the normal penalties for fighting with two weapons. 
Normal: A creature without this feat can make only one attack per round with each extra weapon (or two attacks per round with each weapon if it has Multiweapon Fighting, or three attacks per round with each extra weapon if it has Greater Multiweapon Fighting). Each attack after the first extra attack has a cumulative –5 penalty. 
Special: This feat replaces the Perfect Two-Weapon Fighting feat for creatures with more than two arms.

PERFECT TWO-WEAPON FIGHTING [EPIC] 
Prerequisites: Dex 25, Greater Two-Weapon Fighting, Improved Two-Weapon Fighting, Two-Weapon Fighting. 
Benefit: The character can make as many attacks with his or her off-hand weapon as with his or her primary weapon, using the same base attack bonus. The character still takes the normal penalties for fighting with two weapons. 
Normal: Without this feat, a character can only get a single attack with an off-hand weapon (or two attacks with an off-hand weapon if he or she has Improved Two-Weapon Fighting, or three attacks with an off-hand weapon if he or she has Greater Two-Weapon Fighting). 

PERMANENT EMANATION [EPIC] 
Prerequisites: Spellcraft 25 ranks, ability to cast the spell to be made permanent. 
Benefit: Designate any one of the character’s spells whose area is an emanation from the character. This spell’s effect is permanent (though the character can dismiss or restart it as a free action). Effects that would normally dispel this spell instead suppress it for 2d4 rounds. 
Special: This feat may be taken multiple times. Each time, select a different spell to become permanent. 

PLANAR TURNING [EPIC] 
Prerequisites: Wis 25, Cha 25, ability to turn or rebuke undead. 
Benefit: The character can turn or rebuke outsiders as if they were undead. An outsider has effective turn resistance equal to half its spell resistance (round down). If the character can turn undead, he or she turns (or destroys) all evil outsiders and rebukes (or commands) all nonevil outsiders. If the character can rebuke undead, he or she rebukes (or commands) all evil outsiders and turns (or destroys) all nonevil outsiders. 

PLANT WILD SHAPE [WILD][EPIC]
Prerequisites: Knowledge (nature) 24 ranks, wild shape 4/day. 
Benefit: The character can use his or her normal wild shape ability to take the form of a plant. The size limitation is the same as the character’s limitation on animal size. 

POLYGLOT [EPIC] 
Prerequisites: Int 25, Speak Language (five languages). 
Benefit: The character can speak all languages. If the character is literate, he or she can also read and write all languages (not including magical script). 

POSITIVE ENERGY AURA [EPIC] 
Prerequisites: Cha 25, ability to turn undead, ability to cast dispel evil. 
Benefit: Every undead creature that comes within 15 feet of the character is automatically affected as if the character had turned it. This doesn’t cost a turning attempt, and the character doesn’t have to roll turning damage (it automatically affects all undead in a 15-foot burst), but it only turns undead with Hit Dice equal to or less than the character’s effective cleric level minus 10 (and automatically destroys undead with Hit Dice equal to or less than the character’s effective cleric level minus 20). Just as with normal turning, the character can’t affect undead that have total cover relative to him or her. 

POWER KNOWLEDGE [EPIC, PSIONIC]
You add two additional powers to your list of powers known.
Prerequisites: Character level 21st, ability to manifest powers of the normal maximum power level in at least one psionic class.
Benefit: You learn two new powers of any level up to the highest level of power you can manifest. The powers you select must be on your class list or the list for your discipline.
Special: You can gain this feat multiple times. Each time, you learn two new powers at any level up to the highest level of power you can manifest.

PSICRYSTAL POWER [EPIC, PSIONIC]
Your psicrystal can manifest a power.
Prerequisites: Character level 21st, Intelligence 25 or Charisma 25 (depending on which is your key ability score for manifesting).
Benefit: Choose one power you know of 8th level or lower. Your psicrystal can now manifest this power once per day at your manifester level (the psicrystal gains sufficient power points to manifest the power once). You cannot bestow a power upon your psicrystal if the power normally has any experience point cost.
Special: You can gain this feat multiple times. Each time you take the feat, you can give your psicrystal knowledge of a new power (and it gains sufficient power points to manifest that power once).
All power points gained by a psicrystal from multiple applications of this feat go into its reserve and can be used to manifest the powers it knows as you desire.

RANGED INSPIRATION [EPIC] 
Prerequisite: Bardic music class feature, Perform 25 ranks 
Benefit: Double the range of any bardic music ability that has a range. (If the creature must hear the bard to be affected by the ability, that requirement doesn’t change regardless of any extended range the bard’s ability may have.) 
Special: A character can gain this feat multiple times. Its effects stack. Remember that two doublings equals a tripling, and so forth.

RAPID INSPIRATION [EPIC]
Prerequisite: Perform 25 ranks, bardic music class feature. 
Benefit: The character can use any of his or her bardic music inspiration abilities as a standard action. The inspiration takes effect immediately after the character concludes the action. 

REACTIVE COUNTERSONG [EPIC] 
Prerequisite: Combat Reflexes, Perform 30 ranks, bardic music class feature. 
Benefit: The character can begin a countersong at any time, even when it isn’t his or her turn (much like a wizard who has readied a counterspell action), though the character doesn’t have to ready an action to do so. The character can’t use Reactive Countersong at the same time he or she isusing another bardic music ability (though the character could stop the other bardic music ability to begin Reactive Countersong if so desired). 
Normal: Without this feat, a character can only use counter-song on his or her turn. 

REFLECT ARROWS [EPIC] 
Prerequisites: Dex 25, Deflect Arrows, Improved Unarmed Strike. 
Benefit: When the character deflects an arrow or other ranged attack, the attack is reflected back upon the attacker at the character’s base ranged attack bonus. 

RIGHTEOUS STRIKE [EPIC] 
Prerequisites: Wis 19, Improved Unarmed Strike, Stunning Fist, any lawful alignment. 
Benefit: The character’s unarmed strike is treated as an axiomatic weapon (it is lawfully aligned and deals an extra 2d6 points of damage against creatures of chaotic alignment). This ability doesn’t stack with similar abilities. 

RUINOUS RAGE [EPIC] 
Prerequisites: Str 25, Improved Sunder, Power Attack, rage 5/day. 
Benefit: While in a rage, the character ignores the hardness of any object he or she strikes. Also, double the character’s Strength bonus for the purposes of any Strength check made to break an object with sudden force rather than by dealing normal damage (including bursting bindings, such as ropes or manacles). 

SCRIBE EPIC SCROLL [ITEM CREATION][EPIC] 
Prerequisites: Scribe Scroll, Knowledge (arcana) 24 ranks, Spellcraft 24 ranks. 
Benefit: The character can scribe scrolls that exceed the normal limits for such items. Even this feat does not allow the character to scribe a scroll with an epic spell.

SELF-CONCEALMENT [EPIC] 
Prerequisites: Dex 30, Hide 30 ranks, Tumble 30 ranks, improved evasion. 
Benefit: Attacks against the character have a 10% miss chance, similar to the effect of concealment. The character loses this benefit whenever he or she would lose his or her Dexterity bonus to AC. 
Special: This feat may be taken multiple times. Each time it is taken, the miss chance increases by 10% to a maximum of 50% after it has been taken five times. 

SHATTERING STRIKE [EPIC] 
Prerequisites: Epic Weapon Focus (unarmed strike), Weapon Focus (unarmed strike), Concentration 25 ranks, ki strike (adamantine). 
Benefit: When using an unarmed strike to attempt to break an object with sudden force (rather than by dealing normal damage), make a Concentration check rather than a Strength check. The break DC remains the same. Using Shattering Strike is a full-round action that incurs attacks of opportunity. The character can’t use Shattering Strike to escape bonds (unless he or she is so bound as to allow the character to make an unarmed strike against his or her bindings). 

SNEAK ATTACK OF OPPORTUNITY [EPIC] 
Prerequisites: Sneak attack +8d6, opportunist class feature. 
Benefit: Any attack of opportunity the character makes is considered a sneak attack. 

SPECTRAL STRIKE [EPIC] 
Prerequisites: Wis 19, ability to turn or rebuke undead. 
Benefit: The character’s attacks deal damage normally against incorporeal creatures. 
Normal: Without this feat, even attacks that can damage an incorporeal creature have a 50% chance to deal no damage.

SPELL KNOWLEDGE [EPIC] 
Prerequisite: Ability to cast spells of the maximum normal spell level of an arcane spellcasting class. 
Benefit: The character learns two new arcane spells of any level up to the maximum level he or she can cast. This feat does not grant any additional spell slots. 
Special: A character can gain this feat multiple times. 

SPELL OPPORTUNITY [EPIC] 
Prerequisites: Combat Casting, Combat Reflexes, Quicken Spell, Spellcraft 25 ranks. 
Benefit: Whenever the character is allowed an attack of opportunity, he or she may cast (and attack with) a touch spell as the character’s attack of opportunity. This incurs attacks of opportunity just as if the character had cast the spell normally. 
Normal: Without this feat, a character can only make a melee attack as an attack of opportunity. 

SPELL STOWAWAY [EPIC] 
Prerequisites: Spellcraft 24 ranks, caster level 12th. 
Benefit: Choose a spell-like ability the character knows, or a spell the character cam cast.  The character is attuned to the magic he or she chooses. If another spellcaster within 300 feet of the character uses this magic, the character also immediately gains the magic’s effect as if it had been used on the character by the same caster. The character must have direct line of effect to the spellcaster in order to gain the benefit of the attuned magic (though the character does not have to know the spellcaster is present, and he or she can be flat-footed). The magic’s duration, effect, and other specifics are determined by its original caster’s level. 
Special: A character can gain this feat multiple times. Its effects do not stack. Each time a character takes the feat, it applies to a different spell or spell-like ability. 

SPELLCASTING HARRIER [EPIC] 
Prerequisite: Combat Reflexes. 
Benefit: Any spellcaster the character threatens in melee provokes an attack of opportunity if he or she tries to cast defensively.  The character gets a +4 bonus on this attack roll.

SPONTANEOUS DOMAIN ACCESS [EPIC]
Prerequisites: Wis 25, Spellcraft 30 ranks, ability to cast 9th-level divine spells. 
Benefit: Select a domain the character has access to. The character may spontaneously convert any prepared cleric spell (except a domain spell) into a domain spell of the same level in the selected domain, just as a cleric channels energy to convert spells into cure spells. 
Special: A character can gain this feat multiple times. Each time a character takes the feat, it applies to a different domain. 

SPONTANEOUS SPELL [EPIC]
Prerequisite: Spellcraft 25 ranks, ability to cast the maximum normal spell level of at least one spell-casting class. 
Benefit: Select a spell the character can cast. The character may spontaneously convert any prepared spell of the selected spell’s level into the selected spell, just as a cleric channels energy to convert spells into cure spells. 
Special: A character can gain this feat multiple times. Each time he or she takes the feat, it applies to a different spell. 

STORM OF THROWS [EPIC] 
Prerequisite: Dex 23, Point Blank Shot, Quick Draw, Rapid Shot. 
Benefit: As a full-round action, the character may throw a light weapon at his or her full base attack bonus at each opponent within 30 feet. All light weapons thrown need not be the same type. 

SUPERIOR INITIATIVE [EPIC] 
Prerequisite: Improved Initiative. 
Benefit: The character gets a +8 bonus on initiative checks. This bonus overlaps (does not stack with) the bonus from Improved Initiative. 

SWARM OF ARROWS [EPIC]
Prerequisites: Dex 23, Point Blank Shot, Rapid Shot, Weapon Focus (type of bow used). 
Benefit: As a full-round action, the character may fire an arrow at his or her full base attack bonus at each opponent within 30 feet. 

TERRIFYING RAGE [EPIC]
Prerequisites: Intimidate 25 ranks, rage 5/day
Benefit: While you are raging, any enemy that views you must make a Will save opposed by your Intimidate check of become panicked (if it have HD less than your character level) or shaken (if it has HD equal to or up to twice your character level) for 4d6 rounds.  An enemy with Hit Dice greater than twice your character level is not affected by this feat.

TENACIOUS MAGIC [EPIC] 
Prerequisites: Spellcraft 15 ranks. 
Benefit: Choose one spell the character knows or spell-like ability the character possesses. Whenever the chosen form of magic would otherwise end due to a dispel effect, the magic is instead only suppressed for 1d4 rounds. The magic still ends when its duration expires, but the suppressed rounds do not count against its duration. The character can dismiss his or her own spell or spell-like ability (if dismissible) or dispel his or her own tenacious magic normally. 
Special: A character can gain this feat multiple times. Each time he or she takes the feat, it applies to a different spell or spell-like ability. 

THUNDERING RAGE [EPIC] 
Prerequisites: Str 25, rage 5/day. 
Benefit: Any weapon the character wields while in a rage is treated as a thundering weapon. The DC of the Fortitude save to resist deafness is equal to 10 + 1/2 the character’s level. This ability does not stack with similar abilities. 

TRAP SENSE [EPIC] 
Prerequisites: Search 25 ranks, Spot 25 ranks, trapfinding class ability. 
Benefit: If the character passes within 5 feet of a trap, he or she is entitled to a Search check to notice it as if the character was actively looking for it. 

TWO-WEAPON REND [EPIC] 
Prerequisites: Dex 15, base attack bonus +9, Improved Two-Weapon Fighting, Two-Weapon Fighting. 
Benefit: If the character hits an opponent with a weapon in each hand in the same round, he or she may automatically rend the opponent. This deals additional damage equal to the base damage of the smaller weapon plus 1 1/2 times the character’s Strength modifier. Base weapon damage includes an enhancement bonus on damage, if any. The character can only rend once per round, regardless of how many successful attacks he or she makes. 

UNCANNY ACCURACY [EPIC]
Prerequisites: Dex 21, base attack bonus +11, Point Blank Shot, Precise Shot, Improved Precise Shot, Spot 20 ranks. 
Benefit: The character’s ranged attacks ignore the miss chance granted to targets by total concealment.  The character must aim his or her attacks at the correct square to gain advantage of this feat. 
Normal: Without this feat, characters suffer a 50% miss chance when making a ranged attack against a target with total concealment.
Special: A character with at least 11 levels of ranger can qualify for this feat even if he or she does not have the prerequisites for it, but can only use it when wearing light or no armor.

UNDEAD MASTERY [DIVINE][EPIC] 
Prerequisites: Cha 21, ability to rebuke or command undead. 
Benefit: The character may command up to ten times his or her level in HD of undead. 

UNHOLY STRIKE [EPIC] 
Prerequisites: Smite good class feature, any evil alignment. 
Benefit: Any weapon the character wields is treated as an unholy weapon (it is evil-aligned and deals an extra 2d6 points of damage against creatures of good alignment). This ability doesn’t stack with similar abilities. If the weapon already has an alignment, this feat has no effect on the weapon.

VERMIN WILD SHAPE [WILD][EPIC] 
Prerequisites: Knowledge (nature) 24 ranks, wild shape 6/day. 
Benefit: The character can use his or her normal wild shape ability to take the form of a vermin. The size limitation is the same as the character’s limitation on animal size. 

VORPAL STRIKE [EPIC] 
Prerequisites: Str 25, Wis 25, Improved Critical (unarmed strike), Improved Unarmed Strike, Keen Strike, Stunning Fist, ki strike (adamantine). 
Benefit: The character’s unarmed strike is considered to be a slashing vorpal weapon. (At the character’s option, any unarmed strike can do bludgeoning damage instead, but it loses the vorpal quality.) This ability doesn’t stack with similar abilities

WIDEN AURA OF COURAGE [EPIC]
Prerequisite: Cha 25, aura of courage class ability. 
Benefit: The character’s aura of courage extends to all allies within 100 feet of the character. 

WIDEN AURA OF DESPAIR [EPIC] 
Prerequisite: Cha 25, aura of despair class ability. 
Benefit: The character’s aura of despair extends to all allies within 100 feet of the character. 

ZONE OF ANIMATION [DIVINE][EPIC]
Prerequisite: Cha 25, Undead Mastery, ability to rebuke or command undead. 
Benefit: The character can use a rebuke or command undead attempt to animate corpses within range of his or her rebuke or command attempt. The character animates a total number of HD of undead equal to the number of undead that would be commanded by the character’s result (though the character can’t animate more undead than there are available corpses within range). The character can’t animate more undead with any single attempt than the maximum number he or she can command (including any undead already under his or her command). These undead are automatically under the character’s command, though his or her normal limit of commanded undead still applies. If the corpses are relatively fresh, the animated undead are zombies. Otherwise, they are skeletons.



These feats are not epic feats, so they may be selected by character any time he or she could select a new feat.

GREATER MULTIWEAPON FIGHTING [GENERAL]
Prerequisites: Dex 19, three or more arms, Improved Multiweapon Fighting, Multiweapon Fighting, base attack bonus +15.
Benefit: The creature may make up to three extra attacks with each extra offhand weapon it wields, albeit at a –10 penalty on the third attack with each weapon.
Special: This feat replaces the Greater Two-Weapon Fighting feat for creatures with more than two arms.

IMPROVED FLYBY ATTACK [GENERAL] 
Prerequisite: Fly speed, Dodge, Flyby Attack, Mobility. 
Benefit: If the standard action taken by a creature during a round in which it uses Flyby Attack is a melee attack, the creature provokes no attacks of opportunity from moving out of squares threatened by its target.
Normal: Without this feat, a creature making an attack as part of a Flyby Attack maneuver provokes attacks of opportunity as normal from moving out of squares threatened by its target.

IMPROVED MULTIATTACK [GENERAL]
Prerequisite: Three or more natural weapons, Multiattack
Benefit: The creature’s secondary attacks with natural weapons have no penalty. They still add only one-half the creature’s Strength bonus, if any, to damage dealt.
Normal: Without this feat, the creature’s secondary natural attacks have a –5 penalty (or a –2 penalty if it has the Multiattack feat).

IMPROVED MULTIWEAPON FIGHTING [GENERAL]
Prerequisites: Dex 15, three or more arms, Multiweapon Fighting, base attack bonus +9.
Benefit: In addition to the single extra attack a creature gets with each extra weapon from Multiweapon Fighting, it gets a second attack with each extra weapon, albeit at a –5 penalty.
Normal: With only Multiweapon Fighting, a creater can only get a single attack with each extra weapon. 
Special: This feat replaces the Improved Two-Weapon Fighting feat for creatures with more than two arms.

Monster Feats
-------------

MONSTER FEATS
These feats apply to abilities most commonly found amongst monsters or are related to monsters.

ABILITY FOCUS  [GENERAL]
Choose one of the creature’s special attacks.
Prerequisite: Special attack.
Benefit: Add +2 to the DC for all saving throws against the special attack on which the creature focuses.
Special: A creature can gain this feat multiple times. Its effects do not stack. Each time the creature takes the feat it applies to a different special attack.

AWESOME BLOW [GENERAL, FIGHTER]
Prerequisites: Str 25, Power Attack, Improved Bull Rush, size Large or larger.
Benefit: As a standard action, the creature may choose to subtract 4 from its melee attack roll and deliver an awesome blow. If the creature hits a corporeal opponent smaller than itself with an awesome blow, its opponent must succeed on a Reflex save (DC = damage dealt) or be knocked flying 10 feet in a direction of the attacking creature’s choice and fall prone. The attacking creature can only push the opponent in a straight line, and the opponent can’t move closer to the attacking creature than the square it started in. If an obstacle prevents the completion of the opponent’s move, the opponent and the obstacle each take 1d6 points of damage, and the opponent stops in the space adjacent to the obstacle.

CRAFT CONSTRUCT [ITEM CREATION]
Prerequisites: Craft Magic Arms and Armor, Craft Wondrous Item.
Benefit: A creature with this feat can create any construct whose prerequisites it meets. Enchanting a construct takes one day for each 1,000 gp in its market price. To enchant a construct, a spellcaster must spend 1/25 the item’s price in XP and use up raw materials costing half of this price (see individual construct monster entries for details).
A creature with this feat can repair constructs that have taken damage. In one day of work, the creature can repair up to 20 points of damage by expending 50 gp per point of damage repaired.
A newly created construct has average hit points for its Hit Dice.

EMPOWER SPELL-LIKE ABILITY  [GENERAL]
Prerequisite: Spell-like ability at caster level 6th or higher.
Benefit: Choose one of the creature’s spell-like abilities, subject to the restrictions below. The creature can use that ability as an empowered spell-like ability three times per day (or less, if the ability is normally usable only once or twice per day).
When a creature uses an empowered spell-like ability, all variable, numeric effects of the spell-like ability are increased by one half. Saving throws and opposed rolls are not affected. Spell-like abilities without random variables are not affected.
The creature can only select a spell-like ability duplicating a spell with a level less than or equal to half its caster level (round down) –2. For a summary, see the table in the description of the Quicken Spell-Like Ability feat. 
Special: This feat can be taken multiple times. Each time it is taken, the creature can apply it to a different one of its spell-like abilities.

FLYBY ATTACK  [GENERAL]
Prerequisite: Fly speed.
Benefit: When flying, the creature can take a move action (including a dive) and another standard action at any point during the move. The creature cannot take a second move action during a round when it makes a flyby attack.
Normal: Without this feat, the creature takes a standard action either before or after its move.

HOVER  [GENERAL]
Prerequisite: Fly speed.
Benefit: When flying, the creature can halt its forward motion and hover in place as a move action. It can then fly in any direction, including straight down or straight up, at half speed, regardless of its maneuverability.
If a creature begins its turn hovering, it can hover in place for the turn and take a full-round action. A hovering creature cannot make wing attacks, but it can attack with all other limbs and appendages it could use in a full attack. The creature can instead use a breath weapon or cast a spell instead of making physical attacks, if it could normally do so.
If a creature of Large size or larger hovers within 20 feet of the ground in an area with lots of loose debris, the draft from its wings creates a hemispherical cloud with a radius of 60 feet. The winds so generated can snuff torches, small campfires, exposed lanterns, and other small, open flames of non-magical origin. Clear vision within the cloud is limited to 10 feet. Creatures have concealment at 15 to 20 feet (20% miss chance). At 25 feet or more, creatures have total concealment (50% miss chance, and opponents cannot use sight to locate the creature).
Those caught in the cloud must succeed on a Concentration check (DC 10 + 1/2 creature’s HD) to cast a spell.
Normal: Without this feat, a creature must keep moving while flying unless it has perfect maneuverability.

IMPROVED NATURAL ARMOR  [GENERAL]
Prerequisites: Natural armor, Con 13.
Benefit: The creature’s natural armor bonus increases by 1.
Special: A creature can gain this feat multiple times. Each time the creature takes the feat its natural armor bonus increases by another point.

IMPROVED NATURAL ATTACK  [GENERAL]
Prerequisite: Natural weapon, base attack bonus +4.
Benefit: Choose one of the creature’s natural attack forms. The damage for this natural weapon increases by one step, as if the creature’s size had increased by one category: 1d2, 1d3, 1d4, 1d6, 1d8, 2d6, 3d6, 4d6, 6d6, 8d6, 12d6. 
A weapon or attack that deals 1d10 points of damage increases as follows: 1d10, 2d8, 3d8, 4d8, 6d8, 8d8, 12d8.

MULTIATTACK  [GENERAL]
Prerequisite: Three or more natural attacks.
Benefit: The creature’s secondary attacks with natural weapons take only a –2 penalty.
Normal: Without this feat, the creature’s secondary attacks with natural weapons take a –5 penalty.

MULTIWEAPON FIGHTING  [GENERAL]
Prerequisites: Dex 13, three or more hands.
Benefit: Penalties for fighting with multiple weapons are reduced by 2 with the primary hand and reduced by 6 with off hands.
Normal: A creature without this feat takes a –6 penalty on attacks made with its primary hand and a –10 penalty on attacks made with its off hands. (It has one primary hand, and all the others are off hands.) See Two-Weapon Fighting.
Special: This feat replaces the Two-Weapon Fighting feat for creatures with more than two arms.

QUICKEN SPELL-LIKE ABILITY  [GENERAL]
Prerequisite: Spell-like ability at caster level 10th or higher.
Benefit: Choose one of the creature’s spell-like abilities, subject to the restrictions described below. The creature can use that ability as a quickened spell-like ability three times per day (or less, if the ability is normally usable only once or twice per day).
Using a quickened spell-like ability is a free action that does not provoke an attack of opportunity. The creature can perform another action—including the use of another spell-like ability—in the same round that it uses a quickened spell-like ability. The creature may use only one quickened spell-like ability per round.
The creature can only select a spell-like ability duplicating a spell with a level less than or equal to half its caster level (round down) –4. For a summary, see the table below.
In addition, a spell-like ability that duplicates a spell with a casting time greater than 1 full round cannot be quickened.
Normal: Normally the use of a spell-like ability requires a standard action and provokes an attack of opportunity unless noted otherwise.
Special: This feat can be taken multiple times. Each time it is taken, the creature can apply it to a different one of its spell-like abilities.

Empower and Quicken Spell-Like Ability
Spell Level
Caster Level to Empower
Caster Level to Quicken
0
4th
8th
1st
6th
10th
2nd
8th
12th
3rd
10th
14th
4th
12th
16th
5th
14th
18th
6th
16th
20th
7th
18th
—
8th
20th
—
9th
—
—

SNATCH  [GENERAL]
Prerequisite: Size Huge or larger.
Benefits: The creature can choose to start a grapple when it hits with a claw or bite attack, as though it had the improved grab special attack. If the creature gets a hold on a creature three or more sizes smaller, it squeezes each round for automatic bite or claw damage. A snatched opponent held in the creature’s mouth is not allowed a Reflex save against the creature’s breath weapon, if it has one.
The creature can drop a creature it has snatched as a free action or use a standard action to fling it aside. A flung creature travels 1d6 x 10 feet, and takes 1d6 points of damage per 10 feet traveled. If the creature flings a snatched opponent while flying, the opponent takes this amount or falling damage, whichever is greater.

WINGOVER  [GENERAL]
Prerequisite: Fly speed.
Benefits: A flying creature with this feat can change direction quickly once each round as a free action. This feat allows it to turn up to 180 degrees regardless of its maneuverability, in addition to any other turns it is normally allowed. A creature cannot gain altitude during a round when it executes a wingover, but it can dive.
The change of direction consumes 10 feet of flying movement.
