Races
=====

Miscellaneous
-------------

Favored Class
~~~~~~~~~~~~~

indexterm:[Favored Class]

A character's favored class doesn't count against him or her when determining experience point penalties for multiclassing.

Race and Languages
~~~~~~~~~~~~~~~~~~
All characters know how to speak Common. A dwarf, elf, gnome, half-elf, half-orc, or halfling also speaks a racial language, as appropriate. A character who has an Intelligence bonus at 1st level speaks other languages as well, one extra language per point of Intelligence bonus as a starting character.
indexterm:[Languages,Class Languages]

*Literacy:* Any character except a barbarian can read and write all the languages he or she speaks.

*Class-Related Languages:* Clerics, druids, and wizards can choose certain languages as bonus languages even if they're not on the lists found in the race descriptions. These class-related languages are as follows:

*Cleric:* Abyssal, Celestial, Infernal.

*Druid:* Sylvan.

*Wizard:* Draconic.

Small Characters
~~~~~~~~~~~~~~~~
A Small character gets a +1 size bonus to Armor Class, a +1 size bonus on attack rolls, and a +4 size bonus on Hide checks. A Small character's carrying capacity is three-quarters of that of a Medium character.

A Small character generally moves about two-thirds as fast as a Medium character.

A Small character must use smaller weapons than a Medium character.

Races with Level Adjustment 0
-----------------------------

Humans
~~~~~~
indexterm:[Humans]

* *Medium:* As Medium creatures, humans have no special bonuses or penalties due to their size.

* Human base land speed is 30 feet.

* 1 extra feat at 1st level.

* 4 extra skill points at 1st level and 1 extra skill point at each additional level.

* *Automatic Language:* Common. *Bonus Languages:* Any (other than secret languages, such as Druidic). See the Speak Language skill.

* *Favored Class:* Any. When determining whether a multiclass human takes an experience point penalty, his or her highest-level class does not count.

Dromites
~~~~~~~~

indexterm:[Dromites]

* +2 Charisma, –2 Strength, –2 Wisdom

* *Monstrous Humanoid:* Dromites are not subject to spells or effects that affect humanoids only, such as charm person or dominate person.

* *Small:* As a Small creature, a dromite gains a +1 size bonus to Armor Class, a +1 size bonus on attack rolls, and a +4 size bonus on Hide checks, but it uses smaller weapons than humans use, and its lifting and carrying limits are three-quarters of those of a Medium character.

* Dromite base land speed is 20 feet.

* *Chitin:* A dromite’s skin is hardened, almost like an exoskeleton, and grants the character a +3 natural armor bonus to AC and one of the following kinds of resistance to energy: cold 5, electricity 5, fire 5, or sonic 5. The player chooses what type of energy resistance is gained when the character is created. (This choice also dictates which caste the dromite belongs to.) This natural energy resistance stacks with any future energy resistance gained through other effects.

* *Naturally Psionic:* Dromites gain 1 bonus power point at 1st level. This benefit does not grant them the ability to manifest powers unless they gain that ability through another source, such as levels in a psionic class.

* *Psi-Like Ability:* 1/day—energy ray. A dromite always deals the kind of energy damage that its chitin has resistance to (for example, a dromite who has resistance to cold 5 deals cold damage with its energy ray). Manifester level is equal to 1/2 Hit Dice (minimum 1st). The save DC is Charisma-based.

* *Scent:* Its antennae give a dromite the scent ability. A dromite can detect opponents by scent within 30 feet. If the opponent is upwind, the range increases to 60 feet; if downwind, it drops to 15 feet. Strong scents, such as smoke or rotting garbage, can be detected at twice the ranges noted above. Overpowering scents, such as skunk musk or troglodyte stench, can be detected at triple normal range. When a dromite detects a scent, the exact location of the source is not revealed—only its presence somewhere within range. The dromite can take a move action to note the direction of the scent. Whenever the dromite comes within 5 feet of the source, the dromite pinpoints the source’s location.

* *Blind-Fight:* Its antennae also give a dromite Blind-Fight as a bonus feat.

* *Compound Eyes:* This feature of its anatomy gives a dromite a +2 racial bonus on Spot checks.

* *Automatic Languages:* Common. *Bonus Languages:* Dwarven, Gnome, Goblin, Terran.

* *Favored Class:* Wilder.

* *Level Adjustment:* +1.

Duergar
~~~~~~~

indexterm:[Duergar]

* +2 Constitution, –4 Charisma

* *Medium:* As Medium creatures, duergar have no special bonuses or penalties due to their size.

* Duergar base land speed is 20 feet. However, gray dwarves can move at this speed even when wearing medium or heavy armor or when carrying a medium or heavy load (unlike other creatures, whose speed is reduced in such situations).

* Darkvision out to 120 feet.

* Immunity to paralysis, phantasms, and poison.

* +2 racial bonus on saves against spells and spell-like effects.

* *Stability:* Duergar are exceptionally stable on their feet. A duergar receives a +4 bonus on ability checks made to resist being bull rushed or tripped when standing on the ground (but not when climbing, flying, riding or otherwise not standing firmly on the ground).

* *Stonecunning:* This ability grants a duergar a +2 racial bonus on Search checks to notice unusual stonework, such as sliding walls, stonework, traps, new construction (even when built to match the old), unsafe stone surfaces, shaky stone ceilings, and the like. Something that isn’t stone but that is disguised as stone also counts as unusual stonework.

A gray dwarf who merely comes within 10 feet of unusual stonework can make a Search check as if he were actively searching, and a duergar can use the Search skill to find stonework traps as a rogue can. A duergar can also intuit depth, sensing his approximate depth underground as naturally as a human can sense which way is up. Duergar have a sixth sense about stonework, an innate ability that they get plenty of opportunity to practice and hone in their underground homes.

* *Psi-Like Abilities:* 1/day—expansion, invisibility. These abilities affect only the duergar and whatever he carries. Manifester level is equal to Hit Dice (minimum 3rd).

* *Naturally Psionic:* Duergar gain 3 bonus power points at 1st level. This benefit does not grant them the ability to manifest powers unless they gain that ability through another source, such as levels in a psionic class.

* +1 racial bonus on attack rolls against orcs (including half-orcs) and goblinoids (including goblins, hobgoblins, and bugbears).

* +4 dodge bonus to Armor Class against creatures of the giant type (such as ogres, trolls, and hill giants).

* *Light Sensitivity (Ex):* Duergar are dazzled in sunlight or within the radius of a daylight spell.

* Duergar have a +4 racial bonus on Move Silently checks and a +1 racial bonus on Listen and Spot checks. They have a +2 racial bonus on Appraise and Craft checks that are related to stone or metal.

* *Automatic Languages:* Common, Dwarven, Undercommon. Bonus Languages: Draconic, Giant, Goblin, Orc, Terran.

* *Favored Class:* Fighter.

* *Level Adjustment:* +1.

Dwarves
~~~~~~~
indexterm:[Dwarves]

* +2 Constitution, –2 Charisma.

* *Medium:* As Medium creatures, dwarves have no special bonuses or penalties due to their size.

* Dwarf base land speed is 20 feet. However, dwarves can move at this speed even when wearing medium or heavy armor or when carrying a medium or heavy load (unlike other creatures, whose speed is reduced in such situations).

* *Darkvision:* Dwarves can see in the dark up to 60 feet. Darkvision is black and white only, but it is otherwise like normal sight, and dwarves can function just fine with no light at all.

* *Stonecunning:* This ability grants a dwarf a +2 racial bonus on Search checks to notice unusual stonework, such as sliding walls, stonework traps, new construction (even when built to match the old), unsafe stone surfaces, shaky stone ceilings, and the like. Something that isn't stone but that is disguised as stone also counts as unusual stonework. A dwarf who merely comes within 10 feet of unusual stonework can make a Search check as if he were actively searching, and a dwarf can use the Search skill to find stonework traps as a rogue can. A dwarf can also intuit depth, sensing his approximate depth underground as naturally as a human can sense which way is up.

* *Weapon Familiarity:* Dwarves may treat dwarven waraxes and dwarven urgroshes as martial weapons, rather than exotic weapons.

* *Stability:* A dwarf gains a +4 bonus on ability checks made to resist being bull rushed or tripped when standing on the ground (but not when climbing, flying, riding, or otherwise not standing firmly on the ground).

* +2 racial bonus on saving throws against poison.

* +2 racial bonus on saving throws against spells and spell-like effects.

* +1 racial bonus on attack rolls against orcs and goblinoids.

* +4 dodge bonus to Armor Class against monsters of the giant type. Any time a creature loses its Dexterity bonus (if any) to Armor Class, such as when it's caught flat-footed, it loses its dodge bonus, too.

* +2 racial bonus on Appraise checks that are related to stone or metal items.

* +2 racial bonus on Craft checks that are related to stone or metal.

* *Automatic Languages:* Common and Dwarven. *Bonus Languages:* Giant, Gnome, Goblin, Orc, Terran, and Undercommon.

* *Favored Class:* Fighter. A multiclass dwarf's fighter class does not count when determining whether he takes an experience point penalty for multiclassing

Elans
~~~~~

indexterm:[Elans]

* –2 Charisma

* *Aberration:* Elans are not subject to spells or effects that affect humanoids only, such as charm person or dominate person.

* *Medium:* As Medium creatures, elans have no special bonuses or penalties due to their size.

* Elan base land speed is 30 feet.

* Elans (unlike most aberrations) do not have darkvision.

* *Naturally Psionic:* Elans gain 2 bonus power points at 1st level. This benefit does not grant them the ability to manifest powers unless they gain that ability through another source, such as levels in a psionic class.

* *Resistance (Su):* Elans can use psionic energy to increase their resistance to various forms of attack. As an immediate action, an elan can spend 1 power point to gain a +4 racial bonus on saving throws until the beginning of her next action.

* *Resilience (Su):* When an elan takes damage, she can spend power points to reduce its severity. As an immediate action, she can reduce the damage she is about to take by 2 hit points for every 1 power point she spends.

* *Repletion (Su):* An elan can sustain her body without need of food or water. If she spends 1 power point, an elan does not need to eat or drink for 24 hours.

* *Automatic Language:* Common. *Bonus Languages:* Any (other than secret languages, such as Druidic). Elans’ past lives expose them to wide ranges of language.

* *Favored Class:* Psion.

* *Level Adjustment:* +0.

Elves
~~~~~
indexterm:[Elves]

* +2 Dexterity, –2 Constitution.

* *Medium:* As Medium creatures, elves have no special bonuses or penalties due to their size.

* Elf base land speed is 30 feet.

* Immunity to magic sleep effects, and a +2 racial saving throw bonus against enchantment spells or effects.

* *Low-Light Vision:* An elf can see twice as far as a human in starlight, moonlight, torchlight, and similar conditions of poor illumination. She retains the ability to distinguish color and detail under these conditions.

* *Weapon Proficiency:* Elves receive the Martial Weapon Proficiency feats for the longsword, rapier, longbow (including composite longbow), and shortbow (including composite shortbow) as bonus feats.

* +2 racial bonus on Listen, Search, and Spot checks. An elf who merely passes within 5 feet of a secret or concealed door is entitled to a Search check to notice it as if she were actively looking for it.

* *Automatic Languages:* Common and Elven. *Bonus Languages:* Draconic, Gnoll, Gnome, Goblin, Orc, and Sylvan.

* *Favored Class:* Wizard. A multiclass elf 's wizard class does not count when determining whether she takes an experience point penalty for multiclassing.

Gnomes
~~~~~~
indexterm:[Gnomes]

* +2 Constitution, –2 Strength.

* *Small:* As a Small creature, a gnome gains a +1 size bonus to Armor Class, a +1 size bonus on attack rolls, and a +4 size bonus on Hide checks, but he uses smaller weapons than humans use, and his lifting and carrying limits are three-quarters of those of a Medium character.

* Gnome base land speed is 20 feet.

* *Low-Light Vision:* A gnome can see twice as far as a human in starlight, moonlight, torchlight, and similar conditions of poor illumination. He retains the ability to distinguish color and detail under these conditions.

* *Weapon Familiarity:* Gnomes may treat gnome hooked hammers as martial weapons rather than exotic weapons.

* +2 racial bonus on saving throws against illusions.

* Add +1 to the Difficulty Class for all saving throws against illusion spells cast by gnomes. This adjustment stacks with those from similar effects.

* +1 racial bonus on attack rolls against kobolds and goblinoids.

* +4 dodge bonus to Armor Class against monsters of the giant type. Any time a creature loses its Dexterity bonus (if any) to Armor Class, such as when it's caught flat-footed, it loses its dodge bonus, too.

* +2 racial bonus on Listen checks.

* +2 racial bonus on Craft (alchemy) checks.

* *Automatic Languages:* Common and Gnome. *Bonus Languages:* Draconic, Dwarven, Elven, Giant, Goblin, and Orc. In addition, a gnome can speak with a burrowing mammal (a badger, fox, rabbit, or the like, see below). This ability is innate to gnomes. See the speak with animals spell description.

* *Spell-Like Abilities:* 1/day—speak with animals (burrowing mammal only, duration 1 minute). A gnome with a Charisma score of at least 10 also has the following spell-like abilities: 1/day—dancing lights, ghost sound, prestidigitation. Caster level 1st; save DC 10 + gnome's Cha modifier + spell level.

* *Favored Class:* Bard. A multiclass gnome's bard class does not count when determining whether he takes an experience point penalty.

Half-Elves
~~~~~~~~~~
indexterm:[Half-Elves]

* *Medium:* As Medium creatures, half-elves have no special bonuses or penalties due to their size.

* Half-elf base land speed is 30 feet.

* Immunity to sleep spells and similar magical effects, and a +2 racial bonus on saving throws against enchantment spells or effects.

* *Low-Light Vision:* A half-elf can see twice as far as a human in starlight, moonlight, torchlight, and similar conditions of poor illumination. She retains the ability to distinguish color and detail under these conditions.

* +1 racial bonus on Listen, Search, and Spot checks.

* +2 racial bonus on Diplomacy and Gather Information checks.

* *Elven Blood:* For all effects related to race, a half-elf is considered an elf.

* *Automatic Languages:* Common and Elven. *Bonus Languages:* Any (other than secret languages, such as Druidic).

* *Favored Class:* Any. When determining whether a multiclass half-elf takes an experience point penalty, her highest-level class does not count.

Half-Giants
~~~~~~~~~~~

indexterm:[Half-Giants]

* +2 Strength, +2 Constitution, –2 Dexterity: Half-giants are tough and strong, but not too nimble.

* *Giant:* Half-giants are not subject to spells or effects that affect humanoids only, such as charm person or dominate person.

* *Medium:* As Medium creatures, half-giants have no special bonuses or penalties due to their size.

* Half-giant base land speed is 30 feet.

* *Low-Light Vision:* A half-giant can see twice as far as a human in starlight, moonlight, torchlight, and similar conditions of poor illumination. He retains the ability to distinguish color and detail under these conditions.

* *Fire Acclimated:* Half-giants have a +2 racial bonus on saving throws against all fire spells and effects. Half-giants are accustomed to enduring high temperatures.

* *Powerful Build:* The physical stature of half-giants lets them function in many ways as if they were one size category larger.

Whenever a half-giant is subject to a size modifier or special size modifier for an opposed check (such as during grapple checks, bull rush attempts, and trip attempts), the half-giant is treated as one size larger if doing so is advantageous to him.

A half-giant is also considered to be one size larger when determining whether a creature’s special attacks based on size (such as improved grab or swallow whole) can affect him. A half-giant can use weapons designed for a creature one size larger without penalty. However, his space and reach remain those of a creature of his actual size. The benefits of this racial trait stack with the effects of powers, abilities, and spells that change the subject’s size category.

* *Naturally Psionic:* Half-giants gain 2 bonus power points at 1st level. This benefit does not grant them the ability to manifest powers unless they gain that ability through another source, such as levels in a psionic class.

* *Psi-Like Ability:* 1/day—stomp. Manifester level is equal to 1/2 Hit Dice (minimum 1st). The save DC is Charisma-based.

* *Automatic Language:* Common. *Bonus Languages:* Draconic, Giant, Gnoll, Ignan.

* *Favored Class:* Psychic warrior.

* *Level Adjustment:* +1.

Half-Orcs
~~~~~~~~~
indexterm:[Half-Orcs]

* +2 Strength, –2 Intelligence, –2 Charisma.
A half-orc's starting Intelligence score is always at least 3. If this adjustment would lower the character's score to 1 or 2, his score is nevertheless 3.

* *Medium:* As Medium creatures, half-orcs have no special bonuses or penalties due to their size.

* Half-orc base land speed is 30 feet.

* *Darkvision:* Half-orcs (and orcs) can see in the dark up to 60 feet. Darkvision is black and white only, but it is otherwise like normal sight, and half-orcs can function just fine with no light at all.

* *Orc Blood:* For all effects related to race, a half-orc is considered an orc.

* *Automatic Languages:* Common and Orc. *Bonus Languages:* Draconic, Giant, Gnoll, Goblin, and Abyssal.

* *Favored Class:* Barbarian. A multiclass half-orc's barbarian class does not count when determining whether he takes an experience point penalty.

Halflings
~~~~~~~~~
indexterm:[Halflings]

* +2 Dexterity, –2 Strength.

* *Small:* As a Small creature, a halfling gains a +1 size bonus to Armor Class, a +1 size bonus on attack rolls, and a +4 size bonus on Hide checks, but she uses smaller weapons than humans use, and her lifting and carrying limits are three-quarters of those of a Medium character.

* Halfling base land speed is 20 feet.

* +2 racial bonus on Climb, Jump, and Move Silently checks.

* +1 racial bonus on all saving throws.

* +2 morale bonus on saving throws against fear: This bonus stacks with the halfling's +1 bonus on saving throws in general.

* +1 racial bonus on attack rolls with thrown weapons and slings.

* +2 racial bonus on Listen checks.

* *Automatic Languages:* Common and Halfling. *Bonus Languages:* Dwarven, Elven, Gnome, Goblin, and Orc.

* *Favored Class:* Rogue. A multiclass halfling's rogue class does not count when determining whether she takes an experience point penalty for multiclassing.

Maenads
~~~~~~~

indexterm:[Maenads]

* *Medium:* As Medium creatures, maenads have no special bonuses or penalties due to their size.

* Maenad base land speed is 30 feet.

* *Naturally Psionic:* Maenads gain 2 bonus power points at 1st level. This benefit does not grant them the ability to manifest powers unless they gain that ability through another source, such as levels in a psionic class.

* *Psi-Like Ability:* 1/day—energy ray. A maenad can deal only sonic damage with this ability. It is accompanied by a tremendous scream of rage. Manifester level is equal to 1/2 Hit Dice (minimum 1st). The save DC is Charisma-based.

* *Outburst (Ex):* Once per day, for up to 4 rounds, a maenad can subjugate her mentality to gain a boost of raw physical power. When she does so, she takes a –2 penalty to Intelligence and Wisdom but gains a +2 bonus to Strength.

* *Automatic Languages:* Common, Maenad. *Bonus Languages:* Aquan, Draconic, Dwarven, Elven, Goblin. Maenads commonly know the languages of their enemies and of their friends, as well as Draconic, the language commonly found in ancient tomes of secret knowledge.

* *Favored Class:* Wilder.

* *Level Adjustment:* +0

Xephs
~~~~~

indexterm:[Xephs]

* +2 Dexterity, –2 Strength

* *Medium:* As Medium creatures, xephs have no special bonuses or penalties due to their size.

* Xeph base land speed is 30 feet.

* Darkvision out to 60 feet.

* +1 racial bonus on saving throws against powers, spells, and spell-like effects. Xephs have an innate resistance to psionics and magic.

* *Naturally Psionic:* Xephs gain 1 bonus power point at 1st level. This benefit does not grant them the ability to manifest powers unless they gain that ability through another source, such as levels in a psionic class.

* *Burst (Su):* Three times per day, a xeph can put on a burst of speed to increase her speed by 10 feet, plus 10 feet per four character levels beyond 1st, to a maximum increase of 30 feet at 9th character level and higher. These bursts of speed are considered a competence bonus to the xeph’s base speed. A burst of speed lasts 3 rounds.

* *Automatic Languages:* Common, Xeph. Bonus Languages: Draconic, Elven, Gnoll, Goblin, Halfling, Sylvan.

* *Favored Class:* Soulknife.
