Skills
======

Skills
------

SKILLS SUMMARY
If you buy a class skill, your character gets 1 rank (equal to a +1 bonus on checks with that skill) for each skill point. If you buy other classes’ skills (cross-class skills), you get 1/2 rank per skill point.
Your maximum rank in a class skill is your character level + 3.
Your maximum rank in a cross-class skill is one-half of this number (do not round up or down).
Using Skills: To make a skill check, roll: 1d20 + skill modifier (Skill modifier = skill rank + ability modifier + miscellaneous modifiers)
This roll works just like an attack roll or a saving throw— the higher the roll, the better. Either you’re trying to match or exceed a certain Difficulty Class (DC), or you’re trying to beat another character’s check result.
Skill Ranks: A character’s number of ranks in a skill is based on how many skill points a character has invested in a skill. Many skills can be used even if the character has no ranks in them; doing this is called making an untrained skill check.
Ability Modifier: The ability modifier used in a skill check is the modifier for the skill’s key ability (the ability associated with the skill’s use). The key ability of each skill is noted in its description.
Miscellaneous Modifiers: Miscellaneous modifiers include racial bonuses, armor check penalties, and bonuses provided by feats, among others.

Each skill point you spend on a class skill gets you 1 rank in that skill. Class skills are the skills found on your character’s class skill list. Each skill point you spend on a cross-class skill gets your character 1/2 rank in that skill. Cross-class skills are skills not found on your character’s class skill list. (Half ranks do not improve your skill check, but two 1/2 ranks make 1 rank.) You can’t save skill points to spend later.
The maximum rank in a class skill is the character’s level + 3. If it’s a cross-class skill, the maximum rank is half of that number (do not round up or down).
Regardless of whether a skill is purchased as a class skill or a cross-class skill, if it is a class skill for any of your classes, your maximum rank equals your total character level + 3.

USING SKILLS
When your character uses a skill, you make a skill check to see how well he or she does. The higher the result of the skill check, the better. Based on the circumstances, your result must match or beat a particular number (a DC or the result of an opposed skill check) for the check to be successful. The harder the task, the higher the number you need to roll.
Circumstances can affect your check. A character who is free to work without distractions can make a careful attempt and avoid simple mistakes. A character who has lots of time can try over and over again, thereby assuring the best outcome. If others help, the character may succeed where otherwise he or she would fail.

SKILL CHECKS
A skill check takes into account a character’s training (skill rank), natural talent (ability modifier), and luck (the die roll). It may also take into account his or her race’s knack for doing certain things (racial bonus) or what armor he or she is wearing (armor check penalty), or a certain feat the character possesses, among other things. 
To make a skill check, roll 1d20 and add your character’s skill modifier for that skill. The skill modifier incorporates the character’s ranks in that skill and the ability modifier for that skill’s key ability, plus any other miscellaneous modifiers that may apply, including racial bonuses and armor check penalties. The higher the result, the better. Unlike with attack rolls and saving throws, a natural roll of 20 on the d20 is not an automatic success, and a natural roll of 1 is not an automatic failure.

Difficulty Class
Some checks are made against a Difficulty Class (DC). The DC is a number (set using the skill rules as a guideline) that you must score as a result on your skill check in order to succeed.

Table: Difficulty Class Examples
Difficulty (DC)
Example (Skill Used)
Very easy (0) 
Notice something large in plain sight (Spot)
Easy (5) 
Climb a knotted rope (Climb)
Average (10) 
Hear an approaching guard (Listen)
Tough (15) 
Rig a wagon wheel to fall off (Disable Device)
Challenging (20) 
Swim in stormy water (Swim)
Formidable (25) 
Open an average lock (Open Lock)
Heroic (30) 
Leap across a 30-foot chasm (Jump)
Nearly impossible (40)
Track a squad of orcs across hard ground after 24 hours of rainfall (Survival)

Opposed Checks
An opposed check is a check whose success or failure is determined by comparing the check result to another character’s check result. In an opposed check, the higher result succeeds, while the lower result fails. In case of a tie, the higher skill modifier wins. If these scores are the same, roll again to break the tie.

Table: Example Opposed Checks
Task 
Skill (Key Ability)
Opposing Skill (Key Ability)
Con someone 
Bluff (Cha) 
Sense Motive (Wis)
Pretend to be someone else
Disguise (Cha) 
Spot (Wis)
Create a false map 
Forgery (Int) 
Forgery (Int)
Hide from someone 
Hide (Dex) 
Spot (Wis)
Make a bully back down 
Intimidate (Cha) 
Special1
Sneak up on someone 
Move Silently (Dex) 
Listen (Wis)
Steal a coin pouch 
Sleight of Hand (Dex) 
Spot (Wis)
Tie a prisoner securely 
Use Rope (Dex) 
Escape Artist (Dex)
1 An Intimidate check is opposed by the target’s level check, not a skill check. See the Intimidate skill description for more information.

Trying Again
In general, you can try a skill check again if you fail, and you can keep trying indefinitely. Some skills, however, have consequences of failure that must be taken into account. A few skills are virtually useless once a check has failed on an attempt to accomplish a particular task. For most skills, when a character has succeeded once at a given task, additional successes are meaningless.

Untrained Skill Checks
Generally, if your character attempts to use a skill he or she does not possess, you make a skill check as normal. The skill modifier doesn’t have a skill rank added in because the character has no ranks in the skill. Any other applicable modifiers, such as the modifier for the skill’s key ability, are applied to the check.
Many skills can be used only by someone who is trained in them.

Favorable and Unfavorable Conditions
Some situations may make a skill easier or harder to use, resulting in a bonus or penalty to the skill modifier for a skill check or a change to the DC of the skill check.
The chance of success can be altered in four ways to take into account exceptional circumstances.
1. Give the skill user a +2 circumstance bonus to represent conditions that improve performance, such as having the perfect tool for the job, getting help from another character (see Combining Skill Attempts), or possessing unusually accurate information. 
2. Give the skill user a –2 circumstance penalty to represent conditions that hamper performance, such as being forced to use improvised tools or having misleading information.
3. Reduce the DC by 2 to represent circumstances that make the task easier, such as having a friendly audience or doing work that can be subpar.
4. Increase the DC by 2 to represent circumstances that make the task harder, such as having an uncooperative audience or doing work that must be flawless.
Conditions that affect your character’s ability to perform the skill change the skill modifier. Conditions that modify how well the character has to perform the skill to succeed change the DC. A bonus to the skill modifier and a reduction in the check’s DC have the same result: They create a better chance of success. But they represent different circumstances, and sometimes that difference is important.

Time and Skill Checks
Using a skill might take a round, take no time, or take several rounds or even longer. Most skill uses are standard actions, move actions, or full-round actions. Types of actions define how long activities take to perform within the framework of a combat round (6 seconds) and how movement is treated with respect to the activity. Some skill checks are instant and represent reactions to an event, or are included as part of an action.
These skill checks are not actions. Other skill checks represent part of movement.

Checks without Rolls
A skill check represents an attempt to accomplish some goal, usually while under some sort of time pressure or distraction. Sometimes, though, a character can use a skill under more favorable conditions and eliminate the luck factor.
Taking 10: When your character is not being threatened or distracted, you may choose to take 10. Instead of rolling 1d20 for the skill check, calculate your result as if you had rolled a 10. For many routine tasks, taking 10 makes them automatically successful. Distractions or threats (such as combat) make it impossible for a character to take 10. In most cases, taking 10 is purely a safety measure —you know (or expect) that an average roll will succeed but fear that a poor roll might fail, so you elect to settle for the average roll (a 10). Taking 10 is especially useful in situations where a particularly high roll wouldn’t help.
Taking 20:When you have plenty of time (generally 2 minutes for a skill that can normally be checked in 1 round, one full-round action, or one standard action), you are faced with no threats or distractions, and the skill being attempted carries no penalties for failure, you can take 20. In other words, eventually you will get a 20 on 1d20 if you roll enough times. Instead of rolling 1d20 for the skill check, just calculate your result as if you had rolled a 20.
Taking 20 means you are trying until you get it right, and it assumes that you fail many times before succeeding. Taking 20 takes twenty times as long as making a single check would take.
Since taking 20 assumes that the character will fail many times before succeeding, if you did attempt to take 20 on a skill that carries penalties for failure, your character would automatically incur those penalties before he or she could complete the task. Common “take 20” skills include Escape Artist, Open Lock, and Search.
Ability Checks and Caster Level Checks: The normal take 10 and take 20 rules apply for ability checks. Neither rule applies to caster level checks.

COMBINING SKILL ATTEMPTS
When more than one character tries the same skill at the same time and for the same purpose, their efforts may overlap.

Individual Events
Often, several characters attempt some action and each succeeds or fails independently.  The result of one character’s Climb check does not influence the results of other characters Climb check.

Aid Another
You can help another character achieve success on his or her skill check by making the same kind of skill check in a cooperative effort. If you roll a 10 or higher on your check, the character you are helping gets a +2 bonus to his or her check, as per the rule for favorable conditions. (You can’t take 10 on a skill check to aid another.) In many cases, a character’s help won’t be beneficial, or only a limited number of characters can help at once. 
In cases where the skill restricts who can achieve certain results you can’t aid another to grant a bonus to a task that your character couldn’t achieve alone.

Skill Synergy
It’s possible for a character to have two skills that work well together. In general, having 5 or more ranks in one skill gives the character a +2 bonus on skill checks with each of its synergistic skills, as noted in the skill description. In some cases, this bonus applies only to specific uses of the skill in question, and not to all checks. Some skills provide benefits on other checks made by a character, such as those checks required to use certain class features.

ABILITY CHECKS
Sometimes a character tries to do something to which no specific skill really applies. In these cases, you make an ability check. An ability check is a roll of 1d20 plus the appropriate ability modifier. Essentially, you’re making an untrained skill check. 
In some cases, an action is a straight test of one’s ability with no luck involved. Just as you wouldn’t make a height check to see who is taller, you don’t make a Strength check to see who is stronger.

SKILL DESCRIPTIONS
This section describes each skill, including common uses and typical modifiers. Characters can sometimes use skills for purposes other than those noted here.
Here is the format for skill descriptions.

SKILL NAME
The skill name line includes (in addition to the name of the skill) the following information.
Key Ability: The abbreviation of the ability whose modifier applies to the skill check. Exception: Speak Language has “None” as its key ability because the use of this skill does not require a check.
Trained Only: If this notation is included in the skill name line, you must have at least 1 rank in the skill to use it. If it is omitted, the skill can be used untrained (with a rank of 0). If any special notes apply to trained or untrained use, they are covered in the Untrained section (see below).
Armor Check Penalty: If this notation is included in the skill name line, an armor check penalty applies (when appropriate) to checks using this skill. If this entry is absent, an armor check penalty does not apply.

The skill name line is followed by a general description of what using the skill represents. After the description are a few other types of information:
Check: What a character (“you” in the skill description) can do with a successful skill check and the check’s DC.
Action: The type of action using the skill requires, or the amount of time required for a check.
Try Again: Any conditions that apply to successive attempts to use the skill successfully. If the skill doesn’t allow you to attempt the same task more than once, or if failure carries an inherent penalty (such as with the Climb skill), you can’t take 20. If this paragraph is omitted, the skill can be retried without any inherent penalty, other than the additional time required.
Special: Any extra facts that apply to the skill, such as special effects deriving from its use or bonuses that certain characters receive because of class, feat choices, or race.
Synergy: Some skills grant a bonus to the use of one or more other skills because of a synergistic effect. This entry, when present, indicates what bonuses this skill may grant or receive because of such synergies. See Table 4–5 for a complete list of bonuses granted by synergy between skills (or between a skill and a class feature).
Restriction: The full utility of certain skills is restricted to characters of certain classes or characters who possess certain feats. This entry indicates whether any such restrictions exist for the skill.
Untrained: This entry indicates what a character without at least 1 rank in the skill can do with it. If this entry doesn’t appear, it means that the skill functions normally for untrained characters (if it can be used untrained) or that an untrained character can’t attempt checks with this skill (for skills that are designated as “Trained Only”).

APPRAISE (INT)
Check: You can appraise common or well-known objects with a DC 12 Appraise check. Failure means that you estimate the value at 50% to 150% (2d6+3 times 10%,) of its actual value.
Appraising a rare or exotic item requires a successful check against DC 15, 20, or higher. If the check is successful, you estimate the value correctly; failure means you cannot estimate the item’s value.
A magnifying glass gives you a +2 circumstance bonus on Appraise checks involving any item that is small or highly detailed, such as a gem. A merchant’s scale gives you a +2 circumstance bonus on Appraise checks involving any items that are valued by weight, including anything made of precious metals.
These bonuses stack.
Action: Appraising an item takes 1 minute (ten consecutive full-round actions).
Try Again: No. You cannot try again on the same object, regardless of success.
Special: A dwarf gets a +2 racial bonus on Appraise checks that are related to stone or metal items because dwarves are familiar with valuable items of all kinds (especially those made of stone or metal).
The master of a raven familiar gains a +3 bonus on Appraise checks.
A character with the Diligent feat gets a +2 bonus on Appraise checks.
Synergy: If you have 5 ranks in any Craft skill, you gain a +2 bonus on Appraise checks related to items made with that Craft skill.
Untrained: For common items, failure on an untrained check means no estimate. For rare items, success means an estimate of 50% to 150% (2d6+3 times 10%).

BALANCE (DEX; ARMOR CHECK PENALTY)
Check: You can walk on a precarious surface. A successful check lets you move at half your speed along the surface for 1 round. A failure by 4 or less means you can’t move for 1 round. A failure by 5 or more means you fall. The difficulty varies with the surface, as follows:

Narrow Surface 
Balance DC1 
Difficult Surface
Balance DC1
7–12 inches wide 
10 
Uneven flagstone 
102
2–6 inches wide 
15 
Hewn stone floor 
102
Less than 2 inches wide 
20 
Sloped or angled floor 
102
1 Add modifiers from Narrow Surface Modifiers, below, as appropriate.
2 Only if running or charging. Failure by 4 or less means the character can’t run or charge, but may otherwise act normally.

Narrow Surface Modifiers

Surface 
DC Modifier1
Lightly obstructed  
+2
Severely obstructed 
+5
Lightly slippery
+2
Severely slippery 
+5
Sloped or angled 
+2
1 Add the appropriate modifier to the Balance DC of a narrow surface.
These modifiers stack.

Being Attacked while Balancing: You are considered flat-footed while balancing, since you can’t move to avoid a blow, and thus you lose your Dexterity bonus to AC (if any). If you have 5 or more ranks in Balance, you aren’t considered flat-footed while balancing. If you take damage while balancing, you must make another Balance check against the same DC to remain standing.
Accelerated Movement: You can try to walk across a precarious surface more quickly than normal. If you accept a –5 penalty, you can move your full speed as a move action. (Moving twice your speed in a round requires two Balance checks, one for each move action used.) You may also accept this penalty in order to charge across a precarious surface; charging requires one Balance check for each multiple of your speed (or fraction thereof ) that you charge.
Action: None. A Balance check doesn’t require an action; it is made as part of another action or as a reaction to a situation.
Special: If you have the Agile feat, you get a +2 bonus on Balance checks.
Synergy: If you have 5 or more ranks in Tumble, you get a +2 bonus on Balance checks.

BLUFF (CHA)
Check: A Bluff check is opposed by the target’s Sense Motive check. See the accompanying table for examples of different kinds of bluffs and the modifier to the target’s Sense Motive check for each one.
Favorable and unfavorable circumstances weigh heavily on the outcome of a bluff. Two circumstances can weigh against you: The bluff is hard to believe, or the action that the target is asked to take goes against its self-interest, nature, personality, orders, or the like. If it’s important, you can distinguish between a bluff that fails because the target doesn’t believe it and one that fails because it just asks too much of the target. For instance, if the target gets a +10 bonus on its Sense Motive check because the bluff demands something risky, and the Sense Motive check succeeds by 10 or less, then the target didn’t so much see through the bluff as prove reluctant to go along with it. A target that succeeds by 11 or more has seen through the bluff.
A successful Bluff check indicates that the target reacts as you wish, at least for a short time (usually 1 round or less) or believes something that you want it to believe. Bluff, however, is not a suggestion spell. 
A bluff requires interaction between you and the target. Creatures unaware of you cannot be bluffed.
Feinting in Combat: You can also use Bluff to mislead an opponent in melee combat (so that it can’t dodge your next attack effectively). To feint, make a Bluff check opposed by your target’s Sense Motive check, but in this case, the target may add its base attack bonus to the roll along with any other applicable modifiers.
If your Bluff check result exceeds this special Sense Motive check result, your target is denied its Dexterity bonus to AC (if any) for the next melee attack you make against it. This attack must be made on or before your next turn.
Feinting in this way against a nonhumanoid is difficult because it’s harder to read a strange creature’s body language; you take a –4 penalty on your Bluff check. Against a creature of animal Intelligence (1 or 2) it’s even harder; you take a –8 penalty. Against a nonintelligent creature, it’s impossible.
Feinting in combat does not provoke an attack of opportunity.
Creating a Diversion to Hide: You can use the Bluff skill to help you hide. A successful Bluff check gives you the momentary diversion you need to attempt a Hide check while people are aware of you. This usage does not provoke an attack of opportunity.
Delivering a Secret Message: You can use Bluff to get a message across to another character without others understanding it. The DC is 15 for simple messages, or 20 for complex messages, especially those that rely on getting across new information. Failure by 4 or less means you can’t get the message across. Failure by 5 or more means that some false information has been implied or inferred. Anyone listening to the exchange can make a Sense Motive check opposed by the Bluff check you made to transmit in order to intercept your message (see Sense Motive).
Action: Varies. A Bluff check made as part of general interaction always takes at least 1 round (and is at least a full-round action), but it can take much longer if you try something elaborate. A Bluff check made to feint in combat or create a diversion to hide is a standard action. A Bluff check made to deliver a secret message doesn’t take an action; it is part of normal communication.
Try Again: Varies. Generally, a failed Bluff check in social interaction makes the target too suspicious for you to try again in the same circumstances, but you may retry freely on Bluff checks made to feint in combat. Retries are also allowed when you are trying to send a message, but you may attempt such a retry only once per round.
Each retry carries the same chance of miscommunication.
Special: A ranger gains a bonus on Bluff checks when using this skill against a favored enemy.
The master of a snake familiar gains a +3 bonus on Bluff checks.
If you have the Persuasive feat, you get a +2 bonus on Bluff checks.
Synergy: If you have 5 or more ranks in Bluff, you get a +2 bonus on Diplomacy, Intimidate, and Sleight of Hand checks, as well as on Disguise checks made when you know you’re being observed and you try to act in character.

Bluff Examples
Example Circumstances
Sense Motive Modifier
The target wants to believe you.
–5
The bluff is believable and doesn’t affect the target much. 
+0
The bluff is a little hard to believe or puts the target at some risk. 
+5
The bluff is hard to believe or puts the target at significant risk. 
+10
The bluff is way out there, almost too incredible to consider.
+20

CLIMB (STR; ARMOR CHECK PENALTY)
Check: With a successful Climb check, you can advance up, down, or across a slope, a wall, or some other steep incline (or even a ceiling with handholds) at one-quarter your normal speed. A slope is considered to be any incline at an angle measuring less than 60 degrees; a wall is any incline at an angle measuring 60 degrees or more.
A Climb check that fails by 4 or less means that you make no progress, and one that fails by 5 or more means that you fall from whatever height you have already attained.
A climber’s kit gives you a +2 circumstance bonus on Climb checks.
The DC of the check depends on the conditions of the climb. Compare the task with those on the following table to determine an appropriate DC.

Climb DC 
Example Surface or Activity
0 
A slope too steep to walk up, or a knotted rope with a wall to brace against.
5 
A rope with a wall to brace against, or a knotted rope, or a rope affected by the rope trick spell. 
10 
A surface with ledges to hold on to and stand on, such as a very rough wall or a ship’s rigging. 
15 
Any surface with adequate handholds and footholds (natural or artificial), such as a very rough natural rock surface or a tree, or an unknotted rope, or pulling yourself up when dangling by your hands. 
20 
An uneven surface with some narrow handholds and footholds, such as a typical wall in a dungeon or ruins. 
25 
A rough surface, such as a natural rock wall or a brick wall. 
25 
An overhang or ceiling with handholds but no footholds. 
— 
A perfectly smooth, flat, vertical surface cannot be climbed.

Climb DC Modifier1 
Example Surface or Activity
–10
 Climbing a chimney (artificial or natural) or other location where you can brace against two opposite walls (reduces DC by 10).
–5 
Climbing a corner where you can brace against perpendicular walls (reduces DC by 5).
+5
 Surface is slippery (increases DC by 5).
1These modifiers are cumulative; use any that apply.

You need both hands free to climb, but you may cling to a wall with one hand while you cast a spell or take some other action that requires only one hand. While climbing, you can’t move to avoid a blow, so you lose your Dexterity bonus to AC (if any). You also can’t use a shield while climbing.
Any time you take damage while climbing, make a Climb check against the DC of the slope or wall. Failure means you fall from your current height and sustain the appropriate falling damage.
Accelerated Climbing: You try to climb more quickly than normal. By accepting a –5 penalty, you can move half your speed (instead of one-quarter your speed).
Making Your Own Handholds and Footholds: You can make your own handholds and footholds by pounding pitons into a wall. Doing so takes 1 minute per piton, and one piton is needed per 3 feet of distance. As with any surface that offers handholds and footholds, a wall with pitons in it has a DC of 15. In the same way, a climber with a handaxe or similar implement can cut handholds in an ice wall.
Catching Yourself When Falling: It’s practically impossible to catch yourself on a wall while falling. Make a Climb check (DC = wall’s DC + 20) to do so. It’s much easier to catch yourself on a slope (DC = slope’s DC + 10).
Catching a Falling Character While Climbing: If someone climbing above you or adjacent to you falls, you can attempt to catch the falling character if he or she is within your reach. Doing so requires a successful melee touch attack against the falling character (though he or she can voluntarily forego any Dexterity bonus to AC if desired). If you hit, you must immediately attempt a Climb check (DC = wall’s DC + 10). Success indicates that you catch the falling character, but his or her total weight, including equipment, cannot exceed your heavy load limit or you automatically fall. If you fail your Climb check by 4 or less, you fail to stop the character’s fall but don’t lose your grip on the wall. If you fail by 5 or more, you fail to stop the character’s fall and begin falling as well.
Action: Climbing is part of movement, so it’s generally part of a move action (and may be combined with other types of movement in a move action). Each move action that includes any climbing requires a separate Climb check. Catching yourself or another falling character doesn’t take an action.
Special: You can use a rope to haul a character upward (or lower a character) through sheer strength. You can lift double your maximum load in this manner.
A halfling has a +2 racial bonus on Climb checks because halflings are agile and surefooted.
The master of a lizard familiar gains a +3 bonus on Climb checks.
If you have the Athletic feat, you get a +2 bonus on Climb checks.
A creature with a climb speed has a +8 racial bonus on all Climb checks. The creature must make a Climb check to climb any wall or slope with a DC higher than 0, but it always can choose to take 10, even if rushed or threatened while climbing. If a creature with a climb speed chooses an accelerated climb (see above), it moves at double its climb speed (or at its land speed, whichever is slower) and makes a single Climb check at a –5 penalty. Such a creature retains its Dexterity bonus to Armor Class (if any) while climbing, and opponents get no special bonus to their attacks against it. It cannot, however, use the run action while climbing.
Synergy: If you have 5 or more ranks in Use Rope, you get a +2 bonus on Climb checks made to climb a rope, a knotted rope, or a rope-and-wall combination.

CONCENTRATION (CON)
Check: You must make a Concentration check whenever you might potentially be distracted (by taking damage, by harsh weather, and so on) while engaged in some action that requires your full attention. Such actions include casting a spell, concentrating on an active spell, directing a spell, using a spell-like ability, or using a skill that would provoke an attack of opportunity. In general, if an action wouldn’t normally provoke an attack of opportunity, you need not make a Concentration check to avoid being distracted.
If the Concentration check succeeds, you may continue with the action as normal. If the check fails, the action automatically fails and is wasted. If you were in the process of casting a spell, the spell is lost. If you were concentrating on an active spell, the spell ends as if you had ceased concentrating on it. If you were directing a spell, the direction fails but the spell remains active. If you were using a spell-like ability, that use of the ability is lost. A skill use also fails, and in some cases a failed skill check may have other ramifications as well.
The table below summarizes various types of distractions that cause you to make a Concentration check. If the distraction occurs while you are trying to cast a spell, you must add the level of the spell you are trying to cast to the appropriate Concentration DC. If more than one type of distraction is present, make a check for each one; any failed Concentration check indicates that the task is not completed.

Concentration DC1 
Distraction
10 + damage dealt 
Damaged during the action.2
10 + half of continuous 
Taking continuous damage during the damage last dealt action.3
Distracting spell’s save DC 
Distracted by nondamaging spell.4
10 
Vigorous motion (on a moving mount, taking a bouncy wagon ride, in a small boat in rough water, belowdecks in a stormtossed ship).
15 
Violent motion (on a galloping horse, taking a very rough wagon ride, in a small boat in rapids, on the deck of a storm-tossed ship).
20 
Extraordinarily violent motion (earthquake).
15 
Entangled.
20 
Grappling or pinned. (You can cast only spells without somatic components for which you have any required material component in hand.)
5 
Weather is a high wind carrying blinding rain or sleet.
10 
Weather is wind-driven hail, dust, or debris.
Distracting spell’s save DC 
Weather caused by a spell, such as storm of vengeance.4
1 If you are trying to cast, concentrate on, or direct a spell when the distraction occurs, add the level of the spell to the indicated DC.
2 Such as during the casting of a spell with a casting time of 1 round or more, or the execution of an activity that takes more than a single full-round action (such as Disable Device). Also, damage stemming from an attack of opportunity or readied attack made in response to the spell being cast (for spells with a casting time of 1 action) or the action being taken (for activities requiring no more than a full-round action).
3 Such as from acid arrow.
4 If the spell allows no save, use the save DC it would have if it did allow a save.

Action: None. Making a Concentration check doesn’t take an action; it is either a free action (when attempted reactively) or part of another action (when attempted actively).
Try Again: Yes, though a success doesn’t cancel the effect of a previous failure, such as the loss of a spell you were casting or the disruption of a spell you were concentrating on.
Special: You can use Concentration to cast a spell, use a spell-like ability, or use a skill defensively, so as to avoid attacks of opportunity altogether. This doesn’t apply to other actions that might provoke attacks of opportunity.
The DC of the check is 15 (plus the spell’s level, if casting a spell or using a spell-like ability defensively). If the Concentration check succeeds, you may attempt the action normally without provoking any attacks of opportunity. A successful Concentration check still doesn’t allow you to take 10 on another check if you are in a stressful situation; you must make the check normally. If the Concentration check fails, the related action also automatically fails (with any appropriate ramifications), and the action is wasted, just as if your concentration had been disrupted by a distraction. 
A character with the Combat Casting feat gets a +4 bonus on Concentration checks made to cast a spell or use a spell-like ability while on the defensive or while grappling or pinned.

CRAFT (INT)
Like Knowledge, Perform, and Profession, Craft is actually a number of separate skills. You could have several Craft skills, each with its own ranks, each purchased as a separate skill.
A Craft skill is specifically focused on creating something. If nothing is created by the endeavor, it probably falls under the heading of a Profession skill.
Check: You can practice your trade and make a decent living, earning about half your check result in gold pieces per week of dedicated work. You know how to use the tools of your trade, how to perform the craft’s daily tasks, how to supervise untrained helpers, and how to handle common problems. (Untrained laborers and assistants earn an average of 1 silver piece per day.)
The basic function of the Craft skill, however, is to allow you to make an item of the appropriate type. The DC depends on the complexity of the item to be created. The DC, your check results, and the price of the item determine how long it takes to make a particular item. The item’s finished price also determines the cost of raw materials.
In some cases, the fabricate spell can be used to achieve the results of a Craft check with no actual check involved. However, you must make an appropriate Craft check when using the spell to make articles requiring a high degree of craftsmanship.
A successful Craft check related to woodworking in conjunction with the casting of the ironwood spell enables you to make wooden items that have the strength of steel.
When casting the spell minor creation, you must succeed on an appropriate Craft check to make a complex item.
All crafts require artisan’s tools to give the best chance of success. If improvised tools are used, the check is made with a –2 circumstance penalty. On the other hand, masterwork artisan’s tools provide a +2 circumstance bonus on the check.
To determine how much time and money it takes to make an item, follow these steps.
1. Find the item’s price. Put the price in silver pieces (1 gp = 10 sp).
2. Find the DC from the table below.
3. Pay one-third of the item’s price for the cost of raw materials.
4. Make an appropriate Craft check representing one week’s work. If the check succeeds, multiply your check result by the DC. If the result × the DC equals the price of the item in sp, then you have completed the item. (If the result × the DC equals double or triple the price of the item in silver pieces, then you’ve completed the task in one-half or one-third of the time. Other multiples of the DC reduce the time in the same manner.) If the result × the DC doesn’t equal the price, then it represents the progress you’ve made this week. Record the result and make a new Craft check for the next week. Each week, you make more progress until your total reaches the price of the item in silver pieces.
If you fail a check by 4 or less, you make no progress this week.
If you fail by 5 or more, you ruin half the raw materials and have to pay half the original raw material cost again.
Progress by the Day: You can make checks by the day instead of by the week. In this case your progress (check result × DC) is in copper pieces instead of silver pieces.
Creating Masterwork Items: You can make a masterwork item—a weapon, suit of armor, shield, or tool that conveys a bonus on its use through its exceptional craftsmanship, not through being magical. To create a masterwork item, you create the masterwork component as if it were a separate item in addition to the standard item. The masterwork component has its own price (300 gp for a weapon or 150 gp for a suit of armor or a shield) and a Craft DC of 20. Once both the standard component and the masterwork component are completed, the masterwork item is finished. Note: The cost you pay for the masterwork component is one-third of the given amount, just as it is for the cost in raw materials.
Repairing Items: Generally, you can repair an item by making checks against the same DC that it took to make the item in the first place. The cost of repairing an item is one-fifth of the item’s price. 

When you use the Craft skill to make a particular sort of item, the DC for checks involving the creation of that item are typically as given on the following table.

Item 
Craft Skill 
Craft DC
Acid 
Alchemy1 
15
Alchemist’s fire, smokestick, or tindertwig 
Alchemy1 
20
Antitoxin, sunrod, tanglefoot bag, or thunderstone 
Alchemy1 
25
Armor or shield 
Armorsmithing 
10 + AC bonus
Longbow or shortbow 
Bowmaking 
12
Composite longbow or composite shortbow
Bowmaking 
15
Composite longbow or composite shortbow with high strength rating
Bowmaking 
15 + (2 × rating)
Crossbow 
Weaponsmithing 
15
Simple melee or thrown weapon 
Weaponsmithing 
12
Martial melee or thrown weapon 
Weaponsmithing 
15
Exotic melee or thrown weapon 
Weaponsmithing 
18
Mechanical trap 
Trapmaking 
Varies2
Very simple item (wooden spoon) 
Varies
5
Typical item (iron pot) 
Varies 
10
High-quality item (bell)
Varies 
15
Complex or superior item (lock) 
Varies 
20
1 You must be a spellcaster to craft any of these items.
2 Traps have their own rules for construction.

Action: Does not apply. Craft checks are made by the day or week (see above).
Try Again: Yes, but each time you miss by 5 or more, you ruin half the raw materials and have to pay half the original raw material cost again.
Special: A dwarf has a +2 racial bonus on Craft checks that are related to stone or metal, because dwarves are especially capable with stonework and metalwork.
A gnome has a +2 racial bonus on Craft (alchemy) checks because gnomes have sensitive noses.
You may voluntarily add +10 to the indicated DC to craft an item. This allows you to create the item more quickly (since you’ll be multiplying this higher DC by your Craft check result to determine progress). You must decide whether to increase the DC before you make each weekly or daily check.
To make an item using Craft (alchemy), you must have alchemical equipment and be a spellcaster. If you are working in a city, you can buy what you need as part of the raw materials cost to make the item, but alchemical equipment is difficult or impossible to come by in some places. Purchasing and maintaining an alchemist’s lab grants a +2 circumstance bonus on Craft (alchemy) checks because you have the perfect tools for the job, but it does not affect the cost of any items made using the skill.
Synergy: If you have 5 ranks in a Craft skill, you get a +2 bonus on Appraise checks related to items made with that Craft skill.

DECIPHER SCRIPT (INT; TRAINED ONLY)
Check: You can decipher writing in an unfamiliar language or a message written in an incomplete or archaic form. The base DC is 20 for the simplest messages, 25 for standard texts, and 30 or higher for intricate, exotic, or very old writing.
If the check succeeds, you understand the general content of a piece of writing about one page long (or the equivalent). If the check fails, make a DC 5 Wisdom check to see if you avoid drawing a false conclusion about the text. (Success means that you do not draw a false conclusion; failure means that you do.)
Both the Decipher Script check and (if necessary) the Wisdom check are made secretly, so that you can’t tell whether the conclusion you draw is true or false.
Action: Deciphering the equivalent of a single page of script takes 1 minute (ten consecutive full-round actions).
Try Again: No.
Special: A character with the Diligent feat gets a +2 bonus on Decipher Script checks.
Synergy: If you have 5 or more ranks in Decipher Script, you get a +2 bonus on Use Magic Device checks involving scrolls.

DIPLOMACY (CHA)
Check: You can change the attitudes of others (nonplayer characters) with a successful Diplomacy check; see the Influencing NPC Attitudes sidebar, below, for basic DCs. In negotiations, participants roll opposed Diplomacy checks, and the winner gains the advantage. Opposed checks also resolve situations when two advocates or diplomats plead opposite cases in a hearing before a third party.
Action: Changing others’ attitudes with Diplomacy generally takes at least 1 full minute (10 consecutive full-round actions). In some situations, this time requirement may greatly increase. A rushed Diplomacy check can be made as a full-round action, but you take a –10 penalty on the check.
Try Again: Optional, but not recommended because retries usually do not work. Even if the initial Diplomacy check succeeds, the other character can be persuaded only so far, and a retry may do more harm than good. If the initial check fails, the other character has probably become more firmly committed to his position, and a retry is futile.
Special: A half-elf has a +2 racial bonus on Diplomacy checks.
If you have the Negotiator feat, you get a +2 bonus on Diplomacy checks.
Synergy: If you have 5 or more ranks in Bluff, Knowledge (nobility and royalty), or Sense Motive, you get a +2 bonus on Diplomacy checks.

INFLUENCING NPC ATTITUDES
Use the table below to determine the effectiveness of Diplomacy checks (or Charisma checks) made to influence the attitude of a nonplayer character, or wild empathy checks made to influence the attitude of an animal or magical beast.

Initial Attitude
————— New Attitude (DC to achieve)—————
 
Hostile
Unfriendly
Indifferent
Friendly
Helpful
Hostile
Less than 20
20
25
35
50
Unfriendly
Less than 5
5
15
25
40
Indifferent
—
Less than 1
1
15
30
Friendly
—
—
Less than 1
1
20
Helpful
—
—
—
Less than 1
1

Attitude 
Means 
Possible Actions
Hostile 
Will take risks to hurt you 
Attack, interfere, berate, flee
Unfriendly 
Wishes you ill 
Mislead, gossip, avoid, watch suspiciously, insult
Indifferent 
Doesn’t much care 
Socially expected interaction
Friendly 
Wishes you well 
Chat, advise, offer limited help, advocate
Helpful 
Will take risks to help you 
Protect, back up, heal, aid

DISABLE DEVICE (INT; TRAINED ONLY)
Check: The Disable Device check is made secretly, so that you don’t necessarily know whether you’ve succeeded.
The DC depends on how tricky the device is. Disabling (or rigging or jamming) a fairly simple device has a DC of 10; more intricate and complex devices have higher DCs.
If the check succeeds, you disable the device. If it fails by 4 or less, you have failed but can try again. If you fail by 5 or more, something goes wrong. If the device is a trap, you spring it. If you’re attempting some sort of sabotage, you think the device is disabled, but it still works normally.
You also can rig simple devices such as saddles or wagon wheels to work normally for a while and then fail or fall off some time later (usually after 1d4 rounds or minutes of use).

Device 
Time 
Disable Device DC1
Example
Simple
1 round
10
Jam a lock
Tricky
1d4 rounds
15
Sabotage a wagon wheel
Difficult
2d4 rounds
20
Disarm a trap, reset a trap
Wicked
2d4 rounds
25
Disarm a complex trap, cleverly sabotage a clockwork device
1If you attempt to leave behind no trace of your tampering, add 5 to the DC.

Action: The amount of time needed to make a Disable Device check depends on the task, as noted above. Disabling a simple device takes 1 round and is a full-round action. An intricate or complex device requires 1d4 or 2d4 rounds.
Try Again: Varies. You can retry if you have missed the check by 4 or less, though you must be aware that you have failed in order to try again.
Special: If you have the Nimble Fingers feat, you get a +2 bonus on Disable Device checks.
A rogue who beats a trap’s DC by 10 or more can study the trap, figure out how it works, and bypass it (along with her companions) without disarming it.
Restriction: Rogues (and other characters with the trapfinding class feature) can disarm magic traps. A magic trap generally has a DC of 25 + the spell level of the magic used to create it.
The spells fire trap, glyph of warding, symbol, and teleportation circle also create traps that a rogue can disarm with a successful Disable Device check. Spike growth and spike stones, however, create magic traps against which Disable Device checks do not succeed. See the individual spell descriptions for details.

OTHER WAYS TO BEAT A TRAP
It’s possible to ruin many traps without making a Disable Device check.
Ranged Attack Traps: Once a trap’s location is known, the obvious way to ruin it is to smash the mechanism—assuming the mechanism can be accessed. Failing that, it’s possible to plug up the holes from which the projectiles emerge. Doing this prevents the trap from firing unless its ammunition does enough damage to break through the plugs.
Melee Attack Traps: These devices can be thwarted by smashing the mechanism or blocking the weapons, as noted above. Alternatively, if a character studies the trap as it triggers, he might be able to time his dodges just right to avoid damage. A character who is doing nothing but studying a trap when it first goes off gains a +4 dodge bonus against its attacks if it is triggered again within the next minute.
Pits: Disabling a pit trap generally ruins only the trapdoor, making it an uncovered pit. Filling in the pit or building a makeshift bridge across it is an application of manual labor, not the Disable Device skill. Characters could neutralize any spikes at the bottom of a pit by attacking them—they break just as daggers do.
Magic Traps: Dispel magic helps here. Someone who succeeds on a caster level check against the level of the trap’s creator suppresses the trap for 1d4 rounds. This works only with a targeted dispel magic, not the area version (see the spell description).

DISGUISE (CHA)
Check: Your Disguise check result determines how good the disguise is, and it is opposed by others’ Spot check results. If you don’t draw any attention to yourself, others do not get to make Spot checks. If you come to the attention of people who are suspicious (such as a guard who is watching commoners walking through a city gate), it can be assumed that such observers are taking 10 on their Spot checks.
You get only one Disguise check per use of the skill, even if several people are making Spot checks against it. The Disguise check is made secretly, so that you can’t be sure how good the result is.
The effectiveness of your disguise depends in part on how much you’re attempting to change your appearance.

Disguise 
Disguise Check Modifier
Minor details only 
+5
Disguised as different gender1 
–2
Disguised as different race1 
–2
Disguised as different age category1
–22
1These modifiers are cumulative; use any that apply.
2Per step of difference between your actual age category and your disguised age category. The steps are: young (younger than adulthood), adulthood, middle age, old, and venerable.

If you are impersonating a particular individual, those who know what that person looks like get a bonus on their Spot checks according to the table below. Furthermore, they are automatically considered to be suspicious of you, so opposed checks are always called for.

Familiarity 
Viewer’s Spot Check Bonus
Recognizes on sight 
+4
Friends or associates 
+6
Close friends 
+8
Intimate 
+10

Usually, an individual makes a Spot check to see through your disguise immediately upon meeting you and each hour thereafter. If you casually meet many different creatures, each for a short time, check once per day or hour, using an average Spot modifier for the group. 
Action: Creating a disguise requires 1d3×10 minutes of work.
Try Again: Yes. You may try to redo a failed disguise, but once others know that a disguise was attempted, they’ll be more suspicious.
Special: Magic that alters your form, such as alter self, disguise self, polymorph, or shapechange, grants you a +10 bonus on Disguise checks (see the individual spell descriptions). You must succeed on a Disguise check with a +10 bonus to duplicate the appearance of a specific individual using the veil spell. Divination magic that allows people to see through illusions (such as true seeing) does not penetrate a mundane disguise, but it can negate the magical component of a magically enhanced one.
You must make a Disguise check when you cast a simulacrum spell to determine how good the likeness is.
If you have the Deceitful feat, you get a +2 bonus on Disguise checks.
Synergy: If you have 5 or more ranks in Bluff, you get a +2 bonus on Disguise checks when you know that you’re being observed and you try to act in character.

ESCAPE ARTIST (DEX; ARMOR CHECK PENALTY)
Check: The table below gives the DCs to escape various forms of restraints.
Ropes: Your Escape Artist check is opposed by the binder’s Use Rope check. Since it’s easier to tie someone up than to escape from being tied up, the binder gets a +10 bonus on his or her check.
Manacles and Masterwork Manacles: The DC for manacles is set by their construction.
Tight Space: The DC noted on the table is for getting through a space where your head fits but your shoulders don’t. If the space is long you may need to make multiple checks. You can’t get through a space that your head does not fit through.
Grappler: You can make an Escape Artist check opposed by your enemy’s grapple check to get out of a grapple or out of a pinned condition (so that you’re only grappling).

Restraint 
Escape Artist DC
Ropes Binder’s 
Use Rope check at +10
Net, animate rope spell, command plants spell, control plants spell, or entangle spell
20
Snare spell 
23
Manacles 
30
Tight space 
30
Masterwork manacles 
35
Grappler 
Grappler’s grapple check result

Action: Making an Escape Artist check to escape from rope bindings, manacles, or other restraints (except a grappler) requires 1 minute of work. Escaping from a net or an animate rope, command plants, control plants, or entangle spell is a full-round action. Escaping from a grapple or pin is a standard action. Squeezing through a tight space takes at least 1 minute, maybe longer, depending on how long the space is.
Try Again: Varies. You can make another check after a failed check if you’re squeezing your way through a tight space, making multiple checks. If the situation permits, you can make additional checks, or even take 20, as long as you’re not being actively opposed.
Special: If you have the Agile feat, you get a +2 bonus on Escape Artist checks.
Synergy: If you have 5 or more ranks in Escape Artist, you get a +2 bonus on Use Rope checks to bind someone.
If you have 5 or more ranks in Use Rope, you get a +2 bonus on Escape Artist checks when escaping from rope bonds.

FORGERY (INT)
Check: Forgery requires writing materials appropriate to the document being forged, enough light or sufficient visual acuity to see the details of what you’re writing, wax for seals (if appropriate), and some time. To forge a document on which the handwriting is not specific to a person (military orders, a government decree, a business ledger, or the like), you need only to have seen a similar document before, and you gain a +8 bonus on your check. To forge a signature, you need an autograph of that person to copy, and you gain a +4 bonus on the check. To forge a longer document written in the hand of some particular person, a large sample of that person’s handwriting is needed.
The Forgery check is made secretly, so that you’re not sure how good your forgery is. As with Disguise, you don’t even need to make a check until someone examines the work. Your Forgery check is opposed by the Forgery check of the person who examines the document to check its authenticity. The examiner gains modifiers on his or her check if any of the conditions on the table below exist.

Condition 
Reader’s Forgery Check Modifier
Type of document unknown to reader 
–2
Type of document somewhat known to reader 
+0
Type of document well known to reader 
+2
Handwriting not known to reader 
–2
Handwriting somewhat known to reader 
+0
Handwriting intimately known to reader 
+2
Reader only casually reviews the document 
–2

A document that contradicts procedure, orders, or previous knowledge, or one that requires sacrifice on the part of the person checking the document can increase that character’s suspicion (and thus create favorable circumstances for the checker’s opposing Forgery check).
Action: Forging a very short and simple document takes about 1 minute. A longer or more complex document takes 1d4 minutes per page.
Try Again: Usually, no. A retry is never possible after a particular reader detects a particular forgery. But the document created by the forger might still fool someone else. The result of a Forgery check for a particular document must be used for every instance of a different reader examining the document. No reader can attempt to detect a particular forgery more than once; if that one opposed check goes in favor of the forger, then the reader can’t try using his own skill again, even if he’s suspicious about the document.
Special: If you have the Deceitful feat, you get a +2 bonus on Forgery checks.
Restriction: Forgery is language-dependent; thus, to forge documents and detect forgeries, you must be able to read and write the language in question. A barbarian can’t learn the Forgery skill unless he has learned to read and write.

GATHER INFORMATION (CHA)
Check: An evening’s time, a few gold pieces for buying drinks and making friends, and a DC 10 Gather Information check get you a general idea of a city’s major news items, assuming there are no obvious reasons why the information would be withheld. The higher your check result, the better the information.
If you want to find out about a specific rumor, or a specific item, or obtain a map, or do something else along those lines, the DC for the check is 15 to 25, or even higher.
Action: A typical Gather Information check takes 1d4+1 hours.
Try Again: Yes, but it takes time for each check. Furthermore, you may draw attention to yourself if you repeatedly pursue a certain type of information.
Special: A half-elf has a +2 racial bonus on Gather Information checks.
If you have the Investigator feat, you get a +2 bonus on Gather Information checks.
Synergy: If you have 5 or more ranks in Knowledge (local), you get a +2 bonus on Gather Information checks.

HANDLE ANIMAL (CHA; TRAINED ONLY)
Check: The DC depends on what you are trying to do.

Task 
Handle Animal DC
Handle an animal 
10
“Push” an animal 
25
Teach an animal a trick 
15 or 201
Train an animal for a general purpose 
15 or 201
Rear a wild animal 
15 + HD of animal
1See the specific trick or purpose below.

General Purpose 
DC 
General Purpose 
DC
Combat riding 
20 
Hunting 
20
Fighting 
20 
Performance 
15
Guarding 
20 
Riding 
15
Heavy labor 
15


Handle an Animal: This task involves commanding an animal to perform a task or trick that it knows. If the animal is wounded or has taken any nonlethal damage or ability score damage, the DC increases by 2. If your check succeeds, the animal performs the task or trick on its next action.
“Push” an Animal: To push an animal means to get it to perform a task or trick that it doesn’t know but is physically capable of performing. This category also covers making an animal perform a forced march or forcing it to hustle for more than 1 hour between sleep cycles. If the animal is wounded or has taken any nonlethal damage or ability score damage, the DC increases by 2. If your check succeeds, the animal performs the task or trick on its next action.
Teach an Animal a Trick: You can teach an animal a specific trick with one week of work and a successful Handle Animal check against the indicated DC. An animal with an Intelligence score of 1 can learn a maximum of three tricks, while an animal with an Intelligence score of 2 can learn a maximum of six tricks. Possible tricks (and their associated DCs) include, but are not necessarily limited to, the following.
Attack (DC 20): The animal attacks apparent enemies. You may point to a particular creature that you wish the animal to attack, and it will comply if able. Normally, an animal will attack only humanoids, monstrous humanoids, giants, or other animals. Teaching an animal to attack all creatures (including such unnatural creatures as undead and aberrations) counts as two tricks.
Come (DC 15): The animal comes to you, even if it normally would not do so.
Defend (DC 20): The animal defends you (or is ready to defend you if no threat is present), even without any command being given. Alternatively, you can command the animal to defend a specific other character.
Down (DC 15): The animal breaks off from combat or otherwise backs down. An animal that doesn’t know this trick continues to fight until it must flee (due to injury, a fear effect, or the like) or its opponent is defeated.
Fetch (DC 15): The animal goes and gets something. If you do not point out a specific item, the animal fetches some random object.
Guard (DC 20): The animal stays in place and prevents others from approaching.
Heel (DC 15): The animal follows you closely, even to places where it normally wouldn’t go.
Perform (DC 15): The animal performs a variety of simple tricks, such as sitting up, rolling over, roaring or barking, and so on.
Seek (DC 15): The animal moves into an area and looks around for anything that is obviously alive or animate.
Stay (DC 15): The animal stays in place, waiting for you to return. It does not challenge other creatures that come by,
though it still defends itself if it needs to.
Track (DC 20): The animal tracks the scent presented to it. (This requires the animal to have the scent ability)
Work (DC 15): The animal pulls or pushes a medium or heavy load.

Train an Animal for a Purpose: Rather than teaching an animal individual tricks, you can simply train it for a general purpose. Essentially, an animal’s purpose represents a preselected set of known tricks that fit into a common scheme, such as guarding or heavy labor. The animal must meet all the normal prerequisites for all tricks included in the training package. If the package includes more than three tricks, the animal must have an Intelligence score of 2.
An animal can be trained for only one general purpose, though if the creature is capable of learning additional tricks (above and beyond those included in its general purpose), it may do so. Training an animal for a purpose requires fewer checks than teaching individual tricks does, but no less time. 
Combat Riding (DC 20): An animal trained to bear a rider into combat knows the tricks attack, come, defend, down, guard, and heel. Training an animal for combat riding takes six weeks. You may also “upgrade” an animal trained for riding to one trained for combat riding by spending three weeks and making a successful DC 20 Handle Animal check. The new general purpose and tricks completely replace the animal’s previous purpose and any tricks it once knew. Warhorses and riding dogs are already trained to bear riders into combat, and they don’t require any additional training for this purpose.
Fighting (DC 20): An animal trained to engage in combat knows the tricks attack, down, and stay. Training an animal for fighting takes three weeks.
Guarding (DC 20): An animal trained to guard knows the tricks attack, defend, down, and guard. Training an animal for guarding takes four weeks.
Heavy Labor (DC 15): An animal trained for heavy labor knows the tricks come and work. Training an animal for heavy labor takes two weeks.
Hunting (DC 20): An animal trained for hunting knows the tricks attack, down, fetch, heel, seek, and track. Training an animal for hunting takes six weeks.
Performance (DC 15): An animal trained for performance knows the tricks come, fetch, heel, perform, and stay. Training an animal for performance takes five weeks.
Riding (DC 15): An animal trained to bear a rider knows the tricks come, heel, and stay. Training an animal for riding takes three weeks.

Rear a Wild Animal: To rear an animal means to raise a wild creature from infancy so that it becomes domesticated. A handler can rear as many as three creatures of the same kind at once.
A successfully domesticated animal can be taught tricks at the same time it’s being raised, or it can be taught as a domesticated animal later.
Action: Varies. Handling an animal is a move action, while pushing an animal is a full-round action. (A druid or ranger can handle her animal companion as a free action or push it as a move action.) For tasks with specific time frames noted above, you must spend half this time (at the rate of 3 hours per day per animal being handled) working toward completion of the task before you attempt the Handle Animal check. If the check fails, your attempt to teach, rear, or train the animal fails and you need not complete the teaching, rearing, or training time. If the check succeeds, you must invest the remainder of the time to complete the teaching, rearing, or training. If the time is interrupted or the task is not followed through to completion, the attempt to teach, rear, or train the animal automatically fails.
Try Again: Yes, except for rearing an animal.
Special: You can use this skill on a creature with an Intelligence score of 1 or 2 that is not an animal, but the DC of any such check increases by 5. Such creatures have the same limit on tricks known as animals do.
A druid or ranger gains a +4 circumstance bonus on Handle Animal checks involving her animal companion.
In addition, a druid’s or ranger’s animal companion knows one or more bonus tricks, which don’t count against the normal limit on tricks known and don’t require any training time or Handle Animal checks to teach.
If you have the Animal Affinity feat, you get a +2 bonus on Handle Animal checks.
Synergy: If you have 5 or more ranks in Handle Animal, you get a +2 bonus on Ride checks and wild empathy checks.
Untrained: If you have no ranks in Handle Animal, you can use a Charisma check to handle and push domestic animals, but you can’t teach, rear, or train animals. A druid or ranger with no ranks in Handle Animal can use a Charisma check to handle and push her animal companion, but she can’t teach, rear, or train other nondomestic animals.

HEAL (WIS)
Check: The DC and effect depend on the task you attempt.

Task Heal 
DC
First aid
15
Long-term care 
15
Treat wound from caltrop, spike growth, or spike stones 
15
Treat poison 
Poison’s save DC
Treat disease 
Disease’s save DC

First Aid: You usually use first aid to save a dying character. If a character has negative hit points and is losing hit points (at the rate of 1 per round, 1 per hour, or 1 per day), you can make him or her stable. A stable character regains no hit points but stops losing them.
Long-Term Care: Providing long-term care means treating a wounded person for a day or more. If your Heal check is successful, the patient recovers hit points or ability score points (lost to ability damage) at twice the normal rate: 2 hit points per level for a full 8 hours of rest in a day, or 4 hit points per level for each full day of complete rest; 2 ability score points for a full 8 hours of rest in a day, or 4 ability score points for each full day of complete rest.
You can tend as many as six patients at a time. You need a few items and supplies (bandages, salves, and so on) that are easy to come by in settled lands. Giving long-term care counts as light activity for the healer. You cannot give long-term care to yourself.
Treat Wound from Caltrop, Spike Growth, or Spike Stones: A creature wounded by stepping on a caltrop moves at one-half normal speed. A successful Heal check removes this movement penalty.
A creature wounded by a spike growth or spike stones spell must succeed on a Reflex save or take injuries that reduce his speed by one-third. Another character can remove this penalty by taking 10 minutes to dress the victim’s injuries and succeeding on a Heal check against the spell’s save DC.
Treat Poison: To treat poison means to tend a single character who has been poisoned and who is going to take more damage from the poison (or suffer some other effect). Every time the poisoned character makes a saving throw against the poison, you make a Heal check. The poisoned character uses your check result or his or her saving throw, whichever is higher.
Treat Disease: To treat a disease means to tend a single diseased character. Every time he or she makes a saving throw against disease effects, you make a Heal check. The diseased character uses your check result or his or her saving throw, whichever is higher.
Action: Providing first aid, treating a wound, or treating poison is a standard action. Treating a disease or tending a creature wounded by a spike growth or spike stones spell takes 10 minutes of work. Providing long-term care requires 8 hours of light activity.
Try Again: Varies. Generally speaking, you can’t try a Heal check again without proof of the original check’s failure. You can always retry a check to provide first aid, assuming the target of the previous attempt is still alive.
Special: A character with the Self-Sufficient feat gets a +2 bonus on Heal checks.
A healer’s kit gives you a +2 circumstance bonus on Heal checks.

HIDE (DEX; ARMOR CHECK PENALTY)
Check: Your Hide check is opposed by the Spot check of anyone who might see you. You can move up to one-half your normal speed and hide at no penalty. When moving at a speed greater than one-half but less than your normal speed, you take a –5 penalty. It’s practically impossible (–20 penalty) to hide while attacking, running or charging.
A creature larger or smaller than Medium takes a size bonus or penalty on Hide checks depending on its size category: Fine +16, Diminutive +12, Tiny +8, Small +4, Large –4, Huge –8, Gargantuan –12, Colossal –16.
You need cover or concealment in order to attempt a Hide check. Total cover or total concealment usually (but not always; see Special, below) obviates the need for a Hide check, since nothing can see you anyway.
If people are observing you, even casually, you can’t hide. You can run around a corner or behind cover so that you’re out of sight and then hide, but the others then know at least where you went.
If your observers are momentarily distracted (such as by a Bluff check; see below), though, you can attempt to hide. While the others turn their attention from you, you can attempt a Hide check if you can get to a hiding place of some kind. (As a general guideline, the hiding place has to be within 1 foot per rank you have in Hide.) This check, however, is made at a –10 penalty because you have to move fast.
Sniping: If you’ve already successfully hidden at least 10 feet from your target, you can make one ranged attack, then immediately hide again. You take a –20 penalty on your Hide check to conceal yourself after the shot.
Creating a Diversion to Hide: You can use Bluff to help you hide. A successful Bluff check can give you the momentary diversion you need to attempt a Hide check while people are aware of you.
Action: Usually none. Normally, you make a Hide check as part of movement, so it doesn’t take a separate action. However, hiding immediately after a ranged attack (see Sniping, above) is a move action.
Special: If you are invisible, you gain a +40 bonus on Hide checks if you are immobile, or a +20 bonus on Hide checks if you’re moving.
If you have the Stealthy feat, you get a +2 bonus on Hide checks.
A 13th-level ranger can attempt a Hide check in any sort of natural terrain, even if it doesn’t grant cover or concealment. A 17thlevel ranger can do this even while being observed.

INTIMIDATE (CHA)
Check: You can change another’s behavior with a successful check. Your Intimidate check is opposed by the target’s modified level check (1d20 + character level or Hit Dice + target’s Wisdom bonus [if any] + target’s modifiers on saves against fear). If you beat your target’s check result, you may treat the target as friendly, but only for the purpose of actions taken while it remains intimidated. (That is, the target retains its normal attitude, but will chat, advise, offer limited help, or advocate on your behalf while intimidated. See the Diplomacy skill, above, for additional details.) The effect lasts as long as the target remains in your presence, and for 1d6×10 minutes afterward. After this time, the target’s default attitude toward you shifts to unfriendly (or, if normally unfriendly, to hostile).
If you fail the check by 5 or more, the target provides you with incorrect or useless information, or otherwise frustrates your efforts.
Demoralize Opponent: You can also use Intimidate to weaken an opponent’s resolve in combat. To do so, make an Intimidate check opposed by the target’s modified level check (see above). If you win, the target becomes shaken for 1 round. A shaken character takes a –2 penalty on attack rolls, ability checks, and saving throws. You can intimidate only an opponent that you threaten in melee combat and that can see you.
Action: Varies. Changing another’s behavior requires 1 minute of interaction. Intimidating an opponent in combat is a standard action.
Try Again: Optional, but not recommended because retries usually do not work. Even if the initial check succeeds, the other character can be intimidated only so far, and a retry doesn’t help. If the initial check fails, the other character has probably become more firmly resolved to resist the intimidator, and a retry is futile.
Special: You gain a +4 bonus on your Intimidate check for every size category that you are larger than your target. Conversely, you take a –4 penalty on your Intimidate check for every size category that you are smaller than your target.
A character immune to fear can’t be intimidated, nor can nonintelligent creatures.
If you have the Persuasive feat, you get a +2 bonus on Intimidate checks.
Synergy: If you have 5 or more ranks in Bluff, you get a +2 bonus on Intimidate checks.

JUMP (STR; ARMOR CHECK PENALTY)
Check: The DC and the distance you can cover vary according to the type of jump you are attempting (see below).
Your Jump check is modified by your speed. If your speed is 30 feet then no modifier based on speed applies to the check. If your speed is less than 30 feet, you take a –6 penalty for every 10 feet of speed less than 30 feet. If your speed is greater than 30 feet, you gain a +4 bonus for every 10 feet beyond 30 feet.
All Jump DCs given here assume that you get a running start, which requires that you move at least 20 feet in a straight line before attempting the jump. If you do not get a running start, the DC for the jump is doubled.
Distance moved by jumping is counted against your normal maximum movement in a round.
If you have ranks in Jump and you succeed on a Jump check, you land on your feet (when appropriate). If you attempt a Jump check untrained, you land prone unless you beat the DC by 5 or more.
Long Jump: A long jump is a horizontal jump, made across a gap like a chasm or stream. At the midpoint of the jump, you attain a vertical height equal to one-quarter of the horizontal distance. The DC for the jump is equal to the distance jumped (in feet).
If your check succeeds, you land on your feet at the far end. If you fail the check by less than 5, you don’t clear the distance, but you can make a DC 15 Reflex save to grab the far edge of the gap. You end your movement grasping the far edge. If that leaves you dangling over a chasm or gap, getting up requires a move action and a DC 15 Climb check.

Long Jump Distance
Jump DC1
5 feet
5
10 feet
10
15 feet
15
20 feet
20
25 feet
25
30 feet
30
1 Requires a 20-foot running start. Without a running start, double the DC.

High Jump: A high jump is a vertical leap made to reach a ledge high above or to grasp something overhead. The DC is equal to 4 times the distance to be cleared.
If you jumped up to grab something, a successful check indicates that you reached the desired height. If you wish to pull yourself up, you can do so with a move action and a DC 15 Climb check. If you fail the Jump check, you do not reach the height, and you land on your feet in the same spot from which you jumped. As with a long jump, the DC is doubled if you do not get a running start of at least 20 feet.

High Jump Distance1 
Jump DC2
1 foot 
4
2 feet 
8
3 feet 
12
4 feet 
16
5 feet 
20
6 feet 
24
7 feet 
28
8 feet 
32
1 Not including vertical reach; see below.
2 Requires a 20-foot running start. Without a running start, double the DC.

Obviously, the difficulty of reaching a given height varies according to the size of the character or creature. The maximum vertical reach (height the creature can reach without jumping) for an average creature of a given size is shown on the table below. (As a Medium creature, a typical human can reach 8 feet without jumping.)
Quadrupedal creatures don’t have the same vertical reach as a bipedal creature; treat them as being one size category smaller.

Creature Size 
Vertical Reach
Colossal 
128 ft.
Gargantuan 
64 ft.
Huge 
32 ft.
Large 
16 ft.
Medium 
8 ft.
Small 
4 ft.
Tiny 
2 ft.
Diminutive 
1 ft.
Fine 
1/2 ft.

Hop Up: You can jump up onto an object as tall as your waist, such as a table or small boulder, with a DC 10 Jump check. Doing so counts as 10 feet of movement, so if your speed is 30 feet, you could move 20 feet, then hop up onto a counter. You do not need to get a running start to hop up, so the DC is not doubled if you do not get a running start.
Jumping Down: If you intentionally jump from a height, you take less damage than you would if you just fell. The DC to jump down from a height is 15. You do not have to get a running start to jump down, so the DC is not doubled if you do not get a running start.
If you succeed on the check, you take falling damage as if you had dropped 10 fewer feet than you actually did.
Action: None. A Jump check is included in your movement, so it is part of a move action. If you run out of movement mid-jump, your next action (either on this turn or, if necessary, on your next turn) must be a move action to complete the jump.
Special: Effects that increase your movement also increase your jumping distance, since your check is modified by your speed.
If you have the Run feat, you get a +4 bonus on Jump checks for any jumps made after a running start.
A halfling has a +2 racial bonus on Jump checks because halflings are agile and athletic.
If you have the Acrobatic feat, you get a +2 bonus on Jump checks.
Synergy: If you have 5 or more ranks in Tumble, you get a +2 bonus on Jump checks.
If you have 5 or more ranks in Jump, you get a +2 bonus on Tumble checks.

KNOWLEDGE (INT; TRAINED ONLY)
Like the Craft and Profession skills, Knowledge actually encompasses a number of unrelated skills. Knowledge represents a study of some body of lore, possibly an academic or even scientific discipline.
Below are listed typical fields of study.
• Arcana (ancient mysteries, magic traditions, arcane symbols, cryptic phrases, constructs, dragons, magical beasts)
• Architecture and engineering (buildings, aqueducts, bridges, fortifications)
• Dungeoneering (aberrations, caverns, oozes, spelunking)
• Geography (lands, terrain, climate, people)
• History (royalty, wars, colonies, migrations, founding of cities)
• Local (legends, personalities, inhabitants, laws, customs, traditions, humanoids)
• Nature (animals, fey, giants, monstrous humanoids, plants, seasons and cycles, weather, vermin)
• Nobility and royalty (lineages, heraldry, family trees, mottoes, personalities)
• Religion (gods and goddesses, mythic history, ecclesiastic tradition, holy symbols, undead)
• The planes (the Inner Planes, the Outer Planes, the Astral Plane, the Ethereal Plane, outsiders, elementals, magic related to the planes)
Check: Answering a question within your field of study has a DC of 10 (for really easy questions), 15 (for basic questions), or 20 to 30 (for really tough questions).
In many cases, you can use this skill to identify monsters and their special powers or vulnerabilities. In general, the DC of such a check equals 10 + the monster’s HD. A successful check allows you to remember a bit of useful information about that monster.
For every 5 points by which your check result exceeds the DC, you recall another piece of useful information.
Action: Usually none. In most cases, making a Knowledge check doesn’t take an action—you simply know the answer or you don’t.
Try Again: No. The check represents what you know, and thinking about a topic a second time doesn’t let you know something that you never learned in the first place.
Synergy: If you have 5 or more ranks in Knowledge (arcana), you get a +2 bonus on Spellcraft checks.
If you have 5 or more ranks in Knowledge (architecture and engineering), you get a +2 bonus on Search checks made to find secret doors or hidden compartments.
If you have 5 or more ranks in Knowledge (geography), you get a +2 bonus on Survival checks made to keep from getting lost or to avoid natural hazards.
If you have 5 or more ranks in Knowledge (history), you get a +2 bonus on bardic knowledge checks.
If you have 5 or more ranks in Knowledge (local), you get a +2 bonus on Gather Information checks.
If you have 5 or more ranks in Knowledge (nature), you get a +2 bonus on Survival checks made in aboveground natural environments (aquatic, desert, forest, hill, marsh, mountains, or plains).
If you have 5 or more ranks in Knowledge (nobility and royalty), you get a +2 bonus on Diplomacy checks.
If you have 5 or more ranks in Knowledge (religion), you get a +2 bonus on turning checks against undead.
If you have 5 or more ranks in Knowledge (the planes), you get a +2 bonus on Survival checks made while on other planes.
If you have 5 or more ranks in Knowledge (dungeoneering), you get a +2 bonus on Survival checks made while underground.
If you have 5 or more ranks in Survival, you get a +2 bonus on Knowledge (nature) checks.
Untrained: An untrained Knowledge check is simply an Intelligence check. Without actual training, you know only common knowledge (DC 10 or lower).

LISTEN (WIS)
Check: Your Listen check is either made against a DC that reflects how quiet the noise is that you might hear, or it is opposed by your target’s Move Silently check.

Listen DC 
Sound
–10 
A battle
0 
People talking1
5 
A person in medium armor walking at a slow pace (10 ft./round) trying not to make any noise.
10 
An unarmored person walking at a slow pace (15 ft./round) trying not to make any noise
15 
A 1st-level rogue using Move Silently to sneak past the listener
15 
People whispering1
19 
A cat stalking
30 
An owl gliding in for a kill
1 If you beat the DC by 10 or more, you can make out what’s being said, assuming that you understand the language.

Listen DC Modifier
Condition
+5
Through a door
+15
Through a stone wall
+1
Per 10 feet of distance
+5
Listener distracted

In the case of people trying to be quiet, the DCs given on the table could be replaced by Move Silently checks, in which case the indicated DC would be their average check result. 
Action: Varies. Every time you have a chance to hear something in a reactive manner (such as when someone makes a noise or you move into a new area), you can make a Listen check without using an action. Trying to hear something you failed to hear previously is a move action.
Try Again: Yes. You can try to hear something that you failed to hear previously with no penalty.
Special: When several characters are listening to the same thing, a single 1d20 roll can be used for all the individuals’ Listen checks.
A fascinated creature takes a –4 penalty on Listen checks made as reactions.
If you have the Alertness feat, you get a +2 bonus on Listen checks.
A ranger gains a bonus on Listen checks when using this skill against a favored enemy.
An elf, gnome, or halfling has a +2 racial bonus on Listen checks. 
A half-elf has a +1 racial bonus on Listen checks..
A sleeping character may make Listen checks at a –10 penalty. A successful check awakens the sleeper.

MOVE SILENTLY (DEX; ARMOR CHECK PENALTY)
Check: Your Move Silently check is opposed by the Listen check of anyone who might hear you. You can move up to one-half your normal speed at no penalty. When moving at a speed greater than one-half but less than your full speed, you take a –5 penalty. It’s practically impossible (–20 penalty) to move silently while running or charging.
Noisy surfaces, such as bogs or undergrowth, are tough to move silently across. When you try to sneak across such a surface, you take a penalty on your Move Silently check as indicated below.

Surface 
Check Modifier
Noisy (scree, shallow or deep bog, undergrowth, dense rubble)
–2
Very noisy (dense undergrowth, deep snow) 
–5

Action:None. A Move Silently check is included in your movement or other activity, so it is part of another action.
Special: The master of a cat familiar gains a +3 bonus on Move Silently checks.
A halfling has a +2 racial bonus on Move Silently checks.
If you have the Stealthy feat, you get a +2 bonus on Move Silently checks.

OPEN LOCK (DEX; TRAINED ONLY)
Attempting an Open Lock check without a set of thieves’ tools imposes a –2 circumstance penalty on the check, even if a simple tool is employed. If you use masterwork thieves’ tools, you gain a +2 circumstance bonus on the check.
Check: The DC for opening a lock varies from 20 to 40, depending on the quality of the lock, as given on the table below.

Lock 
DC 
Lock 
DC
Very simple lock 
20 
Good lock 
30
Average lock
 25 
Amazing lock 
40

Action: Opening a lock is a full-round action.
Special: If you have the Nimble Fingers feat, you get a +2 bonus on Open Lock checks.
Untrained: You cannot pick locks untrained, but you might successfully force them open.

PERFORM (CHA)
Like Craft, Knowledge, and Profession, Perform is actually a number of separate skills.
You could have several Perform skills, each with its own ranks, each purchased as a separate skill.
Each of the nine categories of the Perform skill includes a variety of methods, instruments, or techniques, a small list of which is provided for each category below.
• Act (comedy, drama, mime)
• Comedy (buffoonery, limericks, joke-telling)
• Dance (ballet, waltz, jig)
• Keyboard instruments (harpsichord, piano, pipe organ)
• Oratory (epic, ode, storytelling)
• Percussion instruments (bells, chimes, drums, gong)
• String instruments (fiddle, harp, lute, mandolin)
• Wind instruments (flute, pan pipes, recorder, shawm, trumpet)
• Sing (ballad, chant, melody)
Check: You can impress audiences with your talent and skill.
Perform DC
Performance
10
Routine performance. Trying to earn money by playing in public is essentially begging. You can earn 1d10 cp/day.
15
Enjoyable performance. In a prosperous city, you can earn 1d10 sp/day.
20
Great performance. In a prosperous city, you can earn 3d10 sp/day. In time, you may be invited to join a professional troupe and may develop a regional reputation.
25
Memorable performance. In a prosperous city, you can earn 1d6 gp/day. In time, you may come to the attention of noble patrons and develop a national reputation.
30
Extraordinary performance. In a prosperous city, you can earn 3d6 gp/day. In time, you may draw attention from distant potential patrons, or even from extraplanar beings.

A masterwork musical instrument gives you a +2 circumstance bonus on Perform checks that involve its use.
Action: Varies. Trying to earn money by playing in public requires anywhere from an evening’s work to a full day’s performance. The bard’s special Perform-based abilities are described in that class’s description.
Try Again: Yes. Retries are allowed, but they don’t negate previous failures, and an audience that has been unimpressed in the past is likely to be prejudiced against future performances. (Increase the DC by 2 for each previous failure.)
Special: A bard must have at least 3 ranks in a Perform skill to inspire courage in his allies, or to use his countersong or his fascinate ability. A bard needs 6 ranks in a Perform skill to inspire competence, 9 ranks to use his suggestion ability, 12 ranks to inspire greatness, 15 ranks to use his song of freedom ability, 18 ranks to inspire heroics, and 21 ranks to use his mass suggestion ability. See Bardic Music in the bard class description.
In addition to using the Perform skill, you can entertain people with sleight of hand, tumbling, tightrope walking, and spells (especially illusions).

PROFESSION (WIS; TRAINED ONLY)
Like Craft, Knowledge, and Perform, Profession is actually a number of separate skills. You could have several Profession skills, each with its own ranks, each purchased as a separate skill. While a Craft skill represents ability in creating or making an item, a Profession skill represents an aptitude in a vocation requiring a broader range of less specific knowledge. 
Check: You can practice your trade and make a decent living, earning about half your Profession check result in gold pieces per week of dedicated work. You know how to use the tools of your trade, how to perform the profession’s daily tasks, how to supervise helpers, and how to handle common problems.
Action: Not applicable. A single check generally represents a week of work.
Try Again: Varies. An attempt to use a Profession skill to earn an income cannot be retried. You are stuck with whatever weekly wage your check result brought you. Another check may be made after a week to determine a new income for the next period of time. An attempt to accomplish some specific task can usually be retried.
Untrained: Untrained laborers and assistants (that is, characters without any ranks in Profession) earn an average of 1 silver piece per day.

RIDE (DEX)
If you attempt to ride a creature that is ill suited as a mount, you take a –5 penalty on your Ride checks.
Check: Typical riding actions don’t require checks. You can saddle, mount, ride, and dismount from a mount without a problem.
The following tasks do require checks.

Task 
Ride DC 
Task 
Ride DC
Guide with knees 
5
Leap 
15
Stay in saddle 
5
Spur mount 
15
Fight with warhorse 
10
 Control mount in battle
20
Cover 
15
Fast mount or dismount
201
Soft fall
15


1 Armor check penalty applies.

Guide with Knees: You can react instantly to guide your mount with your knees so that you can use both hands in combat. Make your Ride check at the start of your turn. If you fail, you can use only one hand this round because you need to use the other to control your mount.
Stay in Saddle: You can react instantly to try to avoid falling when your mount rears or bolts unexpectedly or when you take damage. This usage does not take an action.
Fight with Warhorse: If you direct your war-trained mount to attack in battle, you can still make your own attack or attacks normally. This usage is a free action.
Cover: You can react instantly to drop down and hang alongside your mount, using it as cover. You can’t attack or cast spells while using your mount as cover. If you fail your Ride check, you don’t get the cover benefit. This usage does not take an action.
Soft Fall: You can react instantly to try to take no damage when you fall off a mount—when it is killed or when it falls, for example. If you fail your Ride check, you take 1d6 points of falling damage. This usage does not take an action.
Leap: You can get your mount to leap obstacles as part of its movement. Use your Ride modifier or the mount’s Jump modifier, whichever is lower, to see how far the creature can jump. If you fail your Ride check, you fall off the mount when it leaps and take the appropriate falling damage (at least 1d6 points). This usage does not take an action, but is part of the mount’s movement.
Spur Mount: You can spur your mount to greater speed with a move action. A successful Ride check increases the mount’s speed by 10 feet for 1 round but deals 1 point of damage to the creature. You can use this ability every round, but each consecutive round of additional speed deals twice as much damage to the mount as the previous round (2 points, 4 points, 8 points, and so on).
Control Mount in Battle: As a move action, you can attempt to control a light horse, pony, heavy horse, or other mount not trained for combat riding while in battle. If you fail the Ride check, you can do nothing else in that round. You do not need to roll for warhorses or warponies.
Fast Mount or Dismount: You can attempt to mount or dismount from a mount of up to one size category larger than yourself as a free action, provided that you still have a move action available that round. If you fail the Ride check, mounting or dismounting is a move action. You can’t use fast mount or dismount on a mount more than one size category larger than yourself.
Action: Varies. Mounting or dismounting normally is a move action. Other checks are a move action, a free action, or no action at all, as noted above.
Special: If you are riding bareback, you take a –5 penalty on Ride checks.
If your mount has a military saddle you get a +2 circumstance bonus on Ride checks related to staying in the saddle.
The Ride skill is a prerequisite for the feats Mounted Archery, Mounted Combat, Ride-By Attack, Spirited Charge,
Trample.
If you have the Animal Affinity feat, you get a +2 bonus on Ride checks.
Synergy: If you have 5 or more ranks in Handle Animal, you get a +2 bonus on Ride checks.

SEARCH (INT)
Check: You generally must be within 10 feet of the object or surface to be searched. The table below gives DCs for typical tasks involving the Search skill.

Task
Search DC
Ransack a chest full of junk to find a certain item
10
Notice a typical secret door or a simple trap 
20
Find a difficult nonmagical trap (rogue only)1 
21 or higher
Find a magic trap (rogue only)1 
25 + level of spell used to create trap
Notice a well-hidden secret door 
30
Find a footprint 
Varies2
1 Dwarves (even if they are not rogues) can use Search to find traps built into or out of stone.
2 A successful Search check can find a footprint or similar sign of a creature’s passage, but it won’t let you find or follow a trail. See the Track feat for the appropriate DC.

Action: It takes a full-round action to search a 5-foot-by-5-foot area or a volume of goods 5 feet on a side.
Special: An elf has a +2 racial bonus on Search checks, and a half-elf has a +1 racial bonus. An elf (but not a half-elf) who simply passes within 5 feet of a secret or concealed door can make a Search check to find that door.
If you have the Investigator feat, you get a +2 bonus on Search checks.
The spells explosive runes, fire trap, glyph of warding, symbol, and teleportation circle create magic traps that a rogue can find by making a successful Search check and then can attempt to disarm by using Disable Device. Identifying the location of a snare spell has a DC of 23. Spike growth and spike stones create magic traps that can be found using Search, but against which Disable Device checks do not succeed. See the individual spell descriptions for details.
Active abjuration spells within 10 feet of each other for 24 hours or more create barely visible energy fluctuations. These fluctuations give you a +4 bonus on Search checks to locate such abjuration spells.
Synergy: If you have 5 or more ranks in Search, you get a +2 bonus on Survival checks to find or follow tracks.
If you have 5 or more ranks in Knowledge (architecture and engineering), you get a +2 bonus on Search checks to find secret doors or hidden compartments.
Restriction: While anyone can use Search to find a trap whose DC is 20 or lower, only a rogue can use Search to locate traps with higher DCs. (Exception: The spell find traps temporarily enables a cleric to use the Search skill as if he were a rogue.)
A dwarf, even one who is not a rogue, can use the Search skill to find a difficult trap (one with a DC higher than 20) if the trap is built into or out of stone. He gains a +2 racial bonus on the Search check from his stonecunning ability.

SENSE MOTIVE (WIS)
Check: A successful check lets you avoid being bluffed (see the Bluff skill). You can also use this skill to determine when “something is up” (that is, something odd is going on) or to assess someone’s trustworthiness. 

Task 
Sense Motive DC
Hunch 
20
Sense enchantment 
25 or 15
Discern secret message 
Varies

Hunch: This use of the skill involves making a gut assessment of the social situation. You can get the feeling from another’s behavior that something is wrong, such as when you’re talking to an impostor. Alternatively, you can get the feeling that someone is trustworthy.
Sense Enchantment: You can tell that someone’s behavior is being influenced by an enchantment effect (by definition, a mind-affecting effect), even if that person isn’t aware of it. The usual DC is 25, but if the target is dominated (see dominate person), the DC is only 15 because of the limited range of the target’s activities.
Discern Secret Message: You may use Sense Motive to detect that a hidden message is being transmitted via the Bluff skill. In this case, your Sense Motive check is opposed by the Bluff check of the character transmitting the message. For each piece of information relating to the message that you are missing, you take a –2 penalty on your Sense Motive check. If you succeed by 4 or less, you know that something hidden is being communicated, but you can’t learn anything specific about its content. If you beat the DC by 5 or more, you intercept and understand the message. If you fail by 4 or less, you don’t detect any hidden communication. If you fail by 5 or more, you infer some false information.
Action: Trying to gain information with Sense Motive generally takes at least 1 minute, and you could spend a whole evening trying to get a sense of the people around you.
Try Again: No, though you may make a Sense Motive check for each Bluff check made against you.
Special: A ranger gains a bonus on Sense Motive checks when using this skill against a favored enemy.
If you have the Negotiator feat, you get a +2 bonus on Sense Motive checks.
Synergy: If you have 5 or more ranks in Sense Motive, you get a +2 bonus on Diplomacy checks.

SLEIGHT OF HAND (DEX; TRAINED ONLY; ARMOR CHECK PENALTY)
Check: A DC 10 Sleight of Hand check lets you palm a coin-sized, unattended object. Performing a minor feat of legerdemain, such as making a coin disappear, also has a DC of 10 unless an observer is determined to note where the item went.
When you use this skill under close observation, your skill check is opposed by the observer’s Spot check. The observer’s success doesn’t prevent you from performing the action, just from doing it unnoticed.
You can hide a small object (including a light weapon or an easily concealed ranged weapon, such as a dart, sling, or hand crossbow) on your body. Your Sleight of Hand check is opposed by the Spot check of anyone observing you or the Search check of anyone frisking you. In the latter case, the searcher gains a +4 bonus on the Search check, since it’s generally easier to find such an object than to hide it. A dagger is easier to hide than most light weapons, and grants you a +2 bonus on your Sleight of Hand check to conceal it. An extraordinarily small object, such as a coin, shuriken, or ring, grants you a +4 bonus on your Sleight of Hand check to conceal it, and heavy or baggy clothing (such as a cloak) grants you a +2 bonus on the check.
Drawing a hidden weapon is a standard action and doesn’t provoke an attack of opportunity.
If you try to take something from another creature, you must make a DC 20 Sleight of Hand check to obtain it. The opponent makes a Spot check to detect the attempt, opposed by the same Sleight of Hand check result you achieved when you tried to grab the item. An opponent who succeeds on this check notices the attempt, regardless of whether you got the item.
You can also use Sleight of Hand to entertain an audience as though you were using the Perform skill. In such a case, your “act” encompasses elements of legerdemain, juggling, and the like.

Sleight of Hand DC 
Task
10
Palm a coin-sized object, make a coin disappear
20
Lift a small object from a person

Action: Any Sleight of Hand check normally is a standard action. However, you may perform a Sleight of Hand check as a free action by taking a –20 penalty on the check.
Try Again: Yes, but after an initial failure, a second Sleight of Hand attempt against the same target (or while you are being watched by the same observer who noticed your previous attempt) increases the DC for the task by 10.
Special: If you have the Deft Hands feat, you get a +2 bonus on Sleight of Hand checks.
Synergy: If you have 5 or more ranks in Bluff, you get a +2 bonus on Sleight of Hand checks.
Untrained: An untrained Sleight of Hand check is simply a Dexterity check. Without actual training, you can’t succeed on any Sleight of Hand check with a DC higher than 10, except for hiding an object on your body.

SPEAK LANGUAGE (NONE; TRAINED ONLY)
Common Languages and Their Alphabets
Language 
Typical Speakers 
Alphabet
Abyssal 
Demons, chaotic evil outsiders 
Infernal
Aquan 
Water-based creatures 
Elven
Auran 
Air-based creatures 
Draconic
Celestial 
Good outsiders 
Celestial
Common 
Humans, halflings, half-elves, half-orcs 
Common
Draconic 
Kobolds, troglodytes, lizardfolk, dragons
Draconic
Druidic 
Druids (only) 
Druidic
Dwarven 
Dwarves 
Dwarven
Elven 
Elves 
Elven
Giant 
Ogres, giants 
Dwarven
Gnome 
Gnomes 
Dwarven
Goblin 
Goblins, hobgoblins, bugbears 
Dwarven
Gnoll 
Gnolls 
Common
Halfling 
Halflings 
Common
Ignan 
Fire-based creatures 
Draconic
Infernal 
Devils, lawful evil outsiders 
Infernal
Orc 
Orcs 
Dwarven
Sylvan 
Dryads, brownies, leprechauns 
Elven
Terran 
Xorns and other earth-based creatures
Dwarven
Undercommon 
Drow
Elven

Action: Not applicable.
Try Again: Not applicable. There are no Speak Language checks to fail.
The Speak Language skill doesn’t work like other skills. Languages work as follows.
• You start at 1st level knowing one or two languages (based on your race), plus an additional number of languages equal to your starting Intelligence bonus.
• You can purchase Speak Language just like any other skill, but instead of buying a rank in it, you choose a new language that you can speak.
• You don’t make Speak Language checks. You either know a language or you don’t.
• A literate character (anyone but a barbarian who has not spent skill points to become literate) can read and write any language she speaks. Each language has an alphabet, though sometimes several spoken languages share a single alphabet.

SPELLCRAFT (INT; TRAINED ONLY)
Use this skill to identify spells as they are cast or spells already in place.

Spellcraft DC 
Task
13 
When using read magic, identify a glyph of warding. No action required.
15 + spell level 
Identify a spell being cast. (You must see or hear the spell’s verbal or somatic components.) No action required. No retry. 
15 + spell level 
Learn a spell from a spellbook or scroll (wizard only). No retry for that spell until you gain at least 1 rank in Spellcraft (even if you find another source to try to learn the spell from). Requires 8 hours.
15 + spell level 
Prepare a spell from a borrowed spellbook (wizard only). One try per day. No extra time required. 
15 + spell level 
When casting detect magic, determine the school of magic involved in the aura of a single item or creature you can see. (If the aura is not a spell effect, the DC is 15 + one-half caster level.) No action required.
19 
When using read magic, identify a symbol. No action required.
20 + spell level 
Identify a spell that’s already in place and in effect. You must be able to see or detect the effects of the spell. No action required. No retry.
20 + spell level 
Identify materials created or shaped by magic, such as noting that an iron wall is the result of a wall of iron spell. No action required. No retry.
20 + spell level 
Decipher a written spell (such as a scroll) without using read magic. One try per day. Requires a full-round action.
25 + spell level 
After rolling a saving throw against a spell targeted on you, determine what that spell was. No action required. No retry.
25 
Identify a potion. Requires 1 minute. No retry.
20 
Draw a diagram to allow dimensional anchor to be cast on a magic circle spell. Requires 10 minutes. No retry. This check is made secretly so you do not know the result.
30 or higher 
Understand a strange or unique magical effect, such as the effects of a magic stream. Time required varies. No retry.

Check: You can identify spells and magic effects. The DCs for Spellcraft checks relating to various tasks are summarized on the table above.
Action: Varies, as noted above.
Try Again: See above.
Special: If you are a specialist wizard, you get a +2 bonus on Spellcraft checks when dealing with a spell or effect from your specialty school. You take a –5 penalty when dealing with a spell or effect from a prohibited school (and some tasks, such as learning a prohibited spell, are just impossible).
If you have the Magical Aptitude feat, you get a +2 bonus on Spellcraft checks.
Synergy: If you have 5 or more ranks in Knowledge (arcana), you get a +2 bonus on Spellcraft checks.
If you have 5 or more ranks in Use Magic Device, you get a +2 bonus on Spellcraft checks to decipher spells on scrolls.
If you have 5 or more ranks in Spellcraft, you get a +2 bonus on Use Magic Device checks related to scrolls.
Additionally, certain spells allow you to gain information about magic, provided that you make a successful Spellcraft check as detailed in the spell description.

SPOT (WIS)
Check: The Spot skill is used primarily to detect characters or creatures who are hiding. Typically, your Spot check is opposed by the Hide check of the creature trying not to be seen. Sometimes a creature isn’t intentionally hiding but is still difficult to see, so a successful Spot check is necessary to notice it.
A Spot check result higher than 20 generally lets you become aware of an invisible creature near you, though you can’t actually see it.
Spot is also used to detect someone in disguise (see the Disguise skill), and to read lips when you can’t hear or understand what someone is saying.
Spot checks may be called for to determine the distance at which an encounter begins. A penalty applies on such checks, depending on the distance between the two individuals or groups, and an additional penalty may apply if the character making the Spot check is distracted (not concentrating on being observant).

Condition 
Penalty
Per 10 feet of distance 
–1
Spotter distracted 
–5

Read Lips: To understand what someone is saying by reading lips, you must be within 30 feet of the speaker, be able to see him or her speak, and understand the speaker’s language. (This use of the skill is language-dependent.) The base DC is 15, but it increases for complex speech or an inarticulate speaker. You must maintain a line of sight to the lips being read.
If your Spot check succeeds, you can understand the general content of a minute’s worth of speaking, but you usually still miss certain details. If the check fails by 4 or less, you can’t read the speaker’s lips. If the check fails by 5 or more, you draw some incorrect conclusion about the speech. The check is rolled secretly in this case, so that you don’t know whether you succeeded or missed by 5.
Action: Varies. Every time you have a chance to spot something in a reactive manner you can make a Spot check without using an action. Trying to spot something you failed to see previously is a move action. To read lips, you must concentrate for a full minute before making a Spot check, and you can’t perform any other action (other than moving at up to half speed) during this minute.
Try Again: Yes. You can try to spot something that you failed to see previously at no penalty. You can attempt to read lips once per minute.
Special: A fascinated creature takes a –4 penalty on Spot checks made as reactions.
If you have the Alertness feat, you get a +2 bonus on Spot checks.
A ranger gains a bonus on Spot checks when using this skill against a favored enemy.
An elf has a +2 racial bonus on Spot checks.
A half-elf has a +1 racial bonus on Spot checks.
The master of a hawk familiar gains a +3 bonus on Spot checks in daylight or other lighted areas.
The master of an owl familiar gains a +3 bonus on Spot checks in shadowy or other darkened areas.

SURVIVAL (WIS)
Check: You can keep yourself and others safe and fed in the wild. The table below gives the DCs for various tasks that require Survival checks.
Survival does not allow you to follow difficult tracks unless you are a ranger or have the Track feat (see the Restriction section below).

Survival DC 
Task
10 
Get along in the wild. Move up to one-half your overland speed while hunting and foraging (no food or water supplies needed). You can provide food and water for one other person for every 2 points by which your check result exceeds 10.
15
Gain a +2 bonus on all Fortitude saves against severe weather while moving up to one-half your overland speed, or gain a +4 bonus if you remain stationary. You may grant the same bonus to one other character for every 1 point by which your Survival check result exceeds 15.
15 
Keep from getting lost or avoid natural hazards, such as quicksand.
15 
Predict the weather up to 24 hours in advance. For every 5 points by which your Survival check result exceeds 15, you can predict the weather for one additional day in advance.
Varies 
Follow tracks (see the Track feat).

Action: Varies. A single Survival check may represent activity over the course of hours or a full day. A Survival check made to find tracks is at least a full-round action, and it may take even longer.
Try Again: Varies. For getting along in the wild or for gaining the Fortitude save bonus noted in the table above, you make a Survival check once every 24 hours. The result of that check applies until the next check is made. To avoid getting lost or avoid natural hazards, you make a Survival check whenever the situation calls for one. Retries to avoid getting lost in a specific situation or to avoid a specific natural hazard are not allowed. For finding tracks, you can retry a failed check after 1 hour (outdoors) or 10 minutes(indoors) of searching.
Restriction: While anyone can use Survival to find tracks (regardless of the DC), or to follow tracks when the DC for the task is 10 or lower, only a ranger (or a character with the Track feat) can use Survival to follow tracks when the task has a higher DC.
Special: If you have 5 or more ranks in Survival, you can automatically determine where true north lies in relation to yourself.
A ranger gains a bonus on Survival checks when using this skill to find or follow the tracks of a favored enemy.
If you have the Self-Sufficient feat, you get a +2 bonus on Survival checks.
Synergy: If you have 5 or more ranks in Survival, you get a +2 bonus on Knowledge (nature) checks.
If you have 5 or more ranks in Knowledge (dungeoneering), you get a +2 bonus on Survival checks made while underground.
If you have 5 or more ranks in Knowledge (nature), you get a +2 bonus on Survival checks in aboveground natural environments (aquatic, desert, forest, hill, marsh, mountains, and plains).
If you have 5 or more ranks in Knowledge (geography), you get a +2 bonus on Survival checks made to keep from getting lost or to avoid natural hazards.
If you have 5 or more ranks in Knowledge (the planes), you get a +2 bonus on Survival checks made while on other planes.
If you have 5 or more ranks in Search, you get a +2 bonus on Survival checks to find or follow tracks.

SWIM (STR; ARMOR CHECK PENALTY)
Check: Make a Swim check once per round while you are in the water. Success means you may swim at up to one-half your speed (as a full-round action) or at one-quarter your speed (as a move action). If you fail by 4 or less, you make no progress through the water. If you fail by 5 or more, you go underwater.
If you are underwater, either because you failed a Swim check or because you are swimming underwater intentionally, you must hold your breath. You can hold your breath for a number of rounds equal to your Constitution score, but only if you do nothing other than take move actions or free actions. If you take a standard action or a full-round action (such as making an attack), the remainder of the duration for which you can hold your breath is reduced by 1 round. (Effectively, a character in combat can hold his or her breath only half as long as normal.) After that period of time, you must make a DC 10 Constitution check every round to continue holding your breath. Each round, the DC for that check increases by 1. If you fail the Constitution check, you begin to drown.
The DC for the Swim check depends on the water, as given on the table below.

Water
Swim DC
Calm water 
10
Rough water 
15
Stormy water 
201
1 You can’t take 10 on a Swim check in stormy water, even if you aren’t otherwise being threatened or distracted.


Each hour that you swim, you must make a DC 20 Swim check or take 1d6 points of nonlethal damage from fatigue.
Action: A successful Swim check allows you to swim one-quarter of your speed as a move action or one-half your speed as a full-round action.
Special: Swim checks are subject to double the normal armor check penalty and encumbrance penalty.
If you have the Athletic feat, you get a +2 bonus on Swim checks.
If you have the Endurance feat, you get a +4 bonus on Swim checks made to avoid taking nonlethal damage from fatigue.
A creature with a swim speed can move through water at its indicated speed without making Swim checks. It gains a +8 racial bonus on any Swim check to perform a special action or avoid a hazard. The creature always can choose to take 10 on a Swim check, even if distracted or endangered when swimming. Such a creature can use the run action while swimming, provided that it swims in a straight line.

TUMBLE (DEX; TRAINED ONLY; ARMOR CHECK PENALTY)
You can’t use this skill if your speed has been reduced by armor, excess equipment, or loot.
Check: You can land softly when you fall or tumble past opponents. You can also tumble to entertain an audience (as though using the Perform skill). The DCs for various tasks involving the Tumble skill are given on the table below.

Tumble DC 
Task
15 
Treat a fall as if it were 10 feet shorter than it really is when determining damage.
15 
Tumble at one-half speed as part of normal movement, provoking no attacks of opportunity while doing so. Failure means you provoke attacks of opportunity normally. Check separately for each opponent you move past, in the order in which you pass them (player’s choice of order in case of a tie).
Each additional enemy after the first adds +2 to the Tumble DC.
25 
Tumble at one-half speed through an area occupied by an enemy (over, under, or around the opponent) as part of normal movement, provoking no attacks of opportunity while doing so. Failure means you stop before entering the enemy-occupied area and provoke an attack of opportunity from that enemy.
Check separately for each opponent. Each additional enemy after the first adds +2 to the Tumble DC.

Obstructed or otherwise treacherous surfaces, such as natural cavern floors or undergrowth, are tough to tumble through. The DC for any Tumble check made to tumble into such a square is modified as indicated below.

Surface Is . . . 
DC Modifier
Lightly obstructed (scree, light rubble, shallow bog1, undergrowth) 
+2
Severely obstructed (natural cavern floor, dense rubble, dense undergrowth) 
+5
Lightly slippery (wet floor) 
+2
Severely slippery (ice sheet) 
+5
Sloped or angled 
+2
1 Tumbling is impossible in a deep bog.

Accelerated Tumbling: You try to tumble past or through enemies more quickly than normal. By accepting a –10 penalty on your Tumble checks, you can move at your full speed instead of one-half your speed.
Action: Not applicable. Tumbling is part of movement, so a Tumble check is part of a move action.
Try Again: Usually no. An audience, once it has judged a tumbler as an uninteresting performer, is not receptive to repeat performances.
You can try to reduce damage from a fall as an instant reaction only once per fall.
Special: If you have 5 or more ranks in Tumble, you gain a +3 dodge bonus to AC when fighting defensively instead of the usual +2 dodge bonus to AC.
If you have 5 or more ranks in Tumble, you gain a +6 dodge bonus to AC when executing the total defense standard action instead of the usual +4 dodge bonus to AC.
If you have the Acrobatic feat, you get a +2 bonus on Tumble checks.
Synergy: If you have 5 or more ranks in Tumble, you get a +2 bonus on Balance and Jump checks.
If you have 5 or more ranks in Jump, you get a +2 bonus on Tumble checks.

USE MAGIC DEVICE (CHA; TRAINED ONLY)
Use this skill to activate magic
Check: You can use this skill to read a spell or to activate a magic item. Use Magic Device lets you use a magic item as if you had the spell ability or class features of another class, as if you were a different race, or as if you were of a different alignment.
You make a Use Magic Device check each time you activate a device such as a wand. If you are using the check to emulate an alignment or some other quality in an ongoing manner, you need to make the relevant Use Magic Device check once per hour.
You must consciously choose which requirement to emulate. That is, you must know what you are trying to emulate when you make a Use Magic Device check for that purpose. The DCs for various tasks involving Use Magic Device checks are summarized on the table below.

Task 
Use Magic Device DC
Activate blindly 
25
Decipher a written spell 
25 + spell level
Use a scroll 
20 + caster level
Use a wand 
20
Emulate a class feature 
20
Emulate an ability score 
See text
Emulate a race 
25
Emulate an alignment 
30

Activate Blindly: Some magic items are activated by special words, thoughts, or actions. You can activate such an item as if you were using the activation word, thought, or action, even when you’re not and even if you don’t know it. You do have to perform some equivalent activity in order to make the check. That is, you must speak, wave the item around, or otherwise attempt to get it to activate. You get a special +2 bonus on your Use Magic Device check if you’ve activated the item in question at least once before. If you fail by 9 or less, you can’t activate the device. If you fail by 10 or more, you suffer a mishap. A mishap means that magical energy gets released but it doesn’t do what you wanted it to do. The default mishaps are that the item affects the wrong target or that uncontrolled magical energy is released, dealing 2d6 points of damage to you. This mishap is in addition to the chance for a mishap that you normally run when you cast a spell from a scroll that you could not otherwise cast yourself.
Decipher a Written Spell: This usage works just like deciphering a written spell with the Spellcraft skill, except that the DC is 5 points higher. Deciphering a written spell requires 1 minute of concentration.
Emulate an Ability Score: To cast a spell from a scroll, you need a high score in the appropriate ability (Intelligence for wizard spells, Wisdom for divine spells, or Charisma for sorcerer or bard spells). Your effective ability score (appropriate to the class you’re emulating when you try to cast the spell from the scroll) is your Use Magic Device check result minus 15. If you already have a high enough score in the appropriate ability, you don’t need to make this check.
Emulate an Alignment: Some magic items have positive or negative effects based on the user’s alignment. Use Magic Device lets you use these items as if you were of an alignment of your choice. You can emulate only one alignment at a time.
Emulate a Class Feature: Sometimes you need to use a class feature to activate a magic item. In this case, your effective level in the emulated class equals your Use Magic Device check result minus 20.  This skill does not let you actually use the class feature of another class. It just lets you activate items as if you had that class feature. If the class whose feature you are emulating has an alignment requirement, you must meet it, either honestly or by emulating an appropriate alignment with a separate Use Magic Device check (see above).
Emulate a Race: Some magic items work only for members of certain races, or work better for members of those races. You can use such an item as if you were a race of your choice. You can emulate only one race at a time.
Use a Scroll: If you are casting a spell from a scroll, you have to decipher it first. Normally, to cast a spell from a scroll, you must have the scroll’s spell on your class spell list. Use Magic Device allows you to use a scroll as if you had a particular spell on your class spell list. The DC is equal to 20 + the caster level of the spell you are trying to cast from the scroll. In addition, casting a spell from a scroll requires a minimum score (10 + spell level) in the appropriate ability. If you don’t have a sufficient score in that ability, you must emulate the ability score with a separate Use Magic Device check (see above).
This use of the skill also applies to other spell completion magic items.
Use a Wand: Normally, to use a wand, you must have the wand’s spell on your class spell list. This use of the skill allows you to use a wand as if you had a particular spell on your class spell list. This use of the skill also applies to other spell trigger magic items, such as staffs.
Action: None. The Use Magic Device check is made as part of the action (if any) required to activate the magic item.
Try Again: Yes, but if you ever roll a natural 1 while attempting to activate an item and you fail, then you can’t try to activate that item again for 24 hours.
Special: You cannot take 10 with this skill.
You can’t aid another on Use Magic Device checks. Only the user of the item may attempt such a check.
If you have the Magical Aptitude feat, you get a +2 bonus on Use Magic Device checks.
Synergy: If you have 5 or more ranks in Spellcraft, you get a +2 bonus on Use Magic Device checks related to scrolls.
If you have 5 or more ranks in Decipher Script, you get a +2 bonus on Use Magic Device checks related to scrolls.
If you have 5 or more ranks in Use Magic Device, you get a +2 bonus to Spellcraft checks made to decipher spells on scrolls.

USE ROPE (DEX)
Check: Most tasks with a rope are relatively simple. The DCs for various tasks utilizing this skill are summarized on the table below.

Use Rope DC
Task
10
Tie a firm knot
101
Secure a grappling hook
15
Tie a special knot, such as one that slips, slides slowly, or loosens with a tug
15
Tie a rope around yourself one-handed
15
Splice two ropes together
Varies
Bind a character
1 Add 2 to the DC for every 10 feet the hook is thrown; see below.

Secure a Grappling Hook: Securing a grappling hook requires a Use Rope check (DC 10, +2 for every 10 feet of distance the grappling hook is thrown, to a maximum DC of 20 at 50 feet). Failure by 4 or less indicates that the hook fails to catch and falls, allowing you to try again. Failure by 5 or more indicates that the grappling hook initially holds, but comes loose after 1d4 rounds of supporting weight. This check is made secretly, so that you don’t know whether the rope will hold your weight.
Bind a Character: When you bind another character with a rope, any Escape Artist check that the bound character makes is opposed by your Use Rope check.
You get a +10 bonus on this check because it is easier to bind someone than to escape from bonds. You don’t even make your Use Rope check until someone tries to escape.
Action: Varies. Throwing a grappling hook is a standard action that provokes an attack of opportunity. Tying a knot, tying a special knot, or tying a rope around yourself one-handed is a full-round action that provokes an attack of opportunity. Splicing two ropes together takes 5 minutes. Binding a character takes 1 minute.
Special: A silk rope gives you a +2 circumstance bonus on Use Rope checks. If you cast an animate rope spell on a rope, you get a +2 circumstance bonus on any Use Rope checks you make when using that rope.
These bonuses stack.
If you have the Deft Hands feat, you get a +2 bonus on Use Rope checks.
Synergy: If you have 5 or more ranks in Use Rope, you get a +2 bonus on Climb checks made to climb a rope, a knotted rope, or a rope-and-wall combination.
If you have 5 or more ranks in Use Rope, you get a +2 bonus on Escape Artist checks when escaping from rope bonds.
If you have 5 or more ranks in Escape Artist, you get a +2 bonus on checks made to bind someone.

Psionic Skills
--------------

PSIONIC SKILLS

SKILL DESCRIPTIONS
The skills below relate to the use of psionics. In addition to three new skills (Autohypnosis, Psicraft, and Use Psionic Device), a new category is provided for the Knowledge skill, and new uses are given for Concentration.

Table: Skill Synergies
5 or more ranks in. . . 
Gives a +2 bonus on. . .
Autohypnosis
Knowledge (psionics) checks
Concentration
Autohypnosis checks
Knowledge (psionics)
Psicraft
Psicraft
Use Psionic Device checks involving power stones
Use Psionic Device
Psicraft checks to address power stones

AUTOHYPNOSIS (WIS; TRAINED ONLY)
You have trained your mind to gain mastery over your body and the mind’s own deepest capabilities.
Check: The DC and the effect of a successful check depend on the task you attempt.
Task
DC
Ignore caltrop wound
18
Memorize
15
Resist dying
20
Resist fear Fear effect
DC
Tolerate poison Poison’s
DC
Willpower
20
Ignore Caltrop Wound: If you are wounded by stepping on a caltrop, your speed is reduced to one-half normal. A successful Autohypnosis check removes this movement penalty. The wound doesn’t go away—it is just ignored through self-persuasion.
Memorize: You can attempt to memorize a long string of numbers, a long passage of verse, or some other particularly difficult piece of information (but you can’t memorize magical writing or similarly exotic scripts). Each successful check allows you to memorize a single page of text (up to 800 words), numbers, diagrams, or sigils (even if you don’t recognize their meaning). If a document is longer than one page, you can make additional checks for each additional page. You always retain this information; however, you can recall it only with another successful Autohypnosis check.
Resist Dying: You can attempt to subconsciously prevent yourself from dying. If you have negative hit points and are losing hit points (at 1 per round, 1 per hour), you can substitute a DC 15 Autohypnosis check for your d% roll to see if you become stable. If the check is successful, you stop losing hit points (you do not gain any hit points, however, as a result of the check). You can substitute this check for the d% roll in later rounds if you are initially unsuccessful.
Resist Fear: In response to any fear effect, you make a saving throw normally. If you fail the saving throw, you can make an Autohypnosis check on your next round even while overcome by fear. If your autohypnosis check meets or beats the DC for the fear effect, you shrug off the fear. On a failed check, the fear affects you normally, and you gain no further attempts to shrug off that particular fear effect.
Tolerate Poison: You can choose to substitute an Autohypnosis check for a saving throw against any standard poison’s secondary damage or effect. This skill has no effect on the initial saving throw against poison.
Willpower: If reduced to 0 hit points (disabled), you can make an Autohypnosis check. If successful, you can take a normal action while at 0 hit points without taking 1 point of damage. You must make a check for each strenuous action you want to take. A failed Autohypnosis check in this circumstance carries no direct penalty—you can choose not to take the strenuous action and thus avoid the hit point loss. If you do so anyway, you drop to –1 hit points, as normal when disabled.
Action: None. Making an Autohypnosis check doesn’t require an action; it is either a free action (when attempted reactively) or part of another action (when attempted actively).
Try Again: Yes, for memorize and willpower uses, though a success doesn’t cancel the effects of a previous failure. No for the other uses.
Synergy: If you have 5 or more ranks in Autohypnosis, you get a +2 bonus on Knowledge (psionics) checks.
If you have 5 or more ranks in Concentration, you get a +2 bonus on Autohypnosis checks.

CONCENTRATION (CON)
You are particularly good at focusing your mind. 
The following are additional uses for the concentration skill.
Check: You must make a Concentration check whenever you might potentially be distracted (by taking damage, by harsh weather, and so on) while engaged in some action that requires your full attention. Such actions include manifesting a power, concentrating on an active power, directing a power, or using a psi-like ability.
If the Concentration check succeeds, you can continue with the action as normal. If the check fails, the action automatically fails and is wasted. If you were in the process of manifesting a power, the power points are lost. If you were concentrating on an active power, the power ends as if you had ceased concentrating on it. If you were directing a power, the direction fails but the power remains active. If you were using a psi-like ability, that use of the ability is lost.
The table below summarizes various types of distractions that cause you to make a Concentration check. If the distraction occurs while you are trying to manifest a power, you must add the level of the power you are trying to manifest to the appropriate Concentration DC.

Concentration DC1
Distraction
10 + damage dealt
Damaged during the action.2
10 + half of continuous damage last dealt
Taking continuous damage during the action.3
15 + power level 
Attempting to manifest a power without its display.
15
Entangled.
Distracting power’s save DC
Distracted by nondamaging power.4
20
Gain psionic focus.
20
Grappling or pinned. (You can manifest powers normally unless you fail your Concentration check.)
Distracting power’s save DC
Weather caused by power4
1 If you are trying to manifest, concentrate on, or direct a power when the distraction occurs, add the level of the power to the indicated DC.
2 Such as during the manifestation of a power with a manifesting time of 1 round or more. Also from an attack of opportunity or readied attack made in response to the power being manifested (for powers with a manifesting time of 1 action) or the action being taken (for activities requiring no more than a full-round action).
3 Such as from standing in natural fire or lava.
4 If the power allows no save, use the save DC it would have if it did allow a save.

Gain Psionic Focus: Merely holding a reservoir of psionic power points in mind gives psionic characters a special energy. Psionic characters can put that energy to work without actually paying a power point cost—they can become psionically focused as a special use of the Concentration skill.
If you have 1 or more power points available, you can meditate to attempt to become psionically focused. The DC to become psionically focused is 20. Meditating is a full-round action that provokes attacks of opportunity. When you are psionically focused, you can expend your focus on any single Concentration check you make thereafter. When you expend your focus in this manner, your Concentration check is treated as if you rolled a 15. It’s like taking 10, except that the number you add to your Concentration modifier is 15. You can also expend your focus to gain the benefit of a psionic feat—many psionic feats are activated in this way.
Once you are psionically focused, you remain focused until you expend your focus, become unconscious, or go to sleep (or enter a meditative trance, in the case of elans), or until your power point reserve drops to 0.
Action: Usually none. In most cases, making a Concentration check doesn’t require an action; it is either a free action (when attempted reactively) or part of another action (when attempted actively). Meditating to gain psionic focus is a full-round action.
Try Again: Yes, though a success doesn’t cancel the effects of a previous failure, such as the loss of the power points for a power being manifested or the disruption of a power being concentrated on.
Special: You can use Concentration to manifest a power or use a psi-like ability defensively, so as to avoid attacks of opportunity altogether. The DC of the check is 15 + the power’s level. If the Concentration check succeeds, you can manifest normally without provoking any attacks of opportunity. If the Concentration check fails, the power also automatically fails and the power points are wasted, just as if your concentration had been disrupted by a distraction.
A character with the Combat Manifestation feat gets a +4 bonus on Concentration checks made to manifest a power or use a psi-like ability while on the defensive or while grappling or pinned.
Synergy: If you have 5 or more ranks in Concentration, you get a +2 bonus on Autohypnosis checks.

KNOWLEDGE (PSIONICS) (INT)
Like the Craft and Profession skills, Knowledge actually encompasses a number of unrelated skills. This entry specifically relates to the body of lore dealing with the phenomena of psionics in all its many manifestations.
Knowledge (psionics) covers ancient mysteries, psionic traditions, psychic symbols, cryptic phrases, astral constructs, and psionic races. You can use this skill to identify psionic monsters and their special powers or vulnerabilities.
Synergy: If you have 5 or more ranks in Knowledge (psionics), you get a +2 bonus on Psicraft checks.
If you have 5 or more ranks in Autohypnosis, you get a +2 bonus on Knowledge (psionics) checks.
Untrained: An untrained Knowledge (psionics) check is simply an Intelligence check. Without actual training, you know only common knowledge (DC 10 or lower).

PSICRAFT (INT; TRAINED ONLY)
Use this skill to identify powers as they are manifest or powers already in place.
Check: You can identify powers and psionic effects. The DCs for Psicraft checks relating to various tasks are summarized on the table below.

Psicraft DC 
Task
15 + power level 
Identify a power being manifested. (You must sense the power’s display, or see some visible effect, to identify a power.) No action required. No retry.
15 + power level
When manifesting detect psionics, determine the discipline involved in the aura of a single item or creature you can see. (If the aura is not a power effect, the DC is 15 + 1/2 manifester level.) No action required.
15 + power level
Address a power stone to figure out what power or powers it contains.
20 + power level
Identify a power that’s already in place and in effect. You must be able to see or detect the effects of the power. No action required. No retry.
20 + power level
Identify materials created or shaped by psionics, such as noting that a particular object was created using a metacreativity power. No action required. No retry.
25 + power level
After rolling a saving throw against a power targeted on you, determine what that power was. No action required. No retry.
25
Identify a psionic tattoo. Requires 1 minute. No retry.
20
Draw a diagram to enhance manifestation of psionic dimensional anchor on a summoned creature. Requires 10 minutes. No retry. The player does not see the result of this check.
30 or higher
Understand a strange or unique psionic effect, such as the effects of an outcrop of psionically resonant crystal. Time required varies. No retry.

Additionally, certain powers allow you to gain information about psionic effects, provided that you make a successful Psicraft check as detailed in the power description.
Action: Varies, as noted above. 
Try Again: See above.
Special: A psion gains a +2 bonus on Psicraft checks when dealing with a power or effect from his discipline.
If you have the Psionic Affinity feat, you get a +2 bonus on Psicraft checks.
Synergy: If you have 5 or more ranks in Psicraft, you get a +2 bonus on Use Psionic Device checks related to power stones.
If you have 5 or more ranks in Use Psionic Device, you get a +2 bonus on Psicraft checks to address power stones.

USE PSIONIC DEVICE (CHA; TRAINED ONLY)
Use this skill to activate psionic devices, including power stones (chunks of crystal that store specific powers) and  dorjes (slender crystal wands charged with several uses of the same power), that otherwise you could not activate.
Check: You can use this skill to address a power stone (to learn what powers are encoded on it) or to activate a psionic item. This skill lets you use a psionic item as if you had the manifesting ability or class features of another class, as if you were a different race, or as if you were a different alignment.
You make Use Psionic Device checks each time you activate a device such as a dorje. If you are using the check to emulate an alignment or some other quality in an ongoing manner, you need to make the relevant emulation checks once per hour.
You must consciously choose what to emulate. That is, you must know what you are trying to emulate when you make an emulation check. The DCs for various tasks involving Use Psionic Device are summarized on the table below.

Use Psionic Device DC
Task
25
Activate blindly
25 + power level
Address a power stone
See text
Emulate an ability score
30
Emulate an alignment
20
Emulate a class feature
25
Emulate a race
20
Use a dorje
20 + manifester level
Use a power stone

Activate Blindly: Some psionic items are activated by special specific thoughts or conceptions. You can activate such items as if you were using the activation method, even if you’re not and even if you don’t know it. You do have to use something equivalent. You have to wave the item around or otherwise attempt to get it to activate. You get a special +2 bonus if you’ve activated the item at least once before.
If you fail the check by 10 or more, you suffer brainburn. This brainburn affects you in the same way as brainburn that can occur when you attempt to manifest a power from a power stone, except that the damage is 1d4 points per power level instead of 1d6. Brainburn damage from activating blindly is in addition to brainburn damage from manifesting a power from a power stone.
Address a Power Stone: Successfully addressing a power stone allows you to find out what power or powers it contains. Doing this requires 1 minute of concentration.
Emulate an Ability Score: To manifest a power from a power stone, you need a high ability score in the appropriate ability. Your effective ability score (appropriate to the class you’re emulating when you try to manifest the power from the power stone) is your check result minus 15. If you already have a high enough score in the appropriate ability, you don’t need to make this check.
Emulate an Alignment: Some psionic items have positive or negative effects based on your alignment. Use Psionic Device lets you use these items as if you were of an alignment of your choice. You can emulate only one alignment at a time. 
Emulate a Class Feature: Sometimes you need to use a class feature to activate a psionic item. Your effective level in the emulated class equals your check result minus 20. This skill does not let you use the class feature of another class. It just lets you activate items as if you had the class feature.
If the class whose feature you are emulating has an alignment requirement, you must meet it, either honestly or by emulating an appropriate alignment as a separate check (see above).
Emulate a Race: Some psionic items work only for certain races, or work better for those of certain races. You can use such an item as if you were a race of your choice. You can emulate only one race at a time.
Use a Dorje: Normally, to use a dorje, you must have the dorje’s power on your class power list. This use of the skill allows you to use a dorje as if you had a particular power on your class power list. This use of the skill applies to other power trigger psionic items, if applicable.
Use a Power Stone: Normally, to manifest a power from a power stone, you must have the power stone’s power on your class power list. This use of the skill allows you to use a power stone as if you had a particular power on your class power list. The DC is equal to 20 + the manifester level of the power you are trying to manifest from the power stone. Note: Before you use
a power stone, you must first have addressed it to determine what powers it contains. In addition, manifesting a power from a power stone requires a minimum score (10 + power level) in the appropriate ability. If you don’t have a high enough score, you must emulate the ability score with a separate check (see above). This use of the skill applies to other power completion
psionic items.
Action: None. The Use Psionic Device check is made as part of the action (if any) required to activate the psionic item.
Try Again: Yes, but if you ever roll a natural 1 while attempting to activate an item and you fail, you can’t try to activate it again for a day.
Special: You cannot take 10 with this skill.
You can’t aid another on Use Psionic Device checks. Only the user of the item can attempt such a check.
A character with the Psionic Affinity feat gets a +2 bonus on Use Psionic Device checks.
Synergy: If you have 5 or more ranks in Psicraft, you get a +2 bonus on Use Magic Device checks related to power stones.
If you have 5 or more ranks in Use Psionic Device, you get a +2 bonus on Psicraft checks to address power stones.

Epic Skills
-----------

EPIC SKILLS 

Despite the near-magical nature of some epic level skill uses, all uses of skills are considered exceptional abilities (except if noted otherwise), and thus function normally even within areas of antimagic. 

Skill Synergy 
Many skills are noted as granting a synergy bonus to the use of another skill when a character has 5 or more ranks in the first skill. This synergy bonus increases by +2 for every additional 20 ranks the character has in the skill. 

SKILL DESCRIPTIONS 
This section describes new DCs and new modifiers for skills. 

Appraise 
The character can sense magical auras in objects. 
Task
DC 
Detect magic
50 
Detect Magic: The character can sense if an item has a magical aura. He or she can then use Spellcraft to learn more about the item as if he or she had already cast detect magic on the item. This requires a full-round action. 

Balance 
Surface
DC 
1–2 inches wide
20 
Up to 1 inch wide
40 
Hair-thin
60 
Liquid*
90 
Cloud
120 
*Includes any other surface that couldn’t support the character’s weight, such as a fragile branch. 

Bluff 
The character can implant a nonmagical suggestion in a target, display a false alignment, or disguise his or her surface thoughts. 
Example Circumstance
Sense Motive Modifier
Instill suggestion in target
+50
Task
DC 
Display false alignment
70 
Disguise surface thoughts
100 
Instill Suggestion in Target: This is identical to the effect of the suggestion spell, except that it is nonmagical and lasts for only 10 minutes. It can be sensed as if it were an enchantment effect (Sense Motive DC 25). 
Display False Alignment: The character can fool alignment-sensing effects by displaying a false alignment of his or her choice. Once set, a false alignment remains as long as the character remains conscious and awake. Setting or changing a false alignment requires a full-round action. 
Disguise Surface Thoughts: The character can fool spells such as detect thoughts (or similar effects) by displaying false surface thoughts. While the character can’t completely mask the presence of his or her thoughts, he or she can change his or her apparent Intelligence score (and thus the character’s apparent mental strength) by as much as 10 points and can place any thought in his or her “surface thoughts” to be read by such spells or effects. If a character attempts to use Sense Motive to detect his or her surface thoughts (see the Sense Motive skill description), this becomes an opposed check (though any result lower than 100 automatically fails). 

Climb 
The character can climb otherwise unclimbable surfaces. 
DC
Surface 
70
A perfectly smooth, flat, vertical surface 
100
A perfectly smooth, flat, overhang or ceiling 
Rapid Climbing: A character can climb his or her speed as a move-equivalent action, or double his or her speed as a full-round action (requiring two Climb checks), but the character takes a –20 penalty on his or her check. 
Special: The Legendary Climber feat allows a character to ignore any penalties for accelerated or rapid climbing. 

Concentration 
The character can cast spells with somatic components even while grappled. 
Task
DC 
Cast spell with somatic component while grappled
50 + spell level 

Craft 
The character can craft items more quickly than normal. 
Task
DC 
Quick creation
+10 or more to DC 
Quick Creation: A character can voluntarily increase the DC of crafting an item by any multiple of 10. This allows the character to create an item more quickly (since he or she will be multiplying this higher DC by his or her skill check result to determine progress). The character must decide the increase to the DC before making the check. 

Craft (Alchemy)
Task
DC (or DC Modifier) 
Create augmented substance
+20 or more to DC 
Create Augmented Alchemical Item or Substance: This requires the Augmented Alchemy feat, and allows a character to create alchemical items and substances of greater power than normal. To augment an alchemical substance, add +20 to the DC required to create the item and multiply the cost by 5. If the item or substance deals damage, double the damage dealt. If the item or substance doesn’t deal damage, double the duration of its effect. If the item or substance doesn’t deal damage and doesn’t have a specific listed duration (or has an instantaneous duration), double all dimensions of its area. If the item or substance doesn’t fit any of these categories, then it cannot be improved in this manner. A character can create an item with multiple degrees of augmentation. For every additional multiplier applied to damage, duration, or area, add an additional +20 to the DC and add an additional 5 to the cost multiplier. 
Item
Effect of Augmenting 
Acid
Direct hit 2d6, splash 2 
Alchemist’s fire
Direct hit 2d6, splash 2 
Antitoxin
Duration 2 hours 
Smokestick
Smoke fills a 20-foot cube 
Sunrod
Glows for 12 hours 
Tanglefoot bag 
Becomes brittle and fragile after 20 minutes
Tindertwig
No effect 

Decipher Script 
The character can decipher magic scrolls. 
Task
DC 
Decipher a written spell (such as a scroll) without using read magic. One try per day.
50 + 5 times spell level 

Diplomacy 
The character can turn a person into a fanatic follower. Refer to the accompanying table.

——————New Attitude ——————
Initial Attitude
Hos
Unf
Indif
Friend
Help
Fanatic
Hostile
Less than 20
20
25
35
50
150
Unfriendly
Less than 5
5
15
25
40
120
Indifferent
—
Less than 1
1
15
30
90
Friendly
—
—
Less than 1
1
20
60
Helpful
—
—
—
Less than 1
1
50
Hos: hostile. Unf: unfriendly. Indif: indifferent. Friend: friendly. Help: helpful. 
Fanatic: The attitude of fanatic is added here. In addition to the obvious effects, any NPC whose attitude is fanatic gains a +2 morale bonus to Strength and Constitution scores, a +1 morale bonus on Will saves, and a –1 penalty to AC whenever fighting for the character or his or her cause. This attitude will remain for one day plus one day per point of the character’s Charisma bonus, at which point the NPC’s attitude will revert to its original attitude (or indifferent, if no attitude is specified). 
Treat the fanatic attitude as a mind-affecting enchantment effect for purposes of immunity, save bonuses, or being detected by the Sense Motive skill. Since it is nonmagical, it can’t be dispelled; however, any effect that suppresses or counters mind-affecting effects will affect it normally. A fanatic NPC’s attitude can’t be further adjusted by the use of skills. 
Attitude 
Means
Possible Actions 
Fanatic 
Will give life to serve you
Fight to the death against overwhelming odds, throw self in front of onrushing dragon 

Disable Device 
The character can rush his or her Disable Device attempt, reducing the amount of time it takes to perform the attempt.
Reduce to
DC Modifier 
1 round
+20 
Move-equivalent action
+50 
Free action
+100 

Disguise 
The character can change his or her apparent height and weight much more than normal. 
Disguise
Modifier
Change height and/or weight 11% to 25%
–25*
Change height and/or weight 26% to 50%
–50*
*Can be negated by any effect that can duplicate a height and/or weight change of this degree. 

Escape Artist 
The character can pass through spaces smaller than his or her head, or even through a wall of force.
DC
Task 
80
Extremely tight space 
120
Pass through wall of force 
Extremely Tight Space: This is the DC for getting through a space when one’s head shouldn’t even be able to fit; this can be as small as 2 inches square for Medium-size creatures. Halve this limit for each size category less than Medium-size; double it for each size category greater than Medium-size. If the space is long, such as in a chimney, multiple checks may be called for. 
Pass through Wall of Force: This allows a character to find a gap of weakness in a wall of force (or similar force effect) and squeeze through it. 

Forgery 
The character can forge handwriting he or she haven’t even seen.
Condition
Reader’s Check Modifier
Forge document without sample
+50
Forge Document without Sample:  The character can forge a document without having seen a similar document or having a sample of the handwriting to be copied.

Gather Information 
The character can gather information without eliciting suspicion. 
Task 
Check Modifier 
Avoid suspicion
–20
Avoid Suspicion: By accepting a –20 penalty on his or her Gather Information check, a character can avoid any suspicions that might otherwise be aroused by someone pursuing sensitive information. 

Handle Animal 
The character can handle creatures other than animals, and can teach or train in much less time than normally required. 
Task
Time
DC 
Rear magical beast 
1 year
30 + HD of magical beast 
Train magical beast 
2 months
40 + HD of magical beast 
Rear vermin 
6 months
35 + HD of vermin 
Train vermin 
2 months
50 + HD of vermin 
Rear other creature 
Varies
40 + HD of creature 
Train other creature 
2 months
60 + HD of creature 

Reduce Teaching/Training to . . . 
DC Modifier
1 month
+25
1 day 
+50
1 hour
+75
1 minute
+100
Reduce Teaching/Training: Normally, teaching or training a creature requires two months of time. A character can accelerate the process of teaching or training a creature, reducing the time required to the listed time, by adding the DC modifier to the base DC for teaching or training the creature. A character can’t reduce the required time to less than 1 minute. 

Heal 
The character can greatly speed a patient’s recovery of hit points. 
Task
DC 
Quicken recovery
50 
Perfect recovery
100 
Quicken Recovery: The character can allow a character to regain hit points in a single hour as if he or she had provided long-term care for a full day (2 or 3 hit points per level, based on activity). The character can quicken the recovery of up to six patients at a time. No character’s recovery can be quickened more than once per day (even by different healers). 
Perfect Recovery: The character can allow a character to regain hit points in a single hour as if he or she had provided long-term care for a full week (2 or 3 hit points per level per day, based on activity). The character can use perfect recovery on up to six patients at a time. No character’s recovery can be perfected more than once per day, nor can perfect recovery and quicken recovery both be used on the same patient in the same day (even by different healers).

Hide 
The character can hide others as well as hiding him or herself. 
Task
Check Modifier
Hide another
–30
Hide Another: By accepting a –30 penalty on his or her Hide check, a character can hide another adjacent creature whose size is no more than one category larger than the character’s own. Modifiers to the check for the size of the creature still apply, as do all other penalties, including those for moving faster than half speed. Likewise, a character can only hide another creature when it is not under direct observation by a third party. The creature the character hides remains hidden until it is spotted or it takes some other action that breaks its concealment, as normal. 

Intimidate 
Intimidate does not possess an epic usage. 
Special: The DC to intimidate any creature whose attitude is fanatic is increased by +20. 

Jump 
Jump does not possess an epic usage. 

Knowledge
Knowledge does not possess an epic usage. 

Listen 
The character can pinpoint the location of an invisible creature, or detect an illusion with an auditory component. 
DC 
Task 
80 
Defeat illusion with auditory component 
Defeat Illusion: The character can automatically detect any illusion with an auditory component for what it truly is. No Will save is required, and the character doesn’t have to interact with the illusion (but he or she must be able to hear its auditory component). Special: A character can use Listen to notice the presence of an invisible creature (generally opposed by a Move Silently check). If the character beats the DC by 20 or more, he or she can pinpoint the location of the invisible creature, though it still maintains total concealment from the character (50% miss chance). 

Move Silently 
Move Silently does not possess an epic usage. 

Open Lock 
The character can open locks more quickly than normal. 
Open lock as . . . 
DC Modifier 
Move-equivalent action 
+20 
Free action 
+50 

Perform 
The character can sway an audience’s attitude with his or her performance.
 
——————New Attitude ——————
Initial Attitude 
Hos
Unf
Indif
Friend
Help
Fanatic
Hostile 
Less than 20
20
25
35
50
150
Unfriendly 
Less than 5
5
15
25
40
120
Indifferent 
—
Less than 1
1
15
30
90
Friendly 
—
—
Less than 1
1
20
60
Helpful 
—
—
—
Less than 1
1
50
Hos: hostile. Unf: unfriendly. Indif: indifferent. Friend: friendly. Help: helpful.
Fanatic: The attitude of fanatic is added here. In addition to the obvious effects, any NPC whose attitude is fanatic gains a +2 morale bonus to Strength and Constitution scores, a +1 morale bonus on Will saves, and a –1 penalty to AC whenever fighting for the character or his or her cause. This attitude will remain for one day plus one day per point of the character’s Charisma bonus, at which point the NPC’s attitude will revert to its original attitude (or indifferent, if no attitude is specified). 
Treat the fanatic attitude as a mind-affecting enchantment effect for purposes of immunity, save bonuses, or being detected by the Sense Motive skill. Since it is nonmagical, it can’t be dispelled; however, any effect that suppresses or counters mind-affecting effects will affect it normally. A fanatic NPC’s attitude can’t be further adjusted by the use of skills. 
Attitude 
Means 
Possible Actions 
Fanatic 
Will give life to serve you
Fight to the death against overwhelming odds, throw self in front of onrushing dragon 

Profession 
Profession does not possess an epic usage. 

Ride 
The character can stand upon his or her mount in combat. 
DC
Task 
40 
Stand on mount 
50 
Unconscious control 
60 
Attack from cover 
Stand on Mount: This allows the character to stand on his or her mount’s back even during movement or combat. The character takes no penalties to actions while doing so. 
Unconscious Control: As a free action, the character can attempt to control a light horse, pony, or heavy horse while in combat. If the character fails, he or she controls the mount as a move-equivalent action. A character does not need to roll for warhorses or warponies. 
Attack from Cover: The character can react instantly to drop down and hang alongside his or her mount, using it as one-half cover. The character can attack and cast spells while using his or her mount as cover without penalty. If the character fails, he or she doesn’t get the cover benefit. 

Search 
The character can sense the presence of magic in an area. 
Task 
DC 
Sense magic 
60 
Sense Magic: The character senses the presence of any active magical effects in the area being searched. The character can’t determine the number, strength, or type of the effects. 

Sense Motive 
The character can discern a target’s alignment and even detect surface thoughts.
Task 
DC
Discern partial alignment 
60 
Discern full alignment 
80 
Detect surface thoughts 
100 
Discern Partial Alignment: This use of the skill lets a character discern one component of a target’s alignment. When making the check, the character states whether he or she is trying to discern the law–chaos or good–evil component. A character can’t retry the check, and he or she can’t use this to discern more than one component of the alignment (but see below). The target must be visible and within 30 feet of the character. 
Discern Full Alignment: This use of the skill lets a character determine both components of a target’s alignment. The character can’t retry the check. The target must be visible and within 30 feet of the character. 
Detect Surface Thoughts: This lets a character read the surface thoughts of a single target (as the 3rd-round effect of the detect thoughts spell). There is no saving throw to resist this effect, though the target can use Bluff to disguise his or her surface thoughts (see the Bluff skill description), in which case this becomes an opposed check (any result lower than 100 automatically fails). The target must be visible and within 30 feet of the character.

Sleight of Hand 
The character can lift another’s weapon and perform major feats of legerdemain. 
DC
 Task
50 
Lift a sheathed weapon from another creature and hide it on the character’s person, if the weapon is no more than one size category larger than the character’s own size. 
80
Make an adjacent, willing creature or object of the character’s size or smaller “disappear” while in plain view. In fact, the willing creature or object is displaced up to 10 feet away—make a separate Hide check to determine how well the “disappeared” creature or object is hidden. 

Spellcraft 
The character can identify properties of a magic item. 
DC 
Task 
50 + caster level 
Identify basic property of magic item 
70 + caster level 
Identify all properties of magic item 
50
Quick identification of alchemical substances and potions
Identify Basic Property of Magic Item: This use of the skill requires one round of inspection, and functions exactly as if the character had cast an identify spell on the item. A character can’t attempt this on the same item more than once. 
Identify All Properties of Magic Item: This requires one minute of inspection, and reveals all properties of a single magic item (including command words and charges remaining). A character can’t attempt this on the same item more than once. If an item has different caster levels for different properties, use the highest caster level. 
Quick Identification: A character can identify a substance or potion in the field as a full-round action, without an alchemical lab or any cost. The character can’t retry this check (or take 20); if he or she fails, the character must identify the substance in an alchemical lab, as normal. 

Spot 
The character can pinpoint the location of an invisible creature, or detect an illusion with a visual component. 
DC 
Task 
20 
Notice presence of active invisible creature 
30 
Notice presence of unmoving, living invisible creature 
40 
Notice presence of inanimate invisible object 
40 
Notice presence of unmoving, unliving invisible creature 
80 
Defeat illusion 
A character can use Spot to notice the presence of an invisible creature. The relevant DCs are reprinted here. If the character beats the DC by 20 or more, he or she can pinpoint the location of the invisible creature, though it still maintains total concealment from the character (50% miss chance). 
Defeat Illusion: The character can automatically detect any illusion with a visual component for what it truly is. No Will save is required, and the character doesn’t have to interact with the illusion (but he or she must be able to see it). 
Using Spot to Read Lips 
Task 
DC Modifier 
Read lips while moving at up to full speed
+20 
Pronounce unfamiliar language 
+20 
Pronounce Unfamiliar Language: This use of the skill allows a character to repeat the speech of an observed creature, potentially allowing a comrade to translate the speech. It doesn’t grant the character any ability to understand the language spoken. 

Survival
The character can ignore the effects of terrain on movement and withstand even the harshest weather. If the character is capable of tracking, he or she can identify the races of creatures being tracked. 
DC 
Task 
40 
Get along in the wild while moving at full speed. The character can provide food and water for one other person for every 2 points by which the check result exceeds 40. 
60 
Automatically succeed on all Fortitude saves against severe weather. The character can extend this benefit to one other character for every 2 points by which the check result exceeds 60. 
60 
Ignore overland movement penalties of terrain. The character and his or her mount can move at full overland speed regardless of terrain. The character can extend this benefit to one other character for every 5 points by which the check result exceeds 60. 
60 
Identify race/kind of creature(s) by tracks.* 
*Requires the Track feat. 

Wherever the character is, he or she can determine the direction to a location on the same plane. 
DC
 Familiarity with Location 
40 
Very familiar 
60 
Studied carefully 
80 
Seen casually 
100 
Viewed once 
120 
Description only 
With a successful check, the character knows the direction to the desired location. This merely points the character in the direction of the location; it doesn’t provide him or her with information on how to get there, nor does it take into account any obstacles in the path. “Very familiar” represents a place where the character has been very often and where he or she feels at home. “Studied carefully” represents a place the character knows well, either because he or she has been there often or has used other means to study the place. “Seen casually” is a place that the character has viewed more than once, but which he or she has not studied. “Viewed once” is a place that the character has seen once, possibly using magic. “Description only” is a place whose location and appearance the character knows through someone else’s description. 

Swim 
The character can swim up vertical surfaces, or swim much faster than normal. 
DC 
Task 
80 
Swim up waterfall 
Swim up Waterfall: This use of the skill allows a character to swim an angled or vertical surface, as long as he or she remains completely or mostly immersed in water. Other examples might include swimming up a whirlpool or an incredibly large wave. 
Circumstance 
DC Modifier 
Speed swimming 
–20 
Speed Swimming: By taking a –20 penalty on the check, a character can swim his or her speed as a move-equivalent action, or double his or her speed as a full-round action. 

Tumble 
The character can fall from great heights without taking damage, move greater distances with an adjustment, or “climb” vertical surfaces with a series of bounces. 
DC 
Task 
30 
Treat a fall as if it were 20 feet shorter when determining damage. 
35 
Free stand. 
45 
Treat a fall as if it were 30 feet shorter when determining damage. 
50 
Climb vertical surface. 
60 
Treat a fall as if it were 40 feet shorter when determining damage. 
100 
Ignore falling damage. 
Free Stand: The character can stand up from prone as a free action (instead of as a move-equivalent action). 
Climb Vertical Surface: The character can climb up to 20 feet (as part of normal move-ment) by jumping and bouncing off walls, trees, or similar vertical surfaces. The character must have at least two vertical surfaces to bounce off, and the two must be within 10 feet of each other. 
Ignore Falling Damage: The character can fall from any height and take no damage. 
Special: A character with 25 or more ranks in Tumble gains a +5 dodge bonus when executing the fight defensively standard or full-round action, instead of a +2 bonus (or the +3 bonus from having 5 or more ranks). Increase this dodge bonus by +1 for every 10 additional ranks above 25 the character has. A character with 25 or more ranks in Tumble gains a +10 dodge bonus to AC when executing the total defense standard action, instead of a +4 bonus (or the +6 bonus from having 5 or more ranks). Increase this dodge bonus by +2 for every 10 additional ranks above 25 the character has. 

Use Magic Device 
Use Magic Device does not possess an epic usage. 

Use Rope 
The character can splice ropes together quickly, tie unique knots, and even animate a rope he or she holds. 
Task
DC 
Quick splicing 
50 
Tie unique knot 
60 
Animate held rope 
80 
Quick Splicing: The character can splice two ropes together as a move-equivalent action. 
Tie Unique Knot: The character can tie a knot that only he or she knows how to untie. This doesn’t affect any Escape Artist checks made to escape these bindings. 
Animate Held Rope: The character can command any rope he or she holds as if it had the animate rope spell cast upon it (except that using the skill in this way doesn’t grant any bonus on Use Rope checks made with the animated rope). Each command requires a separate Use Rope check. Because the effect isn’t magical, it can’t be dispelled. 


PSIONIC SKILLS

Autohypnosis 
The character has trained his or her mind to ignore poison, resist mental influence, and convince his or her body that he or she is tougher than normal. 
DC
Task
Poison’s DC + 5
When poisoned, the character can make an Autohypnosis check on his or her next action. A successful check indicates the character does not have to make a saving throw against the poison’s secondary damage, which he or she instead automatically ignores. 
50 
If a failed saving throw indicates the character is affected by any mind-affecting powers, spells, or spell-like effects, a successful Autohypnosis check allows an immediate second saving throw to resist the effect. If the mind-affecting effect normally does not allow a saving throw, a successful Autohypnosis check allows a saving throw. 
60 
With a successful Autohypnosis check, the character gains temporary hit points equal to 10 + his or her Wisdom modifier. The temporary hit points persist until lost. A character cannot check for temporary hit points more than once per day. Temporary hit points gained through Autohypnosis do not stack with temporary hit points gained through any other source 

Stabilize Self 
Mortal wounds are less lethal for the character. 
DC
Task 
30
If reduced to negative hit points but not dead, make a Stabilize Self check. If successful, the character does not go unconscious and can continue taking actions until he or she bleeds to death or stabilizes (the character can also continue making stabilization checks). If healed or stabilized, the character continues to take actions normally. 
60 
On a successful Stabilize Self check, the character gains damage reduction 2/–. The damage reduction lasts for 12 hours. The character cannot check for damage reduction more than once per day. Damage reduction gained through Stabilize Self does not stack with damage reduction gained through any other source. 

Miscellaneous
Scrying spells
To attempt any of these tasks, the scrying spell must be on your class spell list (though it need not be among your spells known). If you have any bonuses that would apply to the caster level of your scrying spell, add these to your caster level check.
Task
DC 
Learn scryer 
30
Return scrying 
50 
Break scrying 
Opposed caster level check 
Learn Scryer: If you determine that you’re being scried upon, you can learn the identity of the scryer with a DC 30 caster level check. If successful, you learn the name, race, and location of the scryer. 
Return Scrying: If you determine that you’re being scried upon, you can look back through the sensor at the scryer with a DC 50 caster level check. This allows you to spy on the scrying being as if you had cast a scrying spell upon that person. This return scrying can be detected by your target as normal.
Break Scrying: If you determine that you’re being scried, you can make an opposed caster level check with the scryer. (Your caster level must be at least 21st to attempt this task.) If you are successful, the scrying ends, and the scryer may not target you with a Divination (Scrying) spell or effect for a number of hours equal to your Intelligence modifier (minimum 1).
